gradio/inputs.py
* Added the missing `microphone` shortcut
* Per docs:
> By default, no pre-processing is applied to a microphone input file
Thus fixed the preprocessing step to match docs and made MFCC feature extraction configurable
* Sorted imports in inputs.py
* Tested manually using the following variants:
```python
gr.Interface(fn=detect, inputs=gr.inputs.Microphone(preprocessing='mfcc'), outputs='label').launch()
gr.Interface(fn=detect, inputs=gr.inputs.Microphone(preprocessing='invalid'), outputs='label').launch()
gr.Interface(fn=detect, inputs='microphone', outputs='label').launch()
```
* No regression in unit tests
=> Fixed microphone shortcut and preprocessing

gradio/inputs.py
Allows adaptive input sizes for images (e.g., for fully convolutional neural networks).
=> Allow adaptive size inputs for images.

gradio/interface.py, gradio/networking.py
=> Pass server_name  to networking module to make app accessible on LAN.

gradio/static/js/all_io.js
Quick fix, but I know you like to vet all static files changes
=> predict example fix

gradio/inputs.py
In preprocess method of Video class, included ff.run() in the if body so that no conversion occurs if self.type is None.
=> Update preprocess method in Video class

demo/kitchen_sink.py
This makes it easy to e.g. style all possible elements on the same webpage/in the same demo.
cc @gary149
=> [kitchen_sink] demo app with all supported input/output interfaces

demo/kitchen_sink.py, gradio/external.py, gradio/networking.py
=> Add some pipeline types from huggingface

gradio/interface.py, gradio/networking.py, gradio/strings.py, test/test_networking.py
Changed some messaging for `share=True`, see below:
Also updated on the server so that this will apply to people who don't update `gradio` as well
=> updated strings so that people reach out to us via email more

frontend/src/themes/huggingface.scss
cc @gary149
(build not tested)
=> [HF Spaces] Adjust dark background color

gradio/interface.py, test/test_interfaces.py
=> tests for integration and fixes bug

README.md
Out of the box plotly does not work with gradio.
=> change plotly to matplotlib

test/test_interfaces.py
=> add test for capture session

gradio/interface.py, gradio/networking.py
Working on issues #399, #395, #382, #344, and the edge case where if you have a local interface & one on a remote notebook, then it can cause issues.
=> [WIP] Working on fixing issues related to server_name, server_port, and url_ok

demo/gender_sentence_custom_interpretation/run.py, demo/gender_sentence_default_interpretation/run.py
Added 'hers ' to pronouns list
From this issue: https://github.com/gradio-app/gradio/issues/413
=> Added hers to list of female words

.circleci/config.yml, gradio/external.py, gradio/inputs.py, gradio/interface.py, gradio/strings.py, gradio/templates/frontend/asset-manifest.json, gradio/templates/frontend/index.html, test/test_external.py, test/test_interfaces.py
Adds a `gradio.Interface.load_pipeline()` function which consumes `transformers.Pipeline`s
Also a few other misc things:
* Fixes some issues loading Audio models/spaces through Gradio (including #363) 
* Improves sharing message
=> Gradio integration with `transformers` Pipelines

gradio/app.py, gradio/networking.py
There was an issue with the Gradio web app not being able to handle concurrent requests. 
Fixes #447 as well
Please delete options that are not relevant.
=> Fixed concurrency issue

frontend-svelte/package-lock.json, frontend-svelte/package.json, frontend-svelte/src/components/input/Audio/Component.svelte
Adds an audio input component that records from the microphone as the input. Used a slightly different slider component that has roughly the same UX but this should be removed when we create a dedicated audio player/trimmer.
WIP because I haven't been able to test it properly due to the API throwing 500s locally.
Please delete options that are not relevant.
=> Record audio

frontend/package-lock.json, frontend/package.json, frontend/src/Interface.svelte, frontend/src/components/directory.js, frontend/src/components/input/Audio/Component.svelte, frontend/src/components/input/TimeSeries/Component.svelte, frontend/src/components/input/TimeSeries/config.js, frontend/src/components/output/Dataframe/Component.svelte, frontend/src/components/output/HighlightedText/Component.svelte, frontend/src/components/output/TimeSeries/Component.svelte, frontend/src/components/output/TimeSeries/config.js, frontend/src/components/utils/Chart.svelte, frontend/src/components/utils/Tooltip.svelte, frontend/src/components/utils/tooltip.js, frontend/src/components/utils/utils.js
Time series input component. This drops chartjs which is very very large and uses d3 instead.
https://user-images.githubusercontent.com/12937446/151414670-3b88feb7-a914-46b6-819b-7aa84a269387.mov
=> time series component (input)

ui/.editorconfig, ui/.prettierrc.json, ui/package.json, ui/packages/app/src/components/input/Checkbox/Component.svelte, ui/packages/app/src/components/utils/Chart.svelte, ui/packages/app/src/components/utils/utils.ts, ui/pnpm-lock.yaml, ui/tsconfig.json
Adds typescript and a `check` command.
Many errors right now.
=> add typescript

.github/workflows/ui.yml, ui/.prettierignore, ui/package.json, ui/packages/app/index.html, ui/packages/app/postcss.config.js, ui/packages/app/src/Interface.svelte, ui/packages/app/src/api.js, ui/packages/app/src/components/input/Audio/Component.svelte, ui/packages/app/src/components/input/Audio/Interpretation.svelte, ui/packages/app/src/components/input/Checkbox/Interpretation.svelte, ui/packages/app/src/components/input/DataFrame/Component.svelte, ui/packages/app/src/components/input/Dropdown/Component.svelte, ui/packages/app/src/components/input/File/Component.svelte, ui/packages/app/src/components/input/Image/Component.svelte, ui/packages/app/src/components/input/Image/Interpretation.svelte, ui/packages/app/src/components/input/Number/Interpretation.svelte, ui/packages/app/src/components/input/Slider/Interpretation.svelte, ui/packages/app/src/components/input/TimeSeries/Component.svelte, ui/packages/app/src/components/output/Carousel/Component.svelte, ui/packages/app/src/components/output/HighlightedText/Component.svelte, ui/packages/app/src/components/output/Json/JsonNode.svelte, ui/packages/app/src/components/output/Label/Component.svelte, ui/packages/app/src/components/utils/ModifyUpload.svelte, ui/packages/app/src/components/utils/Webcam.svelte, ui/packages/app/src/components/utils/helpers.js, ui/packages/app/src/global.css, ui/packages/app/vite.config.js, ui/pnpm-lock.yaml, ui/tsconfig.json
Adds the following checks to CI:
- format check
- type check (this is currently allowed to fail)
Closes #511.
=> add ci for ui

.github/workflows/ui.yml, ui/README.md
Adds build to ci checks.
closes #518.
=> add frontend build to ci as a smoke test

gradio.egg-info/PKG-INFO, ui/packages/app/src/App.svelte, ui/packages/app/src/Interface.svelte, ui/packages/app/src/components/input/Audio/Component.svelte, ui/packages/app/src/components/input/File/Component.svelte, ui/packages/app/src/components/input/Image/Component.svelte, ui/packages/app/src/components/input/Number/Component.svelte, ui/packages/app/src/components/input/Textbox/Component.svelte, ui/packages/app/src/components/input/Video/Component.svelte, ui/packages/app/src/components/utils/ModifyUpload.svelte, ui/packages/app/src/components/utils/Webcam.svelte, ui/packages/app/src/components/utils/utils.ts, ui/packages/app/src/main.js
=> sync folder ui with frontend

gradio/outputs.py, gradio/processing_utils.py
=> Audio Output Fix

website/homepage/src/guides_template.html, website/homepage/src/index_template.html
Website missing public global css link
=> Website vendor css fix [hotfix]

gradio/interface.py, gradio/networking.py, gradio/strings.py
Adds support for https as requested in #563 and related discussion posts.
=> Adds support for https

.github/workflows/ui.yml, ui/package.json, ui/packages/app/src/components/utils/helpers.test.ts, ui/pnpm-lock.yaml, ui/vitest.config.ts
Adds frontend unit testing framework.
=> add unit tests

website/homepage/.dockerignore, website/homepage/Dockerfile
Website wasn't reloading because of the new frontend changes
* Changed the Dockerfile to build the ui correctly, and pull latest node/npm
* Fixed the directories in .dockerignore
=> Fixing Website Reload 

website/homepage/src/navbar.html
- correcting discord invite link
- navbar linking to /guides instead of guides.html
closes #604
=> Small fixes

website/homepage/Dockerfile
=> fixed mkdir in dockerfile

website/homepage/render_html.py, website/homepage/src/guides_template.html, website/homepage/src/index_template.html, website/homepage/src/other_templates/kitchen_sink_template.html
fix assets link in gradio website
=> fix assets link on gradio homepage [hotfix]

ui/packages/app/public/lang/es.json
I edited sentences to adapt them to the way they are commonly written in Spanish :D
- There were some mistakes with articles and in Spanish we usually write in lower cases.
=> Corrections in Spanish support

gradio/interface.py, test/test_flagging.py
=> black fix [hotfix]

ui/packages/app/src/components/input/DataFrame/DataFrame.svelte
- default data is now respected
- Backspace and Delete can clear cells
- Heading label has been removed
Closes #588
=> Dataframe fixes

ui/packages/app/src/components/utils/helpers.test.ts, ui/packages/app/src/components/utils/helpers.ts
=> More unit tests

ui/packages/app/public/lang/he.json
* Added a draft of hebrew translation (note hebrew is not my native language might need some review but should be understandable to a native speaker)
* 
* Fixes: # (issue)
- [ x] I have performed a self-review of my own code
- [ x] My code follows the style guidelines of this project
- [ x] I have commented my code in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
=> Added hebrew json draft

ui/packages/app/public/lang/zh_TW.json, ui/packages/app/src/i18n.js
Added Chinese language
* Added zh_TW.json files in the lang directory
* Updated i18n.js
=> Added chinese lang

ui/packages/app/public/lang/fr.json, ui/packages/app/src/i18n.js
Added French language
- Added fr.json files in the lang directory
- Updated i18n.js
=> Added French language

ui/packages/app/src/components/output/Chatbot/Chatbot.svelte, ui/packages/app/src/components/utils/Webcam.svelte
=> Some webcam + chatbot fixes

ui/packages/app/src/lang/ko.json
- add Korean language support for UI components
- add `ko.json` file
- no dependencies required
=> add korean support

ui/packages/app/src/lang/ar.json
Added `ar.json`. Couldn't figure out how to test locally and see the interface.
=> Added Arabic

ui/packages/app/public/lang/uz.json
* relevant motivation: Uzbek language
* a summary of the change: added Uzbek language support 
=> Added Uzbek (UZ) support

gradio/networking.py
=> suppress warnings when sharing

ui/packages/app/src/lang/zh-cn.json
* Add Simplified Chinese translation.
=> Add zh-cn translation

ui/packages/app/src/lang/pl.json
=> Add Polish translation

ui/packages/app/src/lang/lt.json
=> Lithuanian language support

gradio/interface.py, gradio/networking.py
=> added ssl_keyfile_password

ui/packages/app/src/App.svelte
=> ensure footer links open in new tab when embedded

ui/packages/app/src/components/utils/Webcam.svelte
https://github.com/gradio-app/gradio/issues/693
=> Issue 693: Video component is flipped horizontally

gradio/networking.py, scripts/format_frontend.sh, test/test_networking.py
Just noticed a small docstring issue for `networking.start_server` -- issued a fix
=> small fix to start_server docstring & added a test

demo/hello_world_2/run.py, demo/hello_world_3/run.py, guides/getting_started.md
Tweaks on the naming and description.
=> Update The Docs on Launch

website/homepage/src/guides_main_template.html, website/homepage/src/guides_template.html
small change so meta image tag shows properly on guides links shared on twitter
=> fixed twitter image tag

gradio/interface.py, gradio/queueing.py, gradio/routes.py, test/test_external.py, test/test_queuing.py
=> Added pydantic data models for all requests

ui/packages/app/src/components/input/DataFrame/DataFrame.svelte, ui/packages/app/src/components/input/DataFrame/Example.svelte, ui/packages/app/src/components/input/DataFrame/config.ts, ui/packages/app/src/components/input/Image/Image.svelte, ui/packages/app/src/components/utils/Webcam.svelte
Fix #767 webcam flip - what was the reason for putting the horizontal flip in the first place? @pngwn
Also 745 (incomplete). Added preview for dataframe example. However clicking still does not load the dataframe.
Also hid null values in dataframe.
=> Fixing issues

guides/using_hugging_face_integrations.md
This guide covers multiple use cases of Gradio and Hugging Face. I hope this helps!
Fixes: #567 and potentially also #703
=> Add Hub integrations Guide

website/homepage/render_html.py, website/homepage/src/guides_template.html
Small changes to move related spaces and render ordered lists
=> Guides stylistic changes 

website/homepage/src/guides_template.html
small css change to remove duplicate marker in ordered lists
=> Guides: remove duplicate list marker

website/homepage/src/guides_main_template.html
Including getting started as a guide in the guides page, and listing it first
=> Add getting started to guides page

gradio/blocks.py, gradio/routes.py
#782 caused an issue with Blocks. This fixes that issue.
=> fixed predict body issue

website/reload_website.sh, website/reload_with_notification.sh
Building a slackbot to send a notification when the website is no longer tracking master
Has not been tested
=> Website Tracker Slackbot

.gitignore, gradio/interface.py, gradio/launchable.py
=> Fix type of server returned by `Launchable`

guides/getting_started.md
Add a missing line to this part:
=> Add a missing line to getting started

gradio/flagging.py, gradio/interface.py, gradio/process_examples.py, gradio/utils.py, test/test_utils.py, ui/packages/app/src/App.svelte, ui/packages/app/src/ExampleSet.svelte, ui/packages/app/src/Interface.svelte, ui/packages/app/src/components/input/Number/Number.svelte
Fixes: #819 #812 
pagination restored
cache examples functionality restored
removed custom csv sanitization logic, instead using builtin library support
=> Fixes to examples; use builtin csv sanitization

gradio/flagging.py, gradio/utils.py
=> Component label fixes

gradio/external.py, gradio/utils.py, scripts/format_backend.sh, test/test_utils.py
=> add pipeline support for token classification

gradio/templates/frontend/index.html, ui/packages/app/src/components/Button/Button.svelte
=> fix buttons

gradio/blocks.py, gradio/templates/frontend/index.html, test/test_data/blocks_configs.py
=> Quick fix: Issue 893

ui/packages/app/package.json, ui/packages/app/src/main.ts, ui/packages/app/test/blocks-basic.spec.ts, ui/packages/app/test/input-output.spec.ts, ui/packages/app/vite.config.js
=> fix endpoint url in prod

demo/xray_blocks/run.py, gradio/blocks.py
- add support for "with gr.Blocks() as demo:" usage
=> blocks-with-fix

ui/packages/app/src/components/Textbox/Textbox.svelte, ui/packages/app/src/components/Textbox/Textbox.test.ts, ui/packages/app/test/blocks-basic.spec.ts, ui/packages/app/test/input-output.spec.ts, ui/packages/form/src/CheckboxGroup.svelte
=> fix unit + browser tests

gradio/templates/frontend/index.html, ui/packages/form/src/Number.svelte, ui/packages/form/src/Textbox.svelte
Closes #923. Closes #863.
@abidlabs @aliabid94  I wasn't able to fully reproduce both of those issues but I _think_ this is the right fix. If you could test and confirm, I'd appreciate it.
=> remove debounce from form inputs

gradio/components.py, test/test_components.py
=> blocks-move-test-data

demo/sst_or_tts/run.py, gradio/__init__.py, gradio/interface.py, gradio/test_data/blocks_configs.py, gradio/utils.py, test/test_interfaces.py, test/test_utils.py
Rewrittion of #924 to clean history from files
=> tabbed-interface-rewritten

guides/using_hugging_face_integrations.md
Add huggingface_hub client library and model comparator space builder section.
=> Add huggingface_hub client library

gradio/blocks.py
* Looks like there was an indentation mistake that @FarukOzderim pointed out, but somehow still got merged. Thanks @FarukOzderim!
=> indentation fix

guides/using_hugging_face_integrations.md
missing quote was causing a rendering error and stopping the website from building
=> missing quote

demo/Image3D/run.py, gradio/component.py, gradio/outputs.py, test/test_outputs.py, ui/packages/app/src/components/input/Image3D/Example.svelte, ui/packages/app/src/components/input/Image3D/Image3D.svelte, ui/packages/app/src/components/input/Image3D/config.ts, ui/packages/app/src/components/input/Image3D/types.ts, ui/packages/app/src/components/output/Image3D/Image3D.svelte
=> Image3D Examples Fix

guides/create_your_own_friends_with_a_gan.md, guides/generate_punks_with_gan.md
This PR adds a step-by-step guide for making a GAN-powered image generator, complete with a Gradio interface. The learning outcomes of this guide are:
* Using an image output component
* Adding examples to a Gradio demo
* Exposure to GANs at a high-level, and seeing a Generator in action
=> Gradio Guides: Creating CryptoPunks with GANs

website/reload_website.sh, website/reload_with_notification.sh
Switched to `chat.postMessage` api instead of incoming webhooks. Errors are posted as a thread reply now
=> Update website tracker slackbot 

website/reload_with_notification.sh
small issue with env var in the instance
=> Slackbot web tracker fix

demo/outbreak_forecast/run.py, gradio/components.py, ui/packages/plot/src/Plot.svelte
=> Plot fixes

website/upload_notebooks/run.py
Small fix to check if a demo is a directory before looking inside it
=> fixing demo issue with website

demo/diff_texts/run.py, ui/packages/highlighted-text/src/HighlightedText.svelte
Fix highlighted text component. Issue was not using $: in svelte component to recheck logic on value change.
=> [hotfix] HighlightedText

ui/packages/app/src/Blocks.svelte
=> fix(ui): Increase contrast for footer

gradio/blocks.py, gradio/interface.py
- enable_queue and cache_examples are activated in spaces in default option
fixes #674 #680
=> spaces-defaults

demo/no_input/run.py, gradio/interface.py
- enable inputless or outputless interfaces
Closes #838 
This is an outputless interface, I think it does not make sense in the Interface context:
This is an inputless interface, spent some time trying to make a single column layout, but it was not very direct to hack it and required a bit effort and was going to make interface design more and unnecessarily complex. I think this does the job. If anyone has more functionality or custom needs s/he can move to `Blocks`.
=> inputless-interfaces

gradio/blocks.py
Quick fix for #1095 
@radames's code snippet is now working fine:
=> hotfix for encrypt issue

.circleci/config.yml
Replicates the node changes we have made to github CI + the website docker image in CircleCI. Also bumped the node verision to match.
=> tweak node circleci settings

setup.py, website/demos/Dockerfile, website/homepage/Dockerfile
Copy the `README.md` file in demos docker like in homepage (See #1099)
=> Website Reload: README in demos docker

gradio/blocks.py, gradio/components.py, gradio/interface.py, gradio/routes.py, test/test_networking.py, test/test_routes.py
This PR fixes a few things currently broken with flagging:
* Only show flagging button if `allow_flagging == "manual"` (Closes: #1086)
* Fixes flagging audio files if they are loaded from examples (Closes: #841)
=> Flagging fixes

gradio/interface.py
Messed up the merge with #1106, so this PR redoes it.
Closes: #851
=> Redos #1106

.github/ISSUE_TEMPLATE/bug_report_template.yml, .github/ISSUE_TEMPLATE/feature_request.md
=> issue-checkbox

demo/image_classifier/run.py, demo/model3D/run.py, demo/streaming_stt/run.py, demo/streaming_wav2vec/run.py, website/demos/run_demos.py, website/homepage/src/index_template.html
- Convert demos on landing page to iframes
- Fix demos in getting_started
=> Fix demos in website

guides/Gradio_ONNX_on_Hugging_Face.md, guides/Gradio_and_ONNX_on_Hugging_Face.md, website/homepage/render_html.py
=> ONNX guide fixes

.circleci/config.yml, website/homepage/Dockerfile
=> pin to pnpm 6 for now

ui/packages/chatbot/package.json, ui/packages/chatbot/src/ChatBot.svelte, ui/packages/workbench/src/routes/chatbot.svelte, ui/pnpm-lock.yaml
use color palette for chatbot colors.
=> use color palette for chatbot

ui/packages/app/index.html, ui/packages/app/src/Blocks.svelte, ui/packages/app/src/main.ts, ui/packages/app/vite.config.js
- all links now open in a new tab
- analytics is enabled in the svelte file, removes the annoying additional text during dev
- the config mustache templates are injected by a vite plugin to avoid syntax errors in the index file
Closes #1032
=> html tweaks

gradio/blocks.py, gradio/components.py, gradio/interface.py, gradio/test_data/blocks_configs.py, gradio/utils.py, ui/packages/app/src/Blocks.svelte, ui/packages/app/src/main.ts
=> Allow enabling queue per event listener

ui/packages/tabs/src/TabItem.svelte
=> wrap tab content in column

ui/packages/app/src/main.ts, ui/packages/image/src/Sketch.svelte, ui/packages/theme/src/colors.ts
Ensures that the Sketch placeholder text only appears when there is nothing on the canvas.
=> fix placeholder prompt

ui/packages/highlighted-text/src/HighlightedText.svelte, ui/packages/workbench/src/routes/highlightedtext.svelte
=> css tweaks

ui/packages/app/src/components/Gallery/Gallery.svelte, ui/packages/app/src/components/Json/Json.svelte, ui/packages/app/src/components/Label/Label.svelte, ui/packages/app/src/components/Row/Row.svelte, ui/packages/app/src/components/TimeSeries/TimeSeries.svelte, ui/packages/file/src/File.svelte, ui/packages/image/src/StaticImage.svelte, ui/packages/video/src/StaticVideo.svelte
Just makes image input -> image output interfaces tidier.
=> ensure defaults height match for media inputs

ui/packages/label/src/Label.svelte, ui/packages/workbench/src/routes/label.svelte
=> Labels spacing

ui/packages/app/src/Blocks.svelte, ui/packages/app/src/components/StatusTracker/StatusTracker.svelte, ui/packages/app/src/main.ts
Closes #1053.
- shows form the moment the page is loaded while fetching both config (where that happens) and loading the components + building the UI
- Error shows if config loading fails
- Error shows is there is an error when loading components or rendering teh app.
- Reuses the component StatusTracker
=> add global loader for gradio app

gradio/components.py, gradio/layouts.py, website/homepage/render_html.py, website/homepage/src/docs_template.html
Adds back docstrings for layouts to appear in the /docs page
=> layout docs

demo/blocks_kinematics/run.py, demo/blocks_update/run.py, demo/fake_gan/run.py, demo/fraud_detector/run.py, demo/generate_tone/run.py, demo/hello_world_3/run.py, demo/kitchen_sink/run.py, demo/outbreak_forecast/run.py, demo/sentence_builder/run.py, demo/stock_forecast/run.py, demo/titanic_survival/run.py, gradio/components.py, guides/create_your_own_friends_with_a_gan.md, test/test_components.py
make min and max first 2 args of slider
=> fix slider

ui/packages/app/src/Blocks.svelte, ui/packages/app/src/main.ts
=> only affect links within the document

ui/packages/app/index.html, ui/packages/table/src/Table.svelte
The dataframe wasn't working properly on mobile. Now it is.
=> ensure table works on mobile

gradio.egg-info/PKG-INFO, gradio/components.py, test/test_components.py, ui/packages/form/src/Number.svelte
=> Fix default cleared value

website/homepage/src/navbar.html
=> wesbite dropdown

ui/packages/app/tailwind.config.js, ui/packages/image/src/Sketch.svelte, ui/packages/theme/src/global.css, ui/packages/workbench/tailwind.config.cjs
dark mode bg tweak. Closes #1267
=> tweak bg colour

README.md, gradio/strings.py, gradio/utils.py, guides/getting_started.md, readme_template.md
* Updates README
* Updates beta invite message
=> updated messaging

gradio/__init__.py, gradio/components.py, website/homepage/src/index_template.html
* Exports `gradio.Dataset` (closes: #1318)
* Fixes audio docstring (closes: #1317)
=> fixes to component docs

demo/blocks_outputs/run.py, ui/packages/app/src/components/DataFrame/DataFrame.svelte, ui/packages/table/src/Table.svelte, ui/packages/workbench/src/routes/table.svelte
- Adds label to dataframe
- fixes bug with column creation
For now I've matched the style of the Forms since we don't wrap the table in a container like we do other components. We can tweak this in the future
Closes #1314.
@gary149 Maybe we can come up with something nicer.
=> add label to data frame

gradio/__init__.py, gradio/blocks.py, gradio/ipython_ext.py, test/test_blocks.py
Adds a jupyter extension `gradio` and associated magic command `%%blocks` that makes it easier to do iterative development with blocks, as shown in the GIF below:
=> Jupyter extension for easier development with Blocks

ui/packages/tabs/src/Tabs.svelte, ui/packages/workbench/src/routes/tabs.svelte
=> fix tab error

demo/blocks_kinematics/run.py, gradio/components.py
=> fix blocks-kinematics demo

CONTRIBUTING.md, gradio/reload.py, scripts/install_gradio.sh, setup.py
- add dev reload mode
- support reload mode from different directories as well
Took some time to do it right but it is completed now. Retrieve developer-reload-mode feature that was removed in #1278 and add support for different directories.
=> reload-dev-mode

.github/workflows/sizewatcher.yml, .sizewatcher.yml
Adds a CI check for the diff size in the PR
=> check-for-big-diff

demo/blocks_simple_squares/run.py, gradio.egg-info/PKG-INFO, gradio/blocks.py, gradio/components.py, gradio/routes.py
Deepcopy default variable value. Otherwise separate sessions will refer to the same value for the variable if the variable is not primitive.
=> fix default variable value

guides/creating_a_chatbot.md
The output should be a chatbot instead of text.
Easily verify the same here: [space-link](https://huggingface.co/spaces/abidlabs/chatbot-minimal/blob/main/app.py#L28)
=> Change output to chatbot

ui/packages/app/src/components/Plot/Plot.svelte, ui/packages/icons/src/Plot.svelte, ui/packages/icons/src/index.ts, ui/packages/model3D/src/Model3D.svelte, ui/packages/model3D/src/Model3DUpload.svelte, ui/packages/plot/package.json, ui/packages/plot/src/Plot.svelte, ui/pnpm-lock.yaml
Make splot consistent with other components:
- uses the `Block` container
- has a `StatusTracker`
- has a `BlockLabel`
- has its own shiny icon
=> update plot ui

demo/blocks_joined/run.py, gradio/components.py, ui/packages/app/src/components/Group/Group.svelte, ui/packages/atoms/src/Block.svelte, ui/packages/button/src/Button.svelte, ui/packages/theme/src/global.css, ui/packages/utils/src/styles.ts
Fixes the dall-e demo with the custom margins.
try `demo/blocks-combined`.
=> fix button styling

gradio/blocks.py, test/test_blocks.py
This addresses what discussed in #1371.
Closes: #1371
=> Changed share argument default in .launch method

README.md, render_readme.py
Removes unnecessarily complexity in github code snippets
=> readme code cleanup

demo/calculator/run.py, demo/image_mod/run.py, gradio/interface.py
Bring back flag options
Fixes: #1496
=> Restore flag options

ui/packages/app/src/components/Dataset/Dataset.svelte
Fix examples / Dataset component, which did not pass correct values beyond page 1.
Fixes: #1505
=> Fix examples

demo/blocks_multiple_event_triggers/run.py
=> add-multiple-event-demo

gradio/components.py, gradio/interface.py
This PR fixes the Model3D deserialization method, so that you can now call external Spaces that use the Model3D component. 
Fixes: #1516
=> Model3d deserialization

ui/packages/app/src/main.ts
Mount the user provided css to the page.
Closes #1487
=> mount custom css to the web component

gradio/components.py, gradio/events.py, website/homepage/render_html.py, website/homepage/src/docs_template.html
Fixes:
* https://github.com/gradio-app/gradio/issues/1368
=> added docs to events & styles

ui/packages/html/src/HTML.svelte
=> broken HTML [hotfix]

ui/packages/app/src/components/Column/Column.svelte, ui/packages/app/src/components/DataFrame/DataFrame.svelte, ui/packages/app/src/components/Dataset/Dataset.svelte, ui/packages/app/src/components/Row/Row.svelte, ui/packages/atoms/src/Block.svelte, ui/packages/button/src/Button.svelte, ui/packages/carousel/src/Carousel.svelte, ui/packages/html/src/HTML.svelte, ui/packages/tabs/src/TabItem.svelte
hidden must be !hidden to overwrite and block or flex. hidden conflicts with flex, !hidden gives !important to hidden to it overrides flex
=> Hidden fix [hotfix]

gradio/networking.py
=> fixed off by one error in messaging

demo/outbreak_forecast/run.py, gradio/components.py
Issue #1594: Plot component is not cached with examples
=> Issue #1594: Plot component is not cached with examples

gradio/components.py, gradio/routes.py
Fixes json serialization so it can handle numpy arrays.
Closes: #1399
Closes: #1408
=> Fixes json serialization issues

ui/packages/chatbot/src/ChatBot.svelte
=> Chatbot text color + custom style fixes

setup.py
In `setup.py`, this reads the version from `version.txt` to have a single source of truth.
Closes: #1629
=> Read version.txt

ui/packages/app/src/components/Column/Column.svelte
Just an overflow issue.
Closes #1618.
=> fix overflow

ui/packages/app/src/Blocks.svelte, ui/packages/app/src/main.ts
@osanseviero Reported some issues with styling when rendering the web component. This is fixed by this PR.
To test (from root):
```
cd ui
pnpm build:cdn-local
pnpm preview:cdn-local
```
Visit `http://localhost:3001`.
Demos should be only as high as they need to with no unnecessary vertical whitespace.
=> fix embedding css

test/test_tunneling.py
Closes: #1616 
The discussion is in the issue as well.
=> fix tunneling test

MANIFEST.in, setup.py
* relevant motivation #1697
* a summary of the change: *adds gradio/test_data in MANIFEST.in*
* which issue is fixed. #1697 maybe
* any additional dependencies that are required for this change. *no*
Closes: #1697 (issue)
=> Distribute gradio.test_data on pypi

.github/workflows/ui.yml
Run integration tests on all prs as opposed to just those that change the ui
=> Run integration tests on all prs

demo/blocks_plug/run.py, demo/blocks_xray/config.json, gradio/layouts.py, gradio/test_data/blocks_configs.py, ui/packages/app/src/Blocks.svelte, ui/packages/app/src/Render.svelte, ui/packages/app/src/components/TabItem/Tabs.svelte, ui/packages/app/src/components/Tabs/Tabs.svelte, ui/packages/tabs/src/TabItem.svelte, ui/packages/tabs/src/Tabs.svelte
Closes #1652 and implement steps noted in the issue.
To test run `demo/blocks_plug`.
=> allow users to update the current tab from python SDK

demo/calculator_blocks/run.py, demo/calculator_blocks_cached/run.py, gradio/examples.py, gradio/layouts.py, guides/adding_examples_to_your_app.md, guides/create_your_own_friends_with_a_gan.md, guides/getting_started.md, guides/image_classification_in_pytorch.md, guides/image_classification_in_tensorflow.md, guides/image_classification_with_vision_transformers.md, guides/using_hugging_face_integrations.md, website/homepage/src/docs/__init__.py, website/homepage/src/docs/obj_doc_template.html, website/homepage/src/docs/template.html
=> Add examples component to docs

test/requirements.txt, test/test_external.py
=> Updated `atomicwrites` version

gradio/components.py
Fixes #1773 
What it looks like in docs:
Tests failing for an unrelated issue
=> Add Dataframe to docs

website/homepage/src/docs/__init__.py
Simple change to remove the optional params from the blocks signature in docs
=> Update Blocks signature

demo/gender_sentence_custom_interpretation/run.py, gradio/interface.py, guides/advanced_interface_features.md
=> Clarify API of custom interpretation function + fix demo

website/homepage/src/guides/template.html, website/homepage/src/templates/meta.html
Don't know of any way to test except to deploy :D
=> Fixes the twitter image preview for Guides 

demo/color_generator/run.py
Add a color generator demo
https://huggingface.co/spaces/Zengyf-CVer/color_generator
Closes: [#1870](https://github.com/gradio-app/gradio/pull/1870)
=> Create a color generator demo

gradio/components.py
Closes: [# (issue)](https://github.com/gradio-app/gradio/pull/1870)
=> Add the color_generator annotation to the ColorPicker class

gradio/__init__.py, gradio/components.py, guides/custom_interpretations_with_blocks.md, website/homepage/src/docs/__init__.py, website/homepage/src/docs/obj_doc_template.html
=> Add Dataset and Interpretation to docs

gradio/blocks.py
=> Add example of using component update method 

ui/packages/app/src/components/Image/Image.svelte, ui/packages/image/src/Image.svelte
=> ensure falsey values are set to null for images

guides/how_to_use_3D_model_component.md
Add guide on using Model3D component
#1758
=> Add New Model3D Guide

gradio/blocks.py, website/homepage/src/docs/template.html
Reading through the docs, I think we need to add a little more explanation in this section: https://gradio.app/docs/#update-section-header
This is just a proposal of what we could add. Feel free to edit @freddyaboulton 
This code hasn't been tested as I'm traveling right now :)
=> Suggestion: add more info on `update()`

guides/getting_started.md
Small fix to make sharing image size smaller as requested by @aliabid94
=> Fix sharing image size in getting started

guides/1)getting_started/2)key_features.md
I added some more details on how data is preprocesses/postprocessed in one of the early Guides. Haven't been able to test locally b/c of travels, so I would appreciate if someone can do a quick review. 
Feedback welcome!
Fixes: #1740
=> How data flows through an app

scripts/build_frontend.sh, scripts/create_test_requirements.sh, scripts/format_backend.sh, scripts/format_frontend.sh, scripts/gh_action_pypi.sh, scripts/helpers.sh, scripts/install_gradio.sh, scripts/install_test_requirements.sh, scripts/launch_website.sh, scripts/run_all_tests.sh, scripts/run_circleci.sh, scripts/run_frontend.sh, scripts/upload_to_pypi.sh
Most of the scripts in the `scripts` folder were written in a complicated way, and there is no convincing reason for this when they can be made simpler (both in terms of reading and understanding) with a few relatively small changes. They also had bugs and I didn't just simplify...
This condition with a strange logic:
```bash
if [ -z "$(ls | grep CONTRIBUTING.md)" ]; then
echo "Please run the script from repo directory"
exit -1
else
...
fi
```
Replaced by this in short:
```bash
cd "$(dirname ${0})/.."
```
A comment for these line of codes in `gh_action_pypi.sh` to avoid misunderstanding:
```bash
old_version=$(grep -Po "(?<=version=\")[^\"]+(?=\")" setup.py)
read -r new_version < gradio/version.txt
sed -i "s/version=\"$old_version\"/version=\"$new_version\"/g" setup.py
```
The above code …
=> Scripts become much easier to read and understand

ui/packages/plot/src/Plot.svelte
https://user-images.githubusercontent.com/12725292/182257243-72a7aab1-0472-4ee6-9e79-31aa8950671d.mov
#1915
=> Fixes: Plot in first tab prevents the second tab from functioning

gradio/blocks.py, gradio/components.py, gradio/documentation.py, test/test_documentation.py, ui/packages/app/src/ApiDocs.svelte, ui/packages/app/src/components/types.ts
When we changed the documentation style, the view API page for Interfaces got broken. Should be fixed now.
=> Fix broken API page

ui/packages/file/src/File.svelte
=> Fixes Download button does not respect the filepath returned by the function

demo/blocks_outputs/config.json, demo/blocks_outputs/run.py, gradio/components.py, test/test_components.py
=> default to a single table row

demo/fake_gan_2/run.py, ui/packages/app/src/Blocks.svelte, ui/packages/app/src/Render.svelte, ui/packages/app/src/api.ts, ui/packages/app/src/components/Chatbot/Chatbot.test.ts, ui/packages/app/src/components/ColorPicker/ColorPicker.test.ts, ui/packages/app/src/components/StatusTracker/StatusTracker.svelte, ui/packages/app/src/components/StatusTracker/types.ts, ui/packages/app/src/components/Textbox/Textbox.test.ts, ui/packages/app/src/main.ts, ui/packages/app/src/stores.ts, ui/pnpm-lock.yaml
This works for the most part although there is some strangeness around the status indicator that I've been able to fully resolve. I think some of the smaller PRs going into the base branch may have implications for the frontend, so it would be good to get those in and retest this.
=> implement queue frontend

gradio/blocks.py, gradio/event_queue.py
1. keep ws connection open after the event process is complete
2. do not send estimations periodically if live queue updates is true
=> Queue keep ws connections open

gradio/blocks.py, gradio/event_queue.py
Some tweaks on the Estimation payload after offline discussions with Ali. Will be merged after #1910
=> Queue tweaks

website/demos/Dockerfile, website/homepage/Dockerfile
Fixes #1654. You can test this on http://54.189.115.49/docs/
Finally got the demos to show up locally 🥲
=> Fix local website build

gradio/__init__.py, gradio/examples.py, gradio/interface.py, gradio/mix.py, test/test_examples.py, test/test_mix.py
Closes: #1999 
Note: commented out one of the tests because we think it will get fixed by #1967
=> Fix async tests

gradio/event_queue.py
1. make gather_data and broadcast_estimation sequential instead of concurrent because they were deleting elements at the same time and raising expections which was lowering the performance
=> queue-concurrency-tweaks

ui/packages/app/index.html, ui/packages/app/src/api.ts
=> Fix space embedding w queue [hotfix]

gradio/components.py, gradio/examples.py, ui/packages/app/src/components/Dataset/Dataset.svelte
Noticed some small issues with the Dataset component
=> dataset-fixes

ui/packages/app/src/components/StatusTracker/StatusTracker.svelte
=> UI: update error message

gradio/components.py, test/test_components.py
Quick fix for #2217 and a corresponding test
=> Fix `HighlightedText` component

.github/workflows/delete-stale-spaces.yml, scripts/delete_old_spaces.py
=> Delete spaces created on PRs after a certain amount of time

gradio/blocks.py, test/test_blocks.py
=> Fix postprocess when value is a dict with only one key

.github/workflows/deploy-pypi.yml, .github/workflows/deploy-spaces.yml
To prevent the job from failing on the PR
=> Do not deploy pr to spaces on prs originating from forks

website/homepage/package.json, website/reload_website.sh, website/reload_with_notification.sh
Fixes the remaining issues in #1731:
Fixes #1731
=> Website fixes and refactoring

guides/5)other_tutorials/running_background_tasks.md
Fix an image path I messed up in #2350
=> Fix typo in guide image path

guides/1)getting_started/2)key_features.md, guides/3)building_with_blocks/1)blocks_and_event_listeners.md, guides/3)building_with_blocks/2)controlling_layout.md
just some typos while reading the doc
=> [doc] typos

CHANGELOG.md, website/homepage/Dockerfile
Since the website is now rendering the changelog, needed to add one line the the Dockerfile to copy the CHANGELOG.md file in the root.
=> Copy changelog file in website docker

.github/workflows/deploy-spaces.yml, CHANGELOG.md, scripts/format_release_notes.py
Manually fix release and fix github action
If you would like an image/gif/video showcasing your feature, it may …
=> Fix CHANGELOG for 3.4.1 release

CHANGELOG.md, ui/packages/image/src/Image.svelte, ui/packages/image/src/Sketch.svelte, ui/packages/upload/src/Upload.svelte
=> 1711 image upload

CHANGELOG.md, gradio/blocks.py
=> bug fix (return ValueError → raise ValueError)

CHANGELOG.md
Github action for formatting the changelog is failing because `main` is a protected branch. Didn't come up when I tested this cause I tested on my fork in which main is not protected 🤦‍♂️ 
Will be fixed in #2488 
If you would like to …
=> Manually format changelog

gradio/tunneling.py
Related to https://github.com/gradio-app/gradio/pull/2509.
Privilege key is now generated based on the current timestamp using md5 hash.
(minor/cosmetic changes) I've also set most of the functions as "private" by prepending a `_` so that `create_tunnel` is seen as the only entrypoint of the module. Idk Gradio policy on this but it seems cleaner to me. And I also moved some comments from @XciD in function dosctrings.
=> Make private method + generate privilege key

CHANGELOG.md
Github action seems to have failed to update the changelog and move upcoming release to the correct version, so doing it manually for v3.7
=> Temporary Changelog Update

CHANGELOG.md, ui/packages/plot/src/Plot.svelte
Fixes plotly whitespace issue.
Closes: #2500 
If you would like to elaborate …
=> fixes plotly whitespace

.circleci/config.yml, gradio/blocks.py, gradio/context.py, gradio/interface.py, gradio/interpretation.py, gradio/layouts.py, gradio/queue.py, gradio/test_data/__init__.py, scripts/format_backend.sh, scripts/lint_backend.sh, test/test_interpretation.py, test/test_tunneling.py
Fixes #2503
No changelog since it's not a user facing change
If you would like an image/gif/video showcasing your …
=> Modify CI to check for unused imports

CHANGELOG.md
=> Changelog update for 3.8

CHANGELOG.md
If you would like an image/gif/video showcasing your feature, it may be best to edit the …
=> Update Changelog 3.9

website/reload_website.sh
Small change to the reload website script that makes it track main again.
=> Reload website on every commit

demo/map_airbnb/DESCRIPTION.md, gradio/components.py, website/homepage/src/demos/__init__.py
As discussed in our brainstorming session, moving the airbnb map to demos. …
=> Move AirBnB map demo to demos page

CHANGELOG.md, gradio/networking.py
Thanks @aliabid94 for the help chasing this down, ended up being a pretty simple fix :)
Fixes: #2700
=> Increase websocket size to 1 GB

CHANGELOG.md
=> Add Scatterplot Img to Changelog

CHANGELOG.md
Just bumping the changelog
If you would like an image/gif/video showcasing your feature, it may …
=> v3.13.0 Release notes

CHANGELOG.md
Manual fix
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG …
=> Format 3.13.2 release notes

CHANGELOG.md, guides/05_tabular_data_science_and_plots/creating_a_dashboard_from_bigquery_data.md
Small fixes to the codeblocks in changelog and the bigquery guide that solve the annoying formatting issue. 
Fixes #2841
=> Fix formatting issues in Big Query guide and Changelog

CHANGELOG.md, website/homepage/src/docs/__init__.py, website/homepage/src/docs/template.html
Adds a matrix to the docs showing which events are supported by each component. 
https://user-images.githubusercontent.com/9021060/210368944-1b3774b1-d106-4b23-bf62-476b5c9810b4.mov
Closes #1923
=> Add a components - events matrix on the docs

CHANGELOG.md
v3.15.0 is listed twice. 
If you would like an image/gif/video showcasing your feature, it may be best to edit …
=> Fix version typo in changelog

CHANGELOG.md, gradio/blocks.py, test/test_blocks.py, test/test_routes.py
Fixes #2937 and adds unit test for `mount_gradio_app`
If you would like an image/gif/video showcasing your …
=> Fix bug in mount_gradio_app with queue enabled

CHANGELOG.md, gradio/external.py, test/test_external.py
Fixes #2982 
Fixes: #2956 
Added unit tests but you can also test with `gr.Interface.load("models/microsoft/DialoGPT-medium")` (conversational) and `gr.Interface.load("models/nlpconnect/vit-gpt2-image-captioning")` (text-to-image)
If …
=> Add conversational and text-to-image pipelines to Interface.load

website/homepage/nginx.conf
There was an infinite redirect loop in the nginx conf for `/quickstart` 
Built locally and I think it's working lol
Gonna merge this in @aliabd since it's broken for all users. Hopefully I don't break it more 😂 
If you would like to …
=> Undo quickstart redirect

CHANGELOG.md, gradio/routes.py, guides/01_getting-started/03_sharing-your-app.md, test/test_blocks.py, ui/packages/app/src/Login.svelte, ui/packages/app/src/main.ts
Fixes auth on spaces. Also in iframes I think. Fixes #2472 
Originally I thought we needed a different approach than #2112 but turns out @aliabid94 did all the hard work already 😄 
This branch is the logic of #2112 with some minor changes:
- Fixes the login button so that you can login after clicking it. Previously it did nothing.
- Adds a message that third party cookies must be enabled in incognito mode in order to use auth on spaces
- Changes the styling of the login page so that the content is vertical. Before the "Login" headder, auth_message, and username/password fields were all displayed horizontally and it looked weird imo.
Visit this space https://huggingface.co/spaces/freddyaboulton/hello_login_main
All pull requests must update …
=> Fix auth on spaces

ui/packages/app/build_plugins.ts, ui/packages/app/src/main.ts, ui/pnpm-lock.yaml
Left over dev mode bug from previous change to scoping. 
If …
=> only mount fonts in prod mode

CHANGELOG.md, guides/01_getting-started/01_quickstart.md
This fixes a broken link in the quickstart guide.
=> [Minor] Correct link

CHANGELOG.md, guides/03_building-with-blocks/02_controlling-layout.md
Fixes #2120
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG …
=> Update docs on equal_height param for Rows

CHANGELOG.md, guides/04_integrating-other-frameworks/Gradio-and-Wandb-Integration.md
Makes changes to the W&B guide originally proposed by @scottire in #2994 
Closes: https://github.com/gradio-app/gradio/issues/2757
=> Changes to W&B guide

CHANGELOG.md, guides/01_getting-started/01_quickstart.md
Sometimes it's not very clear how to run a Gradio app locally. This PR adds a small section in the quick start explaining how to do so.
=> Add a section on how to run a Gradio app locally

CHANGELOG.md, gradio/blocks.py, gradio/test_data/blocks_configs.py, test/test_blocks.py, ui/packages/app/src/components/types.ts
Needed for the client libraries
Fixes #3314
If you would like an image/gif/video showcasing your feature, it may …
=> Add types field to dependency config 

CHANGELOG.md, ui/packages/theme/src/reset.css, ui/packages/theme/src/typography.css
fixes #3329.
Needed some CSS tweaks. Slightly tricky but this should work. …
=> fix markdown css

CHANGELOG.md, ui/packages/gallery/src/Gallery.svelte
Fixes #3320
Example on `gallery_component` demo
If you would like an image/gif/video showcasing your feature, it …
=> Apply height in Gallery.style

CHANGELOG.md
Simple change fixing a bad codeblock in the changelog that caused issues with rendering. 
Closes: #3393
=> Fix changelog rendering

.github/workflows/publish-npm.yml, ui/.changeset/config.json, ui/package.json, ui/pnpm-lock.yaml
Closes #3404. Publishes to npm.
=> fix npm publish

ui/.changeset/config.json
=> make changesets ignore `@gradio/app`

test/test_blocks.py
Fixes the Windows flake (should have included this in the earlier PR) -- cc @freddyaboulton @space-nuko
=> Fix windows flake

CHANGELOG.md, client/python/gradio_client/serializing.py
I think there was a small typo in the wording here. Is it required to change the CHANGELOG.md for such small changes?
=> Nit in ValueError

.github/workflows/backend.yml, client/python/README.md, client/python/gradio_client/client.py, client/python/requirements.txt, client/python/test/conftest.py, client/python/test/requirements.txt
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the …
=> Add job for python client ci

client/python/gradio_client/client.py, client/python/test/test_client.py
Makes the `Job` iterable so that devs can pull the latest output as it arrives and do something with it.
I think this will make it really easy to build applications based on streaming outputs, like LLM Chatbots. Example with images:
```python
import gradio_client as grc
generator_client = grc.Client(src="gradio/count_generator")
def gen_images():
for image1, image2 in generator_client.predict(3, api_name="/gen_images"):
yield image1, image2
with gr.Row():
image_1 = gr.Image()
image_2 = gr.Image()
with gr.Row():
gen_btn = gr.Button("Generate!")
gen_btn.click(gen_images, None, [image_1, image_2])
demo.queue(concurrency_count=10).launch()
```
All pull requests must update the change log located in CHANGELOG.md, …
=> Make Client Jobs Iterable

client/python/gradio_client/client.py, client/python/gradio_client/utils.py
Small PR to add a verbose flag to the client and also print a message if a user checks the status of a job and there's a long queue
=> Py client verbose

CHANGELOG.md, js/app/src/api_docs/ApiDocs.svelte
Issue Solved : After clicking "Use Via API" button at bottom of gradio interface, and when clicking "tyr it out" it gives 
@abidlabs  Check this PR if everything is ok with it
Closes: #3774 
If you would like to elaborate on your …
=> Solved API submission issue

CHANGELOG.md, js/app/src/components/UploadButton/UploadButton.svelte
The upload button was not properly handling the case of multiple files. Going to test in colab once the PR wheel gets built.
Closes: #3729, Closes: #3790
Edit: Works in colab!
If you would like to elaborate on your change further, …
=> Fix Upload Button

CHANGELOG.md, js/video/src/Player.svelte
Closes: #3920
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG …
=> Fix duplicate play commands in full-screen mode of `Vidieo`

CHANGELOG.md, client/python/test/requirements.txt, gradio/flagging.py, test/requirements-37.txt, test/requirements.txt
=> Upgrade pyright to 1.1.305

CHANGELOG.md, website/homepage/Dockerfile
Upgrading node and pnpm in the website Dockerfile to resolve current build issues. Tested on dev and worked fine.
=> Fix website build issue

.config/.prettierignore
These directories should also be ignored by Prettier when developing the frontend.
If you would like an …
=> Update .prettierignore adding client/js/dist and .venv

.vscode/settings.json
=> Fix the prettier.ignorePath field in the VSCode workspace settings

.vscode/settings.json, test/test_interfaces.py
This test just failed on [main](https://github.com/gradio-app/gradio/actions/runs/4949038731/jobs/8850657168#step:11:171) so refactoring it so that it doesn't flake again.
Also adding a line to the vs code config so that you can run tests from vs code. …
=> Fix flaky interface test

.github/workflows/publish-npm.yml
We need this action to run every time main change or it won't stay up to date and we cant merge. …
=> update ci - npm publish

.changeset/config.json, .changeset/funny-balloons-clap.md
=> bump client version

.github/workflows/publish-npm.yml
=> update token for npm action

.github/workflows/publish-npm.yml, package.json
=> Fix npm publish again again

CHANGELOG.md, gradio/helpers.py
=> Fix "TypeError: issubclass() arg 1 must be a class" When Optional args 

.changeset/hip-bags-smile.md, client/js/vite.config.js
Fix external `semiver` import to ensure CDN links work correctly. …
=> Fix semiver import

.github/workflows/publish-npm.yml
=> Fix publish

js/workbench/package.json
=> make workbench private

CHANGELOG.md, client/python/gradio_client/client.py, client/python/test/requirements.txt, client/python/test/test_serializing.py, gradio/external.py, gradio/interface.py, gradio/themes/utils/semver_match.py, test/requirements-37.txt, test/requirements.txt, test/test_blocks.py, test/test_components.py, test/test_networking.py, test/test_theme_sharing.py
This PR upgrades Black from 22.6 to 23.3 and runs it accordingly.
=> Upgrade black to 23.3

client/js/README.md
Small typo fixes.
If you would like an image/gif/video showcasing your feature, it may be best to edit the …
=> Fix typo in client/js/README.md

client/js/src/client.ts
First I thought the `api` variable should have its type annotation for readability, then updated the relevant lines.
I removed `[{ error: string }, 500]` from the return type of `view_config()` which looks like a drastic change. However, even the current type annotation on L48 (`view_api: (c?: Config) => Promise<Record<string, any>>`) already ignores this error case and there are also some lines where we use `api` without caring the error case such as https://github.com/gradio-app/gradio/blob/38607c9967ba6421a9b53c1fd9c94c29e4338365/client/js/src/client.ts#L339, so I judged removing this return type has no effect practically.
All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the …
=> Fix a return type of view_config()

client/js/src/client.ts
Looks like the type-check passes without this `@ts-ignore`.
If you would like an image/gif/video showcasing your …
=> Remove unnecessary @ts-ignore

client/js/src/client.ts
For first-time readers, `const` has more information helping read the code. …
=> Stop using `let` for unchanged variables in `client.ts`

.changeset/soft-insects-know.md, client/js/src/client.ts
Various client refactors.
If you would like to elaborate on …
=> various client refactors + tweaks

CHANGELOG.md, js/app/src/css.ts, pnpm-lock.yaml
=> Restore offline support

.github/workflows/build-version-docs.yml
=> Fix indent in Create Version Docs action

CHANGELOG.md, js/video/src/Player.svelte, js/video/src/StaticVideo.svelte
=> Fix Safari video playback

gradio/components.py
added accidentally on https://github.com/gradio-app/gradio/pull/4481
=> Remove carousel from docs

CHANGELOG.md, js/app/src/lang/ca.json
=> Add Catalan translation

CHANGELOG.md, demo/audio_component/run.py, js/app/src/components/Chatbot/Chatbot.test.ts, js/chatbot/src/ChatBot.svelte, js/chatbot/src/MarkdownCode.svelte, js/theme/src/reset.css, package.json, pnpm-lock.yaml
Closes #4514.
Fix is slightly weird. There could be a bug in our code or there could be a really specific bug in Svelte but that will take some time to debug. This seems to work but I'd appreciate it if someone else could test it too.
a link to the PR (formatted in markdown) and a link to your github …
=> 4614 chatbot

.github/ISSUE_TEMPLATE/bug_report_template.yml
You can see it working here: https://github.com/abidlabs/gradio/issues/new?assignees=&labels=bug&projects=&template=bug_report_template.yml
=> Hotfix for bug issue template

renovate.json
Quick one to ignore the svelte updates for now. Will take care of that manually.
=> ignore svelte

js/app/src/components/Gallery/Gallery.test.ts, js/app/vite.config.js, js/gallery/src/Gallery.svelte, package.json, pnpm-lock.yaml
Need to update our test env but there is a failing test i need to fix here.
=> switch unit test env to jsdom

js/app/test/blocks_chained_events.spec.ts
=> Success e2e test fix

js/app/src/components/Radio/Radio.svelte, js/app/src/components/Radio/Radio.test.ts, js/form/src/Radio.svelte
Unit test for a radio component. 
Closes: #4711
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all …
=> Add radio unit test

CHANGELOG.md
Fixes the changelog issues on the website.
=> Fix changelog issues in website

js/app/src/components/Gallery/Gallery.stories.svelte
Adds some stories for the gallery component. One of our most used components and it has lots of styling options.
1. Unless the pull request is labeled with the …
=> Add storybook for Gallery

CHANGELOG.md, js/app/src/components/File/File.svelte, js/app/src/components/File/File.test.ts
Fixes: #4799
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all pull requests must update the …
=> Fire File change event when updated programmatically

.config/.prettierignore
Following https://github.com/gradio-app/gradio/pull/4824#discussion_r1257947048
1. Unless the pull request is labeled with the "no-changelog-update" label by a …
=> Remove an unnecessary line of .prettierignore

.github/workflows/deploy-pr-to-spaces.yml
=> add wheel install instructions to PR comment

.github/workflows/deploy-pr-to-spaces.yml
=> update pr comment

.config/playwright.config.js, .github/workflows/ui.yml, js/app/test/blocks_chained_events.spec.ts, package.json
=> Fix flaky ui test

CHANGELOG.md, gradio/components/audio.py, gradio/components/video.py, requirements.txt, test/test_components.py
Closes #4878 
You can test with this repro (also added a unit test)
```python
import gradio
url: str = "https://gradio-builds.s3.amazonaws.com/demo-files/a.mp4"
with gradio.Blocks() as interface:
video_in: gradio.Video = gradio.Video(value=url, autoplay=False)
video_out: gradio.Video = gradio.Video()
run: gradio.Button = gradio.Button()
run.click(lambda x: x, video_in, video_out)
interface.launch(debug=True)
```
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up …
=> Fix bug related to preprocessing URLs for video

.github/workflows/deploy-chromatic.yml, js/_website/src/routes/docs/block-layouts/+page.server.ts
gr.Group is missing from the [block layouts docs](https://www.gradio.app/docs/block-layouts) because of a mistake in the website code. This adds it back. 
Closes this from #4804:
=> Add gr.Group to docs

package.json, pnpm-lock.yaml
=> remove three types

CHANGELOG.md, gradio/blocks.py, gradio/utils.py
Internal Slack conversation : https://huggingface.slack.com/archives/C04ABS7C13K/p1689176130473819
=> Queue `max_size` defaults to Block's `max_threads` on ZeroGPU Spaces

guides/04_chatbots/01_creating-a-chatbot-fast.md
=> Quick fix for langchain, openai examples in Guide

guides/04_chatbots/01_creating-a-chatbot-fast.md
=> Quick fix to chat interface code example

CHANGELOG.md, gradio/chat_interface.py, gradio/events.py, test/test_chat_interface.py
Fixes #4975
Saves us a trip from client to server but we still send the entire history from the server to the client for streaming updates
1. Unless the pull …
=> Use state in ChatInterface

CHANGELOG.md, gradio/components/audio.py, js/app/src/components/Audio/Audio.svelte, js/audio/src/StaticAudio.svelte, test/test_components.py
Reverts gradio-app/gradio#4977 -- just until we have the new changelog process
=> Revert "Add download button for audio"

client/python/CHANGELOG.md
=> Fix client changelog

.changeset/changeset.cjs, .github/PULL_REQUEST_TEMPLATE.md
=> Fix changesets action

.github/workflows/generate-changeset.yml
=> Ci fix 1234

test/test_blocks.py
Set ZeroGPU env with MonkeyPatch in the tests (cc @freddyaboulton)
=> [Spaces] ZeroGPU Queue fix - Part.2

.changeset/cyan-dolls-visit.md, .changeset/eight-humans-sniff.md, .changeset/gold-radios-train.md, .changeset/legal-beds-beam.md, .changeset/plain-ties-pick.md, .changeset/silver-signs-speak.md, .changeset/smooth-humans-flash.md
=> fix changelogs

.github/workflows/build-pr.yml, .github/workflows/deploy-pr-to-spaces.yml, scripts/copy_demos.py
=> Install client in PR Build

.github/workflows/generate-changeset.yml, .github/workflows/ui.yml
=> Ci fixes asd

.github/workflows/ui.yml
=> Another fix for ci

.changeset/young-olives-yell.md, .github/workflows/generate-changeset.yml, .github/workflows/ui.yml, js/_website/src/lib/assets/demo_code.js, js/_website/src/lib/components/DemosLanding.svelte, js/_website/src/routes/+page.svelte
Last night I noticed that the demos on the landing page don't reflect the latest "gen ai boom" so I added the llama2 ChatInterface and a Stable Diffusion demo.
=> homepage demo update

demo/chatbot_multimodal/run.py
remove the `.style(...` methods to remove the `deprecation` warnings in the output
=> update to remove `deprecation` warnings

.changeset/fix_changelogs.cjs
=> pin local dependencies when auto-bumping

.changeset/early-guests-visit.md, js/lite/package.json, pnpm-lock.yaml
=> add gradio as a devdep of @gradio/lite

.changeset/dirty-snails-love.md, demo/chatbot_multimodal/run.py, gradio/interface.py, js/app/src/Blocks.svelte, test/test_interfaces.py
Closes: #5203
Also adds `api_name` to Interface class so developers can change the api_name from `predict` or set it to False.
=> Completely hide api page if show_api=False

guides/04_chatbots/03_creating-a-discord-bot-from-a-gradio-app.md
Resolved a typo in the Discord bot documentation.
Should be small enough.
N/A
- Tom Aarsen
=> typo: addion -> addition

.changeset/salty-toys-rest.md, .github/workflows/backend.yml, requirements.txt
=> Remove aiohttp dependency

.changeset/silver-clowns-brush.md
=> fix changeset

.changeset/large-bats-say.md, js/app/src/Blocks.svelte
=> only start listening for events after the components are mounted

.changeset/fix_changelogs.cjs
=> fix changelog generation

.changeset/puny-wombats-tell.md, js/chatbot/Chatbot.stories.svelte, js/chatbot/Chatbot.test.ts, js/chatbot/static/ChatBot.svelte
Hide avatar when message none
Closes: #5357
=> Hide avatar when message none

.changeset/happy-hairs-tell.md, js/markdown/Markdown.stories.svelte, js/markdown/static/Markdown.svelte
Quick fix & visual test, fixes: #5387
=> Adds horizontal scrolling to content that overflows in gr.Markdown

guides/01_getting-started/03_sharing-your-app.md
Fixes small typo in API guide.
Closes: #5388
=> Update guide for API

.github/workflows/backend.yml, .github/workflows/build-pr.yml, .github/workflows/check-demo-notebooks.yml, .github/workflows/delete-stale-spaces.yml, .github/workflows/deploy-chromatic.yml, .github/workflows/deploy-pr-to-spaces.yml, .github/workflows/deploy-website.yml, .github/workflows/generate-changeset.yml, .github/workflows/large-files.yml, .github/workflows/publish-npm.yml, .github/workflows/report-notebook-status-pr.yml, .github/workflows/ui.yml
=> revert to actions/checkout v3

.changeset/six-months-act.md, js/app/index.html, js/app/src/Embed.svelte
Bug repro:
- go here https://huggingface.co/spaces/gradio-pr-deploys/pr-5445-all-demos. (last preview)
- go to `matrix_transform`
- add new rows until the dataframe stops getting bigger
- spam click loads of rows
- scroll to the top of the dataframe
fix test:
- go here: https://huggingface.co/spaces/gradio-pr-deploys/pr-5447-all-demos (this pr preview)
- repeat above steps. …
=> ensure iframe is correct size on spaces

.changeset/tidy-lemons-eat.md, js/dataframe/shared/EditableCell.svelte, js/dataframe/shared/Table.svelte
=> ensure dataframe doesn't steal focus

.changeset/tricky-rabbits-glow.md, js/chatbot/static/ChatBot.svelte
Fix share button position
Closes: #5435
=> Fix share button position

.github/workflows/publish-npm.yml, .github/workflows/trigger-changeset.yml
Quick workflow update so that the v4 branch works.
=> update changeset workflow for v4

.changeset/cold-hoops-heal.md, js/atoms/package.json, js/column/package.json, js/icons/package.json, js/statustracker/package.json, js/tooltip/package.json, js/upload/package.json, js/utils/package.json
This PR releases the following packages (in beta mode hopefully)
- `@gradio/atoms`
- `@gradio/column`
- `@gradio/icons`
- `@gradio/statustracker`
- `@gradio/tooltip`
- `@gradio/upload`
- `@gradio/utils`
This is require for the ongoing work on custom components and is also a good test for the beta release workflow.
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) …
=> release first version

.changeset/fruity-ducks-stay.md, js/gallery/static/Gallery.svelte, js/image/interactive/Image.svelte, js/image/static/ImagePreview.svelte
Lazy loading of images in Image and Gallery
Fixes: #2236
=> Lazy load all images

js/gallery/Gallery.stories.svelte
=> Fix typo in Gallery.stories.svelte

.changeset/chubby-hats-type.md, .changeset/fruity-ducks-stay.md
so that we can release a patch version: 3.44.1
=> fix changesets

.changeset/fine-lamps-take.md, gradio/components/image.py
Minor docstring nit after #5537 
=> Modify Image examples docstring

.changeset/full-doodles-carry.md, js/app/src/lang/eu.json
Added some basque translations.
=> Adding basque language

.github/workflows/build-pr.yml, demo/kitchen_sink_random/run.py, gradio/components/base.py, gradio/components/clear_button.py, gradio/components/dataframe.py, gradio/components/image.py, gradio/interface.py
Fix all_demos in custom-components
=> Fix all demos custom components

.changeset/deep-bugs-study.md, .changeset/eager-wasps-move.md, .changeset/fine-lamps-take.md, .changeset/fluffy-sloths-help.md, .changeset/full-doodles-carry.md, .changeset/new-chairs-kick.md
for yet another patch release :D
=> Fix changesets again

.changeset/hot-words-sin.md, guides/01_getting-started/02_key-features.md, guides/01_getting-started/03_sharing-your-app.md, js/_website/src/lib/assets/prism.css, js/_website/src/routes/[[version]]/guides/[guide]/+page.svelte
Fixes code font on guides, adds previous and next guide buttons, and fixes some broken links.
Closes: #5490 
Closes: #5491 
Closes: #5492
=> Styling fixes to guides

.changeset/purple-jokes-shake.md, gradio/component_meta.py, gradio/components/annotated_image.py, gradio/components/audio.py, gradio/components/bar_plot.py, gradio/components/button.py, gradio/components/checkbox.py, gradio/components/checkboxgroup.py, gradio/components/code.py, gradio/components/color_picker.py, gradio/components/dataframe.py, gradio/components/dropdown.py, gradio/components/file.py, gradio/components/highlighted_text.py, gradio/components/json_component.py, gradio/components/line_plot.py, gradio/components/number.py, gradio/components/radio.py, gradio/components/scatter_plot.py, gradio/components/textbox.py, gradio/events.py, test/test_blocks.py
Do some linting on the backend
=> backend linting

.changeset/lazy-aliens-drive.md, js/theme/package.json
gradio/utils depends on gradio/theme but theme is not published.
=> Publish js theme

package.json
=> Fix build command typo

.changeset/easy-mirrors-retire.md, gradio/cli/commands/create.py
=> Add docstring to trigger release

.changeset/three-trams-sniff.md, gradio/cli/commands/create.py, gradio/cli/commands/files/NoTemplateComponent.py, gradio/cli/commands/files/gitignore, gradio/cli/commands/files/pyproject_.toml, gradio/components/base.py, gradio/data_classes.py, pyproject.toml, requirements.txt
* CC authors can now choose their package name
* Adding node_modules to gitignore
* Have pyright Ignore some build files
* Set version 2 lower bound on pydantic
FYI @pngwn  …
=> Some minor v4 fixes

.changeset/slick-pants-stand.md, gradio/cli/commands/create.py
Add --overwrite flag to create command. If the directory exists, exit unless overwrite is passed in.
=> Add overwrite flag to create command

.changeset/strong-peas-tell.md, gradio/cli/commands/components/_create_utils.py, js/app/build_plugins.ts, js/app/src/Index.svelte, js/app/vite.config.ts
- Fix build command so that it doesn't overwrite the build targets from previous steps
- Fix the file route when demo reloads
- Fix the test dir check to be OS-agnostic
cc @pngwn  …
=> Fix build and file route

.changeset/young-glasses-juggle.md, gradio/blocks.py
Quick fix for: [internal link]
Running on Space here: https://huggingface.co/spaces/abidlabs/share-test
=> setting share=True on Spaces or in wasm should warn instead of raising error

.changeset/fluffy-jokes-crash.md, js/slider/shared/Range.svelte
Increase Slider clickable area
Closes: N/A
=> Increase Slider clickable area

.changeset/purple-laws-smoke.md, js/dataframe/shared/Table.svelte
Fixes gr.select() Method Issues with Dataframe Cells
Closes: #5706
=> Fixes gr.select() Method Issues with Dataframe Cells

.changeset/nice-actors-write.md, gradio/cli/commands/components/_create_utils.py, test/test_gradio_component_cli.py
Fix the regex that was breaking Image template
=> Fix component regex

.changeset/some-shoes-relate.md, gradio/cli/commands/components/_create_utils.py, test/test_gradio_component_cli.py
Fix layout templates (also JSON component) 😅 
=> Fix layout templates

.changeset/some-shoes-relate.md, gradio/cli/commands/components/_create_utils.py, gradio/cli/commands/components/create.py, test/test_gradio_component_cli.py
=> --overwrite deletes previous content

.changeset/true-bugs-shine.md, client/python/gradio_client/client.py, client/python/gradio_client/utils.py, gradio/blocks.py, test/test_blocks.py, test/test_components.py, test/test_mix.py, test/test_pipelines.py
And remove the xfail mark from tests that pass now!
=> Support call method

.changeset/icy-cars-boil.md, gradio/blocks.py, gradio/templates.py, js/audio/interactive/Audio.svelte
=> Fix deployed demos on v4 branch

.changeset/green-pillows-flash.md, gradio/components/chatbot.py, gradio/components/dataframe.py, gradio/components/markdown.py, js/chatbot/static/ChatBot.svelte, js/chatbot/static/StaticChatbot.svelte, js/dataframe/interactive/InteractiveDataframe.svelte, js/dataframe/shared/EditableCell.svelte, js/dataframe/shared/Table.svelte, js/dataframe/static/StaticDataframe.svelte, js/markdown/static/Markdown.svelte, js/markdown/static/MarkdownCode.svelte, js/markdown/static/StaticMarkdown.svelte, js/markdown/static/utils.ts, test/test_components.py, test/test_files/xray_config.json, test/test_files/xray_config_diff_ids.json, test/test_files/xray_config_wrong.json
Adds `line_breaks` param to chatbot, dataframe, and markdown components.
Sets `line_breaks: True` for chatbot and dataframe, and `False` for markdown
Closes: #4344 …
=> Fix new line issue in chatbot

gradio/blocks.py, gradio/component_meta.py, gradio/components/base.py, gradio/routes.py, test/test_components.py
As discussed with @pngwn 
* Added a TEMPLATES_DIR class variable
* Added a `component_class_id` that's unique to each component class
* Moved `component_class_id` and `module_location` to the "top level" blocks config and not as props.
2. You may need to run the …
=> Improvements for component build in V4

.changeset/breezy-birds-bathe.md, js/lite/package.json, js/wasm/package.json, pnpm-lock.yaml
=> fix @gradio/lite dependencies

.changeset/public-chairs-chew.md, js/preview/package.json, js/preview/src/dev.ts, js/preview/src/examine.py, js/preview/src/index.ts, pnpm-lock.yaml
=> In dev/build use full path to python/gradio executables

.changeset/two-games-dress.md, js/app/src/Blocks.svelte, js/app/src/Index.svelte, js/app/src/Render.svelte, js/app/src/main.ts, js/app/src/types.ts, js/app/src/vite-env-override.d.ts
Reinstate types that were removed in error in #5832.
=> Reinstate types that were removed in error in #5832.

.changeset/sad-webs-end.md, js/audio/interactive/Audio.svelte, js/audio/shared/Audio.svelte, js/image/example/Image.svelte, js/image/shared/Image.svelte, js/video/shared/Player.svelte, js/video/shared/Video.svelte
Fixes some styling issues introduced by #5627
=> Fix styling issues with Audio, Image and Video components

.changeset/tasty-candies-type.md, gradio/component_meta.py
The pyi file for Component was not being updated - causing pyright to issue false positives during local dev
=> V4: Update Component pyi file

.changeset/gentle-parks-fry.md, js/wasm/package.json
=> release wasm

.changeset/shy-ghosts-turn.md, js/wasm/src/webworker/index.ts
=> Lite: Explicitly install a specific version of `anyio` to avoid version conflicts

.changeset/serious-pears-tell.md
=> release lite

.changeset/wet-dingos-battle.md, js/wasm/src/webworker/index.ts
I wrote the worker code based on stlite, but left this part unfixed:
https://github.com/whitphx/stlite/blob/2d78c08d83b3ca1989735b4088812a20e57ec748/packages/kernel/src/worker.ts#L458-L461
2. You may need to run the linters: `bash scripts/format_backend.sh` and …
=> Lite fix matplotlib install postprocess

.changeset/dry-kiwis-attend.md, js/lite/package.json
=> fix main entrypoint

.changeset/every-cities-invite.md, .github/workflows/deploy-chromatic.yml, js/app/src/Login.stories.svelte, js/app/src/Login.svelte, js/dataframe/Dataframe.stories.svelte, js/dataframe/Index.svelte, js/dropdown/Dropdown.stories.svelte, js/dropdown/Multiselect.stories.svelte, js/dropdown/shared/Dropdown.svelte, js/gallery/Gallery.stories.svelte, js/highlightedtext/HighlightedText.stories.svelte, js/image/Image.stories.svelte, js/row/Row.stories.svelte, js/storybook/preview.ts
=> fix storybook

.changeset/all-animals-vanish.md, .github/actions/install-all-deps/action.yml, client/python/gradio_client/documentation.py, gradio/component_meta.py, gradio/events.py, js/_website/generate_jsons/generate.py, js/_website/generate_jsons/src/docs/__init__.py, js/_website/src/lib/components/DemosLite.svelte
=> WIP: Fix docs

.changeset/cold-birds-cry.md, js/_website/src/lib/components/Header.svelte
Adds a banner to the youtube livestream https://www.youtube.com/watch?v=5MgmKBCOpvU
=> Add banner for 4.0 livestream to website

.changeset/cold-lemons-roll.md
This reverts commit 20dbf908119b3a19b32f307a40158a9f3b4bf4eb. …
=> Revert "Update cold-lemons-roll.md"

.changeset/poor-lands-talk.md, pyproject.toml
=> Try to trigger a major beta release

.changeset/cute-crabs-know.md, .changeset/five-islands-joke.md, .changeset/hungry-melons-pump.md, .changeset/many-hotels-flow.md, .changeset/pre.json, .changeset/public-worlds-hunt.md, .changeset/tiny-students-hide.md
=> Fix changesets 2

.changeset/cool-ends-end.md, js/_website/src/lib/components/Header.svelte
Was causing height issues in certain pages like playground
=> Small fix to website header 

.changeset/busy-snails-matter.md, js/app/src/lite/ErrorDisplay.svelte, js/app/src/lite/index.ts, js/audio/audio.test.ts, js/audio/package.json, pnpm-lock.yaml
Fixes the failing static tests on v4. 
But there seems to be some other issues with lite on v4 so we'll have to make more fixes on another PR
=> Fix static issues with Lite on v4

.changeset/cool-ties-mix.md, js/image/Index.svelte, js/image/shared/ImagePreview.svelte
=> Fix image double change bug

.changeset/loud-eagles-occur.md, js/lite/package.json
=> make lite private

.changeset/lovely-rocks-cut.md, js/dropdown/shared/Dropdown.svelte, js/dropdown/shared/Multiselect.svelte
=> fix dropdown arrow size

.changeset/quick-beds-tell.md, js/_website/generate_jsons/src/docs/__init__.py, js/_website/src/lib/components/DocsNav.svelte, js/_website/src/routes/[[version]]/docs/+layout.server.ts, js/_website/src/routes/[[version]]/docs/js/+page.server.ts
=> Fix issues with website deploy

client/python/gradio_client/client.py, client/python/test/conftest.py, client/python/test/test_client.py, client/python/test/test_utils.py, gradio/external.py, test/test_external.py, test/test_mix.py
Fix tests on the sse branch
@aliabid94 These are legit I think
FAILED client/python/test/test_client.py::TestClientPredictions::test_cancel_subsequent_jobs_state_reset
FAILED client/python/test/test_client.py::TestStatusUpdates::test_messages_correct_two_concurrent …
=> Fix client tests sse branch

.changeset/chilly-dingos-notice.md, js/app/src/Blocks.svelte
Thanks for catching the error @freddyaboulton! This should fix it.
Closes: N/A
=> Pending outputs fix

.changeset/wide-geese-slide.md, js/accordion/Index.svelte, js/accordion/package.json, js/file/shared/File.svelte, js/file/shared/FileUpload.svelte, js/image/shared/Webcam.svelte, js/model3D/shared/Model3D.svelte, js/model3D/shared/Model3DUpload.svelte, js/preview/src/plugins.ts, pnpm-lock.yaml
=> strip dangling svelte imports

.changeset/pre.json
=> leave pre-release mode

.changeset/stale-buttons-itch.md, gradio/cli/commands/components/files/pyproject_.toml, gradio/cli/commands/components/publish.py, js/_website/generate_jsons/generate.py
=> Final touches main

.changeset/moody-rooms-sleep.md, js/app/build_plugins.ts, js/app/vite.config.ts, js/preview/rollup.config.js, package.json
=> fix cdn build

.changeset/curly-radios-battle.md, js/app/src/Blocks.svelte, js/image/Index.svelte
=> Ensure the statustracker for `gr.Image` displays in static mode

.changeset/five-women-brake.md, CHANGELOG.md, gradio/layouts/column.py
Also fix some debug code that made it in the 4.0 release 😬 
=> Add that api routes are automatically named to CHANGELOG.

js/audio/Audio.stories.svelte, js/file/File.stories.svelte, js/gallery/Gallery.stories.svelte, js/image/Image.stories.svelte, js/radio/Radio.stories.svelte, js/video/Video.stories.svelte, pnpm-lock.yaml
Fixes some Storybook stories that had broken when we refactored `FileData`
=> Fix stories

CHANGELOG.md
Fleshes out the changelog a bit more.
=> Add migration tips to 4.0.0 changelog

.changeset/quiet-walls-float.md, gradio/routes.py
=> Fix file upload on windows

.github/workflows/generate-changeset.yml
=> remove echo from ci

guides/05_custom-components/01_five-minute-guide.md, guides/05_custom-components/06_frequently-asked-questions.md
=> Mention Custom Components Collection in the guides

js/app/test/gallery_component_events.spec.ts
=> WIP: Look into functional test flakes

.changeset/vast-gifts-win.md, gradio/cli/commands/components/_create_utils.py, test/test_gradio_component_cli.py
Can't repro but some people on WSL reported trouble templating Model3D. This has been verified to fix it.
=> Fix Model3D template

.changeset/hot-coins-rescue.md, js/audio/package.json, package.json, pnpm-lock.yaml, test/test_gradio_component_cli.py
=> Move wavesurfer dep to js/audio

.changeset/busy-suns-mate.md, js/_website/src/lib/assets/demo_code.js
=> Tiny fix to indent on landing page demo

guides/05_custom-components/08_multimodal-chatbot-part1.md
A text version of the Youtube Video implementing a custom multimodal chatbot component.
=> Add MultimodalChatbot Custom Component guide to accompany Youtube Video

.changeset/kind-papayas-push.md, js/preview/src/examine.py
I broke dev mode lol. Let's do a new release when this is merged.
About to take off, it's working for me locally so opening for review!
You can test by creating a new component and running `gradio cc dev` …
=> Fix dev mode

client/python/README.md
This PR fixes a broken link in the gradio_client README.
=> Fix broken link in gradio_client README

.changeset/slow-books-like.md
=> Fix release

guides/04_chatbots/01_creating-a-chatbot-fast.md
=> Fix typo envrion -> environ

.changeset/early-fans-work.md, gradio/components/file_explorer.py, test/test_components.py
Fixing error if nothing selected in file_count=single mode (return None rather)
Closes: #6606
=> Update file_explorer.py - Fixing error if nothing selected in file_count=single mode (return None rather)

guides/09_other-tutorials/setting-up-a-demo-for-maximum-performance.md
Updates the Performance guide with 4.x changes
Closes: #6638
=> Updates to the Performance Guide for 4.x

.changeset/great-icons-cut.md, gradio/components/clear_button.py, test/test_buttons.py
Simple repro:
```py
gr.Interface(lambda x,y:(x+y, x+y), [gr.Textbox(), gr.State("")], [gr.Textbox(), gr.State("")]).launch()
```
Fixes: #6465
Fixes: #6510
=> Cause `gr.ClearButton` to reset the value of `gr.State` 

js/app/test/audio_component_events.spec.ts, js/app/test/image_component_events.spec.ts
Closes: #6668
Pulled out of #6689 
=> Fix flaky functional tests

renovate.json
=> ignore vite pkgs

.changeset/slimy-socks-enter.md, gradio/components/file_explorer.py
=> Fixed an issue where files could not be filed

guides/08_client-libraries/02_getting-started-with-the-js-client.md
=> view_api instead of view_info

renovate.json
tiny pr to close an annoying issue -- closes: https://github.com/gradio-app/gradio/issues/4602
=> Remove renovate depedency dashboard

.changeset/tiny-radios-leave.md, gradio/component_meta.py
Fixed duplicate word ("this this")
Fixed duplicate word ("this this")
In comment
=> Fixed duplicate word ("this this")

js/app/test/image_component_events.spec.ts
=> skip flaky functional test

guides/03_building-with-blocks/02_controlling-layout.md
=> Fix typo in 02_controlling-layout.md

.changeset/busy-jobs-exist.md, js/app/src/lite/dev/App.svelte
For the dev convenience, added an instruction about https://github.com/gradio-app/gradio/pull/6398#issuecomment-1849880619
=> Add a dev instruction for lite in SharedWorker mode

.changeset/ten-chefs-argue.md, gradio/components/file_explorer.py, gradio/routes.py, test/test_routes.py
See: https://huggingface.slack.com/archives/C02QZLG8GMN/p1703402300689679?thread_ts=1702901295.299349&cid=C02QZLG8GMN
=> Component Server fix

test/README.md
fixed typo
just fixed a simple typo
=> fixed typo

.changeset/kind-flowers-punch.md, js/app/src/Index.svelte, js/app/src/lite/index.ts, js/gallery/package.json, js/gallery/shared/Gallery.svelte, js/image/package.json, pnpm-lock.yaml
=> Make <Gallery /> Wasm-compatible

.changeset/thirty-grapes-know.md, js/lite/package.json
=> bump lite to match gradio

.github/workflows/publish-npm.yml
=> ensure dist files are built before publishing

.changeset/fast-doodles-carry.md, .github/workflows/publish-npm.yml, js/lite/index.html
=> Add env to lite build

.changeset/cruel-nights-move.md, .changeset/fast-doodles-carry.md
=> hotfix: lite patch versions

.changeset/lucky-meals-sin.md, js/video/package.json, pnpm-lock.yaml
Closes: #7037
To test, 
Go to `js/preview/test`, create a new custom component by templating off the Chatbot, and running dev mode.
=> Fix Chatbot custom component template

.github/workflows/backend.yml, .github/workflows/publish-npm.yml
=> Only run flaky tests if flaky-tests label is applied to PR

.changeset/loud-tips-rest.md, gradio/cli/commands/components/publish.py
#7061 enables more Ruff rules, and it complained loudly about this bit.
cc @freddyaboulton
=> publish: simplify twine_files code

.changeset/fruity-falcons-design.md, js/paramviewer/package.json, pnpm-lock.yaml
=> fix versions

.changeset/eager-grapes-relate.md
=> add changeset feature for autodocs

guides/03_building-with-blocks/02_controlling-layout.md
=> small grammar fix

.changeset/tender-streets-buy.md, gradio/components/code.py, js/code/README.md, js/code/shared/Code.svelte
Minor linting of the `gr.Code` component I noticed while making a custom component
=> Small cleanups of `Code` component

.github/actions/install-all-deps/action.yml, .github/workflows/deploy+test-visual.yml, .github/workflows/deploy-spaces.yml, .github/workflows/deploy-website.yml, .github/workflows/generate-changeset.yml, .github/workflows/publish.yml, .github/workflows/test-functional.yml, .github/workflows/test-hygiene.yml, .github/workflows/test-python.yml, .github/workflows/tests-js.yml
=> Debug ci 2

.github/actions/install-all-deps/action.yml
=> Fix ci cache

.config/playwright.config.js
=> fix timeout

.changeset/major-zoos-write.md, gradio/components/annotated_image.py, gradio/components/base.py, gradio/components/gallery.py, gradio/components/image.py, gradio/components/image_editor.py, gradio/image_utils.py, gradio/templates.py
Follows up on #7116, which changed some of these imports.
See #7116.
=> Fix PIL imports

.github/actions/changes/action.yml, .github/workflows/deploy+test-visual.yml, .github/workflows/publish.yml
=> improve visual ci config

.changeset/ten-bananas-fall.md, js/app/test/on_listener_test.spec.ts, js/number/Example.svelte
Closes: https://github.com/gradio-app/gradio/issues/7293
=> Number example fix

.changeset/puny-bats-say.md, js/file/shared/FilePreview.svelte
Set `overflow: auto` for file-preview.
Closes: #7500
=> Quick fix: File height overflow

.config/playwright.config.js, js/app/test/file_explorer_component_events.spec.ts
=> fix tests?

testing-guidelines/ci.md
=> fix typos in ci.md; labal -> label

gradio/routes.py, guides/01_getting-started/03_sharing-your-app.md, pnpm-lock.yaml, test/test_routes.py
Addresses a long-standing request, closes: https://github.com/gradio-app/gradio/issues/5163 as well as tests and documentation
=> Add `/logout` functionality for Gradio auth

.changeset/smooth-guests-drive.md, js/app/src/Login.stories.svelte, js/app/src/Login.svelte
Quick fix and story test
Fixes: #7535 
Fixes: https://github.com/gradio-app/gradio/issues/7291
=> Fixes `auth_message` so that it correctly renders HTML

client/python/test/test_utils.py, test/test_external.py
=> fix flaky python tests

.changeset/early-moles-watch.md, js/app/src/Index.svelte
I am fixing mistakes made in the previous PR(#7510) by removing unwanted duplicate for-loop.
Closes: #7642
=> fix: redundant meta tags that are unwanted

.changeset/changeset.cjs, .changeset/fix_changelogs.cjs, .changeset/tender-women-tie.md, js/lite/package.json, pnpm-lock.yaml
=> Lite version

js/dataframe/Dataframe.stories.svelte
=> fix dataframe stories

guides/09_other-tutorials/theming-guide.md
Noticed it's a different url for embedding a static space
=> Fix theme gallery embedding in guide

.changeset/sixty-buses-know.md, gradio/components/bar_plot.py, gradio/components/dataframe.py, gradio/components/line_plot.py, gradio/components/scatter_plot.py
Related to #7791 
|   | This PR (e955dcf) | `main` (ecf5c52) |
|---|------------|------|
| 1 | 4.795      | 6.558|
| 2 | 4.659      | 6.599|
| 3 | 4.641      | 6.588|
| Average | 4.698 | 6.582|
=> Lazy-import pandas

js/_website/src/lib/assets/style.css
Added Hover to Show-Alternate class. Including a Screen recording of the demo:
https://github.com/gradio-app/gradio/assets/133722141/9ef7846a-f45e-4e85-9f8e-c0c49d7e4c84
=> Adding hover to shadow-alternate on the cards on the website

testing-guidelines/ci.md
programatically -> programmatically
=> fix typo in ci.md

.changeset/nine-teeth-clean.md, js/imageeditor/shared/ImageEditor.svelte, js/imageeditor/shared/InteractiveImageEditor.svelte
Trigger the "clear" event of Image Editor. The "clear" event is never triggered before. See the issue.
Closes: #7816
=> Trigger the "clear" event of Image Editor

guides/04_chatbots/01_creating-a-chatbot-fast.md
You cannot simply yield one new token at a time, you have to yield the new full response.
=> Clarify the streaming response documentation

.config/playwright-setup.js
Just a refactoring fixing small things I found during another task.
=> Fix .config/playwright-setup.js

.changeset/funny-rice-say.md, js/app/src/Blocks.svelte
=> Fix custom JS function caller to concat the outputs of a dep to the inputs as the arguments

.changeset/legal-bikes-switch.md, .github/workflows/publish.yml
=> fix publish build

.changeset/silent-cases-brush.md, js/preview/package.json, js/preview/src/dev.ts, js/preview/src/plugins.ts, pnpm-lock.yaml
It worked but we had missing dependencies.
=> fix missing dependencies for `@gradio/preview`

guides/09_other-tutorials/setting-up-a-demo-for-maximum-performance.md
=> Update docs on max-threads

.changeset/fuzzy-mirrors-scream.md, client/python/gradio_client/client.py, gradio/utils.py, test/conftest.py, test/test_external.py
=> Support custom components in gr.load

scripts/build_lite.sh
Context: https://huggingface.slack.com/archives/C055NMB0S87/p1713472594108609
=> Delete frontend builds for the normal version before building Lite for faster and lighter build process

.changeset/common-worms-travel.md, demo/fake_diffusion/run.py, gradio/analytics.py
Dumb mistake - comparing a string against a class 🤦 . This is not happening in gradio.api.server
=> Fix custom component detection logic in analytics

.changeset/weak-bugs-itch.md, js/app/src/api_docs/CodeSnippet.svelte
=> Cs fix client

.changeset/dirty-apples-do.md, client/js/src/client.ts, js/app/src/api_docs/CodeSnippet.svelte
=> use the correct query param to pass the jwt to the heartbeat event

.changeset/ready-hotels-create.md, client/js/src/client.ts, js/app/src/api_docs/CodeSnippet.svelte
=> always create a jwt when connecting to a space if a hf_token is present

readme_files/zh-cn/README.md
This pull request updates the Python version requirement in the Chinese README from Python 3.7+ to Python 3.8+.
=> Update Python version requirement in Chinese README

.changeset/red-streets-dress.md, js/_website/src/routes/redirects.js
very small fix to the current website build issue
=> Fix bad redirect breaking website build

.changeset/few-pillows-leave.md, gradio/external.py
=> Added image-to-image diffusers pipeline

.changeset/silent-turkeys-lose.md, js/file/shared/FilePreview.svelte
See https://github.com/gradio-app/gradio/pull/8334#issuecomment-2120464108
=> add missing orig_name (follow up to #8334)

.changeset/fuzzy-spies-notice.md, .changeset/silent-turkeys-lose.md, js/app/src/api_docs/CodeSnippet.svelte
=> Cs fix patch

.changeset/fast-swans-divide.md, js/app/src/api_docs/CodeSnippet.svelte
We don't want a changeset for this.
=> Remove changeset

.changeset/thin-rings-drive.md, gradio/cli/commands/components/docs.py
=> chore: update docs.py

.changeset/cute-ducks-fail.md, gradio/cli/commands/components/build.py, guides/06_custom-components/01_custom-components-in-five-minutes.md, guides/06_custom-components/06_frequently-asked-questions.md
=> Include instructions on starting from someone else's custom component repository

.changeset/chubby-rings-beg.md, js/model3D/shared/Canvas3D.svelte
Revise Canvas3D viewer to use a right-handed coordinate system, leading to fewer confusing or unexpected results for researchers.
Closes: #8375 
=> Model3D right-handed coordinate system

.changeset/three-walls-sell.md, js/app/index.html, js/app/src/api_docs/CodeSnippet.svelte
=> fix scrolling on spaces

.changeset/clever-windows-swim.md, client/js/vite.config.js, js/app/src/api_docs/CodeSnippet.svelte
=> Fix js client bundle

.changeset/quiet-colts-burn.md, client/js/src/client.ts, client/js/src/utils/predict.ts, client/js/src/utils/submit.ts, js/app/src/api_docs/CodeSnippet.svelte
=> Ensure all status are reported internally when calling `predict`

.changeset/strong-pants-create.md, js/_website/src/lib/assets/style.css, js/_website/src/lib/templates/python-client/gradio_client/02_version-1-release.svx
Add the client 1.0 release notes to the website
=> Add Client Release Notes to Docs

README.md
Solve the issue https://github.com/gradio-app/gradio/issues/8551
the fix is very small.
=> fix the link in README

.changeset/tangy-bats-laugh.md, js/_website/vite.config.ts
=> fix website build

guides/01_getting-started/02_key-features.md
Noticed that the type mentioned in the figure (int) and the description (float) were inconsistent.
https://www.gradio.app/guides/key-features
Also included some additional text corrections.
This is very small fix.
=> Fix guides description

.changeset/shaggy-hotels-end.md, js/wasm/package.json, js/wasm/src/webworker/index.ts, pnpm-lock.yaml
Just a house-keeping task upgrading Pyodide.
=> Upgrade pyodide 0.26

.changeset/slick-dancers-lie.md, gradio/routes.py
Hi there!
To do a tiny refactor in `routes.py`.
=> Remove duplicated code in `routes.py`

guides/09_other-tutorials/Gradio-and-Wandb-Integration.md
removes some empty lines that were breaking the codeblock
=> Fix codeblock rendering on WandB guide

.changeset/green-hounds-smoke.md, js/chatbot/shared/ChatBot.svelte
=> Ensure chatbot background is consistent with other components

scripts/copy_demos.py
Fixes chatbot_multimodal issue in the deployed space PR
=> Fix plotly version

guides/08_gradio-clients-and-lite/03_querying-gradio-apps-with-curl.md
Closes: https://github.com/gradio-app/gradio/issues/8617
=> Adds section on authentication in cURL

.changeset/blue-moons-learn.md, gradio/components/chatbot.py
Preview here: https://gradio-be8u1j6gl-hugging-face.vercel.app/main/docs/gradio/chatbot
=> remove `chatbot_multimodal` demo from `gr.Chatbot` documentation page

guides/06_custom-components/07_pdf-component-example.md
=> docs: update 07_pdf-component-example.md

.changeset/fancy-mugs-guess.md, gradio/components/file_explorer.py
add `str` type to `FileExplorer.height` declaration
Closes: #8644
=> Update file_explorer.py for str type `height`

.changeset/curvy-clowns-design.md, js/chatbot/shared/ButtonPanel.svelte, js/chatbot/shared/ChatBot.svelte
=> Ensure copy button on chatbot shows when appropriate

.changeset/lovely-phones-punch.md, js/multimodaltextbox/shared/MultimodalTextbox.svelte
=> Multimodal textbox buttons alignment

.changeset/itchy-cities-walk.md, client/js/src/utils/submit.ts
We weren't existing the iterator when the prediction completed.
Build the client and put the following file in `client/js` and run it with `node test.js`:
```js
import { Client } from "./dist/index.js";
async function run() {
const client = await Client.connect(
"gradio/test_chatinterface_streaming_echo_main",
{
events: ["data", "status"]
}
);
const result = client.submit("/chat", {
message: "Hello!!"
});
for await (const msg of result) {
console.log(msg);
}
console.log("ALL DONE");
}
run();
```
Closes #8502.
Not adhering to this guideline will result in the PR …
=> Ensure `@gradio/client`'s `submit` iterator releases as expected

.changeset/fifty-wings-sip.md, gradio/route_utils.py
Removes the check for when the request has a cookie
=> Perform CORS validation when the request has a cookie

js/chatbot/Index.svelte, js/chatbot/shared/ButtonPanel.svelte, js/chatbot/shared/ChatBot.svelte, js/chatbot/shared/utils.ts
Fix the download and copy buttons for type='messages'
=> Fix chatbot button panel

.changeset/tender-pianos-cross.md, js/preview/src/plugins.ts, pnpm-lock.yaml
=> Fix issue with virtual module in custom components

.changeset/gentle-wombats-thank.md, js/app/src/lite/LiteIndex.svelte, js/app/src/lite/Playground.svelte, js/app/src/lite/index.ts
Changes from #8693 was reverted in #8750, so commit them again.
=> Refactoring <gradio-lite /> component making the code simpler and fixing a Playground mode bug

.changeset/few-gifts-drive.md, gradio/data_classes.py, gradio/server_messages.py, js/wasm/src/webworker/index.ts
Pyodide 0.26.1 upgraded its prebuilt packages including Pydantic (https://github.com/pyodide/pyodide/pull/4500), so its patch is no longer needed.
Closes: #8776
=> Remove Pydantic v2 patch from Lite

.github/workflows/deploy-website.yml, js/_website/generate_jsons/generate.py
=> Fix website pre

guides/01_getting-started/01_quickstart.md
Fix minor issues with quickstart guide:
- Random letters Typo
- Dead link to components list
=> Minor QuickStart changes. Dead link change and typo removal

.github/workflows/test-functional.yml
Want to debug #8847 with the screenshots but this change needs to be in main
=> Upload screenshots for reload mode e2e tests

.changeset/shaggy-carrots-drop.md, gradio/pipelines.py, gradio/pipelines_utils.py
=> Added support for TokenClassificationPipeline

.github/workflows/test-functional.yml
=> Fix artifact name

.changeset/weak-bottles-stick.md, js/preview/src/plugins.ts
There is a weird issue due to the tsconfig of `@gradio/wasm` this fixes it.
Closes #8897
=> fix typescript issue with custom components

.changeset/sad-sides-grow.md, gradio/components/base.py, test/components/test_json.py
Closes: #8916
You can test with `demo/json_component/run.py`
=> Fix Json component serialization bug

.changeset/four-zebras-worry.md, gradio/components/radio.py, gradio/components/upload_button.py, pyproject.toml, test/components/test_radio.py
Correct type hint in UploadButton
Closes: NA - change is small
=> Type hint Correction

.github/workflows/previews-deploy.yml, .github/workflows/storybook-deploy.yml
=> Ci security tweaks take seventy three

.github/actions/changes/action.yml, .github/workflows/update-checks.yml
=> Ci statuses

.config/playwright.config.js, .github/workflows/test-functional-lite.yml, .github/workflows/update-checks.yml
=> split functional test between core and lite to speed up CI

.changeset/slow-planets-fall.md, gradio/interface.py, test/test_interfaces.py
Fixes: https://github.com/gradio-app/gradio/issues/9042
=> Fix `show_progress` in `gr.Interface`

.github/workflows/delete-stale-spaces.yml, .github/workflows/generate-changeset.yml, .github/workflows/previews-build.yml, .github/workflows/previews-deploy.yml, .github/workflows/storybook-build.yml, .github/workflows/storybook-deploy.yml, .github/workflows/test-functional-lite.yml, .github/workflows/test-functional.yml, .github/workflows/test-hygiene.yml, .github/workflows/test-python.yml, .github/workflows/tests-js.yml, .github/workflows/trigger-changeset.yml, .github/workflows/update-checks.yml, .github/workflows/website-build.yml, .github/workflows/website-docs-build.yml, .github/workflows/website-docs-deploy.yml
=> CI tweaks + further security hardening

.github/workflows/website-build.yml, .github/workflows/website-deploy.yml
=> run the website workflows

.github/workflows/website-build.yml, .github/workflows/website-deploy.yml, .github/workflows/website-docs-build.yml, .github/workflows/website-docs-deploy.yml
=> Fix website again again

.changeset/mighty-maps-double.md, gradio/chat_interface.py, test/test_chat_interface.py
=> Fix multimodal chatinterface api bug

.changeset/weak-days-thank.md, gradio/components/download_button.py
=> Set orig_name in downloadbutton postprocess

.github/workflows/previews-deploy.yml
=> fix workflow

.changeset/honest-phones-film.md, js/app/package.json
=> fix version + pkg name

.github/workflows/previews-build.yml
=> fix preview builds

.github/workflows/website-build.yml, .github/workflows/website-docs-build.yml
=> Use python 3.10 for website and docs builds

.changeset/fifty-toys-burn.md, js/chatbot/Chatbot.stories.svelte, js/chatbot/shared/ChatBot.svelte
Fixes lmsys style regressions
Closes: #9159
=> Chatbot Image size and list fixes

.github/actions/install-frontend-deps/action.yml, package.json
=> add command to fe install deps

.github/actions/install-frontend-deps/action.yml
=> fix install

js/spa/test/stream_video_out.spec.ts
=> Update @gradio/tootils import in video e2e test

.github/actions/install-all-deps/action.yml, .github/actions/install-frontend-deps/action.yml, .github/workflows/npm-previews.yml, .github/workflows/previews-build.yml, .github/workflows/publish.yml, .github/workflows/storybook-build.yml, .github/workflows/test-functional-lite.yml, .github/workflows/test-functional.yml, .github/workflows/tests-js.yml, .github/workflows/website-build.yml
=> Fic install deps again

.changeset/moody-dogs-search.md, gradio/routes.py, test/test_routes.py
=> Fix serialization error in curl api

.changeset/curly-bottles-jog.md, .github/workflows/website-deploy.yml, js/_website/package.json, pnpm-lock.yaml
Migrating the website to cloudflare. still need to test out these actions so will likely have to do more PRs. but will run vercel and cloudflare in parallel before removing vercel. 
once things are working as expected we can edit the comment-pr workflow to add the link previews to prs.
=> Cloudflare migration

.github/workflows/website-deploy.yml
=> Correct path for cloudflare upload

.github/actions/install-all-deps/action.yml, .github/actions/install-frontend-deps/action.yml
=> disable cache

.changeset/calm-planets-send.md, gradio/routes.py, js/core/src/Blocks.svelte, js/spa/src/Index.svelte
We were using the wrong url for the `/dev/reload` and `/streaming/` routes. 
=> Fix reload mode and streaming in 5.0 dev

.changeset/green-ways-bet.md, js/_website/src/lib/templates/gradio/05_modals/error.svx
=> chore: update error.svx

.changeset/gold-bats-return.md, gradio/blocks.py, gradio/exceptions.py, gradio/networking.py, gradio/strings.py, gradio/tunneling.py
Small PR that addresses [internal link](https://huggingface.slack.com/archives/C06V0AAK7QB/p1725627451157289?thread_ts=1725461274.060749&cid=C06V0AAK7QB)
=> Raise ChecksumMismatchError

.changeset/tall-moose-yawn.md, gradio/blocks.py, gradio/processing_utils.py, gradio/routes.py, gradio/utils.py, test/test_utils.py
* Handle a corner case in is_in_or_equal
* Tweak is_running in move to cache check
=> Further tweak to is_in_or_equal

.github/workflows/website-deploy.yml
Context: [internal link](https://huggingface.slack.com/archives/C06V0AAK7QB/p1725614634499579)
=> Pin cloudflare action

.changeset/every-candies-sell.md, gradio/utils.py, test/test_utils.py
=> Improve is_in_or_equal and fuzzer

.changeset/wicked-swans-wink.md, js/_website/src/lib/templates/third-party-clients/third-party-clients/01_introduction.svx
Closes: https://github.com/gradio-app/gradio/issues/9289
=> Add info about Powershell client

guides/08_gradio-clients-and-lite/02_getting-started-with-the-js-client.md
=> [doc][gradio-client] small fixes

.github/workflows/previews-deploy.yml, scripts/upload_demo_to_space.py
=> chunk space uploads

.github/workflows/website-build.yml
=> Add find for debugging website build

.github/workflows/website-build.yml
=> New branch

.github/workflows/previews-deploy.yml
Uploads lite to aws on every commit 
still testing
=> Add lite upload to CI 

.github/workflows/previews-build.yml
=> Fix lite upload CI

.github/workflows/previews-build.yml, .github/workflows/previews-deploy.yml
=> Fix lite ci

.github/workflows/website-deploy.yml
=> Fix branch name in Cloudflare deploy CI

.github/workflows/website-deploy.yml
=> Fix cf preview

.github/workflows/website-deploy.yml
=> Simpler CI fix

.changeset/some-clocks-think.md, js/_website/src/lib/components/VersionDropdown.svelte
=> Fix gradio.js aws path 

.changeset/sad-steaks-shout.md, js/_website/src/lib/components/DemosLite.svelte
=> Fixes annoying height bug in playground

gradio/analytics.py, gradio/blocks.py
Nothing huge, but removed some analytics that we never look at and are unlikely to look at in the future.
=> Reduce analytics that are collected

.changeset/honest-plums-peel.md, gradio/chat_interface.py, js/chatbot/shared/ChatBot.svelte
Fixes the chatbot image bugs @yvrjsharma reported.
- image sizing
- single example not showing properly
- webp images should show a preview
=> Chatbot bug fixes

.changeset/tidy-bobcats-marry.md, js/_website/src/lib/components/DemosLite.svelte, js/_website/src/routes/playground/+page.svelte
Makes a few changes to the UI: 
- AI generation will work on every demo, and not just on a blank page. 
- Clearer note on whether the prompt will update existing code or generate code on an empty editor. 
- Placeholder will show suggested prompts 
- If there's an error, it's highlighted on an error modal 
- Can cancel generation if it's not working as expected. 
Preview here: https://playground-ai-always.gradio-website.pages.dev/playground
=> Improve UI on the Playground

.github/workflows/semgrep.yml
Small PR to set up Semgrep with our CI. This is part of ToB's recommendations to make sure that we don't regress on the security vulnerabilities that they pointed out.
=> Add Semgrep to CI

.changeset/swift-pumas-fail.md, .github/workflows/semgrep.yml, .github/workflows/trigger-semgrep.yml, gradio/interface.py
=> test semgrep 2

.changeset/swift-pumas-fail.md, .changeset/tall-dryers-own.md
=> remove changesets

.github/workflows/website-deploy.yml
=> Remove vercel from ci 

.changeset/public-carpets-behave.md, client/python/gradio_client/client.py, gradio/route_utils.py, gradio/routes.py
Fixes the default value used in API code snippets. More context here: https://huggingface.slack.com/archives/C03BHNJCBC4/p1727983395764759
=> Api info fix

.changeset/gold-kiwis-share.md, gradio/chat_interface.py
Fixes issue with uploading image into chat interface.
Fallback to `gr.Examples()` when `additional_inputs` is provided.
Closes: #9477
=> Chat Interface Multimodal Fix & Fallback to `gr.Examples()`

.changeset/evil-clocks-visit.md, client/python/gradio_client/client.py, gradio/blocks.py, gradio/processing_utils.py, test/components/test_json.py
=> Only move files to the cache that have a meta key

.changeset/quiet-gifts-cheer.md, js/chatbot/shared/ChatBot.svelte, js/chatbot/shared/Message.svelte, js/multimodaltextbox/shared/MultimodalTextbox.svelte
- Noticed uploaded images were _full_ size. Some css was not being applied properly.
- Fixes submitting only files when using multimodal textbox …
=> Some more chatbot fixes

.github/workflows/website-deploy.yml
=> Fix cloudflare action pin

.github/workflows/website-deploy.yml
=> try switch to v3 in wrangler action

.github/actions/install-all-deps/action.yml, .github/actions/install-frontend-deps/action.yml
=> Disable cache again

.changeset/clear-walls-unite.md, gradio/blocks.py, gradio/node_server.py, gradio/routes.py, gradio/utils.py, guides/08_custom-components/01_custom-components-in-five-minutes.md, guides/08_custom-components/07_pdf-component-example.md
=> bump to node 20

.changeset/empty-ears-search.md, js/_website/src/lib/components/Header.svelte
=> Add website banner for gradio 5

.changeset/salty-corners-melt.md, js/app/src/app.html
=> fix height in iframe

.changeset/silly-hairs-burn.md, gradio/blocks.py, gradio/chat_interface.py, gradio/components/audio.py, gradio/components/video.py, gradio/routes.py
=> Fix streaming Audio/Video Output

README.md
Addidng Product Hunt Badge to promote our Gradio 5 launch for next couple days. We can remove it after the Launch is over.
=> added product hunt badge to README.md

.changeset/cruel-aliens-reply.md, requirements.txt
Context - https://huggingface.slack.com/archives/C02QNREU24S/p1729021757407899
=> Set min FastAPI version

.github/workflows/tests-js.yml
=> skip fe build in js tests

.github/actions/install-frontend-deps/action.yml, .github/workflows/tests-js.yml
=> Fix js build

.changeset/few-weeks-change.md, js/sanitize/package.json
=> fix `@gradio/sanitize` exports

CONTRIBUTING.md
Makes some updates to the contributing guide, including linking to a video walkthrough
=> Updates to contributing guide

.github/actions/install-all-deps/action.yml, .github/actions/install-frontend-deps/action.yml
=> enable caching

.github/actions/install-all-deps/action.yml, .github/actions/install-frontend-deps/action.yml
=> Ci tweaks 5.3

.github/workflows/test-functional-lite.yml, .github/workflows/test-functional.yml, js/theme/package.json
=> build essential packages fpor functional tests

.changeset/sad-chicken-rule.md, gradio/components/button.py, gradio/components/duplicate_button.py
Align parameter document of button api reference 
Closes: #9787
All tests pass.
=> update docstring for the the "variant" parameter in `gr.Button`

.changeset/small-houses-shake.md, requirements.txt
Updates requirements.txt to allow pillow 11.x
Closes: #9818
=> Update requirements.txt to allow pillow 11.x

CONTRIBUTING.md
Adds instructions to CONTRIBUTING.md on how to work around the JS OOM error described in #2343 that can happen when building the frontend.
=> docs: update CONTRIBUTING.md with troubleshooting step for JS OOM error in scripts/build_frontend.sh

.changeset/silver-planes-guess.md, gradio/components/login_button.py, gradio/routes.py
Fixes issue where HF sign in button was broken in SSR.
[Test Space](https://huggingface.co/spaces/dawood/login-test-1)
Closes: #9820
=> Fixes LoginButton for SSR

.changeset/wet-knives-type.md, gradio/http_server.py, gradio/utils.py
Closes: #9865
You can test with this code
```python
from transformers import pipeline
if gr.NO_RELOAD:
model = pipeline("sentiment-analysis")
print("outside demo********************")
def greeter(x):
output = model(x)
return {o["label"]: o["score"]  for o in output}
print("inside demo********************")
gr.Markdown("# Greetings from Gradio ⚡️")
inp = gr.Textbox(placeholder="Input some text here")
out = gr.Label(label="We will classify it here")
inp.submit(fn=greeter, inputs=inp, outputs=out)
print("inside main********************")
demo.launch()
```
The code in the `gr.NO_RELOAD` block (print `outside demo`) is only loaded once. On changes, only the code outside NO_RELOAD is reloaded (`inside demo`)
```
outside …
```
=> Do not load code in gr.NO_RELOAD in the reload mode watch thread

.changeset/hot-ghosts-crash.md, gradio/routes.py
Fixes SSR Safari Issue
Closes: #9748
=> SSR Safari Fix

.changeset/silly-bananas-run.md, gradio/routes.py
=> Fix Starlette templating deprecation warning

.changeset/fluffy-walls-appear.md, js/gallery/shared/Gallery.svelte
=> Fix double gallery close button in preview

.changeset/beige-ties-lie.md, js/_website/src/lib/components/DemosLite.svelte
=> Fix the Playground to ignore comments in the requirements text

.changeset/ten-poems-flow.md, client/python/requirements.txt, requirements.txt
Closes: https://github.com/gradio-app/gradio/issues/10085
Closes: https://github.com/gradio-app/gradio/issues/10084
=> Update `requirements.txt` for `gradio` and `gradio_client`

.devcontainer/devcontainer.json
Test fix for: https://github.com/gradio-app/gradio/issues/10141
=> Upgrade dev container to use Python 3.10

guides/04_additional-features/09_environment-variables.md
Small PR that closes: https://github.com/gradio-app/gradio/issues/10138
=> Document SSR environment variable

.changeset/cyan-suns-judge.md, .gitignore, pyproject.toml
Closes: https://github.com/gradio-app/gradio/issues/8923
Credit to @silverjam for [providing the guidance](https://github.com/gradio-app/gradio/issues/8923#issuecomment-2524980825).
=> Let Gradio be typed!

.changeset/lovely-bees-change.md, gradio/strings.py
Thoughts @pngwn @dawoodkhan82?
=> Add note that SSR mode is experimental

.changeset/metal-bugs-follow.md, js/multimodaltextbox/MultimodalTextbox.test.ts, js/multimodaltextbox/shared/MultimodalTextbox.svelte
Quick fix to clear the stored mic_audio after submitting.
Closes: #10301
2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes to non-Python files) …
=> Quick Fix: Multimodal microphone audio not clearing

.changeset/funny-heads-play.md, js/image/shared/Webcam.svelte
The purpose of this PR is to provide a solution to the issue.
Closes: #10326 
2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes to non-Python …
=> Fix webcam

.changeset/some-cases-notice.md, gradio/external.py, guides/05_chatbots/01_creating-a-chatbot-fast.md
Closes: https://github.com/gradio-app/gradio/issues/10307
Kwargs support [was requested internally](https://huggingface.slack.com/archives/C02QZLG8GMN/p1736327898002519?thread_ts=1736327534.172879&cid=C02QZLG8GMN)
=> Update guide for `gr.load_chat` and allow `**kwargs`

.changeset/calm-houses-fix.md, js/dataset/Index.svelte
=> Quick fix: 0 is ignored Slider/Number issue

guides/10_other-tutorials/theming-guide.md
fixed 2 typos in theming guide
purpose -> purple
radii and -> radius
=> fixed 2 typos in guides

gradio/processing_utils.py, test/components/test_video.py, test/test_processing_utils.py
Wanted to test something ([see internal link](https://huggingface.slack.com/archives/C02QNREU24S/p1737523234985979)). Closes: https://github.com/gradio-app/gradio/issues/10375
=> Support presigned URLs with gr.Video, gr.Model3D, and other components

.changeset/better-rats-kiss.md, js/_website/src/lib/templates/gradio/03_components/chatbot.svx
**Edits:** Document [gradio/03_components/chatbot.svx](https://github.com/gradio-app/gradio/blob/main/js/_website/src/lib/templates/gradio/03_components/chatbot.svx)
**Fixes:** Multiple syntax errors in `gradio.Chatbot` example code. Updates examples for compatibility with the latest Gradio API.
The documentation for `gradio.Chatbot` contained several syntax errors in the example code (lines 115-137 of [this file](https://github.com/gradio-app/gradio/blob/main/js/_website/src/lib/templates/gradio/03_components/chatbot.svx)). This PR corrects these errors and updates the examples to ensure compatibility with the most recent Gradio API. This improves the accuracy and usability of the documentation.
Closes: #10413
=> Update chatbot.svx for issue#10413

guides/05_chatbots/03_agents-and-tool-usage.md
Added a new section "Building with Citations" to the Gradio Chatbot guide, demonstrating how to integrate Anthropic's Citations API with Gradio's chatbot interface. This addition provides developers with a clear implementation example for creating citation-enabled chatbots using Gradio's metadata features.
The new section includes:
- Complete code examples for handling both plain text and PDF documents
- Integration with Gradio's metadata for collapsible citation displays
This PR enhances Gradio's docs by adding the latest feature from Anthropic. Citations API allows to build more transparent and trustworthy chatbot interfaces that can reference source documents. This guide explain how you can use it with gradio cleanly and efficiently.
- The added documentation follows Gradio's existing …
=> Adding guide for using Anthropics Citations API

.changeset/tidy-results-write.md, gradio/__init__.py, js/chatbot/shared/Message.svelte
=> Small tweaks to `gr.ChatMessage` and spacing between chatbot messages

.changeset/evil-books-knock.md, js/audio/recorder/AudioRecorder.svelte
Context: [internal link](https://huggingface.slack.com/archives/C01B1GU9Q0Z/p1738008113575299)
=> Request mic permissions only after the Record button is clicked in `gr.Audio()`

.changeset/weak-signs-notice.md, gradio/components/dropdown.py
=> chore: update dropdown.py

.changeset/strong-taxes-double.md, js/nativeplot/Index.svelte, js/nativeplot/NativePlot.stories.svelte, js/nativeplot/package.json, pnpm-lock.yaml
Closes: #9322
Also add a story book story …
=> Fix bug where plots wouldn't load when initial value provided

.changeset/short-hands-yawn.md, js/_website/src/lib/utils.ts, js/_website/src/routes/+page.svelte, js/core/src/Embed.svelte, js/theme/src/tokens.css
This is just an annoyance for us with very wide screens. I added 1920px wide resolution after it was no able to be solved with a CSS style file.
Closes: None
I did not submit an issue. My apologies, but the lack of ability to make up for this in CSS was frustrating. It is a minor change but it has wasted hours of my time and I wanted to solve it.
I did format and test per your instructions
=> Add 1920px wide resolution for wide monitors

js/_website/src/lib/components/DemosLite/DemosLite.svelte
tiny fix after changes were merged in playground worker
=> Fix worker link in playground

.changeset/nice-glasses-glow.md, js/sidebar/shared/Sidebar.svelte
https://github.com/user-attachments/assets/e6302eb8-70b3-40e7-abeb-9d56c7cfe155
2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any …
=> Fix Sidebar for mobile

.changeset/short-mangos-post.md, gradio/layouts/row.py
=> Row scale changes

.changeset/huge-rats-knock.md, js/spa/src/Index.svelte
- https://github.com/gradio-app/gradio/pull/10270 follow-up
=> [ZeroGPU] Handshake-based postMessage part.2 (non-SSR mode)

.changeset/tired-eggs-greet.md
=> Another changeset patch

.changeset/brown-laws-jam.md, js/core/src/Embed.svelte, js/lite/src/ErrorDisplay.svelte, js/lite/src/LiteIndex.svelte, js/spa/src/Index.svelte
=> Update Lite to support multi-page apps

.changeset/quick-tires-burn.md, gradio/analytics.py, gradio/cli/commands/sketch.py, gradio/sketch/__init__.py, gradio/sketch/run.py
* Adjusted button sizes, dropdown properties, markdown props to tweak the UI a bit
* Added tracking analytics for the sketch command
=> Ergonomics improvements & analytics for `gradio sketch`

guides/03_building-with-blocks/01_blocks-and-event-listeners.md
While reading the documentation I spotted a typo, this PR fixes it.
Closes: #10654
=> Simple fix for typo in 01_blocks-and-event-listeners.md

.changeset/quiet-files-poke.md, js/_website/src/lib/templates/gradio/04_helpers/load_chat.svx
=> Add load_chat documentation

.github/workflows/website-build.yml, .github/workflows/website-deploy.yml
=> Fix typo in ci 

.github/workflows/website-build.yml, .github/workflows/website-deploy.yml
=> Fix deploy ci again

.github/workflows/website-deploy.yml
=> Fix website deploy CI by pinning cloudflare wrangler action to 3.5 

.changeset/khaki-pillows-send.md, js/chatbot/shared/Message.svelte, js/chatbot/shared/Pending.svelte
Small fix, closes: https://github.com/gradio-app/gradio/issues/10564
=> Fix Chatbot avatar image position

.changeset/clever-bees-invite.md, gradio/components/clear_button.py
Add deepcopying for the returned initial value of ClearButton
Closes: #10747
=> Fix ClearButton

.changeset/silly-mammals-train.md, client/python/CHANGELOG.md
=> Trigger python client release

.changeset/sour-buckets-shop.md, gradio/blocks.py, gradio/helpers.py, requirements.txt
Also includes a couple of type fixes
Closes: https://github.com/gradio-app/gradio/issues/10806
=> Update `markupsafe` dependency version

.changeset/salty-walls-bake.md, gradio/external.py
Currently broken, fixed now.
Fixes: #10825, Fixes: #10762
=> Fix gr.load_chat

.changeset/huge-moles-retire.md, js/imageeditor/Index.svelte, js/imageeditor/InteractiveImageEditor.svelte, js/imageeditor/shared/Controls.svelte, js/imageeditor/shared/ImageEditor.svelte
It wasn't implemented. I forgot.
Closes: #10992 …
=> implement download button for the ImageEditor

.changeset/empty-shoes-share.md, gradio/components/login_button.py, gradio/oauth.py, gradio/routes.py
Test code:
```py
pass
with demo.route("aaa"):
gr.LoginButton()
demo.launch()
```
Test on Spaces: https://huggingface.co/spaces/abidlabs/login-multi
Closes: https://github.com/gradio-app/gradio/issues/10947
=> Ensure that logins and logouts are redirected to the correct page in a multipage Gradio app

.changeset/spicy-parts-clap.md, gradio/chat_interface.py
@yvrjsharma is this workflow you'd expect?
Closes: https://github.com/gradio-app/gradio/issues/11037
=> Show stop button in `gr.ChatInterface` even for non-streaming chat functions

.changeset/eleven-signs-press.md, gradio/chat_interface.py, test/test_chat_interface.py
=> Fix chatinterface icons bug

.changeset/tiny-doodles-repair.md, gradio/interface.py
Fixed here: https://huggingface.co/spaces/gradio/theme_builder …
=> Fix duplicate id issue in spaces when creating an interface inside blocks

.changeset/quick-clowns-build.md, gradio/components/datetime.py, test/components/test_datetime.py
=> Fix passing datetime.datetime instance to gr.Datetime

.changeset/long-spiders-enter.md, client/js/src/test/apply_diff.test.ts, client/js/src/utils/stream.ts, gradio/utils.py, test/test_utils.py
Sending consecutive `delete` diffs doesn't produce the intended result. We send diffs of the form `["delete", [0], null], ["delete", [1], null]` but because we call `splice` to delete the first element, the diff index for the second component is off by one.
My fix is to shift the delete index by 1 in the backend.
This fixes an issue in FastRTC. To see the bug in action in this gradio demo check out
```python
import random
import time
chatbot = gr.Chatbot(type="messages")
msg = gr.Textbox()
clear = gr.Button("Clear")
def user(user_message, history: list):
return "", history + [{"role": "user", "content": user_message}]
def bot(history: list):
bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
history.append({"role": …
```
=> Fix "delete" diff instruction in JS client

.changeset/breezy-hands-notice.md, client/python/gradio_client/utils.py
This small PR evaluates `index` variable in argument description in `client/python/gradio_client/utils.py`.
Small PR.
=> Evaluate index variable in argument description

.changeset/eighty-planes-feel.md, js/dataset/Index.svelte
Closes: https://github.com/gradio-app/gradio/issues/8639
=> Fix the `.select()` event in `gr.Dataset` in table layout 

.changeset/bright-teeth-buy.md, js/tabs/Tabs.stories.svelte, js/tabs/shared/Tabs.svelte
Closes: https://github.com/gradio-app/gradio/issues/10904, test with any of the examples there
=> Ensure that tabs with `visible=False` don't show up in the overflow menu

.changeset/short-beds-fly.md, gradio/processing_utils.py
Context: https://huggingface.slack.com/archives/C048K60MPNF/p1747550973542949
=> Add xethub bridge to host whitelist

.changeset/little-hairs-taste.md, js/model3D/shared/Canvas3D.svelte, js/model3D/shared/Model3D.svelte, js/model3D/shared/Model3DUpload.svelte
Fixes issue where `camera_position` param was not working as expected.
https://github.com/user-attachments/assets/36871f3e-a2eb-45cc-8e78-61baf2ff9b04
Closes: #11216
2. Please run these bash scripts to automatically format …
=> Fix Model3D `camera_position` param

.changeset/hungry-lizards-hang.md, gradio/blocks.py
=> Check file validity even if preprocess=False

.changeset/chubby-trees-pay.md, gradio/components/deep_link_button.py
Context: https://huggingface.slack.com/archives/C02QZLG8GMN/p1747864005014009
2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes to non-Python …
=> Fix DeepLink Query Parameters

.changeset/yummy-rings-raise.md, gradio/interface.py
=> Remove Deep Link events from API page

.changeset/clear-icons-dance.md, gradio/chat_interface.py, gradio/mcp.py, test/test_chat_interface.py
=> Fix parameter names in ChatInterface view api page

guides/05_chatbots/03_agents-and-tool-usage.md
Fixed broken link
Closes: #11290
=> Fix broken documentation link for smolagents in chatbot agents and tool usage guide 

.changeset/early-squids-clap.md, client/python/gradio_client/utils.py, client/python/test/test_utils.py, gradio/events.py
Closes: https://github.com/gradio-app/gradio/issues/11175
=> Fix `gr.api()` to support more types, including optional params

.changeset/famous-rice-nail.md, js/core/src/Blocks.svelte
Closes: #9095 
```python
import random
outer_textbox = gr.Textbox(value="")
@gr.render(inputs=outer_textbox, triggers=[outer_textbox.submit])
def display_content(outer_textbox):
other_textbox = gr.Textbox(value="", label="Other Textbox (for testing)")
def get_filepath(tb):
return f"filepath_{random.randint(0, 1000000)}"
for _ in range(len(outer_textbox) or 0 ):
gr.Textbox(
value=get_filepath,
inputs=other_textbox,
)
demo.launch()
```
1. PRs will only be …
=> Call load events on @gr.render

.changeset/shy-jokes-cry.md, js/preview/src/index.ts
=> Be able to run gradio cc dev if the parent directory has spaces

.github/actions/install-all-deps/action.yml
has to be in main to for https://github.com/gradio-app/gradio/pull/11437 to work
=> Add markdown pip library to docs build action 

js/spa/test/dataframe_events.spec.ts, js/spa/test/dataframe_streaming.spec.ts
=> Revert .only test

.changeset/young-pets-unite.md, js/model3D/package.json, pnpm-lock.yaml
Upgrades `gsplat` to version `1.29.0`. This version is smaller thanks to @dylanebert!
Closes: N/A
2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any …
=> Upgrade `gsplat`

.changeset/whole-lands-grin.md, js/core/src/api_docs/ApiDocs.svelte
See [internal discussion](https://huggingface.slack.com/archives/C03BHNJCBC4/p1752671626922839) for more context
=> Add a query param for the selected language & make MCP the default option when `mcp_server` is enabled

.github/workflows/generate-changeset.yml, .github/workflows/npm-previews.yml, .github/workflows/previews-build.yml, .github/workflows/publish.yml, .github/workflows/storybook-build.yml, .github/workflows/test-functional-lite.yml, .github/workflows/test-functional.yml, .github/workflows/test-python.yml, .github/workflows/tests-js.yml, .github/workflows/website-build.yml, .github/workflows/website-docs-build.yml, CONTRIBUTING.md, package.json
=> CI fix attempt 1

.github/actions/install-frontend-deps/action.yml, package.json
=>  Testing lite in ci with upgraded virtualenv

gradio/components/dialogue.py
=> fix import order

.github/workflows/previews-build.yml, .github/workflows/publish.yml
Reverts gradio-app/gradio#11671
=> Revert "rm lite from previews build"

.changeset/shaggy-swans-read.md, js/atoms/src/IconButtonWrapper.svelte
=> Fix z-index of icon button wrapper

.changeset/salty-heads-knock.md, js/_website/svelte.config.js
No need to set it to the default. It's going to be deprecated soon, so this will save you a deprecation warning
=> chore: remove no-op setting

guides/11_other-tutorials/create-immersive-demo.md
=> Quick fix: Immersive Guide

.changeset/tender-cameras-beg.md, gradio/analytics.py, gradio/cli/cli.py
So that we can track usage as we release new features / comms.
=> Add analytics for `gradio --vibe`

.changeset/khaki-houses-smell.md, client/python/gradio_client/client.py
Needed because of changes made in: https://github.com/gradio-app/gradio/pull/11731
=> fix client

.changeset/dark-pets-decide.md, .gitignore, gradio/utils.py, test/test_mcp.py, test/test_utils.py
As it can provide more context and examples for the MCP server.
Closes: https://github.com/gradio-app/gradio/issues/11568
Test code:
```py
def chat_handler(user_message, informal_prefix=None, max_tokens=None, chat_history=None):
"""
Handles a single chat interaction with the Kimina Prover model designed for 
competition-style problem solving.
Args:
user_message (str): The user's input message or formal statement to be 
solved or discussed by the model.
informal_prefix (str, optional): An optional informal explanation or 
context to prepend to the formal statement.
max_tokens (int, optional): The maximum number of tokens to generate 
in the model's response. Must be between [specific range].
chat_history (list, optional): The conversation history as a list of 
message …
```
=> Use full "Returns" section when generating the function description

.github/workflows/generate-changeset.yml, .github/workflows/trigger-changeset.yml
=> fix changeset CI

.github/workflows/generate-changeset.yml, .github/workflows/trigger-changeset.yml
Reverts gradio-app/gradio#11913
=> Revert "fix changeset CI"

.changeset/twelve-humans-act.md, js/chatbot/shared/Examples.svelte
Closes: #11502
I think it's aligned now
Test with:
```python
from pathlib import Path
image = str(Path(__file__).parent / "files" / "avatar.png")
audio = str(Path(__file__).parent / "files" / "cantina.wav")
def echo(message, history):
return f"You wrote: {message['text']} and uploaded {len(message['files'])} files."
demo = gr.ChatInterface(
fn=echo,
type="messages",
examples=[{"text": "hello"}, 
{"text": "How many strawberries are in this image?", "files": [image]},
{"text": "what's up"},
{"text": "Please describe what's in these files", "files": [image, audio]},
{"text": "Write a poem about this image", "files": [image]}
],
title="Echo Bot",
multimodal=True,
)
demo.launch()
```
Before your create a PR, please check to see if there is [an …
=> Fix Chat Examples Spacing

.changeset/khaki-doors-cheer.md, js/dataset/Index.svelte
=> Fix Examples Pagination

.changeset/breezy-games-nail.md, js/highlightedtext/shared/InteractiveHighlightedtext.svelte, js/highlightedtext/shared/StaticHighlightedtext.svelte
=> Bugfix: Update color map of HighlightedText programmatically 

.changeset/solid-cats-melt.md, gradio/external.py
Closes: #11330
Test with the following script: (ollama and llama3.2)
```python
gr.load_chat("http://localhost:11434/v1/", model="llama3.2:1b").launch()
``` …
=> Allow passing token=None for load_chat

.changeset/breezy-mammals-pick.md, js/_spaces-test/src/routes/embeds/+page.svelte, js/core/src/Blocks.svelte
Short iframe maintain their sticky footer in spa mode: https://huggingface.co/spaces/pngwn/short_iframe
Long iframes are scrollable with no gaps in spa mode: https://huggingface.co/spaces/pngwn/iframe_long
=> fix iframe sizing on spaces for apps runing in SPA mode

.changeset/afraid-boxes-tan.md, gradio/components/model3d.py, gradio/components/video.py
=> Fix example vales

.changeset/spotty-buckets-tickle.md, gradio/mcp.py
Adds the Related Request ID when sending MCP Tool Notifications
Closes: #12034 
We encourage the use of AI tooling in creating PRs, but the any non-trivial use of AI needs be disclosed. E.g. if you used Claude to write a first draft, you should mention that. Trivial tab-completion doesn't need to be disclosed. You should self-review all PRs, especially if they were generated with AI.
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set …
=> route progress notifications to the POST SSE Handler for MCP Servers
