build/lib/gradio/outputs.py
gradio/outputs.py
gradio/static/js/interfaces/output/key_values.js

Fixing KeyValues to match Python code (`dict` instead of `List[Tuple[str, value]]`).
Manually tested:

Fix key_values and a typo

---

gradio/inputs.py
gradio/interface.py
gradio/processing_utils.py
gradio/templates/index.html
gradio/templates/login.html

Fixed line in input.py for File input object causing bug in single file handling
Added params to File input object to allow keepfilename=True or False to be passed
When True, will prefix the safe filename generated upon upload with the original filename and a trailing '_' character 
Thus accessing the file in gradio with f.name will now return 'originalfilenameabc_xxcyidfyudifd.png' or similar

fixed single file handling, added keepfilename

---

gradio/interface.py

This PR:
Enables logging a message to the "Other" tab in a Comet Experiment that helps track whether an experiment was created from the Gradio integration.  
Example shown here:
https://www.comet.ml/team-comet-ml/gradio/ba385bd513df490d90c9f994147a5885?experiment-tab=other&viewId=LoEum7OL84ONyBkoUiX1BPsUX

Log "Created From" text to track Gradio usage in Comet 

---

gradio/utils.py
test/test_utils.py

When any exceptions occur in the "try" block of the code, it would handle it the same way regardless.
In the `version_check`, there are 4 possibilities for an error to occur. These are as follows:
1) Gradio package is installed improperly due to which the version information is inaccessible.
2) JSON cannot be parsed from the Package version URL.
3) JSON that is parsed from the URL does not contain version information.
4) The Package URL is not accessible.
Refactored method to handle these cases and provide appropriate messages.

Adds clauses for specific exceptions in version check

---

demo/sepia_filter.py
gradio/interface.py

At the moment, quoting code between three backticks (i.e. [fenced code blocks](https://spec.commonmark.org/0.30/#fenced-code-blocks)) does not render correctly when passed to `article` in `gr.Interface`, which would come as a surprise to most users that are used to CommonMark and Github-flavoured Markdown. Apparently, `markdown2` does not support it by default, but requires toggling it on via an `extras` argument. 
This PR introduces a small change to enable rendering fenced code blocks in text passed to `article` correctly.

Toggle on markdown support for fenced code blocks

---

gradio/inputs.py
test/test_inputs.py

The line
```
elif self.type == "numpy" or "pil":
```
is interpreted as
```
elif (self.type == "numpy") or ("pil"):
```
where `("pil")` is always evaluated as True. See https://stackoverflow.com/a/20002504/50065 for more info.
The reason this wasn't caught by the tests is because they were written like:
```
with self.assertRaises(ValueError):
wrong_type = gr.inputs.Image(type="unknown")
wrong_type.preprocess(img)
wrong_type.serialize("test/test_files/bus.png", False)
```
The line `wrong_type.preprocess(img)` would trigger a ValueError and the test would be markes as succeeded, but it obscures that the line `wrong_type.serialize("test/test_files/bus.png", False)` would fail with:
```
Traceback (most recent call last):
File "/home/biogeek/github/gradio/test/test_inputs.py", line 320, in …
```

Fix comparison of "numpy" and "pil" types in Image

---

gradio/mix.py
test/test_mix.py

Series working with external (T-93)

---

gradio/interface.py

remove duplicate parameter description for `show_error`

remove duplicate parameter description

---

website/homepage/render_html.py
website/homepage/src/navbar.html

Currently only gradio.app/guides.html works which is inconsistent with /docs/ /getting_started/ and all the other links on the page. We will still also support gradio.app/guides.html

Fixing guides url 

---

.circleci/config.yml
gradio/routes.py
gradio/templates/frontend/index.html
scripts/build_frontend.sh
scripts/run_frontend.sh
scripts/upload_to_pypi.sh
ui/packages/app/package.json
ui/packages/app/src/App.svelte
ui/packages/app/src/Interface.svelte
ui/packages/app/src/components/input/Audio/Interpretation.svelte
ui/packages/app/src/components/input/Image/Image.svelte
ui/packages/app/src/components/input/TimeSeries/TimeSeries.svelte
ui/packages/app/src/components/output/Carousel/Carousel.svelte
ui/packages/app/src/components/output/Json/JsonNode.svelte
ui/packages/app/src/components/output/Label/Label.svelte
ui/packages/app/src/components/utils/Cropper.svelte
ui/packages/app/src/components/utils/ModifySketch.svelte
ui/packages/app/src/components/utils/Webcam.svelte
ui/packages/app/src/main.ts
ui/packages/app/src/themes/grass.css
ui/packages/app/src/themes/huggingface.css
ui/packages/app/src/themes/peach.css
ui/packages/app/src/themes/seafoam.css
ui/packages/app/tailwind.config.js
ui/pnpm-lock.yaml

This PR replace the existing `frontend` directory with the `ui` directory.
- All recent changes to `frontend` synced/ ported to `ui` (including themes)
- `ui/packages/app` builds its output to the template dir (`gradio/templates/frontend`)
- CI updated to build/ use the `ui` dir during the build instead of frontend.
- server updated to serve the `assets` path correctly (as the new build uses an `assets` dir not `build`)

use `ui` for frontend

---

gradio/interface.py
test/test_flagging.py

Launching the interface crashes if the flagging directory is read-only. This happens even if flagging is set to never. 
It looks like one of the if conditions was expecting allow_flagging to be a boolean even though it is now a string, so I've fixed that and added a test case for it.

fixes PermissionError for non-writable flagging path

---

website/homepage/src/guides_template.html

The old related spaces and tags were added back in PR #546 by accident (see [this comment](https://github.com/gradio-app/gradio/pull/546/files#r808970717)). This fixes that and removes them. Before and after:

Fixing related spaces and tags on guides template

---

gradio.egg-info/requires.txt
gradio/routes.py
setup.py

Switched FastAPI from using `json` to `orjson` to render the responses.
**Why did we go from a built-in library to a 3rd-party library**? Understandable question...
- [orjson](https://github.com/ijl/orjson) is a well-maintained library that is faster than `json`, which means everything runs a tad bit faster, especially for large responses (e.g. images, big data frames, etc.)
-  More importantly, it correctly serializes things like `numpy` arrays and `pandas` dataframes, which `json` does not always handle correctly. This allows us to close #371 with a general fix

Switched from `json` to `orjson`

---

ui/packages/app/src/components/input/Number/Number.svelte

Use svelte value bindings instead of listeners as this will handle all number values correctly.
fixes #667

handle input number values correctly

---

ui/packages/app/src/App.svelte
ui/packages/app/src/Interface.svelte

Restores functionality to specify option when flagging. Also flashes the flagging button red when flagging as click feedback.
Fixes:  #709, #682

Restore flagging options

---

gradio/external.py
gradio/inputs.py

Spaces changed how they were rendering Gradio demos, so this broke our regex for extracting the config for the demo. This hotfixes it, though perhaps we should identify a more robust solution for extracting the config.

[hotfix] fixed loading from spaces

---

website/homepage/render_html.py
website/homepage/src/guides_main_template.html

Small issue with search in guides where getting_started caused an off by one error. Fixed now, getting started is always the first guide, but is still included in search.

Fix search bug in guides

---

gradio/flagging.py
gradio/utils.py
test/test_utils.py

To prevent csv injection, this sanitizes flagging inputs before writing to the csv

Sanitize flagging inputs before writing to csv

---

gradio/blocks.py

Users should be able to add css directly to components without having to know class names of elements. Adding a css kwarg to all components will make this possible in most basic cases:
e.g.
A red button:
```python
gr.Button(css={"background-color": "pink", "color": "red"})
```
A custom layout resembling the current Interface
```python
with gr.Row(css={"gap": "2rem"}):
with gr.Column(css={
"background-color": "whitesmoke",
"padding": "2rem",
"border-radius": "1rem"
}):
with gr.Row():
clear = gr.Button()
submit = gr.Button(css={"background-color": "orange"})
```
CSS variables can also be passed in at any component level or at the top Blocks element:
```python
app = Blocks(css={"--primary-color": "red"})
with app:
gr.Button(css={"--secondary-color": "blue"})
```

Adding custom css kwarg directly to a component [WIP]

---

gradio/blocks.py
gradio/components.py

All events are implemented except `Tabs`. `Tabs` is not a component in backend.
Closes #723

Blocks-Backend-Events

---

gradio/external.py
guides/adding_rich_descriptions_to_your_demo.md
guides/building_a_pictionary_app.md
guides/creating_a_chatbot.md
guides/image_classification_in_pytorch.md
guides/image_classification_in_tensorflow.md
guides/image_classification_with_vision_transformers.md
guides/using_flagging.md
guides/using_hugging_face_integrations.md
guides/using_the_api_docs.md
ui/packages/app/src/main.ts

The `/gradioiframe/...` URLs were never really meant to be user facing so we switched to a new URL path on the `hf.space` proxy
URLs are now slightly cleaner-looking, also there was not really anything Gradio specific on Spaces side for this URL, so the new path is more logical. 
Finally moving from huggingface.co to hf.space for this will be more future-proof for when the new Spaces infra is up (cc @cbensimon @christophe-rannou @pierrci)
we redirect the old links to the new so existing links that could live "in the wild" should still work for quite some time. (cc @osanseviero)

[Spaces] Cleaner hf.space URLs

---

gradio/external.py
test/test_external.py
test/test_mix.py

Since Gradio iframes have a new path in HF Spaces, this fixes this issue in blocks-dev branch.
Note that this has already been fixed in main branch

Fixing external.py in blocks-dev to reflect the new HF Spaces paths

---

ui/packages/app/src/Render.svelte
ui/packages/app/src/components/Button/Button.svelte
ui/packages/app/src/components/Chatbot/Chatbot.svelte
ui/packages/app/src/components/Checkbox/Checkbox.svelte
ui/packages/app/src/components/CheckboxGroup/CheckboxGroup.svelte
ui/packages/app/src/components/DataFrame/DataFrame.svelte
ui/packages/app/src/components/Dropdown/Dropdown.svelte
ui/packages/app/src/components/File/File.svelte
ui/packages/app/src/components/HTML/HTML.svelte
ui/packages/app/src/components/HighlightedText/HighlightedText.svelte
ui/packages/app/src/components/Image/Image.svelte
ui/packages/app/src/components/Json/Json.svelte
ui/packages/app/src/components/Label/Label.svelte
ui/packages/app/src/components/Markdown/Markdown.svelte
ui/packages/app/src/components/Number/Number.svelte
ui/packages/app/src/components/Radio/Radio.svelte
ui/packages/app/src/components/Slider/Slider.svelte
ui/packages/app/src/components/Textbox/Textbox.svelte
ui/packages/app/src/components/TimeSeries/TimeSeries.svelte
ui/packages/app/src/components/Video/Video.svelte
ui/packages/highlighted-text/src/HighlightedText.svelte

Some small tweaks to fix a few errors i came across with interfaces.

Interface fix

---

ui/packages/app/src/components/Audio/Audio.svelte
ui/packages/app/src/components/Checkbox/Checkbox.svelte
ui/packages/app/src/components/Column/Column.svelte
ui/packages/app/src/components/Dropdown/Dropdown.svelte
ui/packages/app/src/components/File/File.svelte
ui/packages/app/src/components/HTML/HTML.svelte
ui/packages/app/src/components/HighlightedText/HighlightedText.svelte
ui/packages/app/src/components/Image/Image.svelte
ui/packages/app/src/components/Row/Row.svelte
ui/packages/app/src/components/Slider/Slider.svelte
ui/packages/app/src/components/Video/Video.svelte
ui/packages/audio/src/Audio.svelte
ui/packages/chatbot/src/ChatBot.svelte
ui/packages/file/src/FileUpload.svelte
ui/packages/form/src/Checkbox.svelte
ui/packages/form/src/CheckboxGroup.svelte
ui/packages/form/src/Dropdown.svelte
ui/packages/form/src/Number.svelte
ui/packages/form/src/Radio.svelte
ui/packages/form/src/Textbox.svelte
ui/packages/highlighted-text/src/HighlightedText.svelte
ui/packages/html/src/HTML.svelte
ui/packages/image/src/Image.svelte
ui/packages/upload/src/index.ts
ui/packages/upload/src/utils.ts
ui/packages/video/src/Video.svelte
ui/pnpm-lock.yaml

Audio previosuly expect the value to be an object rather thana string. Audio can now take a string.
Closes #896.

allow audio components to take a string value

---

ui/packages/file/src/FileUpload.svelte
ui/packages/upload/src/Upload.svelte

fix file upload text

---

gradio/blocks.py
gradio/interface.py
gradio/launchable.py
gradio/templates/frontend/index.html

Added launch analytics to `Blocks`. Didn't bother with initiate analytics because we don't use them at all
Closes #705

Blocks analytics

---

gradio/blocks.py
gradio/test_data/blocks_configs.py
test/test_blocks.py

Blocks page load

---

demo/blocks_page_load/run.py
gradio/blocks.py
gradio/test_data/blocks_configs.py
test/test_blocks.py
ui/packages/app/src/Blocks.svelte

Adds frontend for #963.
Also added a demo `blocks_page_load` to test load functions with `inputs` and `outputs`.

add frontend for page load events

---

gradio/components.py
gradio/templates/frontend/index.html
test/test_components.py
test/test_inputs.py
test/test_outputs.py

Replaces nulls with "" (for str type), 0 (for number), False (for boolean), or "01/01/1970" (for date)
So for example, the `demo\filter_records` demo looks like this:

Fixes dataframe nulls

---

gradio/components.py
gradio/templates/frontend/index.html
test/test_components.py
test/test_inputs.py
test/test_outputs.py
ui/package.json
ui/packages/app/src/components/DataFrame/DataFrame.svelte
ui/packages/app/test/blocks-basic.spec.ts
ui/packages/table/src/Table.svelte
ui/packages/workbench/src/routes/table.svelte
ui/pnpm-lock.yaml

Fixes #890. Fixes #921.
(I think these are basically duplicates)

ensure dataframe updates as expected

---

gradio/routes.py

Changed the File function in route.py to make image input available for absolute path.
I tested the absolute, relative path and same folder for image, and it worked properly.
* a summary of the change
Fixes: #988  (issue)

Fixed image input for absolute path

---

gradio/templates/frontend/index.html
test/test_processing_utils.py

Because of the ways the files were reorganized in `blocks-dev`, one of the tests that loaded an image from a URL from the GitHub repo failed. This hotfixes it.

fixed failing test on main

---

gradio/blocks.py
gradio/components.py
gradio/interface.py
gradio/test_data/blocks_configs.py
gradio/utils.py
test/test_networking.py

- enable_queue exists just under Blocks.launch()

remove-queue-from-events

---

CONTRIBUTING.md

Small change to contributing guide to explicitly list pnpm version 6 as a requirement. 
Closes: #1084

Explicitly list pnpm version 6 in contributing guide

---

setup.py
website/homepage/Dockerfile

- Fixing the website reload error. `README.md` was missing from the docker but referenced in `setup.py`
- Removing a print statement from `setup.py`

Website Reload Error

---

gradio/interface.py

Fixes examples for stateful interfaces. Closes: #851
You can test with a code snippet like the following:
```py
import random
def chat(message, history):
history = history or []
if message.startswith("How many"):
response = random.randint(1, 10)
elif message.startswith("How"):
response = random.choice(["Great", "Good", "Okay", "Bad"])
elif message.startswith("Where"):
response = random.choice(["Here", "There", "Somewhere"])
else:
response = "I don't know"
history.append((message, response))
return history, history
iface = gr.Interface(
chat,
["text", "state"],
["chatbot", "state"],
allow_screenshot=False,
allow_flagging="never",
examples=[["How many?"], ["How are you?"]]
)
iface.launch()
```

Examples state

---

ui/packages/theme/src/global.css

Avoid this top margin missalignement (on output):

Stacked form inputs css

---

ui/packages/highlighted-text/package.json
ui/packages/highlighted-text/src/HighlightedText.svelte
ui/packages/highlighted-text/src/utils.ts
ui/packages/theme/src/colors.ts
ui/packages/theme/src/index.ts
ui/packages/workbench/src/routes/highlightedtext.svelte
ui/pnpm-lock.yaml

Adds nicer default colors for HighlightText. The colors are named, so if users pass these names, we will map it to the supported shade (with both a light + dark variant when needed). Users will ahve better results with these named colours, so we should document them. When colours are chosen automatically, they are selected in the following order. I tried to make sure adjacnet colours are not too similar which is important in certain visualisations. Custom colours are still suported.
| name | primary | sceondary | 
|------|---------|-----------|
| red | `#dc2626`| `#fca5a5`|
| green | `#16a34a`| `#86efac`|
| blue | `#2563eb`| `#93c5fd`|
| yellow | `#eab308`| `#fef08a`|
| purple | `#9333ea`| `#d8b4fe`|
| teal | `#0d9488`| `#5eead4`|
| orange | `#ea580c`| `#fdba74`|
| cyan | `#0891b2`| …

highlighted text colors

---

demo/blocks_xray/run.py
gradio/blocks.py
ui/packages/app/src/components/TabItem/Tabs.svelte
ui/packages/tabs/src/TabItem.svelte
ui/packages/workbench/src/routes/tabs.svelte

@abidlabs I went for `select` can you check that my change to the python method is correct please. I have only half tested this, couldn't think of a good test case.
Closes #1123

add select event for tabitems

---

demo/gpt_j/run.py
ui/packages/app/src/components/Textbox/Textbox.svelte
ui/packages/app/src/components/Textbox/Textbox.test.ts
ui/packages/form/src/Textbox.svelte
ui/packages/workbench/src/routes/forms.svelte

- implement max_lines
- fix autoheight bug
- cleanup
Closes #980. Related #1053.

max_lines + autoheight for textbox

---

gradio/blocks.py
gradio/interface.py
ui/packages/app/src/Render.svelte
ui/packages/app/src/components/Column/Column.svelte

Adds a `variant` kwarg to `Column`. Closes #999.
@gary149 If you want to tweak the 'panel' styling for interfaces, feel feree to push to this branch.

move styling for interface panels to frontend

---

ui/packages/theme/src/tokens.css

For individual elements on a row, use `flex-1` so it grows and shrinks as needed
Before:
After:

enable flex grow for gr-box

---

gradio/components.py
gradio/interface.py
gradio/test_data/blocks_configs.py

use secondary buttons in interface

---

demo/blocks_layout/run.py
ui/packages/app/src/Blocks.svelte
ui/packages/app/src/Render.svelte
ui/packages/app/src/api.ts
ui/packages/app/src/components/Column/Column.svelte
ui/packages/app/src/components/Row/Row.svelte
ui/packages/atoms/src/Block.svelte
ui/packages/atoms/src/index.ts
ui/packages/theme/src/global.css
ui/packages/theme/src/tokens.css

This was more involved that I thought it would be. Closes #1183. Closes #1184.
In #1165 we changed some flex behaviour but this didn't work in all contexts, most notably it forced everything to grow regardless of its parent. This worked well for one case but broke some others (including the default interface layout). 
Most components are now aware of their parent and selectively apply `flex-1`.
I've also made some other tweaks as I found a few additional bugs when fixing this, all relating to layout.
**Interface**
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>
**Custom Layout**
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>
We had some custom logic to detect when form components were adjacent to …

1183 component height

---

demo/diff_texts/run.py
ui/packages/app/src/components/HighlightedText/HighlightedText.svelte
ui/packages/highlighted-text/src/HighlightedText.svelte
ui/packages/theme/src/colors.ts
ui/pnpm-lock.yaml

- show HighlightText label
- impropve colors
- tweaks

hltext-label

---

ui/packages/app/src/components/Video/Video.svelte
ui/packages/image/src/Webcam.svelte
ui/packages/video/src/Video.svelte

This fixes the issue with the webcam videos not being capture as data correctly.
I've also removed all flips from webcam related inputs. So they aren't mirrored anymore. This removes any inconsistency in how they displayed. We _actually_ want the opposite, mirror all webcam inputs but it is far more complex than just flipping an element, so I've put that off for now. We might be able to get it done very soon but it isn't a priority over other things.
Closes: #820

ensure webcam video value is propogated correctly

---

ui/packages/app/src/components/Label/Label.svelte

small fix for `gr.Label()` 
vs

Default Label label value

---

demo/blocks_flashcards/run.py
gradio/blocks.py
gradio/components.py
gradio/interface.py
gradio/templates/frontend/index.html
ui/packages/app/package.json
ui/packages/app/src/Render.svelte
ui/packages/app/src/components/Column/Column.svelte
ui/packages/app/src/components/Json/Json.svelte
ui/packages/app/src/components/Row/Row.svelte
ui/packages/atoms/src/Block.svelte
ui/packages/button/src/Button.svelte
ui/packages/form/src/Checkbox.svelte
ui/packages/form/src/CheckboxGroup.svelte
ui/packages/form/src/Dropdown.svelte
ui/packages/form/src/Number.svelte
ui/packages/form/src/Radio.svelte
ui/packages/form/src/Range.svelte
ui/packages/form/src/Textbox.svelte
ui/packages/icons/src/JSON.svelte
ui/packages/theme/src/global.css
ui/packages/theme/src/tokens.css
ui/packages/utils/src/styles.ts
ui/pnpm-lock.yaml

Okay.
Closes #1233. Closes #1237. Closes #1238.
- #1237 was just a classic bug/ oversight.
- #1233 `visible=True|False` wasn't working as we had switched out styling to a new system, reimplemented.
- tweaked the mobile styles for form grouping, so they work when we are in asmaller screen view (where columns collapse into rows)
- added a style option to `Row` (`mobile_collapse`) so that users can disable the mobile collumn collapsing. This is important because we use flex for everything and need to switch this off for some small elements, like buttons, that we want to appear side by side even on mobile (such as the 'Clear' and 'Submit' buttons in interface)
- added a style option to `Button` (`full_width`) as buttons will not fill the width of their container typically (which is good but …

Layout bugs

---

gradio/__init__.py
gradio/components.py
gradio/inputs.py
gradio/interface.py
gradio/outputs.py

* added style components for dall-e mini demo
* added support for Markdown as an IO component (closes: #1241)
* brings back basic implementation of carousel for backwards-compatibility with gradio 2.x for `gr.Interface.load()`
* small cleanups
Started working on this, but will move to a dedicated PR as it is quite complex:
* fixes gr.Interface.load for 3.0 demos (#1248)

Fixes to components

---

gradio/components.py
ui/packages/app/src/components/Gallery/Gallery.svelte
ui/packages/form/src/Textbox.svelte

- Set the default value of Gallery to `None` for some reason this had been changed recently but an empty list is not the same as a null value. A predict function could return an empty list and we need to handle that slightly differently to `None` (which is translated to `null` in js). We display the placeholder for `null` false but not for empty lists of images.
- Adds the submit event listener to the `Textbox` when the lines are equal to 1. For some reason this got removed (it was probably me).

Small bugs

---

ui/packages/app/src/components/Dataset/ExampleComponents/Video.svelte

Videos examples autoplay on mouseover but maybe we want to mute them by default? (I got jump scared)
No super strong opinion on it open to discussions.
example: https://huggingface.co/spaces/radames/edit-video-by-editing-text

Mute examples videos

---

gradio/__init__.py
gradio/blocks.py
gradio/components.py
gradio/events.py
gradio/external.py
gradio/interface.py
gradio/test_data/blocks_configs.py
gradio/utils.py
test/test_blocks.py
test/test_external.py

Took waaay longer than I thought, but there were a lot of cases to cover. We can now load any model, 2.x space, or 3.x space using `gr.Interface.load()` or basically its alias `gr.Blocks.load()`. The basic idea here is:
- When loading a `model`, it creates an `Interface` based on the type of `model`
- When loading a 2.x Space, it creates an `Interface` based on the config (very easy mapping as the config is just basically the keyword arguments needed to instantiate the `Interface`)
- When loading a 3.x Space, it reads the config and recreates the Blocks and components locally. Of course the backend functions are a little different -- instead of calling the local function, it instead calls the remote /api/predict appropriately
Touches a lot of the backend code, so happy to explain anything …

Getting Interface.load() working for 2.x and 3.x models and Spaces

---

gradio/components.py
gradio/interface.py
gradio/test_data/blocks_configs.py
test/test_blocks.py
ui/packages/app/index.html
ui/packages/app/src/Blocks.svelte
ui/packages/app/tailwind.config.js
ui/packages/atoms/src/BlockTitle.svelte
ui/packages/form/src/CheckboxGroup.svelte
ui/packages/form/src/Radio.svelte
ui/packages/theme/src/tokens.css

Introduced some minor cosmetic changes:
- Footer stays at the bottom, is grayed out except on hover
- Button variant is "secondary" (gray) by default
- Font was never loaded properly, fell back on system fonts because index.html loaded IBM Plex, and tailwind.config required Source Sans Pro. Made both refer to IMB Plex (though we could also point both to Source Sans Pro if desired)
- Introduced minor gradient to form buttons (radio / checkboxgroup), and inner shadow to input text. This was done because the UI looked quite "flat", especially when using Blocks instead of Interface since there was no gray panel background when using Blocks. These gradients/shadows were introduced in the original Huggingface theme created by victor/julien in gradio 2.x, but were removed in Gradio 3.0 design. I …

Minor cosmetic changes

---

ui/package.json
ui/packages/app/build_plugins.ts
ui/packages/app/src/main.ts
ui/packages/app/vite.config.js
ui/pnpm-lock.yaml

Adds back the static entrypoint for gradio, so that users can:
```html
<script src="https://cdn.com/{version}/gradio.js">
```
I think this will work but will need to publish and test.

add cdn entrypoint

---

ui/packages/image/src/Webcam.svelte

Quick CSS fix for camera icon, set it to be always `text-white` as icon always has a dark background
**Before:**
**After:**

set camera icon to be always text-white

---

README.md
guides/getting_started.md

This is the main README.md file and a link is written as a reference inside the `guide` folder, this leads to a 404 error. I changed the file to gradio.app website link to fix the issue.
Thanks @abidlabs for the help.

Fix broken link in guides/getting_started

---

gradio/blocks.py

This PR fixes #1406. I also enable iframe features via local jupyter dev.
Notes:
* While `IPython.display.IFrame` is a better method to generate the HTML, temporary `IPython.display.HTML` address the fact google colab is using an outdated IPython https://github.com/googlecolab/colabtools/issues/1582
* The `<div>` wrapping `<iframe>` is a hack to disable the  IPython`HTML` [iframe warning](https://github.com/ipython/ipython/blob/c97f6d2ebb9a2eee5bc6531ecaf96dcb0649dadd/IPython/core/display.py#L416-L419)

set iframe policy to enable camera and audio

---

gradio.egg-info/PKG-INFO
gradio/components.py
gradio/interface.py
ui/packages/app/src/Blocks.svelte

As identified in #1417 and in other places, there was an issue with `gr.Interface.load()` not handling the `Dataset` component correctly, which was making it unable to load Spaces that were running 3.x.  This should fix it.
Now, there is a separate issue in the example with #1417, which is that when 3.x Interfaces are loaded, they are created as regular Blocks and not Interfaces, so they cannot be used with Parallel/Series. Will work on that next, along with making Blocks callable, like what @apolinario has suggested.

Fixes `gr.Interface.load()`

---

gradio/ipython_ext.py

Previously, the %%blocks magic did not import the user's local namespace, so any variables, etc. that were defined were not available to users. This resulted in #1403 
This PR fixes that closes: #1403

bring in local namespace for jupyter magic

---

guides/getting_started.md
setup.py

Gradio no longer works on Python 3.6 becauses it calls `from __future__ import annotations`. Using [python_requires](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires) can help the package to be no longer pip installable on 3.6. 
Closes: #1016

Lower bound Python version to 3.7

---

ui/packages/form/src/Checkbox.svelte

Fixes: #1507 
test:
```
cbox = gr.Checkbox(value=True)
textbox = gr.Textbox("Hey There")
cbox.change(lambda v: gr.update(visible=v), cbox, textbox)
```

Fix checkbox default value

---

gradio/interface.py

* Implements `live=True` for input-less interfaces (closes: #1469)
Test code:
```py
def func3():
return "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"
demo = gr.Interface(func3, None, "image", live=True)
demo.launch()
```
Or a more sophisticated example:
```py
def func3():
return "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"
def f2(x):
return x
demo = gr.Interface(func3, None, "image", live=True)
demo2 = gr.Interface(f2, "text", "text")
gr.TabbedInterface([demo, demo2]).launch()
```

`live=True` for input-less Interfaces

---

ui/packages/plot/src/Plot.svelte

`object-fit:contain` only works with `max-h` if they are set on the same element. I moved `max-h` to `img` and also increased the height a bit such that the plot has enough space and can adapt to the container height.
Fixes #1546

Matplotlib max-h fix so that plots are not cut off

---

gradio/external.py
setup.py
test/test_external.py
test/test_mix.py

Modifies the tests that depend on HF Hub API to be skipped if the tests return a 429 (too many requests)

Skip tests that return 429 from HF Hub API

---

ui/packages/audio/src/Audio.svelte

This PR fixes the issue #1548 . The problem was caused by not stoping the audio tracks of the stream as part of the stop callback.
A more detailed explanation can be found in [this SO link](https://stackoverflow.com/questions/44274410/mediarecorder-stop-doesnt-clear-the-recording-icon-in-the-tab).
Now it behaves in this way:
Closes: #1548

Stop audio tracks of user media on the stop callback for the Audio component

---

ui/packages/plot/src/Plot.svelte

The issue was reported on #1544 . Seems like something is making Svelte not work properly with some document functions like `getElementById`. Anyhow, it also seems like the more Svelte-like way of doing DOM manipulations is via bindings, so I changed the plot div to use bindings and it now works.
Unfortunately, the Bokeh plots also face the same problem and this solution does not work for that case. Bokeh internally uses the div id to render with `embed_item` as it is done [here](https://github.com/gradio-app/gradio/blob/d455baca4ed982846e17b5f27b5a9429b9944f1a/ui/packages/plot/src/Plot.svelte#L58). To solve that I think either a bigger debugging to see what is messing up with the document functions or another way to render Bokeh (maybe using …

Fix plotly rendering in the Plot component

---

ui/packages/app/src/components/DataFrame/DataFrame.svelte

The Dataframe as output update was crashing when clearing due to the value being null. With these changes, when clearing the Dataframe will default to three empty rows and the column number of the headers.
Closes: #1579

Manage a null value update on Dataframe

---

ui/packages/app/src/ApiDocs.svelte

The API url displayed in the api docs is incorrent, should not include url parameter. Removed. Fixes #1572

Remove query parameter from API docs url

---

gradio/components.py
ui/packages/plot/src/Plot.svelte

Right now, you cannot update a component's "interactivity" using the standard `gr.component.update()` method: some components like `Number` actually accept `interactive` as a parameter to their `update()` method, but it has no effect, while others like `Textbox` don't accept it at all and error out.
In this PR, I'm working on fixing that. Note that the `interactive` parameter is a little different than others because it is used indirectly to set a component's `mode` property, which is what actually reflects whether a component is static or dynamic. Because "mode" is only used in the frontend, we shouldn't ask backend users to change "mode" but instead update the "mode" ourselves based on what users pass in for `interactive`. 
So I've done that in this draft PR for the `Number` component. …

Allows updating `interactive` property for components

---

gradio/__init__.py
gradio/components.py

Does a few small misc fixes:
* Creates `gr.Json` as an alias of `gr.JSON`
* Fixes some typing and documentation (Closes: #1380)
* Allows `Label` to accept `{}` as equivalent to `None` (Closes: #1388)

Misc fixes

---

gradio/components.py

Makes `gr.Button` a subclass of `IOComponent` instead of `Component` which gives it default preprocessing/postprocessing methods. This allows the value (label) of the button to be used as an input to a function or set via the output of a function.
Here's a quick example:
```py
gr.Markdown("Counter:")
a = gr.Button("1", variant="primary")
a.click(lambda x: str(int(x) + 1), a, a)
demo.launch()
```
Closes: #1404

Makes Button value gettable/settable

---

gradio/blocks.py
ui/packages/app/index.html
ui/packages/app/src/Blocks.svelte
ui/packages/app/src/components/StatusTracker/StatusTracker.svelte
ui/packages/app/src/main.ts
ui/packages/app/src/stores.ts

Finishes off what was previously started.
Allow autoscroll _only_ when it is explicitly set on the event (as it is in Interface) _and_ when the user has not set `autoscroll` to `"false"` when embedding as a web component. This ensures that 'apps' using interface will always scroll but embedded gradio interfaces won't unless the user explicitly asks them to. This is important for the UX of embedded interfaces and blocks such as on blogs or docs.

fix autoscroll

---

gradio/components.py

The `get_config` function from the Gallery component had been erased, causing the default images set to not be shown.
Closes: #1587

Restore get_config function for Gallery component

---

gradio/interface.py
gradio/mix.py
test/test_mix.py

Raises deprecation warning and rewrite gr.mix.Parallel to not use stack of functions.
Closes: #1605

Deprecation error if multiple functions are passed into `fn` parameter in `Interface`

---

gradio/utils.py
test/test_utils.py

@FarukOzderim realized we don't have auto-completion for the `Request` class. To provide auto-completion, I added the missing type hints to the `__await__`function. 
```python
def __await__(self) -> Generator[None, Any, "Request"]:
# For a quick reference: Generator[YieldType, SendType, ReturnType]
...
```
- Added missing type hints to `Request.__await__` function
- Revised test `Request` instance usages, removed redundant type hints.
-  [typing.Generator documentation](https://docs.python.org/3/library/typing.html?highlight=generator#typing.Generator)

Add type hint to provide autocompletion for the Request class

---

gradio/blocks.py
gradio/components.py
test/test_external.py
test/test_interfaces.py

Fixes #1124 
The other approach is to set postprocessing to False in the event listener. Since `Column` already has a postprocess method that's a no-op, I thought adding a postprocess method to the Interpretation component was more appropriate.
Output:

Fix interpretations

---

gradio/components.py
test/test_components.py

Fixes #1663
The [postprocess function](https://github.com/gradio-app/gradio/blob/main/gradio/external.py#L234) for text-to-speech models already converts the response from the inference api to a base64 blob (and so does postprocess) so the deserialize method should not have to read from a dict.
Tested on the original repro as well as series and parallel interfaces since I know those also use `api_mode`. 
Opting not to unit test this for now as that could introduce further flakes but filed #1665 to track discussion about how to do that in the future.

Fix Audio deserialize method

---

gradio/components.py
test/test_components.py
ui/packages/app/src/Blocks.svelte

ALternative to #1645.
- This PR checks for all types of 'null' default value (i.e. the value we get when no default value is provided), fixing the interactive/ non-interactive autodetection when no default value is given.
- I had to modify the preprocessing for Radio (which Dropdown inherits) as it was selecting the first value for the user even when none was given. I can kind of understand the reasoning but if we do this we have no way of knowing whether or a not a default value is being passed or not. I don't think we should be selecting a value for the user if they have not provided a valid one.
Closes #1569.

detect all types of null default value

---

demo/blocks_outputs/run.py
gradio/components.py
test/test_components.py
ui/packages/app/src/components/DataFrame/DataFrame.svelte
ui/packages/table/src/EditableCell.svelte
ui/packages/table/src/Table.svelte

Allows dataframe cells to contain markdown or html.
- markdown will be processed in the same way that markdown in the `Markdown` component is (using `MarkdownIt`)
- Supports both default values and generated values (via predict function)
- If the table is interactive, the 'editable' value is the resulting HTML. This feels like a niche usecase but it is supported. We could optionally disable editing for html + markdown fields. Allowing the original source markdown to be the editable value is technically possible but introduces a degree of complexity I did not want to introduce in this PR, it would require significant changes to the implementation.
Closes #1364.
cc @radames

add markdown and html support to dataframe

---

gradio/__init__.py
gradio/utils.py
test/test_utils.py

Tests were failing because we removed the .egg file, which means that pkg_resources cannot fetch the version info. This should fix it.

test hotfix

---

demo/blocks_neural_instrument_coding/run.py
demo/blocks_style/run.py
gradio/blocks.py
gradio/interface.py

Allows users to provide a custom title which shows up on the browser tab. For an `Interface`, simply uses the existing `title` kwarg. For Blocks, there is a new `title` kwarg that has been added to the constructor.
Closes #1691

Allows setting custom <title>

---

website/homepage/src/docs/template.html

I accidentally removed the component preprocessing/postprocessing, and supported events from the docs page in #1729

Add back component-specific info to docs

---

.circleci/config.yml
test/conftest.py
test/test_external.py
test/test_mix.py

Mark flaky tests and run them in a separate job. My hope is that we make the "not flaky" tests as required. We should still look into failures in the flaky tests but not prevent people from merging because of them. 
Curious what people think. Certainly we can also make some modifications to `test_external.py` so that all exceptions are ignored but I think it's still valuable to run the tests in separate jobs. 
Tests properly selected:

Mark tests as flaky and run in separate job

---

gradio/flagging.py

If multiple people were simultaneously flagging a demo using `HuggingFaceDatasetSaver`, it would error out because we didn't pull the dataset repo before changing it and trying to push the changes. This fixes and that and closes: #1727

Fixes multiple people using `HuggingFaceDatasetSaver` simultaneously

---

website/homepage/src/guides/__init__.py

Small change to support [https://gradio.app/guides.html](https://gradio.app/guides.html) as a valid URL for guides.

Add /guides.html URL for guides main page

---

gradio/examples.py

Removes public but not intended to be user facing methods from Examples docs

Remove example methods from docs

---

gradio/components.py
website/homepage/src/docs/obj_doc_template.html

Fixes #1737 
You'll see a "Format expected for examples" if the docstring has a line that starts with `Examples`

Add data format expected for examples to Docs page

---

gradio/networking.py
gradio/reload.py

If you close and restart a gradio app, it won't reuse the expected port because the endpoint is in the `TIME_WAIT` state. 
This is a state that basically exists to remove ambiguity because there could still be packages sent back over the network intended for what is now a dead connection (just how TCP works). Typically, this state lasts quite a while, 60-120 seconds which is why there needs to be such a large delay between hitting the server, killing the server, and restarting the on the same port.
We can reuse the port by setting the socket options. That is what this PR does.

reuse port without waiting to leave TIME-WAIT state

---

gradio/inputs.py
gradio/outputs.py
website/demos/map_demos.py

This PR makes it so that all demos tagged in docstrings are run on the website. Previously, we only ran demos for components if they were not listed in the guides. As we add more apis to our docs I think it will be important to automatically run the demos beyond just the components.
Note that `interface_series` and `interface_parallel` are now in the list

Run all demos in website, not just components

---

guides/embedding_gradio_demos.md

Fix formatting of "Embedding gradio demos" guide so that html tags are displayed

---

gradio/components.py
gradio/inputs.py
gradio/outputs.py
test/test_components.py

Fixes #1778
Raising a `UserWarning` instead because the default warnings filter filters out deprecation warnings lol
https://docs.python.org/3/library/warnings.html#default-warning-filter

Raise warning when using gr.inputs or gr.outputs

---

gradio/components.py
gradio/utils.py

Attempt to import TypedDict from typing_extensions
if running on python 3.7.
Remove unused importlib.metadata.
Fixes import issue on 3.7 as TypedDict was introduced in python 3.8
Should get gradio working on default colab again.
This change attempts to import TypedDict from typing_extensions when required so 3.7 users can add the new dependency as required.
This doesn't require 3.8+ users to install typing_extensions.
@pngwn @abidlabs 
Closes: #1801

Fix missing TypedDict on python 3.7

---

MANIFEST.in
setup.py

Fixes #1812
1. Clone this branch
2. python setup.py sdist
3. In a fresh env, `pip install dist/gradio-3.0.26.tar.gz` should install gradio + all dependencies
4. Unpack the source distribution. `test/test_files` and `test/requirements.txt` should be included.

Add requirements.txt and test_files to source dist

---

gradio/blocks.py
gradio/documentation.py
gradio/layouts.py
guides/developing_faster_with_reload_mode.md
website/homepage/src/docs/obj_doc_template.html

Small formatting fixes to docs and guides.
Fixes #1717

Miscellaneous formatting improvements to website

---

gradio/blocks.py
gradio/documentation.py
gradio/interface.py
test/test_blocks.py

As pointed out by @AK391, we currently only support integrating with 3rd party libraries (e.g. W&B or Comet) for `Interface` and not for `Blocks`. This PR moves the `integrate()` method to `Blocks` and adds a quick test to confirm that it is working as expected.

`integrate()` method moved to `Blocks`

---

gradio/blocks.py
gradio/interface.py
scripts/launch_website.sh
website/homepage/src/docs/obj_doc_template.html
website/homepage/src/docs/template.html

Small changes to the wording in various classes to make the documentation easier to follow

Some cleanups to the docs page

---

website/homepage/src/guides/__init__.py

When a demo in a guide has two underscores in the title (for example `hello_world_2.py` in `getting_started.md`) the markdown to HTML generator converts what's between the underscores into italic, which breaks the demo logic. This is causing demos to go missing on guides. 
This was fixed but lost in one of the big website PRs. This PR brings back the fix which is just to replace the underscores with a special token during the HTML rendering process.

Fix Underscore Bug in Demo Names

---

website/homepage/src/docs/obj_doc_template.html

Fixes #1678
I think changing the font color for the supported events (preprocessing/postprocessing) sections + line break is sufficient

Make supported events and other sections of component doc stand out

---

gradio/blocks.py
website/homepage/src/docs/template.html

Move gr.update to helpers as it works for both interfaces and blocks so "blocks utilities" may confuse users.

Move gr update to helpers

---

gradio/documentation.py

Issue is the default value in docs parameter tables gets thrown off for objects that aren't builtin types (eg `flagging_callback = CSVLogger()`). This fixes that by detecting them and using the class name instead.

Fix default value in docs for objects

---

demo/fake_gan_2/run.py
gradio/components.py
test/test_components.py
ui/packages/app/src/components/DataFrame/DataFrame.svelte

Closes #1887.
This PR ensures that Dataframe's postprocess method always returns headers along with the data, this means the frontend does not need to decide what to do with the headers. I've also moved the automatic generation of headers (when none are given, we use the list index + 1) to the backend.
I have also added some additional logic to generate a new compound set of headers for the following case:
- users set headers: `["A", "B"]`
- User returns new dataframe as a list that has more than 2 columns
In this case the existing headers will be used for the first two columns, any subsequent headers will be the list index +1. So in the above case the initial headers would be: `["A", "B"]` and after returning the new list `["A", "B", "3", "4"]`.
This PR modifies the API payload a little …

Always return headers from postprocess

---

ui/packages/app/index.html
ui/packages/app/src/Blocks.svelte

These is white-space at the bottom of any dark mode app thats not long enough for the whole page (most apps). 
Looks very gross. Fixed now. 
Also added the dark bg color to the body, so on chrome when you scroll past the body, it doesn't show white.
Fixes #1772

Fix dark mode with apps smaller than window size

---

gradio/components.py
gradio/processing_utils.py
test/test_components.py

Fixes #1867
Fixes #1533
To test, run `fake_gan` with `cache_examples=True`
```
'Generated Images','flag','username','timestamp'
'Generated Images_68533214-ea69-4e01-a557-94a714440a03','','','2022-08-02 17:02:47.356494'
'Generated Images_5e542cf3-bf6f-42f3-b0de-62dbbd214219','','','2022-08-02 17:02:48.707235'
'Generated Images_4882b0bb-e967-414a-a0e2-38ca5bb278a4','','','2022-08-02 17:02:51.111492'
'Generated Images_ccde2db1-4106-4b14-9c73-d0e5cf86d7db','','','2022-08-02 17:02:54.028124'
'Generated Images_7f8327f8-41b8-454c-990d-a04be1e3d661','','','2022-08-02 17:02:56.513317'
'Generated Images_0e50cc01-9a67-4f0a-8419-636e2d26b99f','','','2022-08-02 17:02:58.628534'
```

Enable flagging/caching examples for Gallery

---

website/homepage/src/index/demos_template.html

Removes the iframes on the landing page, replacing them with web component embeddings. Much better for styling and alignment. Both the spaces (sdk_version) and the landing page (gradio.js) are now pinned to the same version of gradio (v3.1.1). We can update this for major releases but this will insure the demos never break. Also added copy buttons to the codeblocks like we have in docs and guides.

Embedding the spaces on the landing page using web components

---

website/homepage/src/index/demos_template.html

Simple fix to load the correct script for adding copy buttons on the landing page.

Fix add_copy.js on landing page

---

website/homepage/src/index/demos_template.html

Removes the audio demo from the landing page since it isn't working. We should bring it back when #1962 is resolved or this [space](https://huggingface.co/spaces/gradio/same-person-or-different) works.

Remove broken audio demo from landing page

---

demo/dataframe_datatype/run.py
gradio/components.py
test/test_components.py

Calling `to_list()` would change the dtypes of the data in the dataframe. Using `to_dict` preserves the dtypes. 
In my opinion, the `datatype` parameter is confusing. It should not accept the value `date` because it's not clear what dateformat we would use in the conversion. We should be letting users control the format of their data from their predict function by applying as little post-processing as possible.
To test, run `demo/dataframe_datatype`
Fixes: #1833

Prevent Dataframe post-processing from changing dtypes

---

.github/workflows/deploy-pypi.yml
demo/kitchen_sink/run.py
scripts/upload_demo_to_space.py

Fixes #1934
Once a new version is uploaded to pypi, we'll automatically upload the kitchen sink to the [gradio-test-deploys-organization](https://huggingface.co/gradio-test-deploys)
Eventually I want to do this on every PR but we'd need to push the assets to the cdn on every commit

Automatically deploy kitchen sink to spaces on release

---

ui/packages/app/src/components/Gallery/Gallery.svelte

Add empty image icon to gallery when there are no images to show
#2013

Better empty state for the gr.Gallery component

---

demo/fake_gan_2/run.py
gradio/blocks.py
gradio/event_queue.py
gradio/interface.py
gradio/routes.py
guides/1)getting_started/2)key_features.md

Made Queue API a little clearer, added docstrings and documentation to site. Remove print statements. Improved estimation logic (no need to store duration history as a list)

Update Queue API, documentation

---

demo/kitchen_sink/run.py
gradio/examples.py
gradio/flagging.py
gradio/utils.py
test/test_utils.py

I went back and forth on how to best implement this, but I decided on the following approach:
* If any unsafe characters are detected in the cell value, prepend it with a single quotation mark, which prevents it from being run as a formula in Excel / LibreOffice
* Otherwise, the value in unchanged
I'm hoping that for 99% of the users, this means they can read the flagged data like a regular CSV file and not worry about any changes introduced by this quotation.
The reason I went with this approach:
* instead of quoting everything with double and single quotes ([the 2nd solution here](https://owasp.org/www-community/attacks/CSV_Injection)) is because this approach allows the data to be read in a regular CSV format (99% of the time)
* instead of not sanitizing anything: was to prevent CSV …

Sanitize for CSV

---

demo/concurrency_with_queue/run.py
demo/concurrency_without_queue/run.py
gradio/blocks.py
gradio/routes.py
gradio/utils.py

1. move creation of limiter to fastapi endpoint since run_coro_in_background works only in there
2. make max_threads compatible with queue concurrency count
3. add warning to run_coro_in_background
Tested limiter creation with putting a print into `Blocks.predict_api` and tested both queue and nonqueue demos, both works alright!

Max thread tweaks

---

ui/packages/theme/src/tokens.css

Fixes border for image and video examples by switching from shadow to border. See image_mod demo for difference

Fix examples border

---

website/homepage/src/index/demos_template.html

Fixes #2048 
Added two demos:
- [Time series forecasting with Prophet](https://huggingface.co/spaces/gradio/timeseries-forecasting-with-prophet)
- [XGBoost Classification with Explainability](https://huggingface.co/spaces/gradio/xgboost-income-prediction-with-explainability)
Forecasting, Prophet, Tabular datasets, and Prediction Explainability are all concepts that have come up in our conversations with data scientists (both internal and external) and these demos cover those concepts. 
My hope is that putting them in the front page will catch the eyes of prospective data science users. The xgboost example is a sneak peek of what we want to be able to automate for skops models.

Add data science demos to landing page

---

website/homepage/src/index/demos_template.html

Fix a mistake I made in #2067 where I didn't hide the new demos by default

Hide time series + xgboost demos by default

---

demo/all_demos/run.py
gradio/blocks.py
gradio/interface.py
test/test_blocks.py
test/test_documentation.py
test/test_event_queue.py
test/test_flagging.py
test/test_utils.py
website/homepage/src/index/demos_template.html

Three quick changes to our analytics on creation of Blocks/Interface:
* We actually fire the analytics when Blocks are created (previously, it was only when Interface was created)
* We record whether it was a Blocks or Interface that was created (using "mode")
* We also record which Gradio version they are running
I've also updated the `gradio-api-server` running to accept these analytics. We should keep in mind that we'll see an artificial bump in the "initiation" analytics as a result of this. For retrospective analysis, we should stick to launch analytics, which correctly record whenever Blocks are launched

Updated our analytics on creation of Blocks/Interface

---

gradio/components.py
test/test_components.py
test/test_files/test_label_json.json

This PR adds support for filepaths to the `Label` component. Specifically, if you pass in a filepath to a ".json" file that exists, the Label component will read it and display its contents instead of just displaying the string filepath.
This fixes: #2080

`Label` component now accepts file paths to `.json` files 

---

gradio/routes.py
guides/2)building_interfaces/4)advanced_interface_features.md
guides/3)building_with_blocks/4)custom_CSS_and_JS.md

This PR does two things:
* As part of #2086, I changed the route corresponding to serving files from `/file/` to `/file=`. However, I realized that this might break demos if people are providing file paths themselves, for example as part of custom css, as in #2074. So this PR restores the deprecated file path as well. 
* Added documentation about providing files as part of CSS to address questions that have popped up about it (including #2074). So this fixes: #2074

Accept deprecated `file` route as well

---

demo/blocks_flashcards/run.py
demo/blocks_simple_squares/run.py
demo/components_demos/run.py
demo/hangman/run.py
demo/kitchen_sink_random/run.py
demo/stream_audio/run.py
gradio/__init__.py
gradio/components.py
gradio/inputs.py
gradio/interface.py
gradio/outputs.py
gradio/utils.py
guides/2)building_interfaces/1)interface_state.md
guides/3)building_with_blocks/3)state_in_blocks.md
test/test_blocks.py
test/test_components.py
ui/packages/app/src/components/State/index.ts
ui/packages/app/src/components/Variable/index.ts
ui/packages/app/src/components/directory.ts

This PR makes some enhancements to session state. First, it introduces `gr.State()` as an alias of `gr.Variable()`, unifying the naming we use in `Blocks` and `Interface`. To use state in `Interface`, one can do either of these approaches:
* gr.Interface(..., "state", "state")
* gr.Interface(..., `gr.State()`, `gr.State()`) (previously, this would **not** work)
In Blocks, the same approach works as before but using `gr.State()` instead of `gr.Variable()`.
Some additional tests have been added. The demos and documentation have also been updated to use `gr.State()`. For backwards compatibility, `gr.Variable()` is still accepted.
Fixes: #730

Improvements to `State`

---

gradio/processing_utils.py
test/test_processing_utils.py

The goal of this PR is to make the `video_is_playable` catch more exceptions to better account for the unpredictability of the data being returned from the inference function. Noted in this PR [comment](https://github.com/gradio-app/gradio/pull/2003#discussion_r956530287)

Catch IndexError, KeyError in video_is_playable

---

ui/packages/app/package.json
ui/packages/app/src/components/Dataset/Dataset.svelte
ui/packages/app/src/components/Dataset/ExampleComponents/Dataframe.svelte
ui/packages/theme/src/tokens.css
ui/pnpm-lock.yaml

Closes #2092.
(rows x cols )
- 3 x 3, no truncation
- 4+ x 3, rows truncated to 3 and fade on bottom
- 3 x 4+, cols truncated to 3 and ellipsis on right
- 4+ x 4+, both truncated to 3, fade on bottom, ellipsis on right
Looks like this now (one of each variant), the far right preview is a CSV, these are now loaded parsed and displayed with everything else. The file name is not particularly useful information (although I could add the name as well if needed):
The final
Can be tested with the following snippet + the `test.csv` in the same folder [here](https://github.com/gradio-app/gradio/files/9434365/test.csv):
```py
examples = [
[
[
[ 1, 2, 3 ],
[ 1, 2, 3 ],
[ 1, 2, 3 ],
],
],
[
[
[ "a", "b", "c" ],
[ "a", "b", "c" ],
[ "a", "b", "c" ],
[ "a", "b", …
```

2092 df ex

---

ui/packages/theme/src/tokens.css

Crops image/video thumbnails in Examples section so they look neater. [Slack thread on pros/cons](https://huggingface.slack.com/archives/C02QZLG8GMN/p1661502226400639)

feat(samples table/gallery): Crop thumbs to square

---

gradio/examples.py
guides/3)building_with_blocks/2)controlling_layout.md

* Fixes: #2117 so that `gr.Examples` supports an `elem_id` field.
Test by running:
```py
with gr.Blocks(css="#ex{background-color: red}") as demo:
t = gr.Textbox()
gr.Examples(["hi", "hello"], t, elem_id="ex")
demo.launch()
```
* Fixes: #2101 by adding a `run_on_click` parameter to `gr.Examples`
Test by running:
```py
def test(x):
time.sleep(2)
return "xx"
t = gr.Textbox()
o = gr.Textbox()
ex = gr.Examples(["hi", "hello"], t, o, test, run_on_click=True)
demo.launch()
``` 
* Also adds documentation around rendering `gr.Examples()` using components that are placed later in the UI as we tend to get questions around this frequently (e.g. #2042)

Some enhancements to `gr.Examples`

---

ui/packages/app/src/components/Dataset/ExampleComponents/Dataframe.svelte
ui/packages/app/src/main.ts

Some fixes for Safari. Apparently transparent white and transparent black are different colours.

safari fixes

---

gradio/components.py
gradio/examples.py
test/test_components.py

The goal of this PR is to add some processing to the example data passed in by users to either:
1. Accept more data formats as valid examples for a given component, e.g. pandas dataframes for dataframes
2. Improve how the data is displayed in the UI, e.g. only display the filename for a file as opposed to the full path
3. Validate the data matches the expected format by the UI, e.g. an image example must be a path to an image file.
Points 1 and 2 follow my discussion with @abidlabs [here](https://huggingface.slack.com/archives/C02SPHC1KD1/p1661808604873899)
Point 3 is **not implemented** since I did not discuss that with anyone prior  but I think will improve the developer experience. Unfortunately, I don't think we'll be able to validate file-path based components due to the ambiguity …

Better processing of example data prior to creating dataset component

---

gradio/blocks.py
gradio/routes.py
gradio/utils.py
test/test_routes.py
test/test_utils.py

I realized during some routine testing that our named API endpoints didn't actually work -- no matter what `{name}` we provide when we make a POST request to at `/api/{name}`, it is ignored and the function with `fn_index` equal to 0 would be called.
The reason for that is that our `PredictBody` data class would automatically set `fn_index` to `0` if it was not provided:
```py
class PredictBody(BaseModel):
session_hash: Optional[str]
data: Any
fn_index: 0
``` 
This has been fixed now, additional tests have been added. Along the way, also fixed #2135, which concerned the case when two prediction functions had the same `api_name`.
Fixes: #2135

Fixed Named API Requests

---

ui/packages/model3D/src/Model3DUpload.svelte

Quick fix for when the "X" button is pressed on the model3D upload interface, another 3d image would not upload.
https://user-images.githubusercontent.com/12725292/188227654-5bbfdaa7-592d-4e59-a6f5-3a32f40afb37.mov
#2148

Quick Fix: Cannot upload Model3D image after clearing it

---

gradio/blocks.py
gradio/networking.py
gradio/strings.py
test/test_networking.py

Assuming I have this script:
```python
demo = gr.Blocks(title="Test")
demo.launch(server_name='0.0.0.0', server_port=4567)
```
Currently, running this with gradio 3.2 produce this log:
```console
Running on local URL:  http://localhost:4567/
To create a public link, set `share=True` in `launch()`.
```
But this is misleading to user since `localhost` is often associated  to `127.0.0.1` and the log should say this instead:
```console
Running on local URL:  http://0.0.0.0:4567/
``` 
This small PR basically fixed this misleading log

Fixed misleading log when server_name is '0.0.0.0'

---

gradio/components.py
gradio/processing_utils.py
test/test_processing_utils.py

Maintain any text-only PngInfo metadata on a PIL image when dragging UI images between components.
* PNG images can have metadata attached to them. This data could, for example, be added during image generation and store the generation parameters. However, if dragging an annotated image between UI elements in Gradio, the conversion to base64 would lose the metadata
* This change maintains the metadata when dragging PNGs between UI elements

Keep embedded PngInfo metadata

---

gradio/external.py
requirements.txt
test/test_external.py

Ability to load tabular classification and regression models from the hub and turn it into a demo.
Closes: #2015
```python
gr.Interface.load("models/skops-ci/test-3255bd22-bb75-4641-8655-824cd25d140f").launch()
```
Users can edit the dataframe to get new predictions
```python
gr.Interface.load("models/scikit-learn/tabular-playground").launch()
```
```python
gr.Interface.load("models/demo-org/tabular-playground").launch()
```

Skops integration: Load tabular classification and regression models from the hub

---

demo/model3D/run.py
gradio/serializing.py
test/test_components.py

Fixes #2140
The downloaded filename is the same as what is returned from the prediction function now but you'll note that the extension for the file in the Model3D demo is messed up. 
This is because when the output is cached, we return a base64 representation of the file as opposed to serving the file itself. The data streams for Model3D files have `application/x-tgif` and `application/octet-stream` mime types and I think Chrome can't guess the file extension for those mime types. 
To get around this we'd have to serve the file for examples too but decided to hold off and hear other's thoughts on the matter.

Respect original filename when cached example files are downloaded

---

ui/packages/app/src/components/Interpretation/InterpretationComponents/Audio.svelte
ui/packages/app/src/components/Interpretation/InterpretationComponents/Checkbox.svelte
ui/packages/app/src/components/Interpretation/InterpretationComponents/CheckboxGroup.svelte
ui/packages/app/src/components/Interpretation/InterpretationComponents/Dropdown.svelte
ui/packages/app/src/components/Interpretation/InterpretationComponents/Image.svelte
ui/packages/app/src/components/Interpretation/InterpretationComponents/Number.svelte
ui/packages/app/src/components/Interpretation/InterpretationComponents/Radio.svelte
ui/packages/app/src/components/Interpretation/InterpretationComponents/Slider.svelte
ui/packages/app/src/components/Interpretation/InterpretationComponents/Textbox.svelte

Fixes #2098
```python
import random
def is_greater_than_50(num: int) -> bool:
return num > 50
def sum_all(audio, checkbox, checkboxgroup, dropdown, image, number, radio, slider, textbox):
return sum(random.random() * 50 for _ in range(9))
inputs = [gr.Audio(label="My Audio", value="heath_ledger_2.mp3"), gr.Checkbox(label="My Checkbox"),
gr.CheckboxGroup(choices=["a", "b", "c"], value="b", label="My Checkboxgroup"),
gr.Dropdown(choices=["d", "e", "f"], value="f", label="My Dropdown"),
gr.Image(value="lion.jpg", label="My Image"),
gr.Number(value=5, label="My Number"),
gr.Radio(choices=[1, 2, 3, 4], value=3, label="My Radio"),
gr.Slider(minimum=0, maximum=10, value=2, step=1, label="My Slider"),
gr.Textbox(value="I love apples", label="My Textbox")]
iface = …
```

Preserve Labels In Interpretation Components

---

gradio/routes.py

Fixes: #1203 
This makes the server use the proper MIME type for the js-script file.
I made the changes as suggested in the issue. @abidlabs could you please review the changes i made?

use correct MIME type for js-script file

---

demo/blocks_flipper/run.py
demo/rows_and_columns/run.py
gradio/__init__.py
gradio/layouts.py
guides/3)building_with_blocks/2)controlling_layout.md
ui/packages/app/src/components/Accordion/Accordion.svelte
ui/packages/app/src/components/Accordion/index.ts
ui/packages/app/src/components/directory.ts

Allows users to wrap elements in an accordion. It's been requested several times and I thought this might be useful for the more complex SD demos being created right now.
Fixes: #938 
Use:
```python
with gr.Accordion("open up"):
```

Add accordion component

---

gradio/blocks.py
gradio/interface.py
test/test_blocks.py
test/test_interfaces.py

Partial functions don't have the `__name__` attribute, so were causing a problem with Interface/Blocks. This fixes: #2195 and adds a test to prevent regressions in the future.

Quick fix for partial functions

---

test/test_processing_utils.py

Closes: #1995 
I don't think we need to modify `TestFile::test_component_as_output` since the File postprocess method will create a temp file internally.

Remove creation of test.txt file in test

---

ui/packages/app/src/components/Accordion/Accordion.svelte

Accordion would reset its open/close status whenever there was any state change to any component. Fixed now.
Fixes: #2219

Fix accordion

---

gradio/routes.py

Thanks to some nice sleuthing by @dawoodkhan82 and @pngwn, we discovered that the reason the video controls were not working was because Chrome requires very particular headers to be able pause videos. This PR adds those headers.
Tested the kitchen_sink demo and can confirm everything behaves correctly.
Fixes: #2172

Fix video controls

---

demo/reverse_audio/run.py
gradio/components.py
gradio/processing_utils.py
gradio/routes.py
gradio/utils.py

Previously, you could only pass in local filepaths for the `Video` and `Audio` components. This PR adds support for URLs as well. 
Furthermore, while `Image` supported URLs for default values, examples with URLs didn't work. So this PR also fixes that. 
Fixes: #2254

Added support for URLs for `Video`, `Audio`, and `Image`

---

gradio/blocks.py
gradio/test_data/blocks_configs.py
gradio/utils.py

Fixes issue where None values are not filtered out of the config. Initially we modified `delete_none` in #2157 to not delete the `value` key so that the value of a component could be set to `None` in `gr.update`. However, we should still filter out `None` from the config outside of `gr.update`.
To test, the following demo should work without breaking the `blocks_reset` and `blocks_update` demo on spaces.
```python
box = gr.Textbox(value=None)
demo.launch() 
```
Should fix the problem mentioned in #2234

Skip value key in delete_none only during updates

---

demo/custom_path/run.py
demo/custom_paths/run.py
guides/1)getting_started/3)sharing_your_app

Exposing access to the Gradio FastAPI app allows powerful things like:
* Serving your Gradio app on a custom path: https://github.com/gradio-app/gradio/issues/344
* Embedding your Gradio app alongside an existing FastAPI app: https://github.com/gradio-app/gradio/issues/1608
This PR adds a demo and documentation about how to create and use the Gradio FastAPI app 
Fixes: #1612

Add documentation about how to create and use the Gradio FastAPI app 

---

gradio/layouts.py

This change updates the docstrings to clarify that `min_width` overrides `scale` if they conflict.
Closes: #2223

Add clarifications about min width vs. scale parameter to docs

---

gradio/queue.py
test/test_queue.py

Fixes #2282
To test 
```python
import time
def update(name):
time.sleep(5)
return f"Welcome to Gradio, {name}!"
gr.Markdown("Start typing below and then click **Run** to see the output.")
with gr.Row():
inp = gr.Textbox(placeholder="What is your name?")
out = gr.Textbox()
btn = gr.Button("Run")
btn.click(fn=update, inputs=inp, outputs=out)
demo.queue(concurrency_count=2).launch()
```
Launch at least two jobs at the same time and they both should be processing
FYI @apolinario

Fix bug where max concurrency count is not respected in queue

---

.github/workflows/deploy-pypi.yml

It's redundant now that we deploy on every pr (including the pr that triggers the release in the first place)

Don't deploy to spaces on release

---

gradio/blocks.py
gradio/components.py
gradio/examples.py
gradio/flagging.py
gradio/utils.py
test/test_blocks.py
test/test_examples.py

Previously, we couldn't handle `gr.update()` in flagging or example caching, as described in #2305. This PR fixes that.
Fixes: #2305
I'm still writing some tests but ready to be reviewed

Supports `gr.update()` in example caching

---

gradio/external.py
test/test_external.py

Closes: #1316
The approach taken is to open up a websocket connection to the space for each prediction request sent to the loaded space. The main limitation of this approach is that the loaded app doesn't display information about the request's position in the original app's queue. However, there are a couple of reasons why I went with this approach:
1. We can't send updates to the front-end if the front-end isn't running, e.g. when using the interface or app as a function.
2. The app that's loading the interface may have its own queue, and if so, it doesn't make sense to display another app's queue. Imagine you're a user of an app with a queue that's loading another app with a queue. You'd see your position decrease until your request is being processed, but then you'd see your queue …

Respect Upstream Queue when loading interfaces/blocks from Spaces

---

gradio/blocks.py

Previously, the copy button in the JSON output would not work when the Gradio demo was embedded in a jupyter/colab notebook. 
This grants the <iframe> permission to copy. 
Fixes: #2311 (well not the original issue, since that's beyond our control, but the version of it for iframes)

Clipboard fix for iframes

---

demo/custom_path/run.py
gradio/__init__.py
gradio/blocks.py
gradio/routes.py
gradio/utils.py
guides/1)getting_started/3)sharing_your_app.md
test/test_blocks.py
test/test_routes.py
ui/packages/app/src/api.ts
website/homepage/src/docs/template.html

Closes: #2292
There were two problems as noted on the original issue:
1. The ws socket path was incorrect when running as a sub application
2. The thread to run the queue was not started because that's started by the `startup-events` route that's called during `Blocks.launch`.
I think I figured out the ws path issue although I'd like some feedback from @aliabid94 .
The queue thread not starting automatically is an interesting problem. I think the cleanest thing would be to use fastapi startup events to start the queue however there are two issues with that:
- Startup events are not started for sub applications ([docs](https://fastapi.tiangolo.com/advanced/events/)) so it wouldn't solve the problem of the queue not starting when gradio is mounted
- The queue needs to know about the URL …

Start queue when gradio is a sub application

---

website/reload_website.sh
website/reload_with_notification.sh

Fixes the issue with the web tracker script, which is spamming slack with success messages despite not actually reloading the website. 
Problem was that I miswrote the if condition. This should work fine now and I've already started testing it on the gradio machine so we can see until this gets merged.

Fix Web Tracker Script

---

gradio/blocks.py

There is an issue adding 'api_name' to a function that updates a column. The stacktrace showed this was the error:
```
File "/Users/ian/Development/gradio/gradio/documentation.py", line 45, in document_fn
doc_lines = doc_str.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'
```
The function that the doc_str referred to in this case was `BlockContext.postprocess`, so just adding docs to that function was enough to fix the issue.
Closes: #2251

Add docs to blocks context postprocessing function

---

gradio/utils.py
requirements.txt

It turns out we never needed `analytics` given that our analytics are processed through our own backend server hehe
Closes: #2337

Removes `analytics` dependency

---

gradio/inputs.py
gradio/templates.py
website/homepage/src/docs/__init__.py
website/homepage/src/docs/obj_doc_template.html

I noticed that the string shortcuts for some of the new variants of `gr.Image` like `gr.Paint()` were not showing up correctly because of a missing colon:
This PR fixes that and also fixes two other outstanding issues with the docs, fixes: #2040, fixes: #134. Now:

Small fixes to docs for `Image` component

---

CHANGELOG.md
gradio/blocks.py
gradio/examples.py
test/test_blocks.py

Previously, if `postprocess` was `False`  in an event trigger, the `gr.update()`  dictionary would not work. This PR fixes that and can be tested by running the example code in the issue:
```py
base64image = "data:image/gif;base64,R0lGODlhPQBEAPeoAJosM//AwO/AwHVYZ/z595kzAP/s7P+goOXMv8+fhw/v739/f+8PD98fH/8mJl+fn/9ZWb8/PzWlwv///6wWGbImAPgTEMImIN9gUFCEm/gDALULDN8PAD6atYdCTX9gUNKlj8wZAKUsAOzZz+UMAOsJAP/Z2ccMDA8PD/95eX5NWvsJCOVNQPtfX/8zM8+QePLl38MGBr8JCP+zs9myn/8GBqwpAP/GxgwJCPny78lzYLgjAJ8vAP9fX/+MjMUcAN8zM/9wcM8ZGcATEL+QePdZWf/29uc/P9cmJu9MTDImIN+/r7+/vz8/P8VNQGNugV8AAF9fX8swMNgTAFlDOICAgPNSUnNWSMQ5MBAQEJE3QPIGAM9AQMqGcG9vb6MhJsEdGM8vLx8fH98AANIWAMuQeL8fABkTEPPQ0OM5OSYdGFl5jo+Pj/+pqcsTE78wMFNGQLYmID4dGPvd3UBAQJmTkP+8vH9QUK+vr8ZWSHpzcJMmILdwcLOGcHRQUHxwcK9PT9DQ0O/v70w5MLypo …
```

Adds ability to provide a `gr.update()` dictionary even if `postprocess=False` 

---

CHANGELOG.md
gradio/blocks.py
test/test_blocks.py

Fix is to set `show_error` to True in init. This will be overwritten in `launch` but has the benefit of showing errors in reload mode which I think is good DX since developers are writing/debugging their apps simultaneously. 
Closes: #2106 …

Prevent apps from hanging when running in reload mode and error occurs

---

CHANGELOG.md
guides/5)other_tutorials/connecting_to_a_database.md
guides/5)other_tutorials/custom_interpretations_with_blocks.md
guides/5)other_tutorials/running_background_tasks.md

Some of the embedded demos in the guides were not loading because the guide loaded the gradio web component. I think this was causing conflicts because a different version of the web component was loaded elsewhere. 
If you would like …

Fix embedded demos in some guides

---

CHANGELOG.md
ui/packages/_cdn-test/index.html
ui/packages/app/index.html
ui/packages/app/src/Blocks.svelte
ui/packages/app/src/main.ts
ui/pnpm-lock.yaml

Adds option to the `gradio-app` webcomponent to dictate whether or not the gradio app should set the HTML documents `title`. This is set to `false` by default. It is set to `true` in Gradio's own templates (because the gradio app is the _whole_ app in that case).
I've tested it with the `ui/packages/cdn_test`. You can too:
From ui:
```
pnpm build:cdn-local
pnpm preview:cdn-local
```
You can add + remove the `control_page_title` option added to the webcomponent in that package to see the effect.
Closes: #2065
Please add a brief summary of the change to the Upcoming Release > Full Changelog section of …

add option to control page title, default to false

---

CHANGELOG.md
gradio/blocks.py
gradio/exceptions.py
gradio/utils.py

I noticed that if two different users are running an iterative output demo at the same time, the two demos will not iterate asynchronously. When one demo is iterating, the other is not. This increases the latency of serving outputs to users.
You can see this here:
The culprit is that `next(iterator)` is not async, so it blocks the event loop for all users. 
This is the demo code to test:
```python
import time
import random
def fake_diffusion(steps):
for i in range(steps):
time.sleep(1)
yield random.choice([
"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
"https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWd …
```

Use async iteration for progressive outputs

---

CHANGELOG.md
website/homepage/src/demos/restart_demos.py
website/homepage/src/demos/upload_demos.py

This PR adds a script that will check if any of the spaces in the /demos tab are down, and if they are it will restart them. This is important because spaces have gone down recently, especially when we programmatically update many of them at the same time. And often they can be down for a while before we notice. 
Once it's merged I will create a cronjob in the server to run it every 15mins. 
Also, stopped the website build from failing if the AUTH_TOKEN env variable is missing, so that we can build it locally, like @freddy suggested.

Automatically restart spaces if they're down

---

CHANGELOG.md
gradio/components.py
test/test_components.py

Finally deprecates the `Carousel` component.
Closes #2417
Closes: #2426

Deprecates `Carousel` component

---

.github/workflows/ui.yml
CHANGELOG.md

If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the …

Install gradio from source in UI tests

---

CHANGELOG.md
demo/blocks_component_shortcut/run.py
gradio/components.py
gradio/events.py
ui/packages/app/src/components/Number/Number.svelte
ui/packages/app/src/components/Textbox/Textbox.svelte
ui/packages/form/src/Number.svelte
ui/packages/form/src/Textbox.svelte
website/homepage/src/docs/__init__.py

Add blur event. Triggered when user clicks out of textbox.
https://user-images.githubusercontent.com/12725292/195451431-d652365b-ded9-46ec-a6ec-454835fd0679.mov
Closes: #2449 …

Add blur event to textbox and number

---

CHANGELOG.md
website/homepage/src/templates/add_anchors.js

Fixes the issue where the mobile anchor link code is causing the embedded gradio interface to think it's inside an iframe.  
Closes: #1792 
If you would like to elaborate on your change further, feel free to include a longer …

Fix embedded interfaces on touch screen devices

---

CHANGELOG.md
gradio/networking.py
gradio/reload.py

@pngwn fixed ports with the `reuse_ports` argument in `get_first_available_port`, but when it was called from networking.start_server, it was never set to True. I just removed the argument and made the reuse logic always happen. Hopefully will never have to deal with this annoying problem again!
Btw the port would only get clogged if you make an actual request to the server, e.g. open it in a tab. If you just started an app and killed it right after, it wouldn't. FYI in case you're testing this.

Port reuse block fix

---

CHANGELOG.md
website/homepage/upload_demos.py

Demos were unnecessarily reuploading even when the version hasn't changed. This fixes that by correcting the comparison.

Small fix for version check before reuploading demos

---

CHANGELOG.md
ui/packages/app/src/components/HTML/HTML.svelte
ui/packages/app/src/components/Markdown/Markdown.svelte
ui/packages/app/src/components/StatusTracker/StatusTracker.svelte
ui/packages/html/src/HTML.svelte
ui/packages/markdown/src/Markdown.svelte

Adds status tracker to Markdown and HTML components in order to give end users feedback that the a response is pending.
Closes #2473.
Closes #1985 
Can be tested with the following snippet:
```py
from time import sleep
def fn():
sleep(3)
return [
'<div style="text-align: center"><h1>Hello</h1><h2>Hello again</h2><p>hello to all of the people</p></div>',
"# hello friends\n> who are you?",
]
gr.Textbox()
html = gr.HTML()
md = gr.Markdown()
demo.load(fn, inputs=None, outputs=[html, md])
demo.launch()
```
Hello 👋 and thank you for contributing to …

add status tracker to md and html

---

CHANGELOG.md
gradio/components.py
test/test_components.py
ui/packages/video/src/Video.svelte

Fixes #1804
There are two problems that I found:
1) When source="upload", the front-end was flipping videos since `mirror_webcam` is always set to True in the config. Regardless of whether the source is a webcam. This is the problem causing #1804. 
2) When the source is webcam and the `format` is specified (not None), the video was not flipped in the backend. There isn't an issue about this filed I think.
```python
def video_test(video):
return video
inputs_video_p5 = gr.Video(format="mp4", source="upload", label="原始视频")  # webcam
outputs_webcam_p5 = gr.Video(format='mp4', label="检测视频")
gyd = gr.Interface(
fn=video_test,
inputs=[inputs_video_p5],
outputs=[outputs_webcam_p5],
)
gyd.launch(
inbrowser=True,
)
```
```python
def video_test(video):
return …
```

Fix video mirroring issue

---

CHANGELOG.md
gradio/processing_utils.py
test/test_processing_utils.py

Removes special characters from temporary filenames so that the files can be served by components. 
Closes: #2468

Removes special characters from temporary filenames

---

CHANGELOG.md
gradio/routes.py

As discussed with @aliabid94, if a user builds `gradio` locally, we do not want them to be using `share=True` because local changes to the frontend will not be used. Instead, the frontend files from AWS S3 will be fetched. This could lead to some confusion, so instead we raise an Exception.

Fix share error message when files are built locally

---

CHANGELOG.md
gradio/blocks.py
test/test_blocks.py

Updated render() function in Blocks to return self
Closes: #2484 
If you …

Allow render() to return self

---

CHANGELOG.md
gradio/blocks.py
gradio/queue.py
gradio/routes.py
test/test_blocks.py
test/test_routes.py

Fixes #2452
Summary:
- Requests made to `/api` endpoint will be blocked if the queue is enabled for that event, unless a special auth token is passed in the header. This is to allow the queue to make requests.
- Developers can keep the api "open" by setting `queue(api_open=True)`. 
Added some unit tests but you can test yourself as well:
```python
import time
def iteration(steps):
for i in range(steps):
time.sleep(0.5)
yield i
gr.Interface(iteration,
inputs=gr.Slider(minimum=1, maximum=10, step=1, value=5),
outputs=gr.Number()).queue(api_open=False).launch()
```
In a separate process
```python
assert requests.post(
"http://127.0.0.1:7861/api/predict/",
json={"fn_index": 0, "data": [5], "session_hash": 0}).reason == 'Unauthorized'
```
Hello 👋 and thank you for …

Prevent api requests from skipping queue

---

CHANGELOG.md
gradio/blocks.py
test/test_blocks.py

Closes: #2496 and hopefully some other mysterious errors that @freddyaboulton and I have been seeing with the PR deploys

Fixes cancels to work with multiple blocks

---

CHANGELOG.md
ui/packages/app/src/api.ts

As [discussed internally](https://huggingface.slack.com/archives/C02Q9UFS8AW/p1666267765528299), it is no longer necessary to have a different URL for websocket connections on Spaces. 
Quick PR to fix that.

Remove special ws path for spaces

---

CHANGELOG.md
gradio/blocks.py
gradio/events.py
gradio/utils.py
test/test_blocks.py

Continuation of #2530 
Cancelled events were not properly dequeued because the background task was not cancelled. You can see that here:
The fix is to also update the fn indices in the cancel functions. I thought about giving the dependencies an id that's invariant to the number of dependencies in the demo but that would be a bigger change that doesn't seem worth it when adding an if statement to `render` fixes the issue.
a link to the PR (formatted in markdown) and a link …

Properly dequeue cancelled events when multiple apps are rendered

---

.github/ISSUE_TEMPLATE/config.yml

We've started to see a lot of general questions on GitHub issues. As discussed internally, it would be best to direct such users to Discord, which is what this PR does. 
See preview on my fork: https://github.com/abidlabs/gradio/issues/new/choose

Update issue template chooser to link to Discord for general questions 

---

CHANGELOG.md
demo/english_translator/run.py
demo/generate_english_german/run.py
gradio/blocks.py
gradio/exceptions.py
guides/5)other_tutorials/using_blocks_like_functions.md
test/test_external.py

Fixes #2523
Added unit tests. Can also test with some of the spaces we have in the gradio org.
If you would like …

Call fn by api_name when using Blocks.load

---

CHANGELOG.md
demo/chicago-bikeshare-dashboard/requirements.txt
demo/chicago-bikeshare-dashboard/run.py
guides/5)tabular_data_science_and_plots/1)connecting_to_a_database.md

Simplify the "connect to database" guide by using pd.read_sql. 
Also moves the associated space to the gradio org. 
If you would like to elaborate on your change further, feel free to include a longer explanation in …

Use read_sql in database guide

---

website/homepage/src/guides/__init__.py

Adds support for `/quickstart`, `/getting_started`, and `01_quickstart` all to link to the quickstart guide.

Support quickstart link paths

---

CHANGELOG.md

As it was noted in https://github.com/gradio-app/gradio/discussions/290#discussioncomment-4070556 i wrongly added my changelog note for https://github.com/gradio-app/gradio/pull/2577 in the end of the file instead of the upcoming release section. 
Should be labeled with `no-changelog-update`

Put the changelog note in the 3.9 release section

---

CHANGELOG.md

Remove a duplicate line from a changelog. The change was added in 3.9 …

Remove duplicate line from changelog

---

demo/Echocardiogram-Segmentation/run.py
demo/generate_english_german/run.py
demo/stable-diffusion/requirements.txt

The following spaces were not building:
For generate_english_german, it was caused by a typo in gr.Blocks.load. Echocardiogram-Segmentation was using deprecated gr.inputs and gr.outputs modules. stable diffusion was not able to successfully install pytorch.
I manually made fixes to those spaces and now they build. By committing these changes to the repo, they should not break again.
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For …

Fix some website demos that were not building

---

CHANGELOG.md
gradio/blocks.py
gradio/examples.py
test/test_examples.py
test/test_external.py

Fixes #2638
Test with: https://huggingface.co/spaces/freddyaboulton/calculator. This is a space created with this PR.
If you would like to elaborate on your change further, feel free to include a longer explanation in the other …

Fix loading interface with examples

---

CHANGELOG.md
gradio/blocks.py
gradio/components.py
test/test_blocks.py
test/test_examples.py

Fixes #2636 
The original bug is fixed by modifying `Block.get_specific_update` to not pass "mode" as a kwarg to `update` as that's not a user facing argument.
In addition, I made it so that the default value of `interactive` in `update` methods is True. This is because if an update method sets `interactive=False` the user has to explicitly set `interactive=True` again in a separate update call if they want to make the component interactive.
For example, in the original repro, if the default value of `interactive` in the textbox update method is None, after clicking on `short` the textbox will never be interactive again. I figured this might be too confusing for users. Wondering what others thoughts are. See the example below:
fter clicking on "short" if the default value of interactive …

Fix bug with gr.update and interactive=True

---

CHANGELOG.md
gradio/utils.py
test/test_utils.py

**Context**: we use `gr.utils.validate_url` to determine if a string is a URL or a filepath. The logic is quite simple -- we make a GET request to the URL and see if we get a result. 
However, some common media hosting sites (e.g. WikiCommons) [require a User Agent to be set](https://meta.wikimedia.org/wiki/User-Agent_policy#Python) when making a request -- otherwise, the request is immediately rejected. This fact causes `gr.utils.validate_url` to fail for these URLs. In addition, since we were checking for a strict 200 response, URLs that redirected to other URLs would fail.
This PR fixes those issues and add tests. 
Code to reproduce:
```py
gr.Audio("https://upload.wikimedia.org/wikipedia/commons/e/ef/Yellowstone_sound_library_-_Grizzly_Bears …
```

Quick fix to `gr.utils.validate_url`

---

CHANGELOG.md
demo/chicago-bikeshare-dashboard/requirements.txt
demo/generate_tone/run.py
demo/sine_curve/run.py
gradio/outputs.py
guides/03_building_with_blocks/05_using_blocks_like_functions.md

Another day, another demo pr 😂 
Just some minor tweaks. Main issue I noticed is that the markdown conversion will treat text enclosed in underscored to italics which well prevent the demo from loading. So `chicago_bike_dashboard` turned into `chicago_<em>bike<\em>_dashboard` in the `gradio-app` tag.  …

More demo fixes

---

CHANGELOG.md
gradio/interface.py
test/test_external.py

It seems like we accidentally stopped passing in `**kwarg` arguments from `gr.Interface.load()` to `gr.Blocks.load()`. This brings that back and adds a test to prevent regressions in the future.
Fixes: #2665

pass in kwargs to `Blocks.load()`

---

scripts/launch_website.sh

Adds the url arg to the website launch script. Note that this arg is only needed to display to the wheel url in the instructions on building from main in https://gradio.app/docs/main Because running the script locally won't actually build and upload a gradio wheel to aws, that url won't always work, but the website will otherwise build fine.

Fix website launch script

---

CHANGELOG.md
website/homepage/src/docs/obj_doc_template.html
website/homepage/src/docs/template.html

Methods with the same name were clashing in the docs, breaking navigation and anchor links. For example `load` in both `Interface` and `Blocks`, or `change` in every component. 
Closes: #2712

Fix id clashes in docs

---

CHANGELOG.md
gradio/utils.py

As described in the issue https://github.com/gradio-app/gradio/issues/2726: No timeout for version_check's requests, there was no timeout config for `utils.version_check()`, which blocks the Interface initiation under certain network environment.
This is a tiny PR that enables timeout for version_check, after which the waiting time would be 3 seconds instead of the default 5 minutes, or even longer.
Closes: #2726

Enable requests timout for version_check

---

CHANGELOG.md
gradio/components.py
test/test_components.py

Bugfix for the type component, without this fix it is impossible to pick "binary" or "bytes" files because one is thrown out by the validator and one is thrown out by the type check in the process single file loop.
In line 2113 the type was validated as either file or binary:
```python
valid_types = ["file", "binary"]
if type not in valid_types:
raise ValueError(
f"Invalid value for parameter `type`: {type}. Please choose from one of: {valid_types}"
)
```
However line 2183 preprocess single file wanted either "file" or "bytes"
```python
elif self.type == "bytes":
```
I have picked binary as the one to match because the documentation currently reflects the choice of "file" or "binary". No changes should be needed to existing docs.
Please see the following errors for reference:
Process …

Fixed a type bug where the validation was "binary"

---

CHANGELOG.md
website/homepage/src/docs/obj_doc_template.html
website/homepage/src/docs/template.html
website/homepage/src/templates/meta.html

I made some performance improvements to the docs, especially on mobile. I know we've talked about moving the website to a better framework, and we should still do that, but we have to make fixes now as they are currently unusable. 
* Enabled text compression (on nginx) 
* For mobile on load gradio js when example window is clicked. (this means no embedded components on mobile, but much better performance) 
* Figured out a memory leak that was causing the page to climb to insane amounts of memory (>9GB). Was due to some terrible js I wrote for hiding footers from embedded components. Fixed now and page stays at ~350MB.
* Fixed some annoying layout shifts 
* Made the page mobile responsive 
Before changes: 
After: 
Try comparing between the [website](https://gradio.app/docs/main) and [dev …

Performance improvements to docs 

---

CHANGELOG.md

#2690 was stale for a while and so I accidentally added the changelog entry to a past release. 
If you would like …

Move accordion CHANGELOG entry to next release

---

CHANGELOG.md
ui/packages/chatbot/src/ChatBot.svelte

@dawoodkhan82 noticed that images are not resized in the chatbot, which can lead to a degraded experience for very large images. A quick css fix for that.
Before:
After:
Thanks for testing @dawoodkhan82!

Resize images for chatbot

---

CHANGELOG.md
gradio/components.py
test/test_components.py
ui/packages/app/src/components/Label/Label.svelte
ui/packages/label/src/Label.svelte

Demo usecase
```python
import random
def update_color(value):
if value == "bad":
return "brown"
elif value == "so-so":
return "#ff9966"
else:
return None
def update_value():
choice = random.choice(['good', 'bad', 'so-so'])
color = update_color(choice)
return gr.Label.update(value=choice, color=color)
label = gr.Label(value=-10)
demo.load(lambda: update_value(), inputs=None, outputs=[label], every=1)
```
Question about the api: Went with the suggestion to use a function to determine the label color. The one thing I don't like about it is that it couples the styling of the component with its value. We keep those separate for the other components. Curious what others think before going further. @abidlabs @pngwn @aliabid94 …

Update Label color from backend

---

CHANGELOG.md

Small fix to CHANGELOG.md that adds the required `Version ` keyword before the version header which the nav looks for.

Fix Changelog Nav

---

CHANGELOG.md
gradio/external.py
gradio/processing_utils.py
test/test_external.py

As noted by @gary149 on slack, you can't load an automatic speech recognition model on the latest gradio.
Repro here: https://huggingface.co/spaces/freddyaboulton/openai-whisper-large
This change fixes that. Local test:
If you would …

Fix preprocessing for audio input pipelines in external.py

---

CHANGELOG.md
gradio/events.py
gradio/queue.py
guides/03_building_with_blocks/01_blocks_and_event_listeners.md
test/test_blocks.py

Fixes: #2781
The `process_event` method would never terminate even if the websocket was closed. This PR fixes that by checking which events in the batch still have open connections. If None, the task finishes.
To test, run the repro in the original issue. Also added a unit test. …

Terminate generating events early if the session is closed 

---

CHANGELOG.md
test/test_utils.py

`test/test_utils.py::TestIPAddress::test_get_ip` was failing: https://app.circleci.com/pipelines/github/gradio-app/gradio/7552/workflows/f81e5b0e-a644-4680-ab8c-8c49c1457089/jobs/16668
This patches the test

Patch ip test

---

CHANGELOG.md
gradio/utils.py
test/test_utils.py

Previously, we were using `https://api.ipify.org` to get the IP address. But this website has started to occasionally return a "Bad Gateway" response. So I switched to `https://checkip.amazonaws.com/`, which should be more reliable and also marked the test as flaky as it still relies on an external service

Patching `test_get_ip` attempt 2

---

CHANGELOG.md
requirements.txt

No longer relevant after release of httpx==0.23.1. See https://github.com/gradio-app/gradio/pull/1680
Refs https://github.com/gradio-app/gradio/pull/1680 …

Remove h11 pinning

---

CHANGELOG.md
gradio/components.py

This is a Pillow issue but the folks at Pillow suggested a workaround in https://github.com/python-pillow/Pillow/issues/6809#issuecomment-1356864228
Until Pillow merges https://github.com/python-pillow/Pillow/pull/6811 and publishes a new release (in Jan 2023 according to https://github.com/python-pillow/Pillow/issues/6750), this would be the only way to fix it.
The issue is importing matplotlib.figure will in turn import PIL.PngInfoPlugin, which causes existing extensions to not be initialized fully but only initialized with PNG formats. Thus, Image.init() have to be called before this import.
Closes: #2843

Add workaround to prevent importing gradio breaking PIL.Image.registered_extensions()

---

CHANGELOG.md
gradio/components.py
gradio/examples.py
test/test_examples.py
test/test_interfaces.py

Fixes #2186
The Dataset component already supported pagination! (We should publicize this!!)
So the only thing left to do was to make sure you could set `examples_per_page` from the Examples component. The parameter already existed, it just wasn't used.

Re-enable Example pagination on the front-end

---

CHANGELOG.md
gradio/components.py
gradio/examples.py
test/test_components.py
test/test_examples.py
test/test_interfaces.py

Fixes #2562 and add test
We have two options 1) wrap the value in a list if it's not a list already or 2) raise an error. 
I went with option 1 as that's probably what the user meant. 
If you would like to elaborate on your change …

Wrap value in list for CheckBoxGroup.

---

CHANGELOG.md
gradio/blocks.py
test/test_blocks.py

Makes it so that `default_enabled` has no impact on queue behavior as discussed in #2863
Closes: #2863
If you …

Make it so that default_enabled has no impact on queue behavior

---

CHANGELOG.md
gradio/interface.py

Add title to `TabbedInterface`

---

CHANGELOG.md
gradio/queue.py
test/test_queue.py

When an error is raised in a function that returns iterative output to Gradio, the error is not correctly displayed in the user interface. The message is never delivered to the browser.
This function correctly displays the modal error message in the browser:
```python
def foo():
raise gr.Error("Bar") # This will appear in the browser
```
But if the function is a generator that yields any results before the error is raised, the error message never appears in the browser:
```python
def foo():
yield {status_text: "It's about to fail"}
raise gr.Error("Bar") # This will not appear in the browser
```
Console output, thankfully, is not impacted by this bug.
This happens because Queue.process_events does not check the status of the last message received. It gets the status of the second last …

Fixes error message display when raising errors from a generator function

---

CHANGELOG.md
ui/packages/app/src/components/Dataset/ExampleComponents/Dataframe.svelte

Closes: #2602
To test,
1. Clone this space: gradio/test-loading-examples
2. Build this branch and run that space
3. Verify that the dataframe example does not change after click
If you would like to elaborate on your change further, …

Fix bug displaying dataframe examples in csv/tsv files

---

README.md

Small addition to the readme in case someone comes to the repo looking for information about the Discord bot

Add reference to Gradio Discord bot to README

---

CHANGELOG.md
demo/generate_notebooks.py

Checks to see if file is tracked by git before adding a wget for it in the notebook. This issue was getting annoying in a lot of PRs. 
Closes: #2756

Excluding untracked files from demo notebook check action

---

CHANGELOG.md
gradio/blocks.py
gradio/processing_utils.py

`audio_from_file` did not correctly handle the case where the file cannot be opened. This PR fixes e.g. the crash mentioned in [TheAlly's Riffusion tutorial](https://theally.notion.site/theally/Quick-n-Dirty-Riffusion-txt2audio-Tutorial-18e57df9ef214c3280efc5998bbf774d).
a link to the PR (formatted in …

Fix "audio used before assigned" bug

---

gradio/components.py
gradio/processing_utils.py
test/test_components.py

As part of #2896, I accidentally made a change which broke `TimeSeries` if the `y` columns were not specified. This undos that change. Can be tested by running ` python demo/kitchen_sink_random/run.py` on this branch vs. `main`.

Timeseries hotfix

---

.github/workflows/check-demo-notebooks.yml
.github/workflows/comment-pr.yml

Based on #2895 . From now on:
1. The notebook check will run on `pull_request` as opposed to `pull_request_target` to prevent secrets from being leaked to forks
2. The comments will come from @gradio-pr-bot
You can see this running on this PR from my fork: https://github.com/freddyaboulton/gradio/pull/24 …

Use gradio-pr-bot to make notebook check comments on PRs

---

CHANGELOG.md
gradio/blocks.py
test/test_blocks.py

This fixes a bug that prevents passing a long CSS string to `Blocks`
```python
css = """
.gr-button {
color: white;
border-color: black;
background: black;
}
"""
css = css * 5  # simulate a long css string
block = gr.Blocks(css=css)
```
The recent switch from `os.path.exists(css)` to `Path(css).exists()` makes it fail with
```
[/usr/local/lib/python3.8/dist-packages/gradio/blocks.py](https://localhost:8080/#) in __init__(self, theme, analytics_enabled, mode, title, css, **kwargs)
471         self.max_threads = 40
472         self.show_error = True
--> 473         if css is not None and Path(css).exists():
474             with open(css) as css_file:
475                 self.css = css_file.read()
OSError: [Errno 36] File name too long: '\n            .gr-button {\n....
```
Hello 👋 and thank …

Fix the path check for long CSS strings in Blocks

---

CHANGELOG.md
gradio/reload.py
test/test_reload.py

The issue was that were were calling Path().resolve(), which returned the entire path "/Users/...", and then we were replacing all "/" with "." so the path was something like ".Users.freddy." which was being treated as a relative imported.
Simply removing the leading "." was not enough to fix as uvicorn expected "Users" to be a python module. I brought back the old logic to be safe.
Also noticed that the "abs_parent" was "." since we were only getting the "name" property from the absolute path, i.e. the filename so "run.py".
Also added a unit test.
Fixes: #2963
Please add a brief …

Fix reload mode

---

CHANGELOG.md
gradio/interface.py
test/test_interfaces.py

In a recent refactor, the interpretation event was changed to not include the interpretation component as output.
This PR fixes that and adds a check to make sure the output components of the interpretation event match what's expected.
Fixes #2960 …

Fix interpretation events

---

CHANGELOG.md
ui/packages/image/src/Image.svelte

We got some feedback recently to replace the [outdated](https://stackoverflow.com/questions/2086374/what-is-the-difference-between-image-png-and-image-x-png) x-png MIME type with the now standard png MIME type.
I believe this closes: #2110 but if someone with a Mac/Ubuntu could confirm, that would be great

replace x-png with png

---

CHANGELOG.md
gradio/serializing.py
test/test_components.py

Fixes #2996 and added a unit test
You can also run this demo and it should work
```python
whisper = gr.Blocks.load(name="spaces/sanchit-gandhi/whisper-large-v2")
def transcribe(audio):
return whisper(audio, None, "transcribe", api_name="predict")
gr.Interface(
transcribe,
gr.Audio(type="filepath"),
gr.Textbox()).launch()
```
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature …

Fix file serialization so that output is json serializable

---

CHANGELOG.md
gradio/components.py
test/test_components.py

By using [`renderInLine`](https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline), the chatbot history returned does not include `<p>` or `/n`
Closes: #2775  …

Fix issue where chatbot markdown support breaks older demos (removes <p> and /n)

---

CHANGELOG.md
website/homepage/build.py
website/homepage/src/changelog/__init__.py
website/homepage/src/changelog/parent_template.html
website/homepage/src/demos/__init__.py
website/homepage/src/demos/template.html
website/homepage/src/guides/__init__.py
website/homepage/src/guides/template.html
website/homepage/src/index/__init__.py
website/homepage/src/index/demos_template.html
website/homepage/src/templates/load_latest_stable.js

Switches all the pages on the website except for `/docs/main` to use the latest gradio version instead of building from main. Stops embedding from breaking when there's an unintentional change to main. 
Will fix current embedded interfaces in `index`, `demos`, and `guides`. This will always use latest gradio (version isn't hardcoded) the same way it does for `/docs`. This has the caveat that if we publish a guide on something new we'd need a version bump to show the embedded interfaces in it the correct way, but we can move guides to be from main as well if we choose later.

Switch all pages on the website to use latest stable gradio

---

CHANGELOG.md
website/homepage/nginx.conf

Fixes a mistake in the nginx where `.md` was kept in the rules

Fix forwarding for guides after SEO renaming

---

CHANGELOG.md
ui/packages/form/src/Checkbox.svelte
ui/packages/form/src/Dropdown.svelte

Fixes #2995
How to test, run the repro from the issue
If you would like an image/gif/video showcasing your …

Trigger events on programmatic change for Dropdown and Checkbox

---

README.md

Since we removed circleci in #2927 , replacing the status badges in the readme with their github action equilvalents
If you would like to elaborate on your change further, feel free to include a longer explanation in the other …

Use github actions badges in README

---

CHANGELOG.md
ui/packages/upload-button/src/UploadButton.svelte

In the move away from tailwind, we forgot to keep the file upload `input` component hidden for `FileUpload`
https://huggingface.co/spaces/gradio/upload_button_main
If you would like to elaborate on your change …

Hide upload component

---

CHANGELOG.md
ui/packages/gallery/src/Gallery.svelte

Fixes #2984 
If the gallery is updated, we'll preserve the selected index if it corresponds to an image in the new gallery. If not, we'll revert to no image being defined.
To test,
```python
import random
import time
from PIL import Image
with gr.Blocks(analytics_enabled=False) as demo:
go = gr.Button('Go', variant="primary")
gallery = gr.Gallery().style(grid=12)
def create_images(n_images):
a = Image.new("RGB", (512, 512), "red")
b = Image.new("RGB", (512, 512), "green")
c = Image.new("RGB", (512, 512), "blue")
res = [a, b, c][:n_images]
random.shuffle(res)
return res
n_images = gr.Slider(value=3, minimum=1, maximum=3, step=1)
go.click(
fn=create_images,
inputs=[n_images],
outputs=[gallery],
)
demo.launch(share=False)
```
Hello 👋 and thank you for contributing to …

Preserve Gallery selected image through updates

---

CHANGELOG.md
guides/06_other-tutorials/creating-a-new-component.md
ui/packages/_cdn-test/index.html
ui/packages/app/package.json
ui/packages/app/snapshots/blocks_layout.spec.ts
ui/packages/app/snapshots/blocks_xray.spec.ts
ui/packages/app/snapshots/kitchen_sink.spec.ts
ui/packages/app/src/api.ts
ui/packages/app/src/main.ts
ui/packages/app/test/blocks_inputs.spec.ts
ui/packages/app/test/blocks_kinematics.spec.ts
ui/packages/app/test/blocks_page_load.spec.ts
ui/packages/app/test/blocks_xray.spec.ts
ui/packages/app/test/input_output.spec.ts
ui/packages/app/test/kitchen_sink.spec.ts
ui/packages/app/test/outbreak_forecast.spec.ts
ui/packages/app/vite.config.js
ui/playwright-setup.js

Changed the ports in dev mode.
Currently if you try to embed a gradio app (via a space) and run your embedding app locally on port 3000 (which is pretty much a default), the gradio SDK will make requests to `localhost:3000/x/x` rather than the space because of some special handling we have for production testing. This PR changes the local port to something ridiculous which should make it so that these kinds of problems never occur (for most people).
Kind of closes #2880 although I can't actually reproduce that issue.
Edit: I finally figured out #2880. It was due to the `src` attribute on the web component (rather than `host` or `space`). I think we can combine those three attributes into one. Details are here: https://github.com/gradio-app/gradio/issues/2880#issuecomment-1406418035 …

fix space embeds using `src` attribute

---

CHANGELOG.md
requirements.txt

In order for markdown rendering to work, markdown-it-py needs to be at least version 2.0.0 as discussed in the original issue
Closes: #3080
If you would like to elaborate on your change further, feel free to include a longer …

Set minimum markdown-it-py version to 2.0.0

---

CHANGELOG.md
ui/packages/app/src/components/HighlightedText/HighlightedText.svelte
ui/packages/app/src/components/Json/Json.svelte
ui/packages/chatbot/src/ChatBot.svelte

Change event listener was broken on a couple components that simply check for a change in value if the value type is an object. Basically this line:
```javascript
$: value: dispatch("change")
```
will lead to an infinite loop if the value type is an object. See #3056 for example code that causes this bug. 
The reason for this infinite loop is because in a change event listener loop:
1. the value changes, which 
2. fires the event listener, which 
3. triggers a re-render of the whole tree, which 
4. will create a new value object for all components. Values for primitives are still === to their previous values, but objects will not be considered equivalent to their previous values (they have the same internal values to their previous values, but not are not ===). 
5. This causes another …

Fix change event listener

---

CHANGELOG.md
gradio/blocks.py
gradio/utils.py
test/test_utils.py

Enable gradio to run on kaggle notebooks via share link
Test with this notebook: https://www.kaggle.com/code/freddyboultonhf/kaggle-gradio-share
Basically install this gradio build: https://gradio-builds.s3.amazonaws.com/kaggle-launch/attempt-1/gradio-3.17.0-py3-none-any.whl …

Enable gradio to work on kaggle

---

CHANGELOG.md
ui/packages/app/src/components/Dataset/Dataset.svelte

If you run `calculator_blocks` demo, you'll notice that the examples are rendered in "gallery" mode, e.g. a single clickable button, as opposed to a table, which is the right behavior as we have examples for more than one component.
This is because the `Dataset` class is determining whether to use "gallery" mode based on the value of the "headers" array, but that array can be empty if none of the components have labels. Which can be common since the default is for the label to be None.
This PR proposes that we determine whether to use "gallery" mode depending on the length of the `components` array. …

Fix example gallery mode

---

CHANGELOG.md
demo/calculator_blocks/run.py
gradio/blocks.py
gradio/routes.py
guides/06_other-tutorials/developing-faster-with-reload-mode.md
test/test_blocks.py

Fixes #2158
Fixes #1883
I noticed that if you call  `launch(....)` outside of the `if __name__ == "__main__"` block, then the `gradio` reload command will properly pick up whether or not the queue should be enabled as well as `auth` and the other `launch`-related parameters.
The downside is that the page will not reload automatically, but if you reload it yourself, it will reflect the latest state of `app.py`.
I don't think this is too annoying and it beats having to refactor the `launch` method to properly work with reload mode so I'm proposing we just update the docs to explain this behavior and call it a day.
Let me know if you agree!
The script I used to test
```python
def calculator(num1, operation, num2):
if operation == "add":
return num1 + num2
elif operation …
```

Update docs to explain how reload mode can be used with queue/auth

---

CHANGELOG.md
gradio/blocks.py
gradio/routes.py
test/test_routes.py

Add the `file_directories` argument to allow serving files from additional directories.
I was working on separating user data from source code for AUTOMATIC1111/stable-diffusion-webui to a directory external to the source and ran into trouble with various files the webui tries to serve from these locations.

add argument to allow serving files from additional directories

---

CHANGELOG.md
gradio/ipython_ext.py

Fixes #3035 by emitting a warning when a cell run with `%%blocks` has an Interface. 
Can't think of a way to fix the issue in a backwards compatible way. 
I tried skipping the duplicate id check for the magic command but then the demo rendering is messed up (as expected). See below with the code from the reproducer in the original issue:
If you already have a full Interface or blocks app defined, the benefit of the %%blocks magic as opposed to re-running the cell is marginal in my opinion. 
What the warning looks like from jupyter
Please add a brief summary of the change to the Upcoming Release > …

Emit warning when using an interface in reload mode

---

CHANGELOG.md
ui/packages/app/src/components/Dataset/Dataset.svelte

Fixes #3136 
There were two problems:
* Font for the pagination buttons in dark mode was black so you could not see them
* If the the examples table was not wide enough, the pagination buttons would be displayed in the same row as opposed to in a new row
Added some padding to the top of the pagination buttons so that they would not be too close to the table.
```python
input_ = gr.Number(label="Input")
output = gr.Number(label="Input * 2")
calc = gr.Button(value="Calculate")
examples = gr.Examples(examples=[[i] for i in range(20)],
inputs=[input_],
examples_per_page=10)
calc.click(lambda s: s * 2, input_, output)
demo.launch()
```
```python
def calculator(num1, operation, num2):
if operation == "add":
return num1 + num2
elif …
```

Fix examples pagination

---

CHANGELOG.md
ui/packages/plot/src/utils.ts

Toggling between dark and light mode would not switch the font colors used for the native plots. This made it so that you could not read the axis labels and title in dark mode.
This PR fixes that.
Will work with pngwn/ali to get the plots working with the new themes better.
You can test with `native_plots` demo. …

Fix darkmode toggle on native plots

---

CHANGELOG.md
ui/packages/upload/src/utils.ts

Partial fix to #3176. The issue is that we're not using the upstream root to fetch files.
You can test with the following document
```html
<script type="module"
src="https://gradio-dev-cdn.s3.amazonaws.com/3.18.0b1/gradio.js">
</script>
<div>
<gradio-app space="gradio/gallery_component"></gradio-app>
</div>
<div>
<gradio-app space="gradio/video_component"></gradio-app>
</div>
<div>
<gradio-app space="gradio/main_note"></gradio-app>
</div>
<div>
<gradio-app space="gradio/model3D"></gradio-app>
</div>
```
Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the …

Fix loading files from embedded spaces

---

CHANGELOG.md
ui/packages/form/src/MultiSelect.svelte

Fixes #3192
To test, use the reproducer from the original issue. Gif with correct behavior here:
If you would …

Dispatch change event for "Clear All" with multiselect

---

CHANGELOG.md
ui/packages/table/src/EditableCell.svelte

Right now, entering Pinyin in a Dataframe is not possible - see #3083. The issue is because when a cell is being edited in EditableCell.svelte, its value is bound to the array from the parent Table.svelte. So every edit causes the table to rerender, resetting the value of the input field with pinyin. This treats the next letter as a completely new entry, breaking the pinyin chain of letters. Now, the value is only updated when the input blurs, meaning when a user has completed input.
To test, install the Chinese pinyin keyboard, and enter the keys in order: `"w", "o", "1"`. Originally, this would not get converted into 我, but it should now.
I also believe this should improve performance as the table does not rerender on every edit, only when the cell finishes editing.
Fixes: #3083

Fix Table entry for Pinyin

---

CHANGELOG.md
gradio/components.py
gradio/test_data/blocks_configs.py
ui/packages/app/src/components/Button/Button.svelte
ui/packages/app/src/components/Button/index.ts
ui/packages/button/src/Button.svelte

Like other components, `gr.Button` should support a disabled mode if `interactive=False` is set. Note that unlike other components, `gr.Button()`'s interactive state should not be inferred based on whether it is an input component or not, so it needs to be explicitly set to `interactive=False` in order to be disabled. 
The current way of designating the disabled state is to show a "can't-click" cursor and show no color change when a user hovers over the button. Open to feedback on this, though I wanted to keep it pretty simple so as to not need new css variables, etc. 
Fixes: #3084

Add `interactive=False` mode to `gr.Button`

---

CHANGELOG.md
gradio/utils.py
scripts/benchmark_queue.py
test/test_components.py
ui/packages/markdown/src/Markdown.svelte

Fixes LaTeX heights so that they are set based on the height of surrounding text instead of being hardcoded by the rendering engine. Fixes: #3243 
Before:
After:

LaTeX height fix

---

CHANGELOG.md
ui/packages/plot/src/Plot.svelte
ui/pnpm-lock.yaml

Fixes #3210 . Modifies the matplotlib css so that max_height is not set (this was making all the plots tiny) and removes `width` so that the plot size reflects the python configuration.
You can test with `outbreak_forecast` and this demo:
```python
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use("Agg")
def make_plot(width, height):
fig, ax = plt.subplots(figsize=(width, height))
fruits = ['apple', 'blueberry', 'cherry', 'orange']
counts = [40, 100, 30, 55]
bar_labels = ['red', 'blue', '_red', 'orange']
bar_colors = ['tab:red', 'tab:blue', 'tab:red', 'tab:orange']
ax.bar(fruits, counts, label=bar_labels, color=bar_colors)
ax.set_ylabel('fruit supply')
ax.set_title('Fruit supply by kind and color')
ax.legend(title='Fruit color') …
```

Fix matplotlib image size

---

CHANGELOG.md
gradio/components.py
gradio/utils.py
ui/packages/button/src/Button.svelte

Was testing setting `interactive=False` for `gr.Button()` when I noticed two issues:
1. Setting `interactive=False` via a `gr.update()` wasn't working
2. It wasn't visually clear that a button was disabled unless you actually hovered over the button
This PR fixes both of those issues.
To test, run this script:
```py
a = gr.Button()
b = gr.Button(interactive=True)
a.click(lambda :gr.Button.update("hi", interactive=False), None, b)
gr.Button(variant="primary")
gr.Button(variant="primary", interactive=False)
gr.Button(variant="stop")
gr.Button(variant="stop", interactive=False)
demo.launch()
```
Which looks like this:

Some fixes to disabled buttons

---

CHANGELOG.md
gradio/utils.py
test/test_components.py
ui/packages/markdown/src/Markdown.svelte

Based on perceptive feedback from @aliabid94 and @pngwn, this fixes LaTeX font size rendering so that the height adjusts doesn't just match the surrounding text, but also adjusts based on the contents of the LaTeX formula itself. This allows multiline math (fractions, integrals) to be visible, particularly in regular paragraph tags. 
**Before (at 100% zoom)**
**After (at 100% zoom)**

LaTeX fix attempt #2

---

CHANGELOG.md
gradio/components.py

Very simple fix to bug in image docs.
Closes: #3309

Fix change event listed twice in image docs

---

.github/workflows/backend.yml
CHANGELOG.md
test/test_external.py

For the backend tests, if one of the flaky tests fails, the non-flaky tests are immediately cancelled. This is not ideal as the non-flaky tests are the ones that are required for merging.
This PR makes it so that this no longer happens. …

Dont cancel non-flaky tests if flaky tests fail

---

CHANGELOG.md
gradio/blocks.py
gradio/strings.py
website/homepage/src/templates/footer.html

Created a status page to monitor a few different things: https://status.gradio.app
* Sharing (https://gradio.live) 
* API (https://api.gradio.app/)
* Website (https://gradio.app) 
Will probably change some things around in the page so please give feedback :) 
Also added it to the `COULD_NOT_GET_SHARE_LINK` string message. Which I discovered doesn't actually get printed when there's no internet because we were only catching RuntimeErrors but [this line](https://github.com/gradio-app/gradio/blob/53e4733f2a0cbb9a696a28330dc3927c7997c165/gradio/networking.py#L160) causes a ConnectionError
Closes: #3326

Gradio Status Page 

---

CHANGELOG.md
gradio/components.py
ui/packages/gallery/src/Gallery.svelte
ui/packages/utils/src/styles.ts

Fixes #3311
- If `style=True` and the gallery is in a "Cleared State", i.e. value is [] or None, then the next update should display the gallery in preview mode. 
- Otherwise, the behavior should be the same compared to main
To test,
```python
import random
from PIL import Image
def create_images(n_images):
a = Image.new("RGB", (512, 512), "red")
b = Image.new("RGB", (512, 512), "green")
c = Image.new("RGB", (512, 512), "blue")
res = [a, b, c][:n_images]
random.shuffle(res)
return res
gr.Interface(create_images,
inputs=[gr.Slider(value=3, minimum=1, maximum=3, step=1)],
outputs=[gr.Gallery().style(grid=2, preview=True)]).launch()
```
All pull requests must update the change log located in CHANGELOG.md, unless the pull …

Add option to display gallery in preview mode

---

CHANGELOG.md
website/homepage/src/style.css

Fixes the global css that was messing up the embed footer in the guides

Fix css issue with spaces logo 

---

CHANGELOG.md
gradio/utils.py

I can no longer run a demo in the demo folder with a local install because `BlockContext` is not imported when `launched_telemetry` is run. 
Not sure how this made it through unit tests. Can someone recreate this issue on their end?
```bash
❯ python demo/blocks_multiple_event_triggers/run.py
Running on local URL:  http://127.0.0.1:7860
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
File "demo/blocks_multiple_event_triggers/run.py", line 39, in <module>
demo.launch()
File "/Users/freddy/sources/gradio/gradio/blocks.py", line 1581, in launch
utils.launched_telemetry(self, data)
File "/Users/freddy/sources/gradio/gradio/utils.py", line 159, in launched_telemetry
x, BlockContext
NameError: name 'BlockContext' is not defined
```
Hello 👋 and thank …

Fix BlockContext import bug in utils.py

---

CHANGELOG.md
gradio/blocks.py
gradio/documentation.py

Documents `launch`, `queue` and `integrate` methods in blocks. Adds new example syntax to differentiate interface methods from blocks methods in terms of example usage. 
Closes: #3398

Document Blocks methods

---

ui/packages/_website/package.json
ui/packages/_website/src/components/FunctionDoc.svelte
ui/packages/_website/src/routes/+layout.svelte
ui/packages/_website/src/routes/[guide=valid_guide]/+page.server.js
ui/packages/_website/src/routes/[guide=valid_guide]/+page.svelte
ui/packages/_website/src/routes/docs/+page.server.js
ui/packages/_website/src/routes/docs/+page.svelte
ui/packages/_website/src/routes/docs/[doc=valid_doc]/+page.svelte
ui/packages/_website/src/routes/docs/block-layouts/+page.svelte
ui/packages/_website/src/routes/docs/combining-interfaces/+page.svelte
ui/packages/_website/src/routes/docs/flagging/+page.svelte
ui/packages/_website/src/utils.ts
ui/pnpm-lock.yaml

@aliabd 
I did this work in a PR to your branch just so you could easily see what I'm doing here. Feel free to adapt the code in here, copy the changes across however you like. You can close this PR whenever you want to.
Don't know if everyone is familiar with the term 'slug' but it just means then end of the url, after the domain. It needs to be a valid url. 
So the first case is that we have some data, rather than markdown. In this case we can simply pass the most appropriate string to the `slugifier`, i grabbed one from npm. For `fn` names i used a combination of the class name + the function name so we get slugs like `#interface-load`. The slugifier also handles collisions, so if we ever have two links with the same name on the same page then it will generate a different url (it just …

Site slugs for new website

---

guides/03_building-with-blocks/04_custom-CSS-and-JS.md

The code block had a couple of typos, `color` instead of `background-color` and `elem_class` instead of `elem_classes`. 
I still can't get the `elem_class` example to work with font class, however. It doesn't increase the font size, just adds a bunch of weird spacing to the top of the text box. This is with and without `!important` cc @aliabid94 @abidlabs 
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool …

Fix custom css code block in guide

---

CHANGELOG.md
gradio/components.py
test/test_components.py

Fixes: #3552
Test code:
```py
gr.Code("""
def fn(a):
return a
""", language="python")
demo.launch()
```

Removes leading spaces from all lines of code uniformly in the `gr.Code()` component

---

CHANGELOG.md
guides/06_other-tutorials/theming-guide.md

There's a css issue with embedding the demos in the theming guide using web components. The other themes basically clash and the last one ends up applying to all the embedded demos. We had to resort to iframes but the current set up is really not mobile responsive at all. Very annoying for anyone reading the guide on a phone. 
Replacing with this. Please try it first though https://www.gradio-staging.com/theming-guide/

Mobile responsive iframes in themes guide

---

CHANGELOG.md
gradio/blocks.py
gradio/interface.py
gradio/themes/base.py
gradio/themes/default.py
gradio/themes/glass.py
gradio/themes/monochrome.py
gradio/themes/soft.py
test/test_components.py
test/test_theme_sharing.py

As discussed on slack, let's add the theme name to keep track of which themes are popular.
If you would like an …

Set theme name from load

---

CHANGELOG.md
ui/packages/form/src/Range.svelte
ui/packages/form/src/Range.test.ts

Fixes #3443 
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG …

Trigger event when Slider number input is released

---

CHANGELOG.md
gradio/components.py

This closes #3658.
After this fix, I get the correct file content:

Correct the documentation of `gr.File` component

---

website/homepage/upload_demos.py

Website wasn't building because "|" isn't supported in older versions of python. This fixes that

Hotfix website build

---

client/python/gradio_client/client.py
client/python/gradio_client/serializing.py
client/python/test/test_client.py

The root_url is not being set for the file-based serializers so the client can't download output files or videos.
If you would like to elaborate on your change further, feel free to include a longer explanation in …

Add root_url to serializers in gradio_client

---

.github/workflows/backend.yml
client/python/scripts/ci.sh
client/python/scripts/format.sh
client/python/test/requirements.txt
scripts/type_check_backend.sh
test/requirements-37.txt
test/requirements.txt

- Move pyright install to test requirements - consistent with how black and ruff are installed
- typecheck_backend.sh only checks gradio lib instead of gradio lib and gradio client - consistent with how linting is done
- ci.sh and format.sh type check the gradio client
- Set `cancel-in-progress` so that subsequent commits cancel running jobs. This frees up the queue a bit - I've seen jobs for my PRs get queued for a while since old commits are running. I think it's an acceptable trade-off, I haven't had to rely on having all the commit CI run to fix errors in my PRs.
Please add a brief summary of …

CI tweaks for gradio and gradio_client

---

.github/workflows/deploy-client-pypi.yml

The python client didn't successfully push to pypi. But that might be because I forgot to revert something I had changed during testing. Here's a quick reversion

Hot fix token in github action to publish py client to pypi

---

CHANGELOG.md
js/audio/src/Audio.svelte
test/test_pipelines.py

When audio files were being recorded, the filepath would be "audio" instead of "audio.wav", which would lead to problems like: #3479 and https://github.com/gradio-app/gradio/issues/2768#issuecomment-1497976532
This is a quick fix for this. Thanks @aliabid94 for helping me debug
Test by running:
```py
gr.Interface(lambda x:x, gr.Audio(source="microphone", type="filepath"), "textbox").launch()
```
It should now include the `.wav` suffix.
Fixes: #3479

Fix for default file name of recorded audio files

---

CHANGELOG.md
gradio/blocks.py
test/test_blocks.py

When an event handler throws an error, I usually have no idea which event handler it was. This PR attempts to rectify that by introducing the function name and received/required arguments lists in the exception. It also improves the output message for when a JavaScript function modifies the input arguments, but those arguments don't match the list of inputs to the event handler.
Related: #3082

Improve error messages for when argument lists mismatch

---

client/python/gradio_client/client.py
client/python/gradio_client/utils.py
client/python/test/test_client.py

Closes: #3803
During init, check if the space is in an invalid state and raise a helpful error if so.
Technically, the space state can switch after init but seems like a corner case for now. 
If you would like to elaborate on your …

Python Client: Handle invalid space state

---

client/python/CHANGELOG.md
client/python/gradio_client/client.py
client/python/gradio_client/serializing.py

Video components in latest gradio version were not able to be serialized because:
1. VideoSerializer was not included in Serializer map. Solution is to include subclasses as well. 
2. There was an `isinstance(x, tuple)` check in `deserialize` but tuples don't exist in json so when we load the json they get converted to lists.
Should fix the tests on main.
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool …

Fix video serializing in client

---

.github/workflows/backend.yml
CHANGELOG.md
gradio/__init__.py
gradio/themes/__init__.py
gradio/themes/builder.py
requirements.txt
test/test_theme_sharing.py

The error in running `gr.themes.builder()` should be fixed.
Closes: #3864  …

theme builder example doesn't work for `3.25.0` or later

---

CHANGELOG.md
js/plot/src/Plot.svelte

Closes: #3881
Issue was that the same div was edited across multiple plots. Using unique div ids fixes the problem. 
To test, run repro in issue
```python
from bokeh.plotting import figure
x = list(range(11))
y0 = x
y1 = [10 - i for i in x]
p1 = gr.Plot(label='Plot 1')
b1 = gr.Button('B1')
p2 = gr.Plot(label='Plot 2')
b2 = gr.Button('B2')
def plot1():
fig = figure(width=250, height=250, title='Plot1')
fig.circle(x, y0, size=10, color="navy", alpha=0.5)
return fig
def plot2():
fig = figure(width=250, height=250, title='Plot2')
fig.triangle(x, y1, size=10, color="firebrick", alpha=0.5)
return fig
b1.click(plot1, outputs=p1)
b2.click(plot2, outputs=p2)
demo.launch()
```
All pull requests must …

Fix bug multiple bokeh plots

---

CHANGELOG.md
gradio/routes.py
gradio/utils.py
test/test_routes.py
test/test_utils.py

- requesting for a non existing file, mostly through `file=path/filename.ext` would trigger a 500 error
- this update allows for a more smooth HTTP response like 404 or even 403
- simplified the `safe_join` for the use within gradio

Fix HTTP code for file request (static, assets, file)

---

CHANGELOG.md
js/app/index.html
js/app/src/Blocks.svelte

It's not really well documented that using Gradio may make your application communicate with Google Tag Manager, which allows whoever owns the property `UA-156449732-1` (hopefully someone benign) to execute basically **any code**; that should probably be made clearer.
* relevant motivation: I don't think Google Analytics code (even if it does nothing unless GTM is enabled) should exist in the base HTML template when analytics are not enabled.
* a summary of the change: move the initialization code to the Svelte template.

Move Google Tag Manager code to analytics_enabled block in Blocks.svelte

---

CHANGELOG.md
gradio/networking.py
test/test_blocks.py

Closes: #3675
Issue was that the socket was not setup to reuse a port. …

After closing demo, reuse port if its specified

---

client/python/test/conftest.py
client/python/test/test_client.py

- Refactors the tests so that they use locally running demos as opposed to spaces. Namely:
- Adds pytest fixtures for commonly used `Blocks` in the client tests
- adds a context manager called `connect` that will launch the blocks and close the server when the test is done
Kept some tests using spaces, e.g. test connecting to private spaces or to test we can pull files from remote servers correctly.
a link to the PR (formatted in markdown) and a link to your github profile …

Use local demos for client tests

---

.github/workflows/backend.yml
CHANGELOG.md
client/python/scripts/lint.sh
client/python/scripts/test.sh

No need to spend cycles running lints multiple times; just run it once in a separate step.

CI: only run backend lints once, not in all test environments

---

client/python/CHANGELOG.md
client/python/gradio_client/client.py
client/python/test/test_client.py

Long-winded title but the issue was that unnamed routes were shown with `api_name='0'` as opposed to `fn_index=0`, which caused user confusion.
```
client = Client("stabilityai/stable-diffusion") 
client.view_api()
Client.predict() Usage Info
---------------------------
Named API endpoints: 0
Unnamed API endpoints: 4
...
- predict(enter_your_prompt, enter_your_negative_prompt, guidance_scale, api_name="1") -> generated_images
Parameters:
- [Textbox] enter_your_prompt: str (string value)
- [Textbox] enter_your_negative_prompt: str (string value)
- [Slider] guidance_scale: int | float (numeric value)
Returns:
- [Gallery] generated_images: str (path to directory with images and a file associating images with captions called captions.json)
...
```
Hello 👋 and thank you for contributing to …

Fix view_api bug where unnamed rotes where showing api_name instead of fn_index

---

CHANGELOG.md
gradio/blocks.py
gradio/components.py
gradio/external.py
gradio/external_utils.py
gradio/flagging.py
gradio/helpers.py
gradio/interface.py
gradio/interpretation.py
gradio/networking.py
gradio/pipelines.py
gradio/reload.py
gradio/themes/base.py
gradio/tunneling.py
gradio/utils.py
test/test_blocks.py
test/test_components.py
test/test_examples.py
test/test_interfaces.py
test/test_mix.py
test/test_routes.py
website/homepage/src/index/__init__.py

* Relevant motivation: f-strings are cleaner to read and generally more performant than concatenation or `.format`.
* Summary of the change: wherever possible, use of `.format` etc. is replaced with f-strings. Initial automated conversion using ikamensh/flynt followed by manual fixes.

Use f-strings where possible

---

CHANGELOG.md
gradio/blocks.py
test/test_blocks.py

Fixes: #4020 
Generally, we don't allow components to be re-used between Blocks. However, we should make an exception for `gr.State`, which actually can be legitimately reused between different Blocks as the original issue shows. This carves out an exception for `gr.State` and adds a test. See original issue for code to test.

Allow state to be rendered multiple times

---

CHANGELOG.md
js/code/interactive/Code.svelte

Closes #4008 and also fixing a color issue.
The overflowing line is gone and the text is now visible in dark mode when not highlighted. I also updated the cursor to be more visible.

fix overflowing gutter and dark mode base color

---

CHANGELOG.md
gradio/blocks.py
gradio/components.py
gradio/routes.py
gradio/utils.py
guides/01_getting-started/03_sharing-your-app.md
test/test_routes.py

Security around filepaths that Gradio exposes has been something that's come up frequently. This PR adds the ability to blocklist filepaths (and also improves the allowlist mechanism). 
Closes: #3939
Edit: I just merged in #4053, which further adds the ability to specify a location where all temporary files created by Gradio are saved using an environmental variable. I considered also making this a parameter in `launch()` but the problem is that Gradio components are the ones that save temporary files and they are not aware of the `Blocks` instance. Furthermore, the Gradio temporary file location should actually *not* be a parameter in code because it could lead to code breaking if it is uploaded from e.g. a Windows local system to a Linux system like Spaces
Closes: #3597

Add ability to blocklist filepaths, ability to specify where gradio temp files are created

---

CHANGELOG.md
js/gallery/src/Gallery.svelte

Setting a gallery to empty caused an error, fixed now.
Fixes: #3944 #3737

Empty gallery fix

---

CHANGELOG.md
js/app/src/Blocks.svelte

Not sure if this was always broken or broke as a result of changes in client behaviour. Now should handle `.then` if first event fails. 
Fixes: #4113

Fix then logic to work after failures

---

CHANGELOG.md
js/app/src/Blocks.svelte
js/app/src/api_docs/CodeSnippets.svelte
js/app/src/api_docs/ResponseObject.svelte

Makes two fixes to the view API page:
1. The logo next to "view API" was not showing correctly. There was a 403 error on the console log.
2. The "view API" page was showing "undefined" for some properties because we changed the format of the `/info` route
Both are now fixed

Fixes to view API page

---

client/python/CHANGELOG.md
client/python/test/test_client.py

Fixes python client test. Previously, the `finally` block of the interface with generator case would always return an "extra" output (turning the stop button to a submit button). The refactor of the interface generator logic to use `then` gets rid of this extra output. …

Fix python client test

---

CHANGELOG.md
gradio/flagging.py
gradio/helpers.py
gradio/interface.py

Fixes: #4134
Learned something very interesting when I was working on this. We were using `inspect.Parameter.annotation` in several places. This is a method that returns the type hint of a parameter. In Python 3.x, this returns a _class_ if the type hint is a class. [However, in the future, Python (4.x?), this will be replaced with a string](https://peps.python.org/pep-0563/). More importantly, if a user has:
```
from __future__ import annotations
```
in their code while running Python 3.x, this will also return a string (the future behavior). This was causing a subtle bug that took some time to figure out. Anyways, this is now fixed because we are using `typing.get_type_hints()` instead, which is the recommendation in the PEP.

Record username when flagging

---

.editorconfig

A single `*` does not match path separators (`/`). Ref: https://editorconfig.org/#wildcards
If you would like an …

Fix the wildcard in .editorconfig to match files in nested directories

---

CHANGELOG.md
gradio/utils.py
test/test_utils.py

A fix for the issue pointed out by @hysts which was breaking Gradio demos running `Python<=3.9`
It's not a perfect fix, as it parses type annotations as strings, so for example for `gr.Request`, the type annotation has to be `gr.Request` or `gradio.Request` or `Request` for it to be recognized correctly. But I don't believe there is any other way to do it, and this should be strictly better than what we have right now since this alternative logic is only used if an exception would be have been thrown otherwise. 
Fixes: #4216

Fix for `typing.get_type_hints()` on Python 3.9 or lower

---

.changeset/nice-parents-work.md
CHANGELOG.md
client/js/src/client.ts
js/_cdn-test/package.json
package.json

Closes #4263.
There was an error with how `process_completed` messages were being handled causing the error modal to not display. Fixed in this PR. Run `gradio/calulator` with the queue enabled to test.
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, …

Ensure error modal display as expected when using the queue

---

CHANGELOG.md
gradio/blocks.py
gradio/networking.py
gradio/routes.py
test/test_networking.py

* relevant motivation: avoiding hacks that override the hard-coded defaults for `App`
* a summary of the change: threading an `app_kwargs` through to the FastAPI `App` ctor

Allow passing FastAPI app options

---

CHANGELOG.md
gradio/components.py

Simple typo
- [ * ] I have performed a self-review of my own code
- [ * ] I have added a short summary of my change to the CHANGELOG.md
- [ * ] My code follows the style guidelines of this project
- [ * ] I have commented my code in hard-to-understand areas
- [ * ] I have made corresponding changes to the documentation
- [ * ] I have added tests that prove my fix is effective or that my feature works
- [ * ] New and existing unit tests pass locally with my changes
a link to …

typo (minor): extra newline puts the documentation of colums to grid

---

CHANGELOG.md
gradio/analytics.py
gradio/blocks.py
gradio/routes.py
test/test_events.py

So that you can chain `then` off it like other event methods
Closes: #4302  …

return a Dependency instance from Blocks.load event listener

---

CHANGELOG.md
js/app/src/Blocks.svelte

Gradio is occasionally sluggish on my mobile device, so I looked at Chrome's profiler to find out that
* a lot of time is spent in Svelte's `toggle_class`, for which a PR is in: https://github.com/sveltejs/svelte/pull/8629/files
* a lot of time is spent in Gradio's `is_dep`
* `is_dep` used a strange infinite-for-loop-break-on-undefined method of iterating over Arrays; switching that to regular `for..of` (as I'd done in the unlucky #4277 for other loops) optimizes it from being 3.5% of my test app's (stable-diffusion-webui) JS time to 2.0%
* the only caller for `is_dep` is the `reduce` construct directly following it; changing that to a regular `for..of` loop and optimizing it to not even _call_ `is_dep` unless it needs to further optimizes `is_dep` to only being 1.5% of the JS time.
The …

Optimize frontend's is_dep calls

---

.changeset/wicked-eyes-sort.md
client/js/src/client.ts

```js
new Promise((res) => anotherPromise.then(() => { res(someResult) }));
```
is equivalent to
```js
anotherPromise.then(() => {return someResult});
```
Also, an error handler that only has `console.log` has been deleted. I think such an error should be thrown natively, or handled with loggers provided from fully-featured logging libraries to show call stacks and make it developer-friendly.
a link to the PR (formatted in markdown) and a link to your github profile (if you …

Remove unnecessary Promise wrapping another promise

---

CHANGELOG.md
gradio/routes.py
guides/01_getting-started/03_sharing-your-app.md
test/test_routes.py

* relevant motivation: in general, filenames starting with `.` are considered hidden; I don't think Gradio ought to expose them. The same stands for files in hidden-esque directories.

Don't allow dotfiles for /file= route

---

CHANGELOG.md
gradio/blocks.py
gradio/external.py
gradio/interface.py
gradio/routes.py
test/test_external.py
test/test_routes.py

As pointed out by @akx it's not secure to send the HF token to other domains via the `/proxy` route. This PR makes a change so that the HF token is only sent to HF domains

Do not send HF token to other domains via `/proxy`

---

pyproject.toml

Adds [PyPI project classifiers](https://pypi.org/classifiers/)
Classifiers are used to add information to the classifiers panel in PyPI. Example from [NumPy](https://pypi.org/project/numpy/): 
The reason that it is very important for this information to be present is that in an enterprise environment, security tools like [Sonatype Nexus IQ](https://help.sonatype.com/iqserver) are used to manage open source software risk. Nexus IQ specifically can be configured to [classify packages according to their license](https://help.sonatype.com/iqserver/managing/policy-management/license-threat-groups). This prevents developers from inadvertently using licenses like [GNU General Public License v2.0](https://www.tldrlegal.com/license/gnu-general-public-license-v2) without realizing that they may be …

Add pypi classifiers to pyproject.toml

---

.github/workflows/backend.yml
.github/workflows/build-pr.yml
.github/workflows/deploy-pypi.yml
.github/workflows/publish-npm.yml
.github/workflows/ui.yml
CHANGELOG.md
CONTRIBUTING.md
pnpm-lock.yaml

I simply ran `pnpm i` with `pnpm@8.6.0` to re-generate the lock file with the latest version format (`6.1`).
The lock file version has been upgraded from `6.0` to `6.1` with `pnpm@8.1.0` as written in  https://github.com/pnpm/pnpm/blob/main/lockfile/lockfile-file/CHANGELOG.md …

Run `pnpm i` with pnpm@8.6.0 to re-generate the lock file

---

scripts/helpers.sh
scripts/run_circleci.sh

The `scripts/run_circleci.sh` is obsolete, it doesn't work anymore because `.circleci/config.yml` was removed in January.

Remove obsolete run_circleci.sh

---

CHANGELOG.md
gradio/helpers.py
test/test_examples.py

Closes: #3672
To test, run reproducer from the issue. Also added a unit test.
If you would like an …

Fix Bug where File(file_count="multiple") can't be cached as example

---

client/python/pyproject.toml

Adds classifiers to [gradio-client](https://pypi.org/project/gradio-client/) as a continuation of #4383 
which added the following classifiers to the PyPI metadata for gradio:
The only difference with this is that it's for [gradio-client](https://pypi.org/project/gradio-client/), and the Scientific/Engineering :: Visualization tag has been replaced with Software Development :: User Interfaces
Previous change, #4383, was successful and can be seen at https://pypi.org/project/gradio/
No Changelog is necessary as it does not change the functionality of the library
directly via drag-and-drop.

Add pypi classifiers to client pyproject.toml

---

client/python/CHANGELOG.md
client/python/gradio_client/client.py
client/python/gradio_client/utils.py
client/python/test/test_client.py

Closes: #4340 
The problem is that the urls in `utils.py` are absolute so `urllib` will not construct the path we expect
Fix is to make the urls relative and to make sure the src ends with `/`
Added a unit test for this case and all unit tests are passing locally …

Call mounted gradio app via api

---

CHANGELOG.md
gradio/components.py
gradio/queueing.py
js/app/src/components/UploadButton/UploadButton.svelte
js/app/src/components/UploadButton/index.ts
js/upload-button/src/UploadButton.svelte
js/upload-button/src/index.ts

Closes: #4364 
Test code:
```py
gr.Button()
gr.Button(interactive=False)
gr.Button(variant="primary")
gr.Button(variant="stop", interactive=False)
gr.UploadButton()
gr.UploadButton(interactive=False)
gr.UploadButton(variant="primary")
gr.UploadButton(variant="stop", interactive=False)
```

Adds `variant` and `interactive` props to `gr.UploadButton`

---

CHANGELOG.md
gradio/queueing.py
gradio/utils.py
test/test_utils.py

For user experience, some times we need to use 'yield' in func to output part of results immediately instead of waiting for all.
And there is a bug if we use parameters every based on this condition, since in get_continuous_fn, yield a genertor dont match the output.
```
import time
def iterative(chatbot,state):
for i in range(10):
chatbot.append((str(i),str(i)))
state+="ok"
time.sleep(0.5)
yield chatbot,state
demo = gr.Blocks()
with demo:
state=gr.State("")
with gr.Row():
bt5 = gr.Button(value='method')
bt6 = gr.Button(value='cancel')
with gr.Row():
chatbot = gr.Chatbot(label='chatbot')
event = bt5.click(iterative, [chatbot,state], [chatbot,state], every=1)
bt6.click(lambda:None , [], [], cancels=[event])
demo.queue()
demo.launch()
```
```
Traceback (most recent call …
```

fix  get_continuous_fn bug when having every

---

CHANGELOG.md
js/app/src/components/Dataset/Dataset.svelte
js/table/src/Table.svelte

Examples had picked up an ugly container from the styles deprecation PR:
Dataframe had a margin top that made alignment weird - we use Row/Column padding and flex gaps for spacing between components everywhere else.

UI hotfixes for Examples and Dataframe

---

gradio/components.py

@aliabid94 this PR added `scale` and `min_width` to the docstrings for the `HTML` `__init__`, which doesn't have those params and it broke docs on the website: https://github.com/gradio-app/gradio/pull/4374

Fix docstrings in HTML Component and missing @document 

---

CHANGELOG.md
js/app/src/Blocks.svelte

the `_js` parameter would not show updates to components in the cases where both:
- there was no accompanying backend python function
- all updated values were values only, and not `gr.update` JSONs
The reason for this is the line to cause svelte to re-render (`root_node = root_node`) was for some reason only in the code when `gr.update` were loaded, or there was an update to a status-tracker. All backend python functions make status-tracker updates, so if there's any python function then it always updates. Simply moving the re-render line to run after any update should fix this. Test with
```python
a = gr.Textbox()
c = gr.Button()
c.click(None, None, a, _js="() => {console.log('abc'); return ['abc'];}")
demo.launch()
``` 
Closes: #4485

Fix JS call

---

CHANGELOG.md
gradio/routes.py
test/test_routes.py

Adds an `app_kwargs` argument to `mount_gradio_app` to match the interface of `create_app` and `launch`.
See #4488.
Closes: #4488.
- I added a test for this feature, focusing on the documented behavior
- I ran `python -m pytest test/test_routes.py`. Warnings but no errors.
- I ran `python -m pytest -m "not flaky" --ignore=client`, as described in CONTRIBUTING.md. Warnings but no errors.

add app_kwargs for mount_gradio_app

---

CHANGELOG.md
gradio/components/bar_plot.py
js/plot/src/Plot.svelte
js/plot/src/utils.ts
test/test_components.py

Closes: #4530 Closes: #4529
To test, run `native_plots` in dark mode and note that the label for the bar plot does not show up and that the plot text is white when you select `grouped` or `grouped-horizontal` int the bar plot tab.
If …

Some BarPlot Fixes

---

CHANGELOG.md
js/app/src/components/StatusTracker/Error.svelte

Fixes the error modal position. I've also bumped the text size on the error modal because at 12px it is borderline unreadable.

fix modal position

---

CHANGELOG.md
js/gallery/src/Gallery.svelte

Closes: #4543
When setting a height on the gallery, the select event is not being triggered when `allow_preview=False` because `can_zoom` is being calculated as `False`. 
Not too familiar with the gallery code but I assumed the `can_zoom` logic is correct. Since the gallery won't zoom with `allow_preview=False`, my fix is to set `can_zoom=true` in that case to trigger the event. But please check me @pngwn @hannahblair @aliabid94  @dawoodkhan82 
a link to the PR (formatted in …

Fix gallery select event with custom height and allow_preview=False

---

CHANGELOG.md
gradio/components/__init__.py

Restore some missing imports in `__init__`

---

CHANGELOG.md
gradio/components/__init__.py
js/app/src/components/Group/Group.svelte
js/app/src/components/Group/Group.test.ts

Closes: #4505
In order to make sure this regression does not happen again, I wrote a TS test. However, I'm not happy with this test, as it tests implementation (the presence of a class name) instead of behavior (checking to see if the CSS display is actually set to "none"). 
I tried adding these lines of JS to the test but it wouldn't work for me:
at the beginning of the test:
```js
// Wait for any potential reactivity updates in the component
await waitFor(() => {});
```
and at the end of the test:
```js
const computedStyles = window.getComputedStyle(groupElement);
assert(computedStyles.display === 'none', "Group element is not hidden.");
```
If we can get this to work, that'd be much better!

setting `visible=False` to `gr.Group` hides it

---

CHANGELOG.md
js/audio/src/Audio.svelte
js/image/src/Webcam.svelte

Closes: #4547 
The stop_recording event does not send the microphone data when the event is triggered. This PR fixes that. I think the same thing is happening on video, will investigate.
To test, run this demo and observe that the output audio and video components are populated correctly.
```python
def test(ori):
ori
with gr.Row():
audio = gr.Audio(source='microphone')
video = gr.Video(source='webcam')
audio_output = gr.Audio()
video_output = gr.Video()
audio.stop_recording(lambda x: x, inputs=audio, outputs=audio_output)
video.stop_recording(lambda x: x, inputs=video, outputs =video_output)
demo.launch()
```
This repro from the original PR that introduced this PR still works as expected
```python …
```

Send component data on stop_recording event

---

.config/eslint.config.js
.config/playwright-setup.js
js/tootils/src/index.ts
package.json
pnpm-lock.yaml

I have made some improvements the browser tests setup.
**Better logging**
When you run `pnpm test:browser` the runner will _always_ print the python startup logs. Previously most logs were suppressed because they interfere with the test runner logs but when something goes running with starting up the python process, it usually happens before the test have run. Logging at this point will not interfere with the test runner because the test runner hasn't really started yet.  
Logs after the test has started will still be suppressed.
To view all logs you can run `pnpm test:browser:verbose`, this dopes interfere with the test runner logs but it is useful to see them if something isn't working correctly.
I also added some pretty colours. When you run the tests, it now looks like this:
**Better …

Test improve

---

CHANGELOG.md
js/app/src/components/File/File.svelte
js/app/src/components/UploadButton/UploadButton.svelte

There was a delay between an uploaded file and then trigger for `change` and `upload` listeners. This was caused by the fact that files were actually getting uploaded *twice*, once in the svelte File component, and once in the client library when submitting data. This us because the client looks to see if there's any blob in the component data and uploads it. I removed the blob in the component so that the client does not resubmit - ideally we could let the client handle all uploading but the upload animation and dispatching of "change" and "submit" within the component won't work with that, so it's handled only in the component now. 
Fixes: #4385 
To test, run any demo that has a change or upload trigger on file, example below. Previously, you would see a lag between the finishing of the …

fix upload file delay

---

CHANGELOG.md
gradio/components/checkboxgroup.py
gradio/components/color_picker.py
gradio/components/dropdown.py
gradio/components/radio.py
gradio/components/slider.py
gradio/components/textbox.py

After #4456, we no longer make use of `cleared_value`
The only references to `cleared_value` on spaces are a couple of spaces implementing their own clear button running older versions of gradio:
https://huggingface.co/search/full-text?q=cleared_value&type=space
Not used in Auto1111 either so I think its safe to remove: https://github.com/search?q=repo%3AAUTOMATIC1111%2Fstable-diffusion-webui+cleared_value&type=code
1. PRs will only be merged if tests pass on CI. To run the tests locally, please …

Remove cleared_value

---

guides/07_other-tutorials/creating-a-chatbot.md

The chatbot_streaming demo was deleted in this PR: https://github.com/gradio-app/gradio/pull/4662 
But it's still referenced in a guide and when the website builds it tries to find the demo code and can't.

Remove chatbot_streaming from guide

---

.changeset/nasty-crabs-teach.md
js/app/src/lite/index.ts
js/wasm/src/cross-origin-worker.ts
js/wasm/src/worker-proxy.ts

[`@gradio/lite`](https://www.npmjs.com/package/@gradio/lite)@0.1.0 is now on NPM and can be loaded through CDN such as jsdelivr.
However, the execution fails because WebWorker initialization (`new Worker(<url>)`) doesn't work when the worker file is served from a different origin. To reproduce the error, use the HTML file below. The error is like:
```
DOMException: Failed to construct 'Worker': Script at 'https://cdn.jsdelivr.net/npm/@gradio/lite@0.1.0/dist/assets/webworker-d0ef9a1b.js' cannot be accessed from origin 'http://localhost:8080'.
```
To workaround it, I would introduce a technique I introduced to [stlite](https://github.com/whitphx/stlite) at https://github.com/whitphx/stlite/pull/482/commits/94502a0970b788d1f6dea4a6e826a73dea4fb506:
We use the `CrossOriginWorker` class to …

Introduce CrossOriginWorker class to load the WebWorker file from a different domain

---

.changeset/purple-falcons-rhyme.md
js/app/lite.html
js/app/src/lite/index.ts

A new API to rerun the Python code and refresh the frontend app without reloading the whole Pyodide process.
1. Unless the pull request is labeled with the …

Lite: Rerun the Python code and refresh the frontend

---

.config/playwright-setup.js

It seem the port was being freed up but the python process was running in the background. It seem it wasn't responding to SIGTERM. I've changed this to SIGKILL and it seems to clean things up as expected.

kill process properly in test teardown

---

client/python/CHANGELOG.md
client/python/gradio_client/serializing.py
client/python/gradio_client/utils.py
client/python/test/test_utils.py

I was profiling things and noticed a whole lot of time was spent in `is_valid_url` and was pretty surprised that that function actually does HTTP requests if it can.
This PR:
* makes that function share a `requests` session if it needs to do both HEAD + GET
* renames that function to `probe_url` because that's more what it does, with a deprecation trampoline for possible external users
* changes uses where `is_valid_url` was only used to check whether another function that does a `requests` request should be called to the new `is_http_url_like` function.
While working on that I realized there were small bugs in `encode_url_to_base64` and `download_tmp_copy_of_file` where they didn't check for the response status, and would thus happily end up writing e.g. an error page out.
These changes …

URL validation/access fixes

---

.github/workflows/ui.yml

Noticed that Chromatic [job was failing here](https://github.com/gradio-app/gradio/pull/4815) because it was looking for a non-existent version of `gradio`. We should be installing `gradio` from source to test the latest changes on the PR instead of the version of `gradio` that is already released to pypi

Install gradio from source for chromatic

---

.changeset/spicy-fishes-taste.md
js/wasm/src/webworker/index.ts

The package name `markdown-it` passed to the package manager should be `markdown-it[linkify]` to work on Gradio and to make `gr.Markdown()` work, same as
https://github.com/gradio-app/gradio/blob/1c9ebdea5b288bd7358ba6e0d72d8069c021e44a/requirements.txt#L10
1. You …

Lite: Fix the markdown-it package name spec on the Wasm worker

---

CHANGELOG.md
js/app/src/api_docs/CodeSnippets.svelte
js/app/src/api_docs/InstallSnippet.svelte

API page used to render copy buttons weird on safari. Fixed. Also quick fix to spacing in code snippet.

Fix API page code snippets in safari

---

.changeset/evil-mirrors-switch.md
js/theme/src/reset.css
js/theme/src/typography.css

footer img was inheriting margin, and h1 was inheriting color.
Fixes: #4963

Add CSS resets and specifiers to play nice with HF blog

---

.vscode/settings.json

Whenever I update a `.svelte`, `.json` or `.ts` file, vs code will do some autoformatting that introduces a lot of additional changes irrelevant to my PR and doesn't conform to our standard lint commands anyways.
So I'm deleting it so that global user preferences takeover. …

Dont format on save for vscode

---

.changeset/eight-humans-sniff.md
guides/03_building-with-blocks/01_blocks-and-event-listeners.md
js/form/src/Dropdown.stories.svelte
js/form/src/Dropdown.svelte

2 more fixes to `gr.Dropdown()`:
1. In static mode, the `gr.Dropdown(multiselect=True)` still had the X icons, and clicking on an option would remove it. This behavior has been disabled in static mode. Test with:
```py
with gr.Blocks() as gr_training_zoo:
d2 = gr.Dropdown(
["ran", "swam", "ate", "slept"],
value=["swam"],
multiselect=True,
label="Initialized",
info="Only value removal allowed, no adding",
)
gr_training_zoo.launch()
``` 
Also we had never really documented how Gradio determines the interactivity of a component if `interactive` was not specified and the component was neither an input nor an output. I've added that to the relevant Guide. Together, this closes: #4280. 
2. Clicking on a dropdown option `gr.Dropdown(multiselect=False)` would select it, yet it …

`gr.Dropdown` now has correct behavior in static mode as well as when an option is selected

---

.changeset/gold-radios-train.md
.changeset/quick-toes-teach.md
gradio/components/checkboxgroup.py
gradio/components/radio.py

Updates the docstrings for `gr.CheckboxGroup` and `gr.Radio` to include the fact that the components can pass in and return numeric types, not just strings.
Closes: #4859 -- I decided against changing `gr.Dropdown()` to preserve numeric types. Currently `gr.Dropdown` casts everything to a string, the inconsistency is annoying, but changing it would be a breaking change -- it would, in all likelihood, break some demos. Since the community hasn't raised any issues, I've decided to leave as is

Update typing info for `gr.CheckboxGroup` and `gr.Radio`

---

.changeset/true-camels-shave.md
gradio/blocks.py
gradio/utils.py
test/test_blocks.py

https://github.com/gradio-app/gradio/pull/4937 follow-up
- Properly set `Queue.max_size` (default) and `Queue.concurrency_count` (forcefully) on ZeroGPU Spaces environment
- Warn if `concurrency_count` parameter is passed in `Blocks.queue()`
Internal Slack conversation : https://huggingface.slack.com/archives/C04ABS7C13K/p1691484769646489?thread_ts=1689176130.473819&cid=C04ABS7C13K

[Spaces] ZeroGPU Queue fix

---

.changeset/good-years-ask.md
js/textbox/shared/Textbox.svelte

When the textbox value is cleared, it's set to `None` on the backend. When the value is set to None in the backend, this PR adds a func set it to `""` in the frontend. 
Closes: #5103 …

Reset textbox value to empty string when value is None

---

.changeset/wide-bars-train.md
js/video/shared/Player.svelte

Tiniest PR ever, just to fix: #5132 
Test with:
```py
gr.Video("https://kevinqhlin-univtg.hf.space/file=/tmp/gradio/a4dc9029d4e7eb3a2ae7bba8316a4a10ade920a0/youtube.mp4")
demo.launch()
```
Or if you want to create longer local video files:
```py
from moviepy.editor import *
def color_clip(size, duration, fps=25, color=(0,0,0), output='color.mp4'):
ColorClip(size, color, duration=duration).write_videofile(output, fps=fps)
size = (200, 100)
duration = 2*60*60
color_clip(size, duration)
gr.Video("color.mp4")
demo.launch()
```

Fixes the display of minutes in the video player

---

.changeset/new-icons-refuse.md
gradio/flagging.py
test/test_flagging.py

Fixes:
- If a media file (Image/Audio) was None, flagging would fail
- Jsonl dataset format was not compatible with datasets library
- Paths in json files now include the full path relative to the root of the dataset dir. This helps loading to HuggingFace datasets library.
Internal thread where this came up: https://huggingface.slack.com/archives/C02QZLG8GMN/p1691444822924499
To test:
Set up a demo with flagging
```python
def echo(msg, history, img):
return msg
image = gr.Image(label='Image')
chat = gr.ChatInterface(echo, additional_inputs=[image])
flagger = gr.Button("Flag")
flagging = gr.HuggingFaceDatasetSaver(
dataset_name="chatinterface_with_image_csv",
hf_token="<your token>",
separate_dirs=True)
flagging.setup([chat.chatbot, image], …
```

Fix dataset features and dataset preview for HuggingFaceDatasetSaver

---

.changeset/light-mice-bake.md
gradio/themes/app.py
gradio/themes/builder_app.py

The header image in the theme builder was referencing a file from our GitHub repo which was moved due to recent refactoring. I've uploaded the image to the S3 bucket and updated the references.

Fix the images in the theme builder to use permanent URI

---

.changeset/hip-queens-grin.md
gradio/blocks.py

There's no need to be passing inputs and preprocessing them on every generator call - this is extremely inefficient and causes slowdowns if the preprocess step is expensive. Was causing significant issues raised internally here: https://huggingface.slack.com/archives/C02QZLG8GMN/p1692350120362899?thread_ts=1692278870.837829&cid=C02QZLG8GMN
Fixed now, preprocessing only happens on the first step.

Stop passing inputs and preprocessing on iterators

---

.changeset/khaki-otters-wear.md
js/dataframe/Dataframe.stories.svelte
js/dataframe/shared/Table.svelte
js/dropdown/Dropdown.stories.svelte

We were handling empty dataframes incorrectly in the `gr.Dataframe` --> we were turning them into single-row arrays with each cell being "".
This fixes that -- would appreciate if folks could test this out to make sure I didn't miss anything as the dataframe frontend code is quite complex.
Fixes: #5162
Test code:
```py
df_orig = pd.DataFrame([], columns=['a', 'b', 'c'])
df_fill = pd.DataFrame([[1, 2, 3]], columns=['a', 'b', 'c'])
df = gr.Dataframe(value=df_orig, interactive=True, row_count=(0, "dynamic"))
df2 = gr.Dataframe(value=df_fill, interactive=True, row_count=(0, "dynamic"))
btn = gr.Button()
text = gr.Textbox()
btn.click(fn=lambda x: x.shape, inputs=df, outputs=text)
```
Also adds some stories …

Better handling of empty dataframe in `gr.DataFrame`

---

.changeset/young-plums-swim.md
js/app/src/Blocks.svelte

`built_with_gradio` and `use_via_api` weren't rendering correctly due to missing curly braces.

Ensure `Blocks` translation copy renders correctly

---

.changeset/eight-things-travel.md
gradio/components/upload_button.py

Quick fix needed for idefics demo, cc @yvrjsharma @dawoodkhan82 
Test code:
```py
def dummy():
return gr.update(label='🖼️', interactive=True)
def add_text(*args):
pass
def add_file(*args):
pass
def bot(*args):
pass
chatbot = gr.Chatbot([], elem_id="chatbot", height=750)
with gr.Row():
with gr.Column(scale=0.85):
txt = gr.Textbox(
show_label=False,
placeholder="Enter text and press enter, or upload an image",
container=False,
)
with gr.Column(scale=0.15, min_width=0):
btn = gr.UploadButton(label="📁", file_types=["image", "video", "audio"])
txt_msg = txt.submit(add_text, [chatbot, txt], [chatbot, txt], queue=False).then(
bot, chatbot, chatbot
)
txt_msg.then(lambda: gr.update(interactive=True), None, [txt], queue=False)
file_msg = …
```

Allow updating the label of `gr.UpdateButton`

---

.changeset/wide-worlds-yawn.md
gradio/components/dataframe.py
js/dataframe/interactive/InteractiveDataframe.svelte
js/dataframe/shared/Table.svelte
js/dataframe/static/StaticDataframe.svelte
test/test_components.py

Pretty self-descriptive. Closes: #2666
Test code:
```py
df = pd.DataFrame([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]]*10)
gr.Interface(lambda x:[df, df, df], "textbox", [gr.DataFrame(), gr.DataFrame(height=100), gr.DataFrame(height=200)]).launch()
```

Add height parameter and scrolling to `gr.Dataframe`

---

.changeset/warm-nails-brush.md
js/file/static/StaticFile.svelte

Fixes the issue @freddyaboulton found. Test with:
```py
path = "cheetah.jpg"
gr.File([path]*5, interactive=False)
gr.File([path]*5, interactive=True)
demo.launch()
```

Restores missing part of bottom border on file component

---

.changeset/vast-wolves-kick.md
js/dropdown/dropdown.test.ts
js/dropdown/shared/Dropdown.svelte
js/dropdown/shared/DropdownOptions.svelte

Closes #5314.
This was happening because we pass data into component quite frequently, the issue is that Svelte has no way of knowing if the contents of an array have changed (without doing deep equality checks which are expensive).
I've added a simple check around the `filter` logic to make sure the `choices` have changed before we do anything.
There is a better solution to this which is to compile with `immutable: true`. This would require non primitive values to create new structures if the data changes. We actually do this anyway when passing data down but we don't do it inside the component, which means updating a component from outside works fine but Svelte thinks nothing has changed _inside_ of the components, so we never get fresh state.
If we tweak how we gather data to send it …

ensure dropdown stays open when identical data is passed in

---

.changeset/stale-lizards-cut.md
js/checkbox/interactive/InteractiveCheckbox.svelte
js/checkbox/static/StaticCheckbox.svelte

Closes #5327 
The event data was not being passed up.

Fix Checkbox select dispatch

---

.changeset/two-nails-march.md
gradio/utils.py

Fix typo in utils.py

---

.changeset/eighty-animals-judge.md
js/markdown/static/MarkdownCode.svelte
pnpm-lock.yaml

Fixes: #5355. Doesn't break anything as far as I could test.
Try any of the repros in the original issue
Thanks @pngwn for the suggestion

Renders LaTeX that is added to the page in `gr.Markdown`, `gr.Chatbot`, and `gr.DataFrame`

---

.changeset/clever-baboons-act.md
js/_website/src/lib/components/DemosLanding.svelte

Remove stable diffusion demo from landing page due to issues with embedding it.

Remove stable diffusion demo from landing page

---

.changeset/chatty-socks-bow.md
js/dataframe/shared/VirtualTable.svelte

There was some faulty logic when determining if a cell is on or off screen. Clicking a cell would sometimes scroll so that cell appeared at the bottom of the dataframe. This PR fixes it. …

ensure dataframe doesn't scroll unless needed

---

guides/01_getting-started/03_sharing-your-app.md

Related to OAuth PR (https://github.com/gradio-app/gradio/pull/4943) and Spaces PR (https://github.com/huggingface/spaces-app-manager/pull/1037 - private repo).
`gradio[oauth]` is now installed by default on Spaces so no need to add a `requirements.txt` manually. This PR updates the documentation about it.
For the record, here is a [demo Space](https://huggingface.co/spaces/Wauplin/gradio-oauth-demo) with OAuth enabled and no requiremens.txt.

[OAuth docs] No need to install oauth dependency in Spaces

---

.changeset/every-laws-win.md
gradio/queueing.py

Add the code same as https://github.com/tiangolo/fastapi/blob/0.87.0/fastapi/routing.py#L183-L186 

Fix queueing.call_prediction to retrieve the default response class in the same manner as FastAPI's implementation

---

.changeset/deep-socks-rule.md
gradio/queueing.py

Ref: https://github.com/gradio-app/gradio/pull/5165#discussion_r1311215406
This `except` block is no longer necessary because the following `except` block has been changed in 53d7025 so it doesn't catch `asyncio.CancelledError`.
2. You may need to run the linters: …

Remove except asyncio.CancelledError which is no longer necessary due to 53d7025

---

.changeset/chubby-hats-type.md
gradio/components/dropdown.py

The docstring of `allow_custom_value` of `gr.Dropdown` was not updated in #5384.

Fix docstring of dropdown

---

.changeset/chubby-hats-type.md
.changeset/free-terms-follow.md
gradio/components/dropdown.py
test/test_components.py

Fixes: #5519 
Test with original repro in issue:
```py
def update_dropdown():
new_choices = gr.Dropdown.update(choices = ["Hyundai","Suzuki","Mclaren"],label = "Test Dropdown")
return new_choices
def update_text(text):
return "You have chosen: " + text
with gr.Row():
with gr.Column():
test = gr.Dropdown(choices = ["Honda","BMW","Mercedes"], value = "Honda",label = "Test Dropdown")
output = gr.Textbox(lines = 5, label="Details")
with gr.Column():
test_button = gr.Button(value = "Test",variant = "primary" )
test.change(update_text,[test],output)
test_button.click(update_dropdown,[] ,[test])
demo.launch()
```

Fix `.update()` method in `gr.Dropdown()` to handle `choices`

---

gradio/cli/commands/create.py
gradio/cli/commands/files/NoTemplateComponent.py
gradio/cli/commands/files/NoTemplateComponent.svelte

- Use Fallback component when a template component is not specified. FYI @pngwn looks like jsonVIEW can't display a basic number/string. Might be good to fix in the frontend but otherwise we can just modify the NoTemplateComponent postprocess.
- Use `pnpm i --ignore-scripts` if installing in test dir as opposed to npm. Otherwise it's tedious to always type it out yourself. …

Use Fallback component for the no template case

---

gradio/cli/commands/files/NoTemplateComponent.py
gradio/component_meta.py

Language server was not picking up return type for event handler functions, e.g. click

Fix type hint for Dependency

---

.changeset/eighty-buttons-film.md
gradio/components/image.py
test/test_components.py

Quick fix for: https://github.com/gradio-app/gradio/issues/5463

allow gr.Image() examples to take urls

---

.changeset/sour-falcons-marry.md
js/dropdown/dropdown.test.ts
js/dropdown/shared/Dropdown.svelte

Fixes: #5540
Repro: 
```py
with gr.Row():
with gr.Column():
dropdown = gr.Dropdown(
choices=["abc", "def", "ghi"],
value="abc",
allow_custom_value=False,
)
button = gr.Button()
with gr.Column():
out = gr.Textbox()
button.click(fn=lambda x: x, inputs=dropdown, outputs=out)
```
Notably, the Multiselect was not experiencing this bug. 
Adds a couple of unit tests which don't actually test this exact bug (I couldn't figure out simulating the enter key -- tried keyboard("{Enter}") but it wasn't working for me), but they do test related behavior.

Fixes dropdown breaking if a user types in invalid value and presses enter

---

.changeset/fluffy-sloths-help.md
gradio/components/checkboxgroup.py
gradio/components/dropdown.py
gradio/components/radio.py
test/test_components.py

Fix preprocess for components when type='index'

---

.changeset/better-dingos-find.md
js/audio/interactive/InteractiveAudio.svelte
js/image/interactive/Image.svelte

Adds missing `dispatch("clear")`.
Closes: #5548, Closes: #5522

Fix `.clear()` events for audio and image

---

.changeset/rich-points-dance.md
gradio/routes.py
js/wasm/src/webworker/index.ts

Pyodide 0.24.0 started supporting `orjson` 🎉 : https://pyodide.org/en/stable/project/changelog.html#version-0-24-0

Upgrade Pyodide to 0.24.0 and install the native orjson package

---

.changeset/dry-points-join.md
gradio/cli/commands/create.py
package.json

FYI @pngwn 
Bugs:
* We were not updating the js dependency versions because we always thought we were in the test dir 🤦 
* We were not including the gradio-preview artifacts in the wheel …

Fix js deps in cli and add gradio-preview artifacts to build

---

.changeset/puny-papayas-bake.md
gradio/components/gallery.py

Fixing two small typos in the `columns` and `rows` parameter documentation of the Gallery component.

Fix typos in Gallery docs

---

gradio/components/checkboxgroup.py
gradio/components/dropdown.py
gradio/components/radio.py
js/dataframe/shared/VirtualTable.svelte
test/test_components.py

We allow these components to take in tuples of choices, but we when tuples are converted to javascript, they are converted to lists, so we need to handle that as well.
Test with:
```py
demo = gr.load(name="abidlabs/test-radio", src="spaces")
demo.queue(api_open=False)
demo.launch()
```
Fixes: #5632

Allow Gradio apps containing `gr.Radio()`, `gr.Checkboxgroup()`, or `gr.Dropdown()` to be loaded with `gr.load()`

---

.changeset/chatty-adults-reply.md
.changeset/neat-stars-accept.md
gradio/blocks.py
gradio/context.py
gradio/helpers.py
gradio/utils.py
test/test_helpers.py

Closes https://github.com/gradio-app/gradio/issues/5623
Also add `gr.Request` in the new `LocalContext`

Use ContextVar instead of threading.local()

---

.changeset/short-clouds-see.md
gradio/cli/commands/create.py
js/preview/src/dev_server.ts
pnpm-lock.yaml

* Don't try to import the interactive/example versions of a component if they don't exist
* Fix bug where console printed out infinitely if the backend server failed to launch
* Fix bug where the data_model was also being renamed
* Add example_inputs to the demo
cc @pngwn  …

Fix front-end imports + other misc fixes

---

.changeset/few-nights-cheer.md
gradio/themes/builder_app.py

When building a custom theme locally using `gr.themes.builder()`, I encountered an error while attempting to modify the `Secondary Hue` under the `CoreColor` tab. Subsequently, I discovered a spelling mistake in the `builder_app.py` file and made the necessary correction.

Fix secondary hue bug in gr.themes.builder()

---

.changeset/huge-steaks-juggle.md
gradio/components/chatbot.py
js/chatbot/static/ChatBot.svelte
js/chatbot/static/StaticChatbot.svelte
js/markdown/static/MarkdownCode.svelte
test/test_components.py

Allow users to `disable_markdown` for chatbot messages.
Closes: #5513

Add `render_markdown` parameter to chatbot

---

.changeset/honest-phones-divide.md
gradio/components/dataframe.py
js/dataframe/interactive/InteractiveDataframe.svelte
js/dataframe/shared/Table.svelte
js/dataframe/shared/VirtualTable.svelte
test/test_components.py

This is an attempt to fix: https://github.com/gradio-app/gradio/issues/5592. Previously, if you would run a demo like `matrix_transpose` or code like this:
```py
df = [[f"col: {i} -- row:{j}" for j in range(1, 3)] for i in range(1, 5)]
gr.DataFrame(df, headers=list(range(1, 11)))
gr.DataFrame(df, headers=list(range(1, 11)), interactive=True)
demo.launch()
```
you'd end up with a compressed dataframe whose content was cut off and scrollbars would always be present:
This made small dataframes frustrating to use. I think the issue was that the scrollbar width/height was not taken into account. Now, both are taken into account. The scrollbar holders are always present, but the scroll bars themselves only appear when …

Fix width and height issues that would cut off content in `gr.DataFrame`

---

.changeset/brave-toes-hunt.md
.github/workflows/ui.yml
client/js/src/client.ts

The culprit was my PR from last week: https://github.com/gradio-app/gradio/pull/5653
The js client needs to be able to access routes with `api_name=False` since it is used internally by Gradio, so I've reverted those changes. 
Somehow the functional tests didn't fail in the original PR, not sure why. 
cc @aliabd @hannahblair @freddyaboulton @pngwn

Fix functional tests

---

.changeset/fresh-ears-pump.md
gradio/cli/commands/components/_create_utils.py

Merged a bug yesterday cc @pngwn . I accidentally broke layout templates

Use overrides

---

.changeset/quick-streets-taste.md
js/markdown/static/MarkdownCode.svelte
pnpm-lock.yaml

We had a regression -- rendering an empty string / null value in Markdown broke the component. This fixes: #5700

Fix for regression in rendering empty Markdown

---

.changeset/bright-planes-divide.md
.config/copy_frontend.py

We weren't copying the client to the`/ _frontend_code` folder, so the CLI was erroring when trying to replace the version. Only a few components use the js client, so this hasn't come up until now.
cc @freddyaboulton  …

ensure client is copied along with components

---

pyproject.toml

fix build config

---

.changeset/sour-pillows-hug.md
gradio/helpers.py

Since https://github.com/gradio-app/gradio/pull/5625, calling `gr.Info` or `gr.Warning` on a queue-enabled Gradio app with a request originating from `/api/predict` (instead of `/queue/join`) results in an `AssertionError`
This PR fixes this by simply logging or warning, just as if those helpers were called from outside of Gradio
(before https://github.com/gradio-app/gradio/pull/5625, calling `gr.Info` or `gr.Warning` from `/api/predict` was simply a no-op)

fix: prevent internal log_message error from `/api/predict`

---

.changeset/full-hornets-obey.md
gradio/layouts.py

Closes: #5707 
Test with repro on issue or this more comprehensive one:
```py
css = """
.red{
background-color:red;
}
"""
with gr.Blocks(css=css) as demo:
button = gr.Button("Change selected tab")
button2 = gr.Button("Color tab")
def change_tab():
return gr.Tabs(selected=1)
def color_tab():
return gr.Tab(elem_classes="red")
with gr.Tabs() as tabs:
with gr.Tab("a", id=0) as tab1:
pass
with gr.Tab("b", id=1) as tab2:
pass
button.click(change_tab, None, tabs)
button2.click(color_tab, None, tab1)
demo.launch()
```

Make Tab and Tabs updatable

---

.changeset/large-banks-push.md
gradio/cli/commands/components/create.py
gradio/cli/commands/components/dev.py

Should fix the create command on windows
FYI @pngwn 

Use path to npm executable in subprocess

---

.changeset/rare-lines-show.md
client/js/src/client.ts
js/app/src/Blocks.svelte

ensure internal data has updated before dispatching `success` or `then` events

---

.changeset/old-heads-give.md
gradio/cli/commands/components/_create_utils.py
gradio/cli/commands/components/create.py
test/test_gradio_component_cli.py

Better error when the requested template doesn't exist

Add Error + test

---

.changeset/honest-phones-like.md
gradio/tunneling.py

As discussed in #3677, the current implementation for sharing gradio services does not handle [frpc](https://github.com/fatedier/frp) errors well. The error message is not displayed and the while loop to check for success runs forever.
This PR adds the ability to set a timeout (in seconds) for tunneling. This allows all the logs from frpc to be collected and printed in the error stream when an error occurs. It also fixes the possibility of an infinite loop. If possible, the error or success is handled before the timeout by parsing the current logs (as in the actual implementation).
Since creating a tunnel can take a long time (default: `30 seconds`), I would suggest showing a message that the shared link is being created. Otherwise it is not clear to the user that gradio is still doing …

Added timeout and error handling for frpc tunnel

---

.changeset/plenty-teeth-clap.md
gradio/cli/commands/components/_create_utils.py
test/test_gradio_component_cli.py

Make sure the following components can be templated
"AnnotatedImage",
"HighlightedText",
"BarPlot",
"ClearButton",
"ColorPicker",
"DuplicateButton",
"LinePlot",
"LogoutButton",
"LoginButton",
"ScatterPlot",
"UploadButton", …

Fix template remaining components

---

.changeset/heavy-animals-think.md
.github/workflows/backend.yml
js/app/package.json
pnpm-lock.yaml

Fix windows ci build

---

.changeset/yummy-mice-start.md
gradio/blocks.py
test/test_blocks.py
test/test_interfaces.py

Gradio apps running without share links in Colab are acting strange. While we investigate the issue, this is workaround that sets `share=True` for all Gradio apps in Colab. 
Closes: #5762

Set share=True for all Gradio apps in Colab by default

---

.changeset/slick-bats-study.md
client/python/gradio_client/client.py
client/python/gradio_client/utils.py
client/python/test/conftest.py
client/python/test/test_client.py
client/python/test/test_utils.py
gradio/blocks.py
gradio/components/annotated_image.py
gradio/components/audio.py
gradio/components/base.py
gradio/components/chatbot.py
gradio/components/file.py
gradio/components/gallery.py
gradio/components/image.py
gradio/components/model3d.py
gradio/components/upload_button.py
gradio/components/video.py
gradio/helpers.py
gradio/processing_utils.py
gradio/routes.py
test/test_blocks.py
test/test_components.py
test/test_interfaces.py
test/test_processing_utils.py
test/test_routes.py

- There's a lot of duplicate code in the pre/post process of components that moves a file into the "temp file set" (from henceforth called "the cache"). Moving files into the cache and adding it to `temp_files` set is now handled automatically in the Blocks parent class. This should simplify implementing pre/post process for custom components as developers don't need to know anything about how gradio serves files.
- Move all file saving utils from the Component class to processing_utils. This makes each function standalone/independent and easier to use in other components and parts of the code base. 
- Get rid of "temp_file" terminology in public facing methods and use "cache" instead. The term temp_file is misleading (these files are not temporary) and the term "cache" more accurately …

Simplify how files are handled in components in 4.0

---

.changeset/lucky-news-float.md
gradio/helpers.py

We were using `gr.update()` internally which was printing a warning. This quick fix closes: #5746

Don't raise warnings when returning an updated component in a dictionary

---

.changeset/slow-actors-tease.md
gradio/components/gallery.py
js/gallery/Gallery.stories.svelte
js/gallery/static/Gallery.svelte
js/gallery/static/StaticGallery.svelte

The big update PR broke the `columns` and `rows` params for `gr.Gallery` because the parameters in the constructor (`columns` and `rows`) were different than the name of the attributes of the object (`grid_cols` and `grid_row`).
This fixes the issue by using consistent parameter names. 
To confirm the fix, see the storybook or use this test code:
```py
import gradio as gr 
cheetahs = [
"https://upload.wikimedia.org/wikipedia/commons/0/09/TheCheethcat.jpg",
"https://nationalzoo.si.edu/sites/default/files/animals/cheetah-003.jpg",
"https://img.etimg.com/thumb/msid-50159822,width-650,imgsize-129520,,resizemode-4,quality-100/.jpg",
"https://nationalzoo.si.edu/sites/default/files/animals/cheetah-002.jpg",
"https://images.theconversation.com/files/375893/original/file-2 …
```

Fix Gallery `columns` and `rows` params

---

.github/workflows/deploy-pr-to-spaces.yml

Always deploy to spaces even if the PR has failed CI.
When testing changes, its useful just to see if the space loads up and works even if the CI is not 100% ready. 
Also CI can flake …

Always deploy PR to spaces even if CI fails

---

.changeset/forty-hornets-share.md
demo/bokeh_plot/run.py
gradio/components/gallery.py
js/gallery/Gallery.test.ts
js/gallery/package.json
js/gallery/static/Gallery.svelte
js/gallery/static/StaticGallery.svelte
pnpm-lock.yaml

The `gr.Gallery()` component had been missing a `.change()` event. This adds it and closes: #2123
Test code:
```py
with gr.Row():
t = gr.Textbox()
b = gr.Button()
g = gr.Gallery()
n = gr.Number(label="change counter")
t.submit(lambda :["cheetah.jpg", "cat.jpg"], None, g)
b.click(lambda :["cat.jpg", "cheetah.jpg"], None, g)
g.change(lambda x:x+1, n, n)
demo.launch()
```

Adds `change()` event to `gr.Gallery`

---

.changeset/tame-chairs-tan.md
gradio/events.py
gradio/interface.py
test/test_blocks.py
test/test_routes.py

As discussed, the api_name will be set to the name of the function. If the fn is None, set to "unnamed". If it is a lambda, it will be set to "lambda". Multiple lambdas will have an index appended to their name in the order that they're added (this logic already existed). …

Name Endpoints if api_name is None

---

.changeset/thin-rivers-care.md
gradio/components/gallery.py
js/gallery/static/Gallery.svelte
js/gallery/static/StaticGallery.svelte

Adds the ability to set the `selected_index` of a `gr.Gallery`, both at initialization as well as by returning an updated `gr.Gallery` component from a function.
Test code:
```py
images = [
"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
"https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80",
"https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aHVtYW4lMjBmYWNlfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
"https://images.unsplash.com/photo-1546456073-92b9f0a8d413?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fG …
```

Adds the ability to set the `selected_index` in a `gr.Gallery`

---

.changeset/eager-goats-share.md
gradio/helpers.py

Related to #5627 or #4849, but this PR is about the Python code.
For `gr.Examples()` to work, `Examples.create()` needs to be called synchronously [here](https://github.com/gradio-app/gradio/pull/5821/files#diff-2c1920edd2b0301c69c62332fd0724dba3740d966bbddf84a5d0d0462790a1fdR75), but in the Wasm/Pyodide env, `threading` is [not supported](https://pyodide.org/en/stable/usage/wasm-constraints.html#included-but-not-working-modules), so `client_utils.synchronize_async` can't be used.
So I converted the `Examples.create()` async method to a normal synchronous one since the async part is only in `self.cache()` so that `.create()` except calling `.cache()` can be called synchronously even in the Wasm mode.
Found that this change is the right solution to make `gr.Examples` to work on Wasm …

Lite: Fix Examples.create() to be a normal func so it can be called in the Wasm env

---

.changeset/evil-berries-teach.md
gradio/helpers.py
test/test_chat_interface.py
test/test_helpers.py

When working on #5821, I also found some async methods that can be written as normal ones.
This change is not mandatory, but I want to reduce asynchronous code which might potentially be incompatible with the Wasm runtime. …

Convert async methods in the Examples class into normal sync methods

---

.changeset/dry-comics-lick.md
js/dropdown/shared/Dropdown.svelte

As the target index is `undefined` in the on change event caused by dragging the scrollbar inside a dropdown, it should not be treated as something is selected.
Closes: #5759

Fix error when scrolling dropdown with scrollbar

---

.changeset/five-showers-bet.md
gradio/components/audio.py

When converting audio data from a float format to WAV (an audio file format), the audio is being normalized by its peak value (this means the volume of the audio is being adjusted). If algorithms modify the loudness of the audio, the user might not hear these changes because the normalization alters the volume. This could be problematic when the algorithm or model is specifically manipulating loudness and the user expects to hear these changes. 
Mention this in the documentation
Closes: #5484

Mention that audio is normalized when converting to wav in docs

---

.changeset/modern-forks-march.md
gradio/events.py

Cancel events are not meant to be called directly. Plus they clutter the API page.

Set api=False for cancel events

---

.changeset/vast-terms-rhyme.md
gradio/processing_utils.py
test/test_components.py

Some components tests were not setting the output directory correctly so the results were not being deleted after the tests run. Small fix.

V4: Set cache dir for some component tests

---

.changeset/two-mirrors-nail.md
gradio/processing_utils.py
gradio/routes.py

Made some changes to the upload route so that caching is respected. However, this uses possibly blocking shutil.copy code. Fixing.

V4: Use async version of shutil in upload route

---

.changeset/spicy-cycles-send.md
gradio/flagging.py
gradio/interface.py
gradio/themes/builder_app.py

We used the `.update()` logic various places inside `Interface`, which meant that a warning was raised e.g. any time you clicked on the Clear button or passed in an iterator. This replaces with modern syntax.
Test code:
```py
import time
def identity(x):
for i in range(len(x)):
time.sleep(0.5)
yield x[:i+1]
gr.Interface(identity, "textbox", "textbox").queue().launch()
```

Remove deprecated `.update()` usage from Interface internals

---

.changeset/tidy-horses-build.md
js/markdown/static/MarkdownCode.svelte
pnpm-lock.yaml

Fixes: #5802 for `<ul>` and `<ol>`:
Before:
After:
Note that chatbot markdown actually looks better without this change, so I excluded chatbot markdown from the css selector.

Keep Markdown rendered lists within dataframe cells

---

.changeset/chatty-berries-flash.md
js/wasm/src/webworker/index.ts

so it can be delegated to the main thread properly …

Lite: Convert an error object caught in the worker to be cloneable

---

.changeset/nasty-dryers-show.md
gradio/cli/commands/components/create.py
gradio/cli/commands/reload.py

Closes: #5464 
Closes: #5833 
For subprocess commands use the full path to the executable so the OS can find it without having to use `shell=True`

Use full path to executables in CLI

---

.changeset/eager-snakes-look.md
js/app/src/lite/url.ts

For local development convenience.
We sometimes can open the local dev server page via `127.0.0.1` instead of `localhost`.

Lite: Fix is_self_host() to detect `127.0.0.1` as localhost as well

---

gradio/cli/commands/components/create.py
gradio/cli/commands/components/files/pyproject_.toml
pyproject.toml

Introduces a set of development dependencies for custom component packages (`build` and `twine`) that are installed when `--install` is used in create. That way cc authors can run `gradio_component build` without errors. …

Install build and twine with --install

---

.changeset/green-forks-float.md
gradio/themes/utils/fonts.py

To fix the format printed in the doc:
Current (https://www.gradio.app/docs/themes):
Fixed:
Closes: #5902

Define Font.__repr__() to be printed in the doc in a readable format

---

.changeset/tricky-spoons-slide.md
gradio/components/code.py

The rendered document would be:

Fix type the docstring of the Code component

---

.changeset/new-ideas-sniff.md
gradio/components/file.py
gradio/components/file_explorer.py
gradio/components/upload_button.py

For example, in the [`UploadButton` doc](https://www.gradio.app/docs/uploadbutton),
Current:
Fixed:

Fix curly brackets in docstrings

---

.changeset/thirty-planets-smash.md
js/markdown/static/MarkdownCode.svelte

`line_breaks` param actually _was_ being passed down properly. But when adding two line breaks, markdown actually creates a new `<p>` tag for the following text. In the chatbot we added padding between `<p>` tags. I added the same here for dataframe to be consistent. …

Fix Dataframe `line_breaks`

---

.changeset/flat-experts-wink.md
.config/copy_frontend.py
gradio/cli/commands/components/_create_utils.py
gradio/cli/commands/components/dev.py
gradio/components/file_explorer.py
test/test_gradio_component_cli.py

Make FileExplorer templateable

BugFix: Make FileExplorer Component Templateable

---

.changeset/green-tips-read.md
js/app/src/lite/css.ts
js/app/src/lite/url.ts
js/wasm/src/webworker/index.ts
js/wasm/svelte/file-url.ts

Just caught up with the `format_frontend.sh` behavior.

Apply formatter (and small refactoring) to the Lite-related frontend code

---

.changeset/crazy-dancers-allow.md
js/wasm/src/promise-delegate.ts
js/wasm/src/webworker/index.ts
js/wasm/src/webworker/py/script_runner.py
js/wasm/src/worker-proxy.ts

Closes:  #5957 
This PR includes 2 major changes.
1. Make processing HTTP requests wait for the first `run_file()` or `run_code()` promise execution to finish. 1c99d20
2. Top-level `await` will be supported with `run_code()`. 4a95c94
These 2 commits are related but independent, so I recommend to review them one by one.
The first one is the direct solution for the problem of #5957 .
The second one is to support top-level `await` syntax with `run_file()` or the `files` option. The sample code of #5957 uses `run_code()` or the `code` option so it could include the top-level `await` in the code. However, it has not worked with with `run_file()` or the `files` option, so this PR fixes it.

Make the HTTP requests for the Wasm worker wait for the initial `run_code()` or `run_file()` to finish

---

.changeset/brave-cats-show.md
js/app/src/lite/custom-element/index.ts
js/app/src/lite/index.ts
js/app/vite.config.ts
js/theme/src/global.css

A custom element `<gradio-app>` will be registered by importing the `@gradio/lite` script, and users can use it to mount a Gradio app with various configs.
When `<gradio-app>` doesn't have any child elements, its text content is directly interpreted as a script to execute.
```html
<gradio-app>
def greet(name):
return "Hello " + name + "!"
demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch()
</gradio-app>
```
Setting attributes on the `<gradio-app>` tag affects the component configs listed as https://github.com/gradio-app/gradio/blob/fee3d527e83a615109cf937f6ca0a37662af2bb6/js/app/src/lite/index.ts#L52-L60
```html
<gradio-app theme="dark">
...
</gradio-app>
```
This API style is used to
* mount multiple files to the virtual file system
* download …

Lite: Support the custom HTML element syntax `<gradio-lite>`

---

.changeset/red-terms-rest.md
js/wasm/src/webworker/index.ts

Specify FastAPI version for the Wasm runtime as a workaround

---

.changeset/eight-hoops-juggle.md
js/app/src/Index.svelte
js/wasm/src/message-types.ts
js/wasm/src/webworker/index.ts
js/wasm/src/worker-proxy.ts

f36e88b
For the better UX, print and update the progress messages during the initial loading.
https://github.com/gradio-app/gradio/assets/3135397/e8cac8cf-7768-4e4e-8eea-bf559aa1ded5
150bfaa
Fix the error handling so an error thrown during the initialization is caught and the frontend status is set as `error`.
For example, when a user passes a not installable package such as `torch` to the `requirements` option to load it during the initialization, the error is caught and the screen would be as below.

Lite: Show initialization progress messages

---

.changeset/warm-chefs-trade.md
js/wasm/src/webworker/http.ts

For example, when the user runs a script that doesn't call `Blocks.launch()`, the HTTP request would fail because no HTTP server has started.
Such errors thrown from the ASGI app (=HTTP handler) has not been handled properly so in the example case above, the app silently dies with ever-running "loading..." message.
With this PR, such error will be properly propagated to the main thread.

Lite: Fix error handling on the ASGI app

---

test/requirements.txt

CI was breaking because new FastAPI release needs typing_extensions>4.8.0 but we had version 4.7.1. We should not be pinning in this case since we deliberately have a relaxed pin for typing_extensions in our requirements.txt to avoid this kind of situation.
2. You …

Relax pin on typing_extensions

---

.changeset/chatty-laws-drop.md
js/app/src/Index.svelte
js/wasm/src/worker-proxy.ts

#5983 was only about the errors emitted at the initialization.
This PR will add event emitters covering `run_file()`, `run_code()`, `write()`, `rename()`, `unlink()`, and `install()`, and add event handlers in `Index.svelte` to handle these errors to print on the app screen.
Closes: #6003
Invalid syntax when `run_file()` is called.
This is the case of https://huggingface.co/spaces/abidlabs/gradio-lite-classify-error
Installing packages that are not available on Pyodide/Wasm.
For example, when `controller.install(["torch"])` is called:

Lite: Error handling after initialization

---

.changeset/wise-hands-dress.md
js/audio/shared/Audio.svelte
js/audio/static/AudioPlayer.svelte

I missed `js/audio/static/AudioPlayer.svelte` in #5627 which also should be converted to be Wasm-compatible.
Closes: #5999

Update static/AudioPlayerto use ../shared/Audio instead of the native `<audio>` for Wasm support

---

.changeset/big-dogs-chew.md
js/wasm/src/webworker/index.ts

Related to #5983 .
Showing the progress and error handling during the initialization should be covered by #5983 , so this PR shouldn't be mandatory but is intended to be a defensive improvement.
With this PR, even when some error occurs after the initialization and the app screen unexpectedly gets frozen, users can know at least the initialization has finished. It would be helpful for bug reports as well.

Add a message at the end of the Wasm worker initialization

---

gradio/interface.py

Solves the issue of a bug impeding linking different flagging directories to different interfaces in the case of multiple interfaces like gr.TabbedInterface, as discussed with @abidlabs and @harry-urek in pull request [5928](https://github.com/gradio-app/gradio/pull/5928), and in issue #5692.
The cause of the bug was residing in the fact that even if each interface, in theory, should have its proper FlaggingCallback, which in theory should have its own `self.flagging_dir`, both FlaggingCallaback pointed to the same `CSVLogger()` because the argument flagging_callback of `Interface` class in `interface.py` created a FlaggingCallback that pointed to the `CSVLogger()` class and not, as it should, provide to create instance of this class.
I fixed the problem by changing the default value of …

fix: allow multiple flagging directories

---

.changeset/bitter-mirrors-dance.md
js/wasm/src/webworker/index.ts

Closes: #6010
See https://github.com/pyodide/pyodide/issues/4234#issuecomment-1772115575

lite: install typing-extensions to avoid capping fastapi versions

---

.changeset/puny-teeth-notice.md
gradio/routes.py

Sorry for targeting `main` but this is a pretty bad bug -- the login page css is [broken on Spaces](https://huggingface.co/spaces/abidlabs/test-auth):
This PR fixes it. Verified by installing this PR on a different Space: https://huggingface.co/spaces/abidlabs/test-auth2
Fixes: #5932

Fix `root` when user is unauthenticated so that login page appears correctly

---

gradio/components/dropdown.py
gradio/helpers.py

Fixes: #6043 
Check by running `demo/kitchen_sink/run.py` or
```py
example_1 = [["a", "b"]]
example_2 = [["a"]]
io = gr.Interface(lambda x:x, 
gr.Dropdown(["a", "b"], 
multiselect=True), "dropdown", examples=[example_1, example_2])
io.launch()
```

Fix Dropdown Example component and example processing logic

---

.changeset/quick-bottles-find.md
js/app/src/Index.svelte
js/app/src/lite/ErrorDisplay.svelte
js/app/src/lite/index.ts
js/wasm/src/worker-proxy.ts

Closes: #6022
The error handler introduced in #6005 was not good because the frontend app for Gradio-lite is designed to be refreshed on every run as
https://github.com/gradio-app/gradio/blob/8241f9a7bd034256aabb9efa9acb9e36216557ac/js/app/src/lite/index.ts#L148-L149
but that error handling reuses the already mounted component without refreshing.
In this PR, I moved the error handler to `lite/index.ts` so the mounted component will be refreshed with a new one even when an error is caught from the Wasm `worker_proxy`.
As a result of this change, #6022 is fixed since the entire app is replaced with the error display component when an error is caught.
Along with it, I created a new component `lite/ErrorDisplay` to show the error details to help users.
`torch` is included in the initial …

Lite error handler

---

.changeset/rare-hornets-take.md
client/python/gradio_client/client.py
client/python/gradio_client/serializing.py
client/python/gradio_client/utils.py
client/python/test/test_client.py
client/python/test/test_utils.py
gradio/blocks.py
gradio/component_meta.py
gradio/components/audio.py
gradio/components/dataset.py
gradio/components/image.py
gradio/exceptions.py
gradio/external.py
gradio/package.json
gradio/utils.py
test/test_blocks.py
test/test_external.py
test/test_mix.py

* Make `gradio_client` backwards compatible with v3 spaces
* Raise an error if someone tries to load a v3 space with gradio v4 via `gr.load`
* Fix the remaining tests that are failing in the backend. All of them related to `external.py` or `gr.load` 😓 . This uncovered some gaps/bugs in v4.
~There's still an outstanding issue - since we removed **kwargs from component init, we can't call `gr.load` on a space that has examples because the dataset component has `component_props` saved in the config but `component_props` is not a parameter of init. @abidlabs let's synch tomorrow on the best pattern to deal with this.~
Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before …

Fix remaining xfail tests in backend

---

.changeset/mighty-coats-do.md
gradio/cli/cli.py
gradio/cli/commands/components/app.py
gradio/cli/commands/components/create.py
gradio/cli/commands/components/install_component.py
js/fallback/Index.svelte
test/test_gradio_component_cli.py

Add a stand-alone install command. This will be useful when cloning a custom component hosted on any git repo. Just clone as you normally would and then run `gradio cc install`. Should make it easier to "remix" custom components.
2. You may need to run the linters: …

Add a stand-alone install command and tidy-up the fallback template

---

.changeset/pretty-apples-juggle.md
gradio/blocks.py
gradio/blocks_events.py
gradio/events.py
js/app/src/Blocks.svelte
test/test_blocks.py
test/test_events.py

Decorator-based events was actually broken on `v4`.
This fixes that and fixes: #5401, which means `demo.load` works with decorator-based syntax:
Test with:
```py
name = gr.Textbox(label="Name")
output = gr.Textbox(label="Output Box")
@demo.load(outputs=name)
def test():
return "Abubakar"
demo.launch()
```
It also works with `gr.on`:
```py
name = gr.Textbox(value="Abubakar")
output = gr.Textbox(label="Output Box")
gr.on([demo.load, name.submit], lambda x:x, name, output)
demo.launch()
```

Refactor `Blocks.load()` so that it is in the same style as the other listeners

---

.changeset/deep-spies-rhyme.md
gradio/blocks.py
gradio/routes.py
test/test_routes.py

Closes: #3947
Test with (new default):
```py
import requests
_, url, _ = gr.Interface(lambda x:x, "textbox", "textbox").queue().launch(inline=False)
r = requests.post(url + "run/predict", json={ "data": [ "abc" ], "event_data":  None, "fn_index": 0, "session_hash": "nxml3nqiic9" })
r.json()
```
vs.
```py
import requests
_, url, _ = gr.Interface(lambda x:x, "textbox", "textbox").queue(api_open=True).launch(inline=False)
r = requests.post(url + "run/predict", json={ "data": [ "abc" ], "event_data":  None, "fn_index": 0, "session_hash": "nxml3nqiic9" })
r.json()
```

Small change to make `api_open=False` by default

---

.changeset/hungry-spiders-cross.md
gradio/blocks.py
gradio/components/annotated_image.py
gradio/components/base.py
gradio/components/chatbot.py
gradio/components/checkbox.py
gradio/components/checkboxgroup.py
gradio/components/dataframe.py
gradio/components/dataset.py
gradio/components/dropdown.py
gradio/components/file.py
gradio/components/gallery.py
gradio/components/highlighted_text.py
gradio/components/image.py
gradio/components/label.py
gradio/components/radio.py
gradio/components/textbox.py
gradio/events.py
js/chatbot/Index.svelte
js/file/Index.svelte
js/highlightedtext/Index.svelte
js/image/Index.svelte
js/label/Index.svelte
test/test_components.py

The selectable prop was not properly being set in the config in the backend.
This fixes that. We need to add `selectable` to the init for `gr.load` to work. This is a bug on main actually. If you `gr.load("spaces/gradio/tictactoe")`, the dataframe's selectable prop will be `False` …

Fix selectable prop in the backend

---

client/python/gradio_client/client.py
gradio/helpers.py
gradio/routes.py
guides/01_getting-started/03_sharing-your-app.md

This should fix the issue where the cached example files were not showing up, and also doesn't pollute the user's working directory with cached examples, which are really an internal gradio resource. 
cc @hannahblair @freddyaboulton 
Will test in @hannahblair's PR to confirm

Moves `gradio_cached_folder` inside the gradio temp direcotry

---

.changeset/shy-bugs-sneeze.md
js/app/src/Blocks.svelte

Make output components not editable if they are being updated
Closes: #4733

Make output components not editable if they are being updated

---

.changeset/clever-brooms-lay.md
gradio/blocks.py
gradio/component_meta.py
gradio/components/clear_button.py
gradio/helpers.py
gradio/processing_utils.py
test/test_blocks.py
test/test_components.py

Part I: Remove serializes

---

.changeset/eighty-sides-visit.md
gradio/queueing.py
gradio/routes.py

So now you can curl directly, e.g.
```
curl "http://localhost:7860/queue/join?fn_index=0&session_hash=1&data=%5B%22hello%22%5D"
data: {"msg": "estimation", "rank": 0, "queue_size": 1, "avg_event_process_time": 0.0, "avg_event_concurrent_process_time": null, "rank_eta": null, "queue_eta": 1.0}
data: {"msg": "process_starts"}
data: {"msg": "process_completed", "output": {"data": ["Hello hello!"], "is_generating": false, "duration": 0.0006520748138427734, "average_duration": 0.0006520748138427734}, "success": true}
```

Allow data at queue join

---

.changeset/thirty-beans-type.md
gradio/themes/base.py
js/markdown/shared/prism.css

Wasn't much to cleanup, just chatbot_code_background_color was too component specific, and  not accurate either because all markdown used this variable. Renamed to code_background_fill, (change color -> fill for background, because we always use fill for background variable names, not color, because these can also be images/gradients/etc)

Cleanup theme vars

---

.changeset/tame-singers-join.md
gradio/components/file_explorer.py

The datamodel for FileExplorer changed with a recent pr (i think #6181) but the preprocess was not modified to reflect this. The Signature for preprocess also wasn't updated which is probably what allowed this to creep in.
run `demo/file_explorer` to test. …

fix`FileExplorer` preprocess

---

.changeset/major-bushes-ring.md
gradio/components/chatbot.py
test/test_components.py

Repro in issue.
We added some under-the-hood logic to Blocks to set `_selectable` in the config without it being present in the init signature. I don't like treating some props as privileged though. Doesn't scale for custom component authors who want to set event-based props in their custom component. So I'm adding likeable to the config.
Closes: #6230  …

Add likeable to config for Chatbot

---

.changeset/fruity-peaches-appear.md
gradio/components/model3d.py
js/model3D/shared/Model3D.svelte
js/model3D/shared/Model3DUpload.svelte
js/model3D/shared/utils.ts
test/test_components.py

Improvements to the Model3D component
- Enabled panning
- Adapt pan and zoom speed to scene radius, creating a consistent experience across various model sizes
- Set lower radius limit to prevent zoom inversion (zooming in below 0)
Closes: #6119

Model3D panning, improved UX

---

.changeset/cute-poems-cover.md
gradio/routes.py
js/app/src/Blocks.svelte

Fixes: #6239 
Previously if a user closed the browser, their session was not removed from queue. This is now handled.
Test this via:
```python
def greet(name):
import time
time.sleep(20)
return "Hello " + name + "!"
demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch()   
```
Launch a couple sessions across a few tabs and then close some tabs. The positions in the other tabs should update.

Remove session if browser closed on mobile

---

gradio/components/base.py
gradio/flagging.py
test/test_flagging.py

As discussed with @abidlabs in #6196, fixes the issue by moving the creation of a folder for flagged components inside the `.flag()` method in `components/base.py`, making it run only when data_model is not `none` before the payload is copied inside of it.
Closes: #6196
1. I followed the guidelines to contribute (https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and ran the tests: `bash scripts/run_all_tests.sh`. All tests passed.
2. I ran `bash scripts/format_backend.sh` to lint my code.

fix: avoid unnecessary folders creation when flagging

---

.changeset/public-banks-film.md
gradio/chat_interface.py

Include initial value in chat history for chat interface.
Closes: #6194

Fixes: Initial message is overwrtitten in chat interface 

---

.changeset/pretty-doodles-work.md
demo/hello_blocks/run.py
js/radio/Index.svelte
js/radio/Radio.test.ts
js/radio/shared/Radio.svelte
js/tootils/src/render.ts

Closes #6198 
Funny issue. The `name` attribute on a Radio button has to be unique across the page or there will be conflicts. We were using the internal value (in the PR example 'Yes' and 'No'). SO when we had duplicates with the same value only one 'Yes' or one 'No' could be 'checked' at the same time (because radio inputs are xor).
Added a few defaults again to make testing easier and added a unit test for this case.
1. PRs will only be merged if tests pass on CI. To run the tests locally, …

ensure radios have different names

---

.changeset/neat-cups-jump.md
gradio/themes/utils/semver_match.py
js/app/test/gallery_component_events.spec.ts
test/test_theme_sharing.py

Commented out a check to make sure that the loaded theme has the correct tags, as it seems that the `huggingface_hub` library is not parsing tags from Spaces
Closes: #6298

Temporary fix to be able to load themes from Hub

---

.changeset/all-cougars-matter.md
gradio/components/dataframe.py
js/app/test/gallery_component_events.spec.ts
test/test_components.py

Closes: #6297
Test with:
```py
def fn(df: pd.DataFrame) -> str:
return df
df_orig = pd.DataFrame(data={"a": [1, 2, 3]})
df = gr.Dataframe(value=df_orig, type="pandas")
df2 = gr.Dataframe(value=df_orig, type="pandas")
btn = gr.Button()
btn.click(fn=fn, inputs=df, outputs=df2)
demo.launch()
```
or repro in original issue

Fix data model for `gr.DataFrame`

---

.changeset/floppy-crews-do.md
js/app/test/dataframe_colorful.spec.ts
js/dataframe/Index.svelte

Fixes a regression: https://github.com/gradio-app/gradio/issues/6315
Sample code:
```py
import pandas as pd 
df = pd.DataFrame({
"A" : [14, 4, 5, 4, 1], 
"B" : [5, 2, 54, 3, 2], 
"C" : [20, 20, 7, 3, 8], 
"D" : [14, 3, 6, 2, 6], 
"E" : [23, 45, 64, 32, 23]
}) 
styler = df.style.highlight_max(color = 'lightgreen', axis = 0)
gr.DataFrame(styler)
demo.launch()
```
Explanation: the introduction of
```js
on:change={(e) => (value = e.detail)}
```
was causing an infinite loop when working with metadata. This fixes it, but as I'm not sure if this is the best fix, feel free to suggest an alternative. But basically here, we check to see if a Dataframe is interactive before updating the value. I've tested with `matrix_transpose`, which continues to work. …

Fix for stylized DataFrame

---

.changeset/bitter-knives-yawn.md
client/js/src/client.ts
demo/hello_world/run.py

We lost query parameters in the request in upgrading to 4.0, because we were sending the queue information (session_hash, fn_index) via query params - now we send both URL params and queue information via request.url_params. 
This does mean that when a user searches the request for url_params, there will be additional url_parameters they will find now in 4.0. I wanted to strip these but the fastapi.Request object is immutable and would be very messy / hacky to create a new object without these URL parameters. I think this is okay because users are usually looking for a specific key when searching url parameters.
Fixes: #6283 
Try with
```python
def echo(params):
print(params)
return params
def get_params(request: gr.Request):
params = request.query_params
ip = …
```

Restore query parameters in request

---

.changeset/tired-berries-tease.md
client/js/src/client.ts
client/js/src/upload.ts
gradio/route_utils.py
gradio/routes.py
gradio/utils.py
js/app/test/audio_component_events.spec.ts
js/app/test/video_component_events.spec.ts
js/upload/src/Upload.svelte
js/upload/src/UploadProgress.svelte

Closes #6218
* Adds an optional upload_id query parameter to the `/upload` route. When specified, you can listen to progress updates on the `upload_progress` route. I originally wanted the `/upload` route to return the `upload_id` you can use to listen to updates but we can't send intermediate information from the `/upload` route without closing the request and the `/upload` route needs the request to stay open to stream the files.
* Adds a `UploadProgress.svelte` class in `@gradio/upload` that streams and displays progress updates from the server.
* The `upload_id` parameter is added to the `@gradio/client` but not the python client.
Try it here: https://huggingface.co/spaces/freddyaboulton/file_component
Questions:
* There's a bit of flicker if the uploaded file is really small. Should …

Provide status updates on file uploads

---

.changeset/cute-ghosts-grab.md
gradio/blocks.py

This is kind of a question, rather than a change request/proposal.
I wonder `inspect.isasyncgenfunction()` should be added here because it is usually used along with `inspect.isgeneratorfunction` in other places to check the function is generator-like,
such as:
https://github.com/gradio-app/gradio/blob/f1409f95ed39c5565bed6a601e41f94e30196a57/gradio/interface.py#L457-L459
https://github.com/gradio-app/gradio/blob/f1409f95ed39c5565bed6a601e41f94e30196a57/gradio/interface.py#L464-L466
If not, plz close the PR.
Not adhering to this guideline will result in the PR …

Add AsyncGenerator to the check-list of `dependencies.types.generator`

---

.changeset/late-donuts-warn.md
gradio/themes/utils/readme_content.py

As pointed out by @coyotte508, we use an invalid  `colorFrom` in the theme space readmes, which is preventing theme spaces from returning the tags correctly. 
This changes `orange` to `red`
cc @freddyaboulton @Wauplin

Fix `colorFrom` in theme space readmes

---

.changeset/red-ties-turn.md
gradio/processing_utils.py
js/audio/player/AudioPlayer.svelte

Streaming audio out broke in 4.0, as can be seen in the `stream_audio_out` demo. The waveform generator does not support a streaming audio source, so did a fallback onto a regular audio component. Test this via `stream_audio_out` demo.
There was another issue that whenever the DOM re-rendered for any reason, the waveform would have to regenerate, causing it to fetch the audio source on every DOM re-render. This is because normalize_files caused a new JSON to be passed to the AudioPlayer, so any DOM change caused a re-render. Now only re-renders if the URL changes. Test this via demo below while watching the Network Chrome inspector:
```python
def greet(audio):
for i in range(10):
import time
time.sleep(1)
yield i
name = gr.Audio(label="Name") …
```

Fix audio streaming output issues in 4.0

---

.changeset/olive-baboons-divide.md
js/image/Index.svelte

Fix image upload

---

.changeset/early-geese-relate.md
gradio/component_meta.py
test/test_blocks.py

Fixes: #6342
The problem was that if the component was initialized for the first time in an event listener, __init__ was not being called. This was a bug that was in version 3 too. 
The reason the bug doesn't "surface" for a normal generator is that "in_event_listener" returns false - probably because it's running in a separate thread (to avoid blocking the event loop) - so the __init__ is always called.
The fix is to call init if it hasn't been called before in an event listener
1. PRs will only …

Fix component update bug
