- .changeset/eleven-windows-relate.md
- gradio/components/audio.py
- gradio/components/image.py
- gradio/components/video.py
- test/test_components.py
A typo was causing the frontend to crash if `sources` was specified as a string
Closes: #6371 
Closes: #6337
> Allows `sources` to be a string for `gr.Image`

- .changeset/deep-cycles-switch.md
- requirements.txt
> Remove  websockets dependency

- .changeset/cold-gifts-tickle.md
- gradio/utils.py
- test/test_utils.py
Currently looks like the [`every`](https://www.gradio.app/guides/blocks-and-event-listeners#running-events-continuously) option expects `fn` to be only a normal function or a generator function.
However, `fn` can be an async function (coroutine function) or an async generator function in normal use, so such types should also be able to be passed as `fn` with the `every` option.
The following code should work.
```python
async def get_data():
res = await async_data_fetcher()
return res
textbox = gr.Textbox()
demo.load(get_data, None, textbox, every=1)
```
However, currently the returned coroutine is not awaited and the result would be like this:
This PR modifies `utils.get_continuous_fn()` to deal …
> Async functions and async generator functions with the `every` option to work

- .changeset/twelve-monkeys-move.md
- gradio/blocks.py
In Gradio 4.0, all API endpoints are named by default, which means that warnings about duplicated api names pop up too easily and pollute the stdout. This PR removes those warnings, which are not too necessary.
> Do not show warnings when renaming api_names

- .changeset/whole-eels-poke.md
- js/dropdown/dropdown.test.ts
- js/dropdown/shared/Dropdown.svelte
- pnpm-lock.yaml
Due to a regression, we weren't updating the "selected indices" (which dropdown options had a tick next to them) when the value was programmatically changed. 
This PR fixes that and adds a unit test.
Closes: #6408
> Update the selected indices in `Dropdown` when value changes programmatically

- .changeset/slimy-oranges-dress.md
- js/_website/src/routes/+layout.svelte
- js/app/src/Blocks.svelte
- pnpm-lock.yaml
Following https://stackoverflow.com/questions/74494818/google-analytics-not-working-for-web-site-embeded-in-iframe (thanks for sharing @aliabd), modified our google analytics tag to work on Spaces. 
Not sure if there's an easy way to test that this is working, but will take a look at our GA to see if anything shows up due to the deployed Space PR.
> Allow google analytics to work on Spaces (and other iframe situations)

- .changeset/rotten-results-judge.md
- gradio/components/image.py
- gradio/image_utils.py
- gradio/processing_utils.py
- js/app/test/image_component_events.spec.ts
Jpegs were being converted to png always.
e2e test reflects this change.
> Preserve original image extension in backend processing

- .changeset/nice-dolls-rescue.md
- gradio/image_utils.py
Was breaking the image_mod_default_image demo
> Catch ValueError, KeyError when saving PIL Image

- gradio/__init__.py
- gradio/components/image_editor.py
- gradio/templates.py
Adds back template classes:
* ImageMask
* Sketchpad
* Paint
Deletes:
* Pil (kinda pointless)
* ImagePaint (the default ImageEditor)
> Add back templates based on `gr.ImageEditor`

- .changeset/whole-buckets-add.md
- gradio/components/image_editor.py
- js/imageeditor/shared/ImageEditor.svelte
_I am not here. I did not make this PR_
There was a bug (pretty bad one imo), where the crop and draw/erase cursor would get funky if the user scrolled the page after uploading an image. This is because they rely on DOM measurements but those measurements are not updated on scroll.  This PR fixes that.
Also corrected the typos in the docstrings. …
> Ensure image editor crop and draw cursor works as expected when the scroll position changes

- .changeset/bumpy-rockets-rush.md
- gradio/cli/commands/reload.py
- gradio/networking.py
- gradio/utils.py
- test/test_reload.py
Current reloader manages the target module only with a name e.g. `"app"` even when its source file is located in a nested path like "./sub/path/app.py". So it wrongly imports a module with the same name from a different path which is registered in `sys.path` with a higher priority like ".".
This PR fixes it by modifying the reloader to manage the target module with a qualified name like `"sub.path.app"` to avoid such unexpected imports.
Closes:  #6488
> Fix SourceFileReloader to watch the module with a qualified name to avoid importing a module with the same name from a different path

- .changeset/stupid-knives-fold.md
- js/file/shared/FilePreview.svelte
- js/file/shared/utils.ts
From the a11y perspective, file names shouldn't be truncated at HTML/JS level. Instead, such text truncation only for visual appearance should be controlled by CSS.
Full width:
Narrow screen:
ARIA properties:
For a11y purpose, setting `aria-label` might be enough though, the overridden "Contents" still keeps original file name readable.
> File table style with accessible file name texts

- client/python/gradio_client/client.py
[internal convo](https://huggingface.slack.com/archives/C02QZLG8GMN/p1700475888741849). When passing the token explicitly, e.g.
```python
from gradio_client import Client
client = Client.duplicate("abidlabs/whisper", hf_token="token")
```
the repo is duplicated with a CPU but then the client fails with a 
```
Repository Not Found for url: https://huggingface.co/api/spaces/osanseviero/whisper/hardware.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
``` 
error. This is due to the token not being passed when requesting a hardware.
> Fix gradio_client duplicating upgraded Spaces

- .changeset/nine-bats-sin.md
- js/dropdown/dropdown.test.ts
- js/dropdown/shared/Dropdown.svelte
Fixes the issue identified by [sbarman-mi9](https://github.com/sbarman-mi9) in https://github.com/gradio-app/gradio/pull/6425#issuecomment-1817426966
Test with:
```py
def do_something():
return gr.update(value=None)
drop_dwn = gr.Dropdown(["a", "b", "c", "d", "e"], 
value='b', 
label="Select", 
elem_id="drp_dwn",
interactive=True
)
reset_btn = gr.Button("Reset")
reset_btn.click(do_something, None, [drop_dwn])
demo.queue(default_concurrency_limit=13).launch()
```
> Allow reselecting the original option in `gr.Dropdown` after value has changed programmatically

- .changeset/warm-otters-rest.md
- gradio/chat_interface.py
- test/test_chat_interface.py
Deprecates the overly restrictive `additional_inputs_accordion_name` argument and instead replaces it with a `additional_inputs_accordion` argument which can take either a string or a whole `gr.Accordion` object. 
This is more inline with the other arguments in `gr.ChatInterface`, such as `submit_btn`
Test with:
```py
def echo_system_prompt_plus_message(message, history, system_prompt, tokens):
response = f"{system_prompt} {message}"
for i in range(min(len(response), int(tokens))):
yield response[: i + 1]
chatbot = gr.ChatInterface(
echo_system_prompt_plus_message,
additional_inputs=["textbox", "slider"],
additional_inputs_accordion=gr.Accordion(open=True, label="MOAR"),
)
```
Closes: https://github.com/gradio-app/gradio/issues/6493
> Allows setting parameters of `gr.ChatInterface`'s `Accordion`

- .changeset/easy-turtles-tie.md
- gradio/themes/app.py
- gradio/themes/utils/theme_dropdown.py
Closes: #6527
https://huggingface.co/spaces/freddyaboulton/testSoft
You need to install the package from this PR for the deployed space to work though.
> Fix Theme Dropdown in deployed theme space

- .changeset/tangy-pots-speak.md
- gradio/components/upload_button.py
- js/uploadbutton/Index.svelte
- js/uploadbutton/UploadButton.stories.svelte
- js/uploadbutton/shared/UploadButton.svelte
Make UploadButton accept icon parameter
Closes: #6422
> Feat: make UploadButton accept icon

- .changeset/heavy-planes-dig.md
- gradio/cli/commands/reload.py
- guides/09_other-tutorials/developing-faster-with-reload-mode.md
- guides/cn/07_other-tutorials/developing-faster-with-reload-mode.md
This fix is target on Windows platform.
In reload mode, the dev-created Python script shall be crunched via cmd, however the script's encoding format is not informed for it. This PR fix the problem.
Meanwhile, if I'd like to use GBK encoding (or anything but UTF-8) for my script, such error occurs:
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 2517: illegal mutibyte sequence
```
Therefore I added a `encoding` parameter into cli, allowing devs free to specify any encoding format they want.
Doc changes are included in the PR.
Closes: [#6364]
> Fix encoding issue #6364 of reload mode

- js/dropdown/Multiselect.stories.svelte
- js/highlightedtext/HighlightedText.stories.svelte
- js/row/Row.stories.svelte
- js/video/Video.stories.svelte
- pnpm-lock.yaml
Some quick fixes to get the storybook CI to work.
> Hotfix related to stories

- .changeset/eager-snakes-boil.md
- gradio/components/audio.py
Quick fix, closes: https://github.com/gradio-app/gradio/issues/6335
> use gr.Error for audio length errors

- .changeset/dark-wolves-sit.md
- js/_website/src/lib/components/Header.svelte
Removes link to forum from the website header, since we're [shutting it down](https://discuss.huggingface.co/t/announcement-we-will-be-closing-this-gradio-section-of-the-forums/64720).
> Remove Discourse Forum Link from Website

- .changeset/tall-regions-wash.md
- .github/ISSUE_TEMPLATE/bug_report_template.yml
- gradio/networking.py
- gradio/tunneling.py
Small tweak to our bug issue template which adds the code syntax to the "Reproduction" section. I've noticed a lot of people dump code without the formatting, which makes it hard to parse. Hopefully, this will help!
Here's how it looks: https://github.com/abidlabs/gradio/issues/new?assignees=&labels=bug&projects=&template=bug_report_template.yml
> Tweak to our bug issue template

- .changeset/odd-garlics-teach.md
- gradio/networking.py
Set share link server from env `GRADIO_API_SERVER` so that I can make the gradio automatically use another gradio share server without changing the source code.
This fix is very small, so I do not create an issue for it. …
> Set gradio api server from env

- .changeset/small-crabs-take.md
- js/dropdown/dropdown.test.ts
- js/dropdown/shared/Dropdown.svelte
- pnpm-lock.yaml
Fixes: #6596 and adds a test
Test with:
```py
with gr.Blocks(
title="dropdown tuples bug reproducer",
) as demo:
gr.Dropdown(
label="Dropdown with tuples",
choices=[("Model 1", "model1"), ("Model 2", "model2")],
value="model1",
interactive=True,
)
gr.Dropdown(
label="Dropdown with values",
choices=["model1", "model2"],
value="model1",
interactive=True,
)
demo.launch()
```
> Fix dropdown blur bug when values are provided as tuples

- .changeset/evil-readers-reply.md
- gradio/components/image.py
- gradio/processing_utils.py
- test/test_components.py
- test/test_processing_utils.py
Closes: #6617
Added a unit test. Test visually by running `image_mod_default_image` with the `rotated_image.jpeg` saved in `test/test_files`.
The correct output is a 45 degree rotation from the upright position. …
> Rotate Images to Upright Position in preprocess

- .changeset/tough-beers-unite.md
- client/python/requirements.txt
- requirements.txt
- test/test_theme_sharing.py
As part of #6616, some of the backend tests now need a valid hf token to run. These can be specified via the HF_TOKEN environment variable, or by logging in via the hf-cli. In the GitHub CI runners, we use the HF_TOKEN variable, so we use the former approach. However, this requires `huggingface_hub>=0.19.3` since in previous versions, the `huggingface_hub` library looked for a different environment variable called `HUGGING_FACE_HUB_TOKEN`
> Hotfix: update `huggingface_hub` dependency version

- .changeset/legal-geese-agree.md
- js/image/Example.svelte
- js/image/shared/Image.svelte
- js/video/Example.svelte
- js/video/shared/Player.svelte
- js/video/shared/Video.svelte
This PR contains these:
* Remove the styles from `js/image/shared/Image.svelte` and `js/video/shared/Video.svelte`, which are reusable components and shouldn't have their own styles.
* Instead, apply the styles to them by adding the `<container-selector> :global(img or video)` style to the user components.
* See https://github.com/gradio-app/gradio/pull/6726#issuecomment-1848788599
* Also fixed two inconsistent styles. Plz see the following comments (https://github.com/gradio-app/gradio/pull/6726#discussion_r1421611426 and https://github.com/gradio-app/gradio/pull/6726#issuecomment-1848790865). Plz let me know what you think.
> Remove the styles from the Image/Video primitive components and Fix the container styles

- .changeset/fresh-dryers-send.md
- gradio/utils.py
- js/app/src/Index.svelte
- js/app/src/css.ts
- js/preview/package.json
- package.json
- pnpm-lock.yaml
This has been driving me up the wall all weekend, so here is a fix.
- Ensure the app reloads + css is correctly applied when CSS files in a watch dir are edited. cc @freddyaboulton 
- Ensure CSS is correctly applied when CSS (as a string) changed.
- Make working with custom CSS much simpler (genuine fix for #3851) cc @aliabid94 @abidlabs 
This should work fine now with no need for `!important` modifiers or other CSS hacks:
```python
css = """
#custom-md h1 {
color: hotpink;
}
.custom-md h2 {
color: orange;
}
"""
with gr.Blocks(css=css) as demo:
gr.Markdown("# Heading one", elem_id="custom-md")
gr.Markdown("## Heading two", elem_classes=["custom-md"])
demo.launch()
```
We do this by modifying the selectors passed by a user, prepending them with a series of addition …
> reload on css changes + fix css specificity

- .changeset/wild-planets-sin.md
- gradio/routes.py
- test/test_routes.py
When mounted on a FastAPI implementing a lifespan context manager the requests remain in the queue.
Stack a new context manager on top of the original one.
`gradio>routes.py>mount_gradio_app`
\>>>
```python
...
@app.on_event("startup")
async def start_queue():
gradio_app.get_blocks().startup_events()
...
```
<<<
```python
...
old_lifespan = app.router.lifespan_context
@contextlib.asynccontextmanager
async def new_lifespan(app: FastAPI):
async with old_lifespan(
app
):  # Instert the startup events inside the FastAPI context manager
gradio_app.get_blocks().startup_events()
yield
app.router.lifespan_context = new_lifespan
...
```
Closes: #6718 
Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, …
> Mount on a FastAPI app with lifespan manager

- .changeset/yummy-roses-decide.md
- client/js/src/client.ts
- client/python/gradio_client/client.py
- client/python/gradio_client/utils.py
- client/python/test/conftest.py
- client/python/test/test_client.py
- demo/hello_world/run.py
- gradio/queueing.py
- gradio/routes.py
- test/test_queueing.py
Closes: #6319 
Closes: #6601 
Closes: #6541 
Closes: #6494
Closes: #6776
> Python client properly handles hearbeat and log messages. Also handles responses longer than 65k

- .changeset/vast-kings-deny.md
- gradio/components/file_explorer.py
- test/test_components.py
2 non-flaky tests were failing on Windows. Turns out one was a problem with the test, while the other was actually an issue in the code. Both should be fixed now.
> Fix backend tests on Windows

- .changeset/shy-pots-stare.md
- gradio/external.py
- test/test_external.py
Stupidly simple fix 🥲 
Fixes: https://github.com/gradio-app/gradio/issues/5927
> Fix `gr.load()` so that it works with the SSE v1 protocol

- .changeset/dirty-experts-cry.md
- client/js/src/client.ts
- gradio/routes.py
Noticed two things when I was debugging flaky tests:
- If there's an exception in the `queue/data/` route the client will hang forever. the server now catches general exceptions
- If the message didn't have an `event_id`, the client would error out, e.g. heartbeat, server_stopped. This wouldn't cause any noticeable errors to users (except console exceptions) but wanted to fix.My guess is that the playwright tests are mysteriously erroring server side so printing the exception message in the UI can help us debug.
- `gr.Info` and `gr.Warning` would also raise exceptions in the client. Would not be obvious to users but not desirable anyways.
- Think I found the issue for the weird HTTPExceptions in logs
Before your create a PR, please check to see if there is [an existing …
> Improve how server/js client handle unexpected errors

- .changeset/bitter-brooms-beg.md
- demo/markdown_example/run.py
- js/app/test/upload_button_component_events.spec.ts
- js/markdown/shared/utils.ts
some weird issues as we were reusing the same marked instance across multiple instances of `gr.Markdown`. The issues only seems to present when more than on markdown component is used.
https://marked.js.org/using_advanced#instance
The quickstart for marked is idiotic in the extreme but this should fix it.
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run …
> Fix md highlight

- .changeset/bumpy-baths-agree.md
- client/js/src/client.ts
- js/app/src/Blocks.svelte
- js/app/src/Index.svelte
- js/app/test/chatinterface_streaming_echo.spec.ts
The issue is that we were constructing the URL manually but we can just use `config.root` which is the correct url hosting the gradio demo even if it's behind a proxy.
Closes: #6739 
Closes: #6748
I tested several demos when running behind a local nginx reverse proxy
This is the nginx.conf
```
daemon off;
worker_processes auto;  ## Default: 1
worker_rlimit_nofile 8192;
events {
worker_connections 8000;
}
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
error_log  var/log/nginx/error.log warn;
pid var/run/nginx.pid;
http {
access_log var/log/nginx/access.log;
server_tokens off;
server_names_hash_bucket_size 64;
include mime.types;
default_type application/octet-stream;
keepalive_timeout 20s;
sendfile on;
tcp_nopush on;
gzip on;
gzip_comp_level 5;
gzip_min_length 256; …
```
> Fix JS Client when app is running behind a proxy

- .changeset/nasty-eagles-do.md
- gradio/components/file.py
- gradio/components/upload_button.py
- gradio/data_classes.py
- test/test_components.py
Specifies that if file_count is set to directory when using File we should expect a list of files rather than a single file.
Closes: #6873
> fix issue 6873: File with file_count='directory' bug

- .changeset/tender-parks-change.md
- js/wasm/src/webworker/index.ts
Fixes an error reported in https://github.com/gradio-app/gradio/pull/6870#issuecomment-1869749020.
#6432 was not sufficient as the app home directory (`/home/pyodide/<appId>`) is only created when at least one file is mounted [here](https://github.com/gradio-app/gradio/blob/31c23166f0113ab6506575f345c31c952e57e137/js/wasm/src/webworker/index.ts#L209), so the app home directory won't exist for example when using `run_code()` and it's the reason of the error above.
> Fix the Wasm worker to initialize the app directories

- .changeset/fruity-taxis-sit.md
- gradio/analytics.py
- js/wasm/src/webworker/index.ts
…ersion after distutils deprecation (in 3.10) and removal in Python 3.12 (see https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated)
gradio had an error on startup on Python 3.12.1:
```
(.venv) daniel@Daniels-MacBook-Pro gradio_dev % python main.py
Traceback (most recent call last):
File "/Users/daniel/git/gradio_dev/main.py", line 1, in <module>
File "/Users/daniel/git/gradio_dev/.venv/lib/python3.12/site-packages/gradio/__init__.py", line 3, in <module>
import gradio._simple_templates
File "/Users/daniel/git/gradio_dev/.venv/lib/python3.12/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
from .simpledropdown import SimpleDropdown
File "/Users/daniel/git/gradio_dev/.venv/lib/python3.12/site-packages/gradio/_simple_templates/simple …
```
> replacing distutils.StrictVersion dependency for Python 3.12

- .changeset/tangy-spoons-hug.md
- gradio/blocks.py
- test/test_blocks.py
Closes: #6608
Repro: 
```py
import random
import time
chatbot = gr.Chatbot()
chatbot2 = gr.Chatbot()
chatbot3 = gr.Chatbot()
msg = gr.Textbox()
clear = gr.Button("Clear")
def user(user_message, history):
return "", history + [[user_message, None]]
def bot(history):
bot_message = ' '.join(['a'] * 1)
history[-1][1] = bot_message
yield history, history, history
msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
fn=bot, inputs=chatbot, outputs=[chatbot, chatbot2, chatbot3], api_name='bot',
)
def clear_func():
return tuple([gr.Chatbot(value=[])]*3)
clear.click(fn=clear_func, outputs=[chatbot, chatbot2, chatbot3], api_name='clear')
demo.queue()
demo.launch()
```
> Fix returning copies of a component instance from a prediction function

- gradio/route_utils.py
- gradio/routes.py
- js/app/src/lite/fetch.ts
- js/wasm/src/http.ts
- js/wasm/src/worker-proxy.ts
This PR solves a problem in [this comment](https://github.com/gradio-app/gradio/pull/6965#issuecomment-1881385151) that the upload progress spinner doesn't work in the Wasm mode.
The base branch of this PR is set to #6965 because this is a successive work and the code changes in #6965 is convenient for testing of this PR,
while I made this a separate PR as it can/should be reviewed and merged independently.
This PR contains following parts:
1. 23dd40a: Enhancing the HTTP emulation in the Wasm mode to handle `ReadableStream`. This is needed to upload the files in chunks in the Wasm mode
2. ca1d48b: Bug fix in the Wasm code. Due to this bug, `upload_id` has not been sent to the server previously.
3. 583dfce: Improving the `/upload_progress` endpoint in the Python server. In the Wasm setup, …
> Lite: Fix and improve the file upload progress SSE

- .changeset/floppy-mugs-fall.md
- js/lite/README.md
- js/lite/package.json
- Makes the [gradio lite guide](https://www.gradio.app/guides/gradio-lite) the readme so it shows up on https://www.npmjs.com/package/@gradio/lite where there isn't currently any info. 
- Removes `private` flag from package.json to allow npm to publish
> Add README to @gradio/lite 

- .github/actions/install-all-deps/action.yml
- .github/workflows/backend.yml
Closes: #7001
I haven't seen this action flake yet but I figure it's easy enough to just revert it rather than implement it ourselves. Don't think there's a reason we need to be on v3. …
> Revert install ffmpeg action to version 2

- .changeset/tame-cloths-cough.md
- gradio/themes/app.py
https://gradio-static-files.s3.us-west-2.amazonaws.com/header-image.jpgjpg does not exist.
https://gradio-static-files.s3.us-west-2.amazonaws.com/header-image.jpg does.
> Themes: fix bogus header image URL

- .changeset/modern-pugs-allow.md
- client/python/gradio_client/client.py
Adds an encoding to the file open, temp file on line 844, 850. These are .py files so utf-8 encoding should be safe
When running deploy_discord on a windows machine, the windows CP1252 encoding does not encapsulate all characters, forcing an encoding=utf-8 allows the deploy_discord call to work on windows jupyter notebooks
> Add encoding to open/writing files on the deploy_discord function

- .changeset/cruel-games-wash.md
- gradio/blocks.py
Closes: #6782
You can test with the same repro from the issue.
> Fix bug preventing layout components to be used as custom components

- .git-blame-ignore-revs
Follows up on #4586 to add more reformatting commits to the ignore file.
> Add more reformatting commits to .git-blame-ignore-revs

- client/python/gradio_client/client.py
Without this fix, as long as client is waiting for server messages, the client consumes 100% of 1 core due to rapid looping.  Added small ms sleep that avoids that wasteful use of CPU.
Closes: https://github.com/gradio-app/gradio/issues/7086
https://github.com/gradio-app/gradio/issues/7086
```
def test_hang():
import time
chatbot = gr.Chatbot()
msg = gr.Textbox()
def respond(message, chat_history):
time.sleep(10000)
if not chat_history:
chat_history = [[message, '']]
chat_history[-1][1] = message
for fake in range(0, 1000):
chat_history[-1][1] += str(fake)
time.sleep(0.1)
yield "", chat_history
return
msg.submit(respond, [msg, chatbot], [msg, chatbot], api_name='submit')
demo.queue(api_open=True)
demo.launch(prevent_thread_lock=True, …
```
> Fixes excessive CPU use by client while it waits for server to send messages during streaming

- .changeset/flat-suns-cry.md
- js/app/src/Blocks.svelte
As reported by @oobabooga in #6847, there is considerable lag when there's very high rate of UI updates, e.g. when streaming text to a chatbot. This is because we re-render the UI on every update, which is expensive. A low hanging fruit is throttling the maximum rate of UI updates to once per 50ms. In the demo code below, I see speed increases of over 10x, from 37s to 2.5s:
```python
import random
import time
chatbot = gr.Chatbot()
msg = gr.Textbox()
clear = gr.ClearButton([msg, chatbot])
def respond(message, chat_history):
bot_message = "How are you?" * 10000
chat_history.append((message, bot_message))
for i in range(2000):
chat_history[-1] = (chat_history[-1][0], chat_history[-1][1] + " " + str(i))
yield "", chat_history
print("done") …
```
> Improve rapid generation performance via UI throttling

- .changeset/big-bananas-sell.md
- gradio/processing_utils.py
Fix for Audio data cannot be converted automatically from int8 to 16-bit int format
Closes: https://github.com/gradio-app/gradio/issues/7099
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: …
> Support audio data in `np.int8` format in the `gr.Audio` component

- .changeset/famous-mammals-attend.md
- gradio/cli/commands/components/publish.py
Closes: #7106
Fix is to programmatically determine the most recent wheel version to push to spaces.
> Programmatically determine max wheel version to push to spaces

- .changeset/petite-islands-follow.md
- gradio/cli/commands/reload.py
- gradio/utils.py
Closes: #7095
We're watching the files of the gradio source code in addition to the demo. This increases the number of files that are polled for changes by an order of magnitude and most users are not installing gradio from source and making changes to the source code. 
Fix:
- Only watch the gradio source code if installed in edit mode from source. There isn't a foolproof way to determine this but I have implemented a heuristic that should work most of the time. This change will only be "breaking" users who install gradio from pypi and who edit the source code in the `site-packages` directory. I think that's a small proportion of users and they can always do an editable install to get around this.
- Introduce a short sleep between watch iterations. I'm using 0.05 seconds which should be …
> Reduce CPU usage of dev mode

- .changeset/lemon-tips-switch.md
- js/app/src/Blocks.svelte
- pnpm-lock.yaml
This fixes a regression identified by @pseudotensor, closes: https://github.com/gradio-app/gradio/issues/7078
Test code:
```py
def upload_file(files):
file_paths = [file.name for file in files]
return file_paths
file_output = gr.File()
upload_button = gr.UploadButton("Click to Upload a File", file_types=["image", "video", ".pdf"], file_count="multiple")
event = upload_button.upload(upload_file, upload_button, file_output)
def check(x):
raise ValueError("Cannot handle jpg")
event.then(check, inputs=upload_button, outputs=upload_button)
demo.launch()
```
> un-disable output components after exception is raised

- .changeset/lazy-things-accept.md
- gradio/cli/commands/components/build.py
- gradio/cli/commands/components/docs.py
- js/paramviewer/ParamViewer.svelte
Runs the docs generator as part of the build. This only provides defaults with no options (so as not to bloat the build command). If you users wish to customise the behaviour, they can use the `docs` command.
Added new arg to `build` to optionally disbale the docs gen:
```bash
gradio cc build --no-generate-docs
```
Related to #7080.
1. PRs will …
> generate docs when running `gradio cc build`

- .changeset/swift-frogs-bow.md
- js/wasm/src/webworker/index.ts
`ruff` can't be installed on Pyodide, so mock it.
Closes: #7120
> Add ruff mock for Lite

- .changeset/few-things-smash.md
- gradio/templates.py
- test/test_components.py
Closes: #7137
The issue is that only props that are explicitly listed in the __init__ are saved to the config. For this reason we removed **kwargs from the main components. We kept them in the templates by mistake.
I removed kwargs from the templates and made sure every parameter listed in the parent component is also listed in the template component. Also added a unit test to prevent this in the future.
Repro from original issue
```python
files = gr.Files(interactive=True, file_types=["image"])
demo.launch(share=True)
```
Go to share link from your phone and upload a photo. You should be able to select from photo gallery.
https://github.com/gradio-app/gradio/assets/41651716/575c0798-d593-4c47-839a-953a77d88503
Before your create a PR, please …
> Remove kwargs from template components

- .changeset/smooth-bears-change.md
- js/wasm/src/webworker/py/script_runner.py
Closes: #7044
Fixes a bug introduced in #6099.
Due to the SharedWorker mode, `appHomeDir` must be added to `sys.path` when user scripts are executed.
> Lite: Add the `home_dir` to `sys.path`

- guides/03_building-with-blocks/01_blocks-and-event-listeners.md
Signed-off-by: thiswillbeyourgithub <26625900+thiswillbeyourgithub@users.noreply.github.com>
Rephrase the docs of `gr.on` as it was a bit misleading, as evidenced by #6730.
This PR was requested by @abidlabs [here](https://github.com/gradio-app/gradio/issues/6730#issuecomment-1903435699)
Closes: #6730
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the …
> docs: more explicit pharsing for gr.on

- .changeset/old-rice-laugh.md
- gradio/helpers.py
- gradio/utils.py
The Gradio features that actually require matplotlib are few and far between, and most matplotlib importing is already deferred.
This moves the rest.
> Defer importing matplotlib

- .changeset/dirty-crabs-wear.md
- gradio/blocks.py
- gradio/external.py
- gradio/interface.py
Small PR to to add missing  parameters to `gr.TabbedInterface`, as well as fix some related docstrings.
Closes: https://github.com/gradio-app/gradio/issues/7171
> Add missing parameters and docstrings for `gr.TabbedInterface`

- .changeset/spicy-rabbits-check.md
- gradio/cli/commands/components/publish.py
Partially closes #7213 
If there was a hyphen in a parent directory, the publish command would fail.
> Fix hyphen-bug in gradio cc publish

- .github/actions/changes/action.yml
- .github/workflows/delete-stale-spaces.yml
- .github/workflows/deploy+test-visual.yml
- .github/workflows/deploy-spaces.yml
- .github/workflows/deploy-website.yml
- .github/workflows/generate-changeset.yml
- .github/workflows/publish.yml
- .github/workflows/test-functional.yml
- .github/workflows/test-hygiene.yml
- .github/workflows/test-python.yml
- .github/workflows/tests-js.yml
Updates `action/checkout` to avoid the Node 16 warning on every CI run.
Executed with [`gha-tools`](https://github.com/akx/gha-tools) `autoupdate`.
In addition, there's a couple more upgrades available that I didn't include here:
* `FedericoCarboni/setup-ffmpeg@v2` => `FedericoCarboni/setup-ffmpeg@v3`
* `dorny/paths-filter@v2` => `dorny/paths-filter@v3`
Follows up on #7233, #7243, #7244, #7245, #7246, #7248.
> CI: update GitHub Actions versions

- .changeset/slow-bikes-thank.md
- gradio/components/base.py
- gradio/components/json_component.py
- gradio/components/state.py
- gradio/helpers.py
- guides/05_custom-components/04_backend.md
The argument isn't used by the function, and [it doesn't seem to be used by external code across GitHub either](https://github.com/search?q=read_from_flag+language%3APython&type=code&l=Python&p=1).
This was flagged by Ruff's ARG lint.
> Remove flag_dir from read_from_flag()

- gradio/components/code.py
The Code component can accept a Callable as value, as said on the documentation, but the typing on that parameter wasn't following that.
> fix: Code component not accepting type Callable on value parameter

- .changeset/light-lemons-shout.md
- gradio/cli/commands/components/_docs_utils.py
Closes: https://github.com/gradio-app/gradio/issues/7239
> Escape triple quotes when creating `space.py` for custom components

- .changeset/red-turkeys-make.md
- gradio/utils.py
The `article` parameter of `gradio.Interface` takes both an URL and markdown/HTML text. The constructor first tries to use article string as URL, and if that throws an `httpx.RequestError`, the article string is used directly. This does not work if the article string is longer than `httpx._urlparse.MAX_URL_LENGTH` or contains non-printable characters, in which case `httpx.InvalidURL` is raised. This PR handles this error.
> Handle httpx.InvalidURL when setting non-URL article strings

- .changeset/tired-suns-judge.md
- gradio/external.py
- gradio/external_utils.py
- gradio/utils.py
- guides/06_integrating-other-frameworks/01_using-hugging-face-integrations.md
- guides/cn/04_integrating-other-frameworks/01_using-hugging-face-integrations.md
- test/test_external.py
- test/test_utils.py
Since "Inference API" has been renamed -> "Serverless Inference Endpoints" on hf.co, this PR makes the same change throughout our documentation.
Closes: #7181 
I also used this opportunity to refactor `gr.load()` to use the `huggingface_hub.InferenceClient` wherever possible, and added the Wait-for-Model header:
Closes: #5483 
Closes: #7238 
I also added examples to the Interfaces that are produced by `gr.load()` since they make the resulting demos easier to use (if needed, it is possible to revert to no examples by explicitly setting `examples=None` in `load()`). 
In a few cases, I made some changes to the resulting interface, for example: the `text-generation` pipeline now produces a unified interface, which imo looks nicer:
(sigh, remember gpt-2's idiosyncrasies)
I went through all of …
> Refactor Inference API and rename it to Serverless Inference Endpoints

- .changeset/two-pants-flow.md
- gradio/data_classes.py
The following error started to occur on Lite after #7333.
Because Pydantic V2 is not available on Pyodide yet, Lite still uses Pydantic V1 with patches bridging the V1 APIs to V2 interfaces so the original Gradio code relying on the V2 API works.
The patch didn't support the `Config` class API V1, which is deprecated in V2 and #7333 switched from to the new one. This PR updates the patch to support the configuration interface in V2 using the V1 API.
```
Error
Traceback (most recent call last): File "/lib/python311.zip/_pyodide/_base.py", line 571, in eval_code_async await CodeRunner( File "/lib/python311.zip/_pyodide/_base.py", line 394, in run_async coroutine = eval(self.code, globals, locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<exec>", line 1, in <module> File …
```
> Update Pydantic patch for Lite that emulates PydanticV2 API using V1

- .changeset/social-loops-send.md
- js/gallery/package.json
- pnpm-lock.yaml
Clean-up.
I added the `@gradio/wasm` dependency to the `@gradio/gallery` package during the work on #6967, but finally the Wasm feature of the package relies on the image module and this dependency is no longer needed.
> Remove the `@gradio/wasm` dependency from `@gradio/gallery` that is not used

- .changeset/rare-months-guess.md
- client/python/gradio_client/documentation.py
- gradio/cli/commands/components/_create_utils.py
- test/test_gradio_component_cli.py
Also strips the `\@document()` call from custom component templates so authors don't get a warning about the documentation group not being found.
> Make set_documentation_group a no-op

- .changeset/tasty-spies-spend.md
- js/dropdown/dropdown.test.ts
- js/dropdown/shared/Dropdown.svelte
Closes: https://github.com/gradio-app/gradio/issues/6853 and adds a unit test.
> Retain dropdown value if choices have been changed

- .changeset/solid-coats-sort.md
- gradio/components/file_explorer.py
- js/fileexplorer/shared/FileTree.svelte
Fixes #6627 
When FileExplorer is not interactive, checkboxes are hidden
> Fix File Explorer interactivity

- .changeset/fine-pets-switch.md
- gradio/route_utils.py
- gradio/routes.py
- test/test_routes.py
This way we compare passwords is vulnerable to timing attack to guess the password. This PR uses `hmac` to prevent that, as described here: https://sqreen.github.io/DevelopersSecurityBestPractices/timing-attack/python
> Prevent timing attacks to guess Gradio passwords

- .changeset/bumpy-wasps-march.md
- gradio/route_utils.py
- gradio/routes.py
- requirements.txt
- test/test_routes.py
Slightly more general fix for #7444 to handle IPFS and other crazy formats
> Make fix in #7444 (Block /file= filepaths that could expose credentials on Windows) more general

- guides/08_gradio-clients-and-lite/02_getting-started-with-the-js-client.md
I was trying to run this example, but it failed.  predict() is a method of the app object, not client.  Fixed!
> Fixed typo in example: client -> app

- .changeset/spicy-zebras-lay.md
- js/dataframe/shared/VirtualTable.svelte
Closes #5458
I'm not really sure why this was happening, i think it something to do with reasons.
What I do know is that it isn't reproducible with headers and content of consistent length, it is only when I used more organic data that the bug surfaced.
With the below reproduction this is reproducible in all browsers (that I have access to).
Simple reproduction: https://huggingface.co/spaces/pngwn/df_scroll_bug_repo
Same demo with fix: https://huggingface.co/spaces/pngwn/df_scroll_bug_fix
@clefourrier @tomaarsen @ThiloteE @19kmunz @severo if you have the time could you check my simple reproduction reproduces the issue you have seen in whatever browsers you are using and also check the fix does indeed fix the issue.
Thanks!
> ensure Dataframe headers are aligned with content when scrolling

- .changeset/nine-drinks-clap.md
- js/statustracker/static/index.svelte
This fixes #7368 and works fine from what I tested, I just don't know exactly all the implications of changing this `z-index` 
> Fix z-index layer of orange generating border

- .changeset/yummy-states-wink.md
- js/model3D/shared/Model3D.svelte
- js/model3D/shared/Model3DUpload.svelte
Closes: #7484
The main fix is 041eb99.
903c81d is a refactoring commit.
In d2ee5df, the undo buttons are disabled in the Gaussian Splatting mode as it's not implemented.
> Fix Canvas3D/Canvas3DGS async imports

- guides/04_chatbots/01_creating-a-chatbot-fast.md
This PR updates the usage of the OpenAI API in accordance with the changes in version 1.0.0. The deprecated `openai.ChatCompletion` has been replaced with `client.ChatCompletion.create()`.
Additionally, the way we extract the content from the API response has been updated. Previously, we checked if the length of `chunk['choices'][0]['delta']` was not zero. Now, we check if `chunk.choices[0].delta.content` is not `None` before appending it to `partial_message`.
Closes: #7242
> Streaming example for the updated OpenAI API

- .changeset/witty-walls-brake.md
- gradio/route_utils.py
- gradio/routes.py
- test/test_routes.py
Path starting with // or \\ on Windows are interpreted as SMB share paths and automatically opened with the open function.
> Prevent paths beginning with `//` or `\\`

- guides/04_chatbots/01_creating-a-chatbot-fast.md
The changes only affect a single markdown page in `guides/`.
In the end, my PR only addresses a single code example in a single guide.
---
EDIT: After reading through the CI logs, I realised that the redirect fixes I proposed were faulty. I thus reverted these.
> Fixed redirects and reformatted code in creating-a-fast-chatbot guide

- client/python/gradio_client/client.py
type_python => python_type
Doc info out of date or is a typo
https://www.gradio.app/docs/client#client-view-api-example-usage
> Update client.py: Docs typo

- .changeset/deep-teeth-sleep.md
- gradio/processing_utils.py
- test/test_processing_utils.py
There was a mistake in how we were updating the `root` url, so that they weren't being updated correctly after the first time, which was leading to issues like this: https://github.com/gradio-app/gradio/issues/7531
Test with:
```py
gr.Audio("https://file-examples.com/storage/fe98e6ab1965df346a899de/2017/11/file_example_MP3_700KB.mp3")
demo.launch(share=True)
```
Fixes: https://github.com/gradio-app/gradio/issues/7531
Fixes: https://github.com/gradio-app/gradio/pull/7566
> Fixes method to resolve the `root` URLs

- .changeset/silver-hairs-roll.md
- gradio/server_messages.py
Fix on #7407 for Wasm.
`pydantic.BaseModel` (and `RootModel`) is patched in `data_classes.py` for Wasm env (the normal one is used in the normal env), so we should use it instead of directly importing `pydantic.BaseModel`.
https://github.com/gradio-app/gradio/blob/a57e34ef87d24f40f09380b7b71a052f120a19fe/gradio/data_classes.py#L18-L75
> Fix server_messages.py to use the patched BaseModel class for Wasm env

- .github/workflows/deploy-spaces.yml
- scripts/upload_website_demos.py
Adds the missing client wheel url to the requirements for main website spaces.
> Add client wheel url to main spaces 

- .changeset/common-months-guess.md
- js/upload/src/Upload.svelte
Quick fix for broken image upload. There was a bug when parsing the `file_types`.
> image upload fix

- .changeset/fast-heads-visit.md
- gradio/cli/commands/components/build.py
- gradio/cli/commands/components/create.py
- gradio/cli/commands/components/dev.py
- gradio/cli/commands/components/install_component.py
- guides/05_custom-components/06_frequently-asked-questions.md
- js/preview/src/build.ts
- js/preview/src/dev.ts
- js/preview/src/examine.py
- js/preview/src/index.ts
- test/test_gradio_component_cli.py
Closes: #7621 
Adds CLI arguments to let developers control the path of the python executables used in create, dev, and build commands.
Also adds some debugging information to dev mode in case no custom components are found. I suspect this will help debug issues like #6821  …
> Add --python-path, --pip-path, --gradio-path CLI arguments to let custom component developers control which executable is used

- .changeset/fix_changelogs.cjs
We need a new line at the end of the `@gradio/lite` `package.json` file to make the formatter happy.
> fix formatting error in gradio/lite package.json

- .changeset/plain-guests-attend.md
- gradio/oauth.py
- gradio/route_utils.py
- guides/01_getting-started/03_sharing-your-app.md
2 things in this PR:
1. Fix https://github.com/gradio-app/gradio/issues/7695. The snippet example in the OAuth docs is not complete, resulting in a runtime error when running it. I forgot `from huggingface_hub import whoami` and `demo.launch()`. This is now fixed and I've been able to run it both locally and in a Space. I also took the opportunity to remove mentions to `gr.LogoutButton` from the docs (deprecated in https://github.com/gradio-app/gradio/pull/7063).
2. There seem to be a major bug that broke all OAuth apps on the latest version of gradio. For some reason, now `request.session` is not a dictionary anymore but a `Obj` object that mimics it. The `Obj` class has been added 6 months ago but the bug is for sure much more recent. Can it be related to …
> Fix OAuth + fix OAuth documentation + undocument logout button

- .github/actions/install-all-deps/action.yml
Our Linux CI was running Python 3.10. This sets it to Python 3.8, which is the minimum supported version by `gradio`. Note that our Windows CI was always running on 3.8.
I've confirmed that once the cache is deleted, this change is sufficient to run the CI on 3.8 in this fork: https://github.com/abidlabs/gradio/actions/runs/8283404782/job/22666866280
> Run Linux CI on Python 3.8

- .changeset/wise-bikes-hear.md
- gradio/blocks.py
- gradio/networking.py
- gradio/utils.py
Closes: #5143 
I actually can't repro #5143 at all. But this PR looks at the exceptions raised in #7644 and #7673 and I modified the code so that httpx does not timeout anymore in those cases. 
For #7644, the issue is that by default `httpx` has a 5 second timeout. requests does not. So when we switched from requests to httpx, we simply changed `requests.get( f"{self.local_url}startup-events",...)` to `httpx.get(f"{self.local_url}startup-events, ...)", ...)`. We need to add `timeout=None` to the httpx get function to get the same behavior.
For #7673, the issue is that we're not catching httpx's timeout exception. If we catch it, `url_ok` can try to connect the local URL again. This mirrors the implementation in 3.50.2. 
I don't think we need to add an API to let developers control the …
> Fix httpx timeout issues

- .changeset/curly-ends-feel.md
- gradio/external.py
- gradio/external_utils.py
Fixes: https://github.com/gradio-app/gradio/issues/7583
Test with:
```py
demo = gr.load(name="microsoft/table-transformer-detection", src="models", examples=["https://nielsr-tatr-demo.hf.space/--replicas/8duds/file=/tmp/gradio/7f043c2497be0235345dcfc1e2d111b46782cbe7/image.png"])
demo.launch()
```
> Add support for object-detection models in `gr.load()`

- .changeset/kind-eyes-shake.md
- client/python/gradio_client/client.py
- client/python/gradio_client/compatibility.py
- client/python/gradio_client/utils.py
- client/python/test/test_client.py
- client/python/test/test_utils.py
This PR adds an `ssl_verify` parameter to `gradio_client.Client` to match the corresponding parameter in `launch()`
Not easy to write a unit test for this but you can run the following to confirm:
1. `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes` in terminal
2. In the same directory, launch a gradio app:
```py
demo = gr.Interface(lambda x:x, "image", "image")
_, url, _ = demo.launch(
ssl_certfile="cert.pem",
ssl_keyfile="key.pem",
ssl_verify=False
)
```
3. Connect with the client:
```py
from gradio_client import Client, file
client = Client(url, ssl_verify=False)
client.predict(file("cheetah.jpg"))
```
Fixes: https://github.com/gradio-app/gradio/issues/5497
> Add support for python client connecting to gradio apps running with self-signed SSL certificates

- .changeset/spotty-parents-wink.md
- gradio/processing_utils.py
Replaced httpx with requests library in `save_url_to_cache` of `processing_utils.py`  to load example urls in wasm mode for gradio lite.
Closes: #6837 
2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`: Ran it on my files.
> Replace httpx with requests library in save_url_to_cache to make it work in wasm mode

- .changeset/tiny-years-rest.md
- js/app/src/lite/css.ts
Fixes #7694
See this comment about this PR -> https://github.com/gradio-app/gradio/pull/7709#discussion_r1525824675
> Fix wasm_proxied_mount_css to not reuse an existing style element

- .changeset/spotty-parents-wink.md
- gradio/processing_utils.py
Reverts gradio-app/gradio#7725:
> One issue is that this PR makes requests a dependency of gradio, which is not ideal. Currently, this passes because requests is a dependency of huggingface_hub but that may change in the future so we would need to include it as an explicit dependency. Let me revert this PR and we can figure this out as part of https://github.com/gradio-app/gradio/pull/7728
> Revert "Replace httpx with requests library in save_url_to_cache to make it work in wasm mode"

- .changeset/tasty-donkeys-warn.md
- gradio/components/button.py
- test/test_components.py
Gradio launch succeeds but gets stuck on loading screen if you use integers instead of strings for the "value" field on gr.Button().
Add forced casting to string of button value in postprocess function of gradio Button component (`return str(value)`)
Closes: #7690
(https://github.com/gradio-app/gradio/issues/7690#issuecomment-1997718185)
> Cast button value as string in postprocess

- .changeset/plenty-paths-sing.md
- js/markdown/shared/MarkdownCode.svelte
Trying to `render_math_in_element` was causing errors, because the kaTex seemed to be trying to access elements in the DOM that weren't loaded yet. Added a check that only runs the `render_math_in_element` when `latex_delimiters` are found in the markdown `value`.
Closes: #7569 …
> Fixes: gr.Markdown is not updated properly when it has an image tag

- .config/playwright.config.js
- js/app/test/chatbot_multimodal.spec.ts
Tests that pass when they are retried are reported as flaky by playwright
So the idea here is to notice the flakes but not slow down development velocity. 
> Configure playwright to automatically retry failing tests up to 3 times

- .changeset/mighty-bags-begin.md
- js/radio/Index.svelte
Closes: #7757
The `input` event was not triggered if the Radio was output by an event. But based on the docstring for `input`, it should be triggered for all user input, which makes it equivalent to `select` event.
Based on the discussion in the issue, it seems like this was working in a previous version. Not sure what could have changed (didn't look into it), but I think this refactor makes sense anyways.
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your …
> Trigger input event for Radio even when radio is output component

- .changeset/two-suns-trade.md
- gradio/events.py
- gradio/interface.py
- test/test_interfaces.py
Closes: #7752 
You can test it here: https://huggingface.co/spaces/freddyaboulton/fast-typing-live-bug
Should not drop any text like the video in the original issue …
> Adds trigger_mode to gr.on. Use it to set trigger_model="always_last" for live interfaces.

- .changeset/clever-masks-melt.md
- client/python/gradio_client/client.py
I forgot to address this comment by @freddyaboulton: https://github.com/gradio-app/gradio/pull/7732#discussion_r1534706772. This PR fixes it. 
Test with:
```py
lambda x,y:x,
[gr.Audio("test.mp3"), gr.Number()],
"audio"
)
_, url, _ = demo.launch(inline=False)
from gradio_client import Client
client = Client(url)
client.view_api()
```
> Small fix to client.view_api() in the case of default file values

- .changeset/weak-shoes-judge.md
- js/slider/Index.svelte
- js/slider/Slider.stories.svelte
This pull request makes the slider look more logical and compliant with UX standards. Now in the inactive state the slider looks more subdued and the cursor on the hover is displayed correctly.
Closes: #7813
> Improve UX of non-interactive slider

- .changeset/silly-spies-cross.md
- gradio/__init__.py
- gradio/blocks.py
- requirements.txt
Related to #7791 
|  | This PR (`f86fea0`) | `main` (ff6bf3e) |
|---|---|---|
| 1 | 9.861 | 10.090 |
| 2 | 8.722 | 9.548 |
| 3 | 8.511 | 8.099 |
| Avg | 9.031 | 9.246 |
Also, the initial payload size is reduced from 110MB to 105MB because `typer` and its deps such as `click` and `rich` are not downloaded.
> Exclude `typer` from the requirements list for Wasm env and fix `gradio.cli` not to be imported

- .changeset/neat-numbers-matter.md
- gradio/__init__.py
Related to #7791 
`gradio.ipython_ext` is one major part taking the import time which is also an unnecessary part for Wasm, so it shouldn't be imported in the Wasm env.
To make the change effective, set `IS_WASM = True` manually during the measurement.
> Stop importing gradio.ipython_ext in Wasm mode

- guides/09_other-tutorials/running-gradio-on-your-web-server-with-nginx.md
As I was looking at https://github.com/gradio-app/gradio/issues/7749, I realized we never really documented our process for constructing the `root_url` or explained what headers are needed in nginx. This add additional documentation.
> Additional documentation related to nginx and `root_url`

- .changeset/solid-cars-spend.md
- gradio/components/dataframe.py
Related to #7791 
`pandas.io` imports `matplotlib` internally. It takes a long time and makes #7157 less effective.
This PR fixes it.
|  | This PR (8194bfd) | `main` (1a7c8d3) |
| --- | --- | --- |
| 1 | 7.369 | 9.023 |
| 2 | 6.909 | 8.798 |
| 3 | 6.991 | 9.556 |
| Average | 7.090 | 9.126 |
> Fix gradio/components/dataframe.py not to import `pandas.io`

- .changeset/eleven-states-tan.md
- js/app/vite.config.ts
Ref: https://huggingface.slack.com/archives/C055NMB0S87/p1711525308205149?thread_ts=1711089573.553429&cid=C055NMB0S87
Confirmed that `pnpm --filter @gradio/app build:lite` generated a minified `lite.js`.
> Revert the minify setting in vite.config.js which was mistakingly introduced in #6261

- .changeset/beige-animals-tan.md
- gradio/components/chatbot.py
- js/chatbot/Chatbot.stories.svelte
- js/chatbot/Index.svelte
- js/chatbot/shared/ChatBot.svelte
- test/test_components.py
I had previously created a custom component with this functionality but after discussion with @dawoodkhan82 figured it'd be useful to have in core. 
Here's what it looks like:
```py
placeholder = """
**Gradio Helper**
This Chatbot can help you on any topic related to Gradio.
"""
gr.ChatInterface(lambda x,y:x, chatbot=gr.Chatbot(placeholder=placeholder)).launch()
```
The placeholder only appears when there are no messages to display.
> Adds a `placeholder` argument to `gr.Chatbot`

- .changeset/shaggy-symbols-tie.md
- gradio/chat_interface.py
Reduces the default min width of the buttons in `gr.ChatInterface` to make it more mobile-friendly.
Before:
After:
> Make buttons in `gr.ChatInterface` more mobile-friendly

- .changeset/green-brooms-work.md
- gradio/blocks.py
Suppress printing "Running on local URL:" when quiet is set
Closes: #7864  …
> Suppress printing "Running on local URL:" when quiet is set

- .changeset/strong-hornets-push.md
- gradio/chat_interface.py
- gradio/interface.py
- gradio/utils.py
As discussed [earlier](https://huggingface.slack.com/archives/C02QNREU24S/p1711549951697389?thread_ts=1711493071.830579&cid=C02QNREU24S), most of the event handlers for manipulating the UI in gr.Interface and gr.ChatInterface can be made async. This should lead to better performance as new threads would not be spun up to handle these quick updates. …
> Make internal event handlers of gr.Interface and gr.ChatInterface async

- .changeset/fast-walls-drop.md
- gradio/components/code.py
- test/test_components.py
You can display a filename for the code component example as opposed to the whole contents of the file. Just need to pass in a tuple to denote it's a file (same as postprocess)
Test with
```python
lambda x: x,
gr.Code(),
gr.Code(),
examples=[[("/Users/freddy/sources/gradio/demo/code_component/run.py",)], ]
)
demo.launch()
```
Don't think we need #4268 for this
1. PRs will only be merged if tests pass on CI. To run the tests …
> Allow displaying gr.Code examples by their filename if value is a tuple

- .changeset/pretty-walls-try.md
- gradio/queueing.py
- guides/09_other-tutorials/deploying-gradio-with-docker.md
- js/_website/src/routes/[[version]]/guides/[guide]/+page.server.ts
When documenting the fix for https://github.com/gradio-app/gradio/issues/6920, I felt there was no adequate place to put this information in our existing docs/guides, so I added a Guide on deploying Gradio apps with Docker.
Closes: #6920 
fwiw this was requested quite a bit a long time ago (#378, #24) and I think would be good from a seo perspective
Also makes the exception that users observed in #6920 more informative
> Adds a Guide on deploying Gradio apps with Docker

- .changeset/little-breads-allow.md
- gradio/route_utils.py
- test/test_routes.py
While investigating https://github.com/gradio-app/gradio/issues/7934, I learned that the x-forwarded-host and x-forwarded-proto headers can contain multiple values if the request has passed through several proxies. 
E.g. see https://gitlab.com/gitlab-org/gitlab-pages/-/merge_requests/386
This PR modifies the `get_root_url()` method to handle these cases
> Handle the case of multiple headers when constructing root url

- .changeset/tiny-friends-stick.md
- client/python/test/test_client.py
- gradio/blocks.py
- gradio/route_utils.py
- gradio/routes.py
- gradio/utils.py
- js/app/test/unload_event_test.spec.ts
This may fix some of the slowdowns we've seen in spaces loading recently. 
> Use asyncio.Event to stop stream in heartbeat route

- .changeset/twenty-paws-poke.md
- gradio/route_utils.py
Closes a task bug found by @aliabd in python 3.9. Python 3.10 and 3.11 are good.
> Fix task bug in python 3.9

- .changeset/honest-spiders-visit.md
- gradio/chat_interface.py
This PR add the hint type `list[list]` in the example parameter of the `gr.ChatInterface()` object, to resolve the "Expected parameter" message when a single or multiple additionnal_inputs are provided to the instance.
Closes: #7931 (closed)
> Adding hint `list[list]` for example parameter

- client/js/src/client.ts
- client/js/src/utils.ts
- gradio/blocks.py
Provide a logged-in experience for ZeroGPU (regarding GPU quotas)
ZeroGPU functions are marked with a `zerogpu` attribute by the `@spaces.GPU` decorator
When this attribute is detected, `"zerogpu"` is set to `True` in the dependency config
On JS client side, when `dependency.zerogpu` is `true` we ask parent frame (HF hub) for headers to be included in the API request (through the postMessage API)
> [ZeroGPU] postMessage `zerogpu-headers`

- .changeset/eighty-rockets-march.md
- client/js/src/client.ts
Fixes this error
> GET http://localhost:7860/heartbeat/0gcss84krmc5 net::ERR_CONNECTION_REFUSED
> Fix heartbeat in the js client to be Lite compatible

- .changeset/free-things-wink.md
- gradio/blocks.py
This feature lets you override the `share` argument passed into the `launch()` method.
There are many gradio apps, and some apps have the `share=True` hardcoded and some don't. But sometimes we want to just take ANY gradio app and make them shareable via the gradio.live URL, even if the original source code does not specify `app.launch(share=True)`.
How it works:
1. `GRADIO_SHARE=1 python app.py`: will launch the gradio.live share link even if the `app.py` launched the server with `app.launch()`.
2. `GRADIO_SHARE=0 python app.py`: will launch WITHOUT the gradio.live share link even if the `app.py` launched with the server with `app.launch(share=True)`
I've searched and couldn't find any similar issue. So just created one here: https://github.com/gradio-app/gradio/issues/7985
I tested this …
> GRADIO_SHARE Environment Variable

- .changeset/fair-trains-marry.md
- js/app/test/gradio_pdf_demo.spec.ts
- js/multimodaltextbox/shared/MultimodalTextbox.svelte
- js/upload/src/Upload.svelte
Closes #7988 
We want a custom progress animation for MultimodalTextbox than we do for the other components uploads. So I'm adding a `show_progress` prop to be able to better distinguish between the two cases. …
> Add show_progress prop to Upload Component to bring back upload progress animation

- .changeset/upset-coins-remain.md
- gradio/components/textbox.py
- test/test_helpers.py
As discussed in the issue mentioned below, it was not mirrored in the docstring of `gr.Textbox` that `show_copy_button` is not visible when `show_label=False`. This PR adds a short Note about this after the already existing Parameters doc.
Closes: #7717 - @abidlabs  …
> Document that show_copy_button in gr.Textbox is not visible when show_label=False

- .changeset/strong-colts-take.md
- js/app/src/lite/custom-element/index.ts
With this PR, using the custom component like below becomes possible where the child elements such as `<gradio-requirements>` are used with the text literal directly inside the top-level `<gradio-lite>`.
```html
<gradio-lite>
gr.Interface(
fn=lambda x: x,
inputs=gr.Textbox(),
outputs=gr.Textbox()
).launch()
<gradio-requirements>
matplotlib
</gradio-requirements>
</gradio-lite>
```
Before this PR, the `<gradio-code>` element is needed to declare the source code with using `<gradio-requirements>`.
> Update the Lite custom element parser

- .changeset/sour-queens-count.md
- requirements.txt
Source: https://typer.tiangolo.com/release-notes/#0121
> Update `typer` to drop `[all]` as it is no longer needed

- .changeset/green-keys-invite.md
- js/imageeditor/shared/ImageEditor.svelte
**round [x, y, w, h] before cropping to avoid unexpected interpolation on pixel values**
I'm working on some demo of image watermarking. Cropping the test image using `ImageEditor` ruins the watermark while my watermark should have the ability to withstand cropping.
After some investigation into both front-end and back-end, I figured the problem is that the current implementation of cropping using `CanvasRenderingContext2D: drawImage()` in front-end would produce undesired interpolation on pixel values **if the canvas dimensions are not integers**.
Therefore, a simple fix is to round the cropping parameters before calling `$pixi.get_layers()`
> round [x, y, w, h] before cropping to avoid unexpected interpolation on pixel values

- CHANGELOG.md
- README.md
Fixed two small typos in text files:
Its -> It's in README
builing -> building in CHANGELOG
> fix typos in README and CHANGELOG

- .changeset/easy-symbols-pick.md
- gradio/utils.py
Fixes bug causing Hot Reload failure in code with non-English languages due to missing encoding specification.
I hardcoded UTF-8 because I couldn't figure out how to specify the encoding, similar to the fix in `gradio\cli\commands\reload.py`.
Closes: #8070
> Fix causing Hot Reload (#8070)

- js/dropdown/shared/DropdownOptions.svelte
- js/dropdown/shared/Multiselect.svelte
As seen in the issue below, the dropdown options and multiselect have text that trails off the screen if the text is too long. I included `word-break` in the styling and adjusted the sizing of the dropdown option to resolve the issue. For example in this demo,
```python
d = gr.Dropdown(value=None, choices=["too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too …
```
> fix: break words in dropdown + multiselect

- js/label/Label.stories.svelte
Rel: #8063
Found that the visual CI is not testing what #8063 fixed properly as there is no line-break in the stories.
This PR fixes it.
Before:
This PR:
> Fix the visual test on the Label component

- .changeset/silly-drinks-glow.md
- js/label/Index.svelte
Happened to find the `<Label />` component continues to dispatch the `change` event once it gets some `value`.
For example, if you add `console.log("gradio event.", e.detail);` in this event listener↓
https://github.com/gradio-app/gradio/blob/0424c759d8a790529406229c52f47cb469e78d3e/js/app/src/Blocks.svelte#L423-L442
and run the following app,
```python
def fn(_):
return {"foo": 0.9, "bar": 0.8}
fn=fn,
inputs=None,
outputs=gr.Label()
)
demo.launch()
```
you can find the event is dispatched infinitely after clicking the submit button as below.
I modified `<Label />`'s code detecting the changes of `value` to be like other component such as 
https://github.com/gradio-app/gradio/blob/0424c759d8a790529406229c52f47cb469e78d3e/js/json/Index.svelte#L29-L34 …
> Fix Label component's value change detection to avoid infinite loop dispatching the change event

- .changeset/cuddly-snakes-swim.md
- js/app/src/lite/custom-element/index.ts
With #7975, the Lite custom component app like below started to fail because the user intends to execute `app.py` but the parser tries to get the source code directly from the text content of most-outer `<gradio-lite>` tag.
```html
<gradio-lite>
<gradio-file name="app.py" entrypoint>
fn=lambda x: x,
inputs="text",
outputs="text"
)
demo.launch()
</gradio-file>
</gradio-lite>
```
This PR fixes it.
> Fix the Lite custom element parser so it doesn't add the .code option when the entrypoint file is already specified

- .changeset/flat-planets-love.md
- gradio/pipelines_utils.py
During #8052, I found something.
---
Reference: [first commit of `from_pipeline`](https://github.com/gradio-app/gradio/commit/c2f081e5bf7da7158ed92a2998df81fc61dbb4c3#diff-275f9a5e534203c28d9c5f44db604c6d0aa108005e22a118a8873a3c4af66d38)
> Fix `gr.Interface.from_pipeline()` to allow audio uploads and to display classification labels correctly

- .changeset/puny-sites-marry.md
- gradio/helpers.py
Closes: https://github.com/gradio-app/gradio/issues/8017
Repro:
```py
import os
os.environ["GRADIO_CACHE_EXAMPLES"] = "lazy"
text = gr.Textbox()
out = gr.Textbox()
gr.Examples(examples=["aaa", "bbb"], inputs=text)
demo.launch()
```
which would previously throw an error
@hysts would appreciate if you can confirm the fix for ZeroGPU Spaces
> Fix `GRADIO_CACHE_EXAMPLES` environment variable to only take effect if `fn` and `outputs` parameters are provided

- .changeset/purple-radios-marry.md
- gradio/components/login_button.py
- gradio/processing_utils.py
- test/test_pipelines.py
When using "Sign in with HF", the server returns an OAuth token that is limited in time. Currently we pass the `expires_at` value to the gradio functions but it's useless as it means Space authors have to deal with it (which is undocumented anyway). The problem with expired tokens been passed to functions is that it leads to HTTP errors when making calls to the Hub. These errors are annoying both for Space authors and users as they can't do much about them. The current solution is for the user to logout + login again.
This PR changes this workflow. Now on every page load/refresh (i.e. with `LoginButton.attach_load_event(..., None)`) we check if the user has an outdated session (based on `expires_at` attribute). If yes, then we delete the session cookie and display a `"Sign in with HF"` …
> [HF OAuth] Logout user if oauth token has expired

- .changeset/loud-ears-grab.md
- js/audio/shared/WaveformControls.svelte
The scrollable styling in the `WaveformControls` component was introduced in #6991 which is great,
but in some environments the scroll bars are displayed in any time which can be visually annoying.
For example, on Mac, when the "Show scroll bars" setting is not "When scrolling",
the scroll bars are always shown like this even when scrolling is not necessary.
So in this PR,
* Disable the vertical scroll bar which is always not necessary.
* Set narrower width as a break point to show the horizontal scroll bar. I set the breakpoint as 319px, assuming the narrowest width of popular smartphones are 320px and there is an enough margin between it and the max width with which the scroll bar becomes necessary.
Before your create a PR, please check to see if there is [an existing …
> Hide the scroll bar in WaveformControls when it's not necessary

- .changeset/rotten-pears-pay.md
- gradio/blocks.py
- gradio/chat_interface.py
- gradio/interface.py
I tried to use this parameter and was confused on how to set it up. Thanks @dawoodkhan82 @pngwn for clarifying, I've carried over your comments to the docstrings here.
> improve the documentation for `js` parameter in `Blocks`, `Interface`, `ChatInterface`

- .changeset/great-plants-deny.md
- .gitignore
- gradio/route_utils.py
- gradio/routes.py
Being able to pull the session_hash has come up twice recently: the command+R demo and I personally wanted build a demo where I use the session hash to save some files to disk and then clean them up with `unload`. To get the session hash, you have to use `await request.body()` which is not ideal since you'd have to make your handler async and it's also not clear you have to parse the body to get the session hash.
I think this should make it easier in the future for others.
1. PRs will only be …
> Add session hash to gr request

- .changeset/puny-queens-clean.md
- js/_website/src/routes/custom-components/gallery/+page.svelte
- js/_website/src/routes/custom-components/gallery/utils.ts
- pnpm-lock.yaml
Added a `Share` button to the custom component card that copies a link to your clipboard that you can use to open the gallery to that component. 
> Be able to link to a custom component in the gallery directly

- .changeset/metal-doodles-grow.md
- gradio/cli/commands/components/_create_utils.py
> Allow users to template the `ImageEditor` when using custom components

- .changeset/mean-coins-push.md
- gradio/analytics.py
- gradio/cli/commands/components/build.py
- gradio/cli/commands/components/create.py
- gradio/cli/commands/components/dev.py
- gradio/cli/commands/components/docs.py
- gradio/cli/commands/components/publish.py
- gradio/cli/commands/components/show.py
- pnpm-lock.yaml
> Add Analytics for custom components

- .changeset/rich-bikes-crash.md
- js/app/src/Blocks.svelte
Background: https://github.com/gradio-app/gradio/pull/8041#issuecomment-2059945536
When an error occurs for example at the `/info` endpoint, the frontend app silently crashes which is confusing,
because [an error from `Client.submit`](https://github.com/gradio-app/gradio/blob/487db7b5d57e1a1350494efdf37c121cbf627780/client/js/src/utils/submit.ts#L48-L49) is not caught to show the message toast.
Sample code:
```python
import numpy as np
inp = gr.JSON(
value=np.array([1, 2, 3])
)
out = gr.JSON()
btn = gr.Button("Submit")
btn.click(lambda x: x, inp, out)
demo.launch()
```
While the exact error occurring in the examle above will be fixed in #8041 on the server side, these should be such an error handler on the frontend for potential similar …
> Cache an error from app.submit() and show it on frontend

- .changeset/slick-buses-bake.md
- .github/workflows/publish.yml
We have a slight issue with the build caching, we only cache the frontend dir in the templates but the build also build multiple packages that we need to publish. Ideally we would have more granular caching. For now I've just added the preview build in a different step because it is very fast anyway.
Closes: #8138 
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) …
> ensure @gradio/preview dist files are published

- guides/09_other-tutorials/developing-faster-with-reload-mode.md
Changes this line: `gradio run.py my_demo` to include the flag --demo_name. Running the gradio command without the flag would typically yield this error for me: Got unexpected extra argument [insert demo name]
Closes: N/A
Super small change :)
> add flag for hot reload example

- .changeset/four-crabs-rescue.md
- guides/05_custom-components/05_frontend.md
- guides/05_custom-components/07_pdf-component-example.md
- guides/05_custom-components/08_multimodal-chatbot-part1.md
- js/_website/package.json
- js/_website/src/routes/[[version]]/guides/[guide]/+page.server.ts
- pnpm-lock.yaml
The guide for tailwind left out a few details for example that tailwindcss 4.0-alpha has to be used. This makes the instructions a bit more verbose
> Make guide for tailwind more verbose

- .changeset/icy-otters-stand.md
- gradio/routes.py
Setting an ETag in the response of `/custom_component` that's equal to the hash of the requested file. I think this is preferable than setting a `max-age` because it should minimize the chance of a stale cache. During development, it's possible to build frequently to see if latest changes work outside the development server ( I do that atleast) so the `max-age` would be hard to set in this case.
Closes: #8168 
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up …
> Add ETag to `/custom_component` route to control browser caching

- .changeset/public-falcons-float.md
- js/_website/package.json
- js/preview/test/test/frontend/package.json
- pnpm-lock.yaml
Uses workspace for @gradio/code in the _website package.json instead of a pinned version. Removes the circular import from js/preview/test/test/frontend that was causing the issue. Also changes the version of postcss to use pnpm 9.0.0
> Use workspace version for code in _website

- .changeset/slow-bats-sniff.md
- gradio/http_server.py
- gradio/routes.py
- gradio/utils.py
- js/app/src/Blocks.svelte
- js/app/src/Index.svelte
Let clients know when an error happened during reload. Also refactored the route to support more than one client connecting simultaneously.
Logic is here and should not conflict with #8056 but will wait for #8056
There are two message types in the thread `reload` and `error`.
Edit: also errors are shown in the UI now
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) …
> Pass Error status in /dev/reload stream

- .changeset/major-zoos-read.md
- gradio/utils.py
Add a conditional to run reload only on python files.
Closes: #8192
Targets issue #8192
> run python reload only if python file changed

- .changeset/cold-spies-fail.md
- gradio/blocks.py
- gradio/cli/commands/reload.py
* Handle SIGINT correctly in reload.py, to prevent gradio-cli exit when subprocess running 
* Make sure there is only a single entrance of block_thread in blocks.py
Closes: #8157
> fix: handling SIGINT correctly in reload.py, single entrance of block_thread in blocks.py

- .changeset/gentle-berries-fetch.md
- gradio/analytics.py
- scripts/run_lite.sh
- test/test_analytics.py
> Refactor analytics to not use api.gradio.app

- .changeset/shiny-toes-beam.md
- js/wasm/src/webworker/index.ts
> Specify the fastapi version on Lite to avoid ujson installation which is not available on Pyodide yet

- .changeset/cruel-cars-think.md
- gradio/blocks.py
Hide the "Use via API" link on Lite, which doesn't make sense in Lite env.
<table>
<tr>
<th> <code>main</code> </th>
<th>this PR</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> Set the show_api flag on Lite

- .changeset/gold-frogs-sniff.md
- client/js/src/client.ts
The old event source logic was mistakenly added back in in #8181. This removes that.
> remove redundant event source logic

- .changeset/polite-lamps-burn.md
- client/js/src/client.ts
- client/js/src/helpers/init_helpers.ts
- client/js/src/types.ts
- gradio/blocks.py
Closes: #8022 
Rather than always connecting to the heartbeat route, we should do so only when gr.State variables are used (to clean up state) or when the `unload` event is set. Users may still run into the browser limit, however. 
EDIT: I originally wanted to raise an error or message when the page locked up due to the connection limit. But the browser will block all requests after the limit is reached so we won't be able to fetch the config and progressively load the app.
1. PRs will only be …
> Only connect to heartbeat if needed

- .changeset/social-tigers-lie.md
- gradio/blocks.py
- test/test_blocks.py
Small PR that fixes: https://github.com/gradio-app/gradio/issues/8164
> Allow Spaces with `.success()` to be `gr.load`-ed

- .changeset/upset-lands-add.md
- .github/workflows/tests-js.yml
- client/js/src/client.ts
- client/js/src/test/mock_eventsource.ts
- client/js/src/test/stream.test.ts
- client/js/src/utils/stream.ts
- client/js/src/utils/submit.ts
- js/app/src/lite/index.ts
- js/audio/Index.svelte
- js/audio/interactive/InteractiveAudio.svelte
- js/dataframe/Index.svelte
- js/dataframe/shared/Table.svelte
- js/file/Index.svelte
- js/file/shared/FileUpload.svelte
- js/gallery/Index.svelte
- js/image/Index.svelte
- js/image/shared/ImageUploader.svelte
- js/imageeditor/Index.svelte
- js/imageeditor/shared/InteractiveImageEditor.svelte
- js/imageeditor/shared/tools/Sources.svelte
- js/model3D/Index.svelte
- js/model3D/shared/Model3DUpload.svelte
- js/multimodaltextbox/Index.svelte
- js/multimodaltextbox/shared/MultimodalTextbox.svelte
- js/simpleimage/Index.svelte
- js/simpleimage/shared/ImageUploader.svelte
- js/upload/src/Upload.svelte
- js/upload/src/UploadProgress.svelte
- js/video/Index.svelte
- js/video/shared/InteractiveVideo.svelte
Fixes the client in node, we just needed to await the module as it was trying to be used prior to the module being loaded.
I also had to change some things to async because of this change.
I also noticed that the `stream` rename in a previous PR actually renamed an internal method to stream, so I renamed `stream_handler` to `stream` as well.
Closes: #8213 …
> Client node fix

- .changeset/fruity-books-win.md
- gradio/chat_interface.py
- gradio/interface.py
- guides/04_chatbots/01_creating-a-chatbot-fast.md
A few small changes in this PR:
1. First, adds `examples_per_page` to `gr.ChatInterface`, closes: https://github.com/gradio-app/gradio/issues/8233. My original plan had been to add support for providing an instance of `gr.Examples` but this does not really make sense since a user can't provide the correct `fn` to `examples` since the example function is redefined internally. We also have the same `examples_per_page` argument in `gr.Interface`
2. I went through the arguments of `gr.Interface` to make sure that we have equivalent arguments in `gr.ChatInterface` and made a few other small tweaks, such as allowing `clear_btn` in `gr.Interface` to be set to `None` hiding it, similar to how the buttons in `gr.ChatInterface`. I believe there was an issue about this that we closed
3. Adds some …
> Adds `examples_per_page` to `gr.ChatInterface` and allows `clear_btn` in `gr.Interface` to be hidden

- guides/08_gradio-clients-and-lite/06_gradio-lite-and-transformers-js.md
Currently the embedded `<gradio-lite>` apps in the docs are broken.
Context: https://huggingface.slack.com/archives/C055NMB0S87/p1715007103672639
> Delete embedded Lite apps in the doc

- .changeset/tidy-groups-lose.md
- js/statustracker/static/index.svelte
Closes: #8250 
I removed the `pointer-events: none` in #7909 so that users can close the error modal but this caused #8250. 
My fix was to apply `pointer-events: none` when the component is generating. …
> Fix bug where status tracker was the target of pointer events

- .changeset/khaki-toys-hammer.md
- guides/08_gradio-clients-and-lite/06_gradio-lite-and-transformers-js.md
- js/_website/src/routes/[[version]]/guides/[guide]/+page.server.ts
Restore the in-page Lite examples deleted in #8232
Preview page: https://gradio-6np8jo72s-hugging-face.vercel.app/main/guides/gradio-lite-and-transformers-js
> Embedded Lite example apps in the docs

- .changeset/red-bottles-brake.md
- gradio/blocks.py
- gradio/events.py
- gradio/queueing.py
- gradio/routes.py
- gradio/utils.py
- test/test_blocks.py
If a job is cancelled, the server and the client will keep the `/queue/data` stream open forever.
Notice that in the first image, the multiple heartbeats gets sent after the job is cancelled (indicating the channel was kept open for at least 45 seconds post cancellation) while in the second message the process_completed and close_stream messages are sent after cancellation. This was tested on the `fake_diffusion` demo.
1. PRs will only be merged if tests pass on CI. To run the tests locally, please …
> Send ProcessCompleted message when job is cancelled

- .changeset/strong-cases-study.md
- guides/06_custom-components/06_frequently-asked-questions.md
- js/app/src/Index.svelte
- js/statustracker/static/index.svelte
Adds a link to the troubleshooting guide in the loading text of the custom component index page. That way, if something goes wrong during the dev command, developers can get to the troubleshooting tips from their app. …
> Link to troubleshooting guide in the custom component loading status

- .changeset/gentle-socks-pay.md
- gradio/components/base.py
- gradio/components/json_component.py
- gradio/data_classes.py
- gradio/helpers.py
- gradio/processing_utils.py
- test/components/test_json.py
- test/test_helpers.py
- test/test_processing_utils.py
* Makes sure json component outputs do not get moved to cache
* `EventData` instances must only reference data in the cache
> Ensure JSON component outputs handled properly in postprocess

- guides/06_custom-components/01_custom-components-in-five-minutes.md
- Added pip 21.3+ requirement to be able to build from pyproject.toml otherwise get errors of this type:
```
👷 Installing python... (/my/path/.venv/bin/pip3 install -e testcomponent[dev])                                                                           │
│ 🟥 Python installation failed                                                                                                                                                                                  │
│ ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /my/path/gradio-components/testcomponent              │
│ (A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.) 
```
> Update custom component installation requirements

- client/js/src/utils/submit.ts
When sending requests to a ZeroGPU endpoint via the JS client on node, the client would attempt to index `window` while getting credentials, causing an error. The logic has been changed to prefer the `hf_token`, falling back to the `post_message` if the `window` is available, and finally falling back to `null`.
I have not included an issue due to the size of the PR, as per the PR template, but will add if needed!
> Fix zero gpu auth ignoring hf_token

- .changeset/light-rats-exist.md
- js/file/shared/FilePreview.svelte
the select event shouldn't be triggering on any of the files, but it did because of some dom-bubbling and svelte lifecycle
just adding the key to the each fixes that issue by ensuring the element is removed,
added additional checks just to be sure and so that e.g. clicking the download like doesn't trigger select
Closes: #8268
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRI …
> fix: prevent triggering gr.File.select on delete

- .changeset/tall-suits-train.md
- js/markdown/shared/MarkdownCode.svelte
- js/markdown/shared/utils.ts
Closes: #8309
You can verify this works by templating off of DataFrame or Chatbot and making the following modifications to `@gradio/markdown` in node_modules.
> Fix Chatbot, Dataframe, Markdown custom components

- .changeset/sixty-horses-tell.md
- client/js/src/helpers/data.ts
- client/js/src/test/data.test.ts
The `walk_and_store_blobs` function was ignoring blobs that were directly inside of arrays such as `[blob]` due to the `map` using the blob value as the key, rather than the index.
Closes: #7778
> ensure the client correctly handles all binary data

- .changeset/dark-streets-visit.md
- gradio/route_utils.py
I've tested and this fixes the issue that @hannahblair I identified. I don't think this introduces any security risk based on my mental model (as long as the origins are trusted, we do indeed want to pass on cookies and authorization headers).
> Add allow-credentials to preflight header

- .changeset/poor-roses-wait.md
- client/python/gradio_client/client.py
- client/python/test/test_client.py
> Set orig_name in python client file uploads

- .changeset/ripe-tools-jam.md
- client/python/gradio_client/client.py
- gradio/blocks.py
- gradio/utils.py
Closes #8384 
Fixes the linked issue specific reload mode. But the equality check for state, basically `current_state != old_state` would throw an error for some types like numpy/dataframe. So proposing a function to handle that case.
2. You may need to run the …
> Fix bug in reload mode equality check. Better equality conversion for state variables

- .changeset/easy-trains-obey.md
- client/js/src/client.ts
- client/js/src/utils/submit.ts
- gradio/blocks.py
- gradio/utils.py
Noticed a bug where the heartbeat was not established if a state variable was created in a render.
In the process of fixing that, I noticed that components were not being removed from the old config. The rendered_in key is in props, not the top level component config. …
> Connect heartbeat if state created in render. Also fix config cleanup bug #8407

- js/app/test/render_merge.spec.ts
Render test was flaky because sometimes it would start editing a component while it was being re-rendered. Edited the test to start editing the last component in a render first, which ensures the render is complete before starting to edit.
> Fix flaky render test

- gradio/routes.py
`gradio/routes.py`
```python
if key not in app.custom_component_hashes:
app.custom_component_hashes[key] = hashlib.md5(
Path(path).read_text().encode()
).hexdigest()
```
Change `Path(path).read_text().encode()` to `Path(path).read_text(encoding="utf-8").encode()` to support custom components with i18n code.
Closes: #8426
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING …
> Fix encoding error in gradio/routes.py

- .changeset/breezy-bottles-hide.md
- gradio/events.py
- gradio/renderable.py
I noticed two things that were off about the type hints for on and render
- We were using `Any` for the triggers of `gr.on`. Which was too broad.
- In `render`, the triggers were not typed correctly so passing a valid trigger, e.g. `slider.change` would be flagged in vs code. 
- In `render`, the type hint did not allow for a single component to be passed as input, but it is allowed.
**Main**
**PR**
Invalid value for `triggers` of `gr.on` is flagged
Passing an event listener method for `render` is not flagged
Not adhering to this guideline will result in the PR …
> Fix type hints for render and on

- .changeset/early-files-allow.md
- js/_website/src/lib/templates/python-client/gradio_client/01_introduction.svx
- js/_website/src/routes/[[version]]/docs/js-client/+page.svelte
- js/_website/src/routes/[[version]]/docs/python-client/[doc]/+page.svelte
Now the pages are: 
title: Gradio Python Client -  Introduction Docs 
description: Make programmatic requests to Gradio applications from Python environments.
title: Gradio Python Client -  Client Class Docs 
description: Using the Client Class in the Gradio Python Client
> Tweak meta titles and descriptions for clients

- .changeset/crazy-turtles-sing.md
- client/python/gradio_client/client.py
- client/python/test/test_client.py
- test/test_external.py
Some Client tests were failing because we now require `handle_file()`.
And https://huggingface.co/osanseviero/BigGAN-deep-128 no longer has an Inference API for some reason so I've just removed those tests
> fix client flaky tests

- .changeset/long-tables-guess.md
- js/_website/src/routes/redirects.js
- js/upload/package.json
- pnpm-lock.yaml
For some reason key features guide was redirected to queuing guide by mistake. Removes that line
Also fixes dependency loop with @gradio/upload https://github.com/gradio-app/gradio/actions/runs/9410901936/job/25923318456
> Remove broken guide redirect

- .changeset/pretty-clowns-fall.md
- gradio/blocks.py
- test/test_interfaces.py
Closes: #8425
Test with the following demo:
```python
hello_world = gr.Interface(lambda name: "Hello " + name, "text", "text")
bye_world = gr.Interface(lambda name: "Bye " + name, "text", "text")
demo = gr.TabbedInterface([hello_world, bye_world], ["Hello World", "Bye World"])
demo.launch()
``` …
> Fixes TabbedInterface bug where only first interface events get triggered

- .changeset/tired-dryers-retire.md
- client/js/README.md
Adds `handle_file` documentation to the client README.
Closes: #8476.
> add handle_file docs

- .changeset/tangy-moose-check.md
- gradio/components/file.py
According to docs, Parameter `file_count` of `File` component must be one of them(`single, multiple, directory`). But I put other integer value(ex. `file_count=0`) in the parameter by mistake, below error occurs.
```zsh
Traceback (most recent call last):
File "/Users/zedd.ai/.pyenv/versions/3.10.12/envs/gradio-pr/lib/python3.10/site-packages/gradio/queueing.py", line 532, in process_events
response = await route_utils.call_process_api(
File "/Users/zedd.ai/.pyenv/versions/3.10.12/envs/gradio-pr/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
output = await app.get_blocks().process_api(
File "/Users/zedd.ai/.pyenv/versions/3.10.12/envs/gradio-pr/lib/python3.10/site-packages/gradio/blocks.py", line 1924, in process_api
inputs = await self.preprocess_data( …
```
> feat: exception handling about file_count params of File component

- .changeset/dull-lizards-suffer.md
- gradio/data_classes.py
- test/test_routes.py
This commit addresses a serialization issue in the `PredictBody` model that has been present since version 4.0. The `request` attribute, being of type `Request`, could not be serialized automatically, affecting FastAPI's auto-generated documentation (/openapi.json).
By adding a custom `__get_pydantic_json_schema__` method, the serialization schema is manually defined, ensuring correct documentation generation.
This is also one of the reasons why applications like "stable-diffusion-webui," which require /docs pages, have not updated to newer versions of Gradio.
Closes: #7287
> Fix request serialization for fastapi `/docs`

- .changeset/neat-roses-tan.md
- client/js/src/helpers/api_info.ts
- client/js/src/types.ts
- client/js/src/utils/submit.ts
- gradio/exceptions.py
- gradio/helpers.py
- gradio/queueing.py
- gradio/routes.py
- gradio/server_messages.py
- gradio/utils.py
- js/_website/src/lib/assets/style.css
- js/_website/src/lib/templates/gradio/05_modals/error.svx
- js/_website/src/lib/templates/gradio/05_modals/info.svx
- js/_website/src/lib/templates/gradio/05_modals/warning.svx
- js/app/src/Blocks.svelte
- js/statustracker/static/Toast.svelte
- js/statustracker/static/ToastContent.svelte
- js/statustracker/static/types.ts
Adds `duration` property to `gr.Warning`, `gr.Info`, and `gr.Error`.
Setting `duration` to 0 not display the toast in the UI. This is useful for giving useful error messages for clients. For example, the data validation done in the component classes can now raise `gr.Error` instead of `TypeError` or `ValueError` and clients will see the exact error message.
The `duration` parameter is specified in seconds. If it's `None`, the toast will be displayed indefinitely.
Closes: https://github.com/gradio-app/gradio/issues/6480
```python
from functools import partial
with gr.Row():
duration = gr.Number(label="Duration", info="Set to -1 for infinite", value=10, minimum=-1)
with gr.Row():
error = gr.Button("Error")
info = gr.Button("Info")
warning = …
```
> Control Display of Error, Info, Warning

- .changeset/true-places-post.md
- gradio/helpers.py
- js/_website/generate_jsons/generate.py
- js/_website/generate_jsons/src/docs/__init__.py
- js/_website/src/lib/components/DocsNav.svelte
- js/_website/src/lib/components/EventListeners.svelte
- js/_website/src/lib/components/FunctionDoc.svelte
- js/_website/src/lib/components/Header.svelte
- js/_website/src/lib/components/ParamTable.svelte
- js/_website/src/routes/[[version]]/docs/+layout.server.ts
- js/_website/src/routes/[[version]]/docs/gradio/[doc]/+page.svelte
- js/_website/src/routes/[[version]]/docs/js-client/+page.server.ts
- js/_website/src/routes/[[version]]/docs/js-client/+page.svelte
- js/_website/src/routes/[[version]]/docs/python-client/[doc]/+page.svelte
- scripts/upload_website_demos.py
Makes a lot of small fixes to the docs that have been requested: 
- changes banner to remove the livestream date 
- replaces Sequence with list as a preprocessing step on all parameter docs 
- fixes capitlization issues with functions names on the docs navbar, and shows correct names for components (ImageEditor not Imageeditor) 
-  removes fake_gan as a demo for gr.Examples, and replaces it with calculator_blocks
- adds respective install from main commands for the python client and js client pages 
- fixes the upload_website_demos script to only update versioned demos when a new version is released and not on every commit
> Many small fixes to website and docs

- .changeset/slick-ducks-fry.md
- gradio/cli/commands/components/build.py
- js/preview/src/build.ts
- js/preview/src/dev.ts
- pnpm-lock.yaml
> Fix custom components on windows

- .changeset/red-rice-build.md
- client/js/src/client.ts
- js/app/test/test_chatinterface.reload.spec.ts
Reload mode would break because the heartbeat could not be closed - 
You can test by with a stateful demo like ChatInterface
> Fix reload mode by implementing `close` on the client

- .changeset/red-badgers-sip.md
- gradio/routes.py
Trying to fix the bug related to `favicon_path` which doesn't seem to work when using it as a path for `gradio.mount_gradio_app` and FastAPI.
I've made the appropriate changes as suggested by @freddyaboulton on the issue:
"""
It would be here:
https://github.com/gradio-app/gradio/blob/94a1143686733c7fe16e204764b9a3e7240ccf02/gradio/routes.py#L1222
We want to output a warning if `favicon_path` is not `None` and the `path` is not `/`
"""
Closes: #8137 
1. PRs will only be merged if tests pass on CI. …
> Fixes the `favicon_path` working error

- .changeset/soft-worms-remain.md
- gradio/blocks.py
- gradio/components/dataset.py
- gradio/flagging.py
- gradio/helpers.py
- gradio/utils.py
- js/_website/src/lib/templates/gradio/03_components/dataset.svx
- js/dataset/Index.svelte
- test/components/test_dataset.py
- test/test_blocks.py
Allows the samples in a `gr.Dataset` to be updated. Here's a quick example:
```py
def update(value):
print(value)
return value, gr.Dataset(samples=[["a"],["b"]])
with gr.Row():
textbox = gr.Textbox()
dataset = gr.Dataset(components = ["text"], samples = [["This"]], label="Saved Prompts")
dataset.click(update, inputs=[dataset], outputs=[textbox, dataset])
demo.launch()
```
Closes: https://github.com/gradio-app/gradio/issues/8312
Closes: https://github.com/gradio-app/gradio/issues/7282
Closes: https://github.com/gradio-app/gradio/issues/6415
Also fixes the issue where clearing an `Interface` that included a `Dataset` would cause the Interface to crash. 
Closes: https://github.com/gradio-app/gradio/issues/6807
> fix dataset update

- .changeset/quick-dolls-admire.md
- gradio/blocks.py
- test/test_external.py
Closes: https://github.com/gradio-app/gradio/issues/7996. Now both of these work:
```py
gr.load("abidlabs/en2fr", src="spaces").launch()
```
and 
```py
gr.load("abidlabs/en2fr", src="spaces")
demo.launch()
```
> Allow `gr.load` to work inside `gr.Blocks` automatically

- .changeset/fifty-peaches-hug.md
- gradio/components/multimodal_textbox.py
- js/icons/src/Send.svelte
- js/multimodaltextbox/shared/MultimodalTextbox.svelte
There was too much spacing before between the attach button and the textbox. Also looked in the file and we were using absolute positioning as well as percents for padding - should avoid both of these.
> Fix multimodal chat look

- .changeset/five-bags-dress.md
- js/_website/src/routes/[[version]]/guides/[guide]/+page.svelte
tiny fix that's been annoying me for a while. On guides without headings, there's no need to show a headings section under the guide name in the sidebar. 
vs
> Small fix to guide styling

- .changeset/fifty-books-fly.md
- gradio/analytics.py
Fix to the issue: "You are using gradio version" should be a warning #8595 
Closes: #8595 
> Changed gradio version check from print statement to warning

- .changeset/few-camels-swim.md
- js/plot/shared/plot_types/AltairPlot.svelte
when using altair with gr.Plot, the resizer is not guaranteed to work. It only works when using native plots (`gr.LinePlot`, `gr.BarPlot`, `gr.ScatterPlot`). Made it so resizing logic only applies when the chart type is provided, meaning this is a native plot.
test with `altair_plot` and `native_plots` demos/
> Fix resizer on altair

- .changeset/wild-cases-obey.md
- js/_website/src/lib/templates/gradio/03_components/annotatedimage.svx
- js/_website/src/lib/templates/gradio/03_components/audio.svx
Fixes the problems with [Audio](http://localhost:5173/main/docs/gradio/audio) and [AnnotatedImage](http://localhost:5173/main/docs/gradio/annotatedimage) component demos.
> Fix CORS issues with Lite Component Demos

- .changeset/light-gifts-pull.md
- gradio/components/code.py
- js/code/shared/Download.svelte
- js/code/shared/language.ts
Adding c/cpp support to `gr.Code.languages`
Closes: #8584
c code example!
> Add c/cpp code support

- guides/03_additional-features/05_progress-bars.md
Tiny fix to the name of the Progress Bars guide in the gallery and navbar.
> Fix Progress Bars Guide Name

- .changeset/chubby-spiders-love.md
- gradio/blocks.py
Allowing Falsy auth credentials will cause problems later, for example in `hmac.compare_digest(input_password.encode(), correct_password.encode())` as NoneType has no `encode` method. Moreover, allowing empty passwords would make no sense from a security point of view.
Let me know if any changes are required.
> Warn against Falsy credentials

- .changeset/witty-pugs-beg.md
- client/js/src/types.ts
- globals.d.ts
- gradio/blocks.py
- gradio/data_classes.py
- gradio/external.py
- gradio/route_utils.py
- gradio/routes.py
- gradio/utils.py
- guides/08_gradio-clients-and-lite/01_getting-started-with-the-python-client.md
- guides/08_gradio-clients-and-lite/02_getting-started-with-the-js-client.md
- js/app/src/Blocks.svelte
- js/app/src/Index.svelte
- js/app/src/api_docs/ApiDocs.svelte
- js/app/src/api_docs/CodeSnippet.svelte
- js/app/src/api_docs/RecordingSnippet.svelte
This PR does a few different things:
* In the Client Guides, it includes sections explaining how to connect to a Gradio app with `auth`
* In the view API page, if you look at the sample code with the clients, it includes the `auth` parameter if the gradio app includes auth
Closes: #8700 
* It also adds typing for the `Blocks.config` attribute in the backend. I believe should be good to closes: https://github.com/gradio-app/gradio/issues/2376, because (1) the information that the original user was asking for is already available in the `/info` route, in the `.view_api()` method, and in the view API page / docs. (2) in terms of documenting the /config route, I don't think it makes sense to add to our docs / guide, but now we at least have a well-defined typeddict that we point users to.
> Documents auth in the guides, in the view API page, and also types the Blocks.config object 

- .changeset/sad-suits-burn.md
- gradio/cli/commands/components/_create_utils.py
- gradio/utils.py
- test/test_gradio_component_cli.py
> Fix multimodal textbox custom components

- .changeset/three-eyes-know.md
- gradio/components/plot.py
Context: #8770
`gr.Plot` renders the plot before encoding it in `postprocess` by using `matplotlib`,
but the installed version of it in Wasm (3.5.2) doesn't support the `webp` format which is the default of the component. So use `png` as the default instead in Wasm.
`webp` itself is a good default for speed in general: https://github.com/gradio-app/gradio/pull/7845#issuecomment-2050668343
> Set the default format of gr.Plot as png for Wasm mode

- .changeset/silver-emus-attend.md
- js/imageeditor/shared/tools/Brush.svelte
Fixes #6611.
This can be tested with the following reproduction:
```py
img = gr.ImageEditor(
brush=gr.Brush(
default_color="rgb(200, 200, 200)",
colors=["rgb(200, 200, 200)"],
color_mode="fixed",
),
interactive=True,
)
change_color = gr.Button(
value="Change color",
)
change_color.click(
fn=lambda: gr.update(
brush=gr.Brush(default_color="rgb(0, 0, 0)", colors=["rgb(0, 0, 0)"])
),
inputs=None,
outputs=img,
)
demo.launch(height=1024)
```
This does nothing on main but works in this PR.
> Ensure `ImageEditor` brush color can be updated with `gr.update`

- .changeset/full-hats-hunt.md
- js/app/src/lite/Playground.svelte
- js/code/shared/Code.svelte
* Use `BaseCode` instead of `Code` which made the code simpler getting rid of `dummy_*` variables.
* Fixes [this issue](https://github.com/gradio-app/gradio/pull/7660#discussion_r1530483279) in e5dff89
* Attach the KeyDown event listener only to the DOM element inside the `<Playground />` component instead of searching all DOMs from the page so that "ctrl+Enter" key-down in a specific playground element in a page only triggers rerunning of that component, avoiding affecting other embedded playgrounds: a2eac0b
> Fix Lite's <Playground />

- .changeset/cyan-cycles-yawn.md
- gradio/components/audio.py
- gradio/components/video.py
- gradio/templates.py
- js/audio/Index.svelte
- js/audio/interactive/InteractiveAudio.svelte
- js/audio/player/AudioPlayer.svelte
- js/audio/static/StaticAudio.svelte
- js/video/Example.svelte
- js/video/Index.svelte
- js/video/shared/InteractiveVideo.svelte
- js/video/shared/Player.svelte
- js/video/shared/Video.svelte
- js/video/shared/VideoPreview.svelte
- test/components/test_audio.py
- test/components/test_video.py
Quick PR for https://github.com/gradio-app/gradio/issues/8805 and https://github.com/gradio-app/gradio/issues/7689 (which has quite a bit of interest)
```py
gr.Audio("https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav", loop=True)
demo.launch()
```
```py
gr.Video("https://github.com/gradio-app/gradio/raw/main/demo/video_component/files/world.mp4", loop=True)
demo.launch()
```
Closes: https://github.com/gradio-app/gradio/issues/8805, Closes: https://github.com/gradio-app/gradio/issues/7689
> Add `loop` parameters to `gr.Audio` and `gr.Video`

- .changeset/swift-ghosts-spend.md
- js/statustracker/package.json
- js/statustracker/static/ToastContent.svelte
- pnpm-lock.yaml
There's a dependency loop introduced by https://github.com/gradio-app/gradio/pull/8817 where statustracker imports markdown which imports statustracker. 
This PR implements https://github.com/gradio-app/gradio/pull/8817 without using markdown.
> Fix dependency loop with statustracker and markdown 

- .changeset/all-beds-design.md
- js/_website/src/lib/templates/gradio/03_components/datetime.svx
Not sure how this happened but the svx file for datetime references textbox instead. 
Closes: #8793
> Fix DateTime docs

- .changeset/huge-pears-like.md
- js/_website/src/routes/[[version]]/docs/gradio/[doc]/+page.svelte
What's happening is paramviewer's styling references css variables defined in the gradio theme, which is not on the page. The simplest fix i could think of was to just import the stylesheet from here: https://gradio-hello-world.hf.space/theme.css
I already do that for lite demos on the website. Which is why you'll only see this error when directly navigating to a page without demos or embedded components, for example: https://www.gradio.app/docs/gradio/render
> Fix param table rendering 

- .changeset/nasty-clowns-show.md
- .github/workflows/deploy-website.yml
- js/_website/generate_jsons/generate.py
- js/app/vite.config.ts
There is a discrepancy between the version formatting for pre-released which is causing an issue with the build for lite.
- js: `<x.y.z>-<beta|alpha>-<n>` eg: `5.0.0-beta.0`
- python: `<x.y.x><b|a><n>` eg: `5.0.0b0`
This just reformats for lite. This is tested for the v5 branch, if CI here is good I'll merge.
> Fix build for pre-release

- .changeset/huge-donuts-draw.md
- js/markdown/shared/MarkdownCode.svelte
- js/markdown/shared/utils.ts
Fixes how latex is rendered. there was an issue where the markdown parser would apply its rules to latex equations which would cause rendering issues.
Closes: #8780 …
> Latex Rendering Fix

- .changeset/cool-buckets-notice.md
- js/_website/src/lib/components/DemosLite.svelte
Adds a confirmation dialogue before leaving the Playground if there are changes to a demo. 
https://github.com/user-attachments/assets/97964249-2aba-4439-8937-6216cc9ec3d4
cc @apolinario 
Closes: #6588
> Add confirmation dialogue if leaving playground 

- scripts/helpers.sh
Appears that the given pnpm link no longer exists. Suggesting a more generic one.
To get version 7.x, users will need to do the follow (for example, for version 7.1.0): 
`curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION="7.1.0" sh -`
But the gradio error I get suggests it should be ~9.1.0, which would be:
`curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION="9.1.0" sh -`
not sure how you want to handle that.
> pnpm link deprecated

- .changeset/tame-clouds-draw.md
- gradio/route_utils.py
Making `update_root_in_config` atomic is better from a security perspective. @aliabid94 could you check if this has any performance-related implications?
> Make `update_root_in_config` atomic

- .changeset/common-poets-retire.md
- js/multimodaltextbox/Example.svelte
- js/multimodaltextbox/package.json
- pnpm-lock.yaml
Fixes issue with image examples being too big. Also adds support for video and audio in `multimodaltextbox` examples, instead of just showing the filepath.
Main:
This PR:
Closes: #8834 …
> Fix Chatbot Multimodal Examples

- .changeset/rude-women-fly.md
- js/utils/src/utils.ts
Fixes 
```
Could not resolve "virtual:component-loader"
node_modules/@gradio/utils/src/utils.ts:237:10:
237 │       import("virtual:component-loader").then((module) ...
╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~
You can mark the path "virtual:component-loader" as external to
exclude it from the bundle, which will remove this error and leave
the unresolved path in the bundle. You can also add ".catch()" here
to handle this failure at run-time instead of bundle-time.
```
which occurs when installing any gradio component with the newest version from npm in a typescript svelte project.
This bug prevents us from switching from an old version of @gradio/audio from 0.11.4 to 0.13.0 and of @gradio/atoms from 0.7.3 to 0.7.7.
> Fix `Could not resolve "virtual:component-loader"` in gradio/utils package

- .changeset/chilly-boxes-build.md
- js/json/shared/JSON.svelte
- js/json/shared/JSONNode.svelte
Add `overflow: wrap` to catch any overflow in gr.JSON when the device is extra small. 
Thanks for the catch @freddyaboulton!
> Add `overflow: wrap` to JSON to catch overflow in xs device widths 

- .changeset/common-otters-dream.md
- js/code/shared/Copy.svelte
- js/icons/src/Check.svelte
- js/icons/src/Copy.svelte
- js/json/shared/JSON.svelte
Fixes the check icon in gr.Code and gr.JSON
Before 🐛 
After
Note, I've made the check icon 1px thinner because I think that better matches the copy icon it goes with, and other icons we have. 
Closes: #8915 …
> Fix check icon in gr.JSON and gr.Code

- .changeset/small-coins-rescue.md
- gradio/oauth.py
- gradio/route_utils.py
In https://github.com/gradio-app/gradio/issues/8660, @abidlabs reported some issues when trying to debug locally a Gradio app that uses OAuth. Since "official" OAuth cannot be done locally (redirect to localhost is forbidden), we use fake data based on the user access token from the machine. This PR fixes 2 things:
- `expires_at` was set to a constant value in the past which was automatically logging out the user
- `Obj` class (used for `session`) did not implement `pop` which was causing a failure [here](https://github.com/gradio-app/gradio/blob/d1f044145ae93e5838042d9fb25f4f17def9c774/gradio/components/login_button.py#L108)
Copy this snippet in an `app.py` and run it:
```py
from huggingface_hub import list_models
def hello(profile: gr.OAuthProfile | None) -> str:
if …
```
> Fix running local app with fake OAuth

- .changeset/five-crabs-listen.md
- client/python/requirements.txt
gradio-client has had a pinned version maximum for websockets of 12.0 that was created before websockets 12.0 was released.
websockets 12.0 has since been released, and the only backwards-incompatible change was ending support for python 3.7, which gradio-client and gradio don't support anymore either. 
To keep with the spirit of the original file, I've bumped up the version requirement to 13.0, which may in the future present other breaking changes.
> Bump websockets version max for gradio-client

- .changeset/hungry-tips-sin.md
- gradio/blocks.py
- gradio/route_utils.py
- gradio/routes.py
- test/test_routes.py
Added tests to ensure that CSRF attacks cannot happen. To test this change with regards to embedding, create a Gradio app, and then embed it with web components in a static file. Follow these steps:
1. create a gradio app:
```py
gr.Interface(lambda x:x, "text", "text").launch(strict_cors=False)
```
2. create an index.html file with
```
<script
type="module"
src="https://gradio.s3-us-west-2.amazonaws.com/4.40.0/gradio.js"
></script>
<gradio-app src="http://localhost:7860"></gradio-app>
```
If you open the file in a browser, the embedded app should work as long as you include the `strict_cors=False` parameter above.
> Adds `strict_cors` parameter to `launch()`

- guides/04_additional-features/08_environment-variables.md
Per ToB's recommendation, adds information about `FORWARDED_ALLOW_IPS` environment variable
> Add information about `FORWARDED_ALLOW_IPS` environment variable

- .changeset/eager-roses-throw.md
- gradio/networking.py
This has been fixed in https://github.com/gradio-app/gradio/pull/7707, but it seems it has been reintroduced during some other code changes/refactoring.
Closes: #8671 …
> fix: httpx timeouts cause gradio to fail during launch

- guides/08_gradio-clients-and-lite/01_getting-started-with-the-python-client.md
- guides/08_gradio-clients-and-lite/02_getting-started-with-the-js-client.md
- guides/08_gradio-clients-and-lite/07_fastapi-app-with-the-gradio-client.md
Updated examples in documentation for Gradio python and js clients to replace deprecated file() function by handle_file() in order to make usage and comprehension clearer.
Fixed also a small synthax typo. …
> Update gradio clients documentation examples for file handling

- gradio/blocks.py
- gradio/component_meta.py
- gradio/helpers.py
Adds missing typing to some exported definitions from `gradio/helpers.py`, `gradio/blocks.py` as well as stub files generated by `INTERFACE_TEMPLATE` from `gradio/component_meta.py`
Closes: #8928
> fix insufficient typing of event listeners

- .github/workflows/previews-deploy.yml
- .github/workflows/storybook-deploy.yml
- package.json
> Ci security tweaks take seventy three

- .github/workflows/website-deploy.yml
Fixes problem with production website thinking its on a bumped version that hasn't been released yet. 
Checks that `needs.changes.outputs.source_branch` == 'refs/heads/main'.
> Fix production website deploy action to only deploy from main 

- .changeset/better-results-try.md
- gradio/flagging.py
> Catch OSErrors in `HuggingFaceDatasetSaver._deserialize_components`

- .changeset/ripe-aliens-invent.md
- gradio/blocks.py
- gradio/component_meta.py
This adds more typing definitions that I forgot to add in https://github.com/gradio-app/gradio/pull/8983
Closes: #8928
> Add more typing to event listeners

- .changeset/every-parks-count.md
- gradio/cli/commands/components/build.py
- gradio/cli/commands/components/install_component.py
> Set non-zero exit codes for custom component build and install commands when failures occur

- gradio/events.py
If you have a demo like this:
```python
a = gr.Number(1)
b = gr.Number(1)
c = gr.Number()
@gr.on(inputs=[a,b], outputs=c)
def add(x,y):
return x + y
demo.launch()
```
c will only be set to the value of a + b when they change, not initially when the demo runs. Usually users would want the initial value to also be a function of the inputs (when no trigger is specified).
This is also consistent with the behaviour of gr.render and value=fn, e.g. both of these would set c to 2 intitially:
```python
a = gr.Number(1)
b = gr.Number(1)
@gr.render(inputs=[a, b])
def renderfn(x, y):
gr.Number(x + y)
demo.launch()
```
```python
a = gr.Number(1)
b = gr.Number(1)
c = gr.Number(lambda x, y: x + y, inputs=[a, b])
demo.launch() …
```
> Have gr.on set value at start as well

- .github/actions/install-all-deps/action.yml
- .github/actions/install-frontend-deps/action.yml
- .github/workflows/delete-stale-spaces.yml
- .github/workflows/publish.yml
- .github/workflows/storybook-deploy.yml
- .github/workflows/test-hygiene.yml
Of the following actions:
- dorny/paths-filter@v3 
- FedericoCarboni/setup-ffmpeg@v2 
- pnpm/action-setup@v2 
- chromaui/action@v11 
- changesets/action@v1 
- actionsdesk/lfs-warning@v3.3
We no longer use:
- dorny/paths-filter@v3 
The others have been pinned tot he appropriate SHA with a comment detailing the version tag it corresponds to. Gradio specific or official github actions have been left as they are.
The delete stale space workflow has also been tweaked to circumvent potential command injection attacks.
> CI dependency hardening

- .changeset/petite-animals-raise.md
- js/dataset/Index.svelte
Resets the page of the Dataset component to page 0 when the samples change, preventing issues like this: https://github.com/gradio-app/gradio/issues/9083
Closes: https://github.com/gradio-app/gradio/issues/9083
> Reset `Dataset` page to 0 when samples change

- .changeset/wise-sites-learn.md
- js/_website/src/lib/assets/style.css
Some content on the docs has weird spacing, like https://www.gradio.app/docs/gradio/chatbot cc @freddyaboulton 
Just adds margin and increases the font 
Before             |  After
:-------------------------:|:-------------------------:
We can change it up more if this isn't good
> Better text styling on docs

- .github/actions/install-all-deps/action.yml
- .github/workflows/delete-stale-spaces.yml
- .github/workflows/previews-build.yml
- .github/workflows/test-python.yml
In order to upgrade our codebase to use Python 3.10, I'd like to first get in this PR which sets CI to use Python 3.10. This will make it easier to test any changes I make in https://github.com/gradio-app/gradio/pull/9129
> Upgrade CI to use Python 3.10

- .changeset/olive-loops-look.md
- gradio/route_utils.py
- test/test_routes.py
Closes: https://github.com/gradio-app/gradio/issues/8844. So the underlying issue is that the `fastapi.Request` class is not pickleable. Making it pickleable is tricky because it contains lots of attributes that are custom classes, which themselves are not serializeable. So what I've done here is extract the main attributes that we mention in our docs are users are likely using and ensured that they are preserved when the `gr.Request` object is picked and unpickled. I've added unit tests to confirm this. @hysts, quick favor -- if you have a chance to test on ZeroGPU directly, that'd be awesome.
> Allow `gr.Request` to work with ZeroGPU

- .changeset/legal-donkeys-accept.md
- gradio/routes.py
- test/test_routes.py
We made a change the all `file=` endpoints loaded as attachments. However, it is fine to allow all media types (except SVG, which could contain JS) to load in the browser. This PR makes that change. 
Closes: https://github.com/gradio-app/gradio/issues/9137
> Open media type files in browser

- .github/actions/install-all-deps/action.yml
Should keep the cache between main and 5.0-dev separate
> Set python version in CI cache key

- package.json
- scripts/build_lite.sh
- scripts/run_lite.sh
Based on #9163. 
This PR updates `scripts/*_lite.sh` to run with the changes by #9163.
> Fix scripts/run_lite.sh and scripts/build_lite.sh

- .changeset/dirty-pugs-hunt.md
- gradio/networking.py
- gradio/strings.py
- gradio/tunneling.py
The FRP tunnel that we use when `share=True` is now encrypted with TLS! To review this PR, you can do a few things:
1. Try creating a share link, it should work in the same way as before:
```py
demo = gr.Interface(lambda x:x, "image", "image")
demo.launch(share=True)
```
(Probably good to try a few different demos)
2. Confirm that the FRP tunnel link has TLS enabled. Run from Terminal:
```
openssl s_client -connect gradio-live.com:7000
```
3. If you want, you can modify the root certificate that is download from the Gradio API server and confirm that this does not let you create a share link anymore. For example, you could modify this line:
https://github.com/gradio-app/gradio/blob/11f9edac7663eba35109df900170c4c9d99121a4/gradio/networking.py#L35
to be e.g.
```py …
```
> Adds TLS to FRP tunnel

- .changeset/eighty-jeans-unite.md
- gradio/component_meta.py
Sometimes the `read_text()` call in `create_or_modify_pyi` will not use expected encoding when reading the `source_file`. 
This will declare the encoding that `read_text` is supposed to use. It is reading files that are encoded in 'utf-8'. Windows seems to sometimes default to 'CP-1252', but not always. Issue was not present when tested in Unix. I think it is safer to explicitly declare the encoding to be 'utf-8' since the gradio source files that are being read are encoded in 'utf-8'.
Closes: #8316 and Closes: #9241
> Fix for create_or_modify_pyi read_text Windows Issue in component_meta.py

- .changeset/few-clowns-notice.md
- gradio/components/button.py
- gradio/components/duplicate_button.py
- gradio/components/login_button.py
- js/button/shared/Button.svelte
For more consistency with HF Hub branding, this PR adds a "huggingface" button variant, and makes it the default for `gr.LoginButton`
Here are the "primary", "secondary", and "clear" variants:
Compare with HF Hub branding: https://huggingface.co/docs/hub/en/oauth#branding
Closes: https://github.com/gradio-app/gradio/issues/5628
wdyt @hannahblair @Wauplin @gary149 @julien-c
> Adds a "huggingface" button variant, and makes it the default for `gr.LoginButton` and `gr.DuplicateButton`

- .changeset/seven-deer-occur.md
- gradio/tunneling.py
Context: [internal conversation](https://huggingface.slack.com/archives/C06V0AAK7QB/p1725461274060749)
> Raise error instead of warning if checksums for binary do not match

- .changeset/tall-maps-relate.md
- requirements.txt
Fairly certain the latest `fastapi` release is broken, pinning to any earlier version for now
Closes: https://github.com/gradio-app/gradio/issues/9275
> Pin `fastapi<0.113.0` in `requirements.txt`

- .changeset/sad-chicken-sleep.md
- js/image/shared/Webcam.svelte
Recent changes to the Square icon accidentally changed the color of the webcam stop recording button.
Before
After
> Fix stop recording button colors

- .changeset/warm-lemons-mate.md
- js/icons/src/Square.svelte
- js/multimodaltextbox/shared/MultimodalTextbox.svelte
- js/textbox/shared/Textbox.svelte
Modify textbox stop button styling to match that the submit button. Happy to tweak further.
> Match style of textbox stop button to submit button

- .changeset/warm-impalas-turn.md
- js/json/Index.svelte
- js/json/shared/JSON.svelte
In the JSON component we added scrollbars to all .blocks, adding scrollbars everywhere. So if any component had a JSON component, we got scrollbars everywhere. Removed this CSS.
> Fix scrollbars everywhere

- .changeset/rich-plants-sneeze.md
- gradio/blocks.py
- test/test_blocks.py
> Add root_url to components created by gr.render

- .changeset/blue-rooms-run.md
- js/audio/interactive/InteractiveAudio.svelte
- js/audio/recorder/AudioRecorder.svelte
- js/core/src/Blocks.svelte
Closes: #9180
Changes the audio component so that multiple events are not triggered but also fixed the bigger issue that the app was not respecting `trigger_mode` if the function ran `js` …
> Fix multiple trigger bug when function has js

- .changeset/khaki-ducks-stare.md
- gradio/components/chatbot.py
> Dont move files to cache automatically in chatbot postprocess

- .changeset/cute-rules-write.md
- gradio/routes.py
- requirements.txt
`importlib_resources` is not needed anymore since `importlib.resources.files` exists in Python 3.10 and higher: https://docs.python.org/3.10/library/importlib.html?highlight=importlib#importlib.resources.files
`urllib3` is only needed in Gradio-lite so I've updated the requirements.txt accordingly
> Remove two dependencies: `importlib_resources` and `urllib3` (if not in Wasm)

- .changeset/floppy-keys-heal.md
- gradio/tunneling.py
Fix mistake from https://github.com/gradio-app/gradio/commit/6309a48e3a89a13137ec9d61c1c722eb59b8e3dc#diff-26073d5b5461562f83e4f50470636e2d595c5dd03c9b5223efb59575645e7eb2L72 that  would prevent frpc from being downloaded
> Fix typo in `tunneling.py`

- .changeset/breezy-olives-wonder.md
- js/chatbot/shared/ChatBot.svelte
- js/chatbot/shared/MessageBox.svelte
A small tweak, as I was testing the ability to show "thoughts" in `gr.Chatbot`: now accordions will shown expanded if they are the last message in the Chatbot history:
```py
import time
thought = "I need to use the weather API tool"
def return_thought():
value = [{"role": "user", "content": "What is the weather in San Francisco?"}]
value += [{"role": "assistant", "content": "", "metadata": {"title":  "🧠 Thinking"}}]
for i in range(len(thought)):
value[-1]["content"] = thought[:i+1]
time.sleep(0.02)
yield value
value += [{"role": "assistant", "content": "85 degrees"}]
value += [{"role": "user", "content": "What is the weather in Miami?"}]
yield value
value += [{"role": "assistant", "content": "", "metadata": {"title":  "🧠 Thinking"}}]
for i in range(len(thought)): …
```
> Small tweak to how thoughts are shown in `gr.Chatbot`

- .changeset/tough-rooms-flash.md
- js/multimodaltextbox/shared/MultimodalTextbox.svelte
Seems like `file_types` was broken completely for `multimodaltextbox`. 
Would be nice to see if this also fixes the issue on Windows @yvrjsharma.
Also noticed dragging and dropping is broken for multimodaltextbox. Opened an issue here: 9392
Closes: #8801
2. You may …
> Fix File Types for MultimodalTextbox

- demo/hello_blocks/run.py
- demo/hello_world/run.py
- gradio/blocks.py
- gradio/node_server.py
- gradio/routes.py
- gradio/strings.py
Makes the two changes I suggested on the SSR PR:
(1) Renames `spa_mode` to `ssr_mode` 
(2) Moves the parameter to `launch()`, which means that it can be used with Interface, ChatInterface, Blocks, etc. Also added to `gr.mount_gradio_app`, meaning it can be used when Gradio is part of larger FastAPI apps
> Tweaks to SSR mode

- .changeset/cruel-heads-hunt.md
- js/button/Button.stories.svelte
- js/button/shared/Button.svelte
Small design issue, but when an icon was present in a button and no text was present, the icon would be off-centered due to right padding. This PR closes: https://github.com/gradio-app/gradio/issues/9352
To repro, just run something like:
```py
gr.Button(icon="cheetah.jpg", min_width=0)
gr.Button(icon="cheetah.jpg", value="", min_width=0)
demo.launch()
```
and view on a mobile / small width
> Center icon in button when no text is present

- test/test_routes.py
Ok so we have several issues going on when you mount a Gradio app inside of another FastAPI app:
* For some reason, the FastAPI TestClient is not able to successfully GET the `/` route of the mounted Gradio app, even though its accessible using the browser. I think its because the TestClient doesn't run JS the same way that a browser does, leading to this error:
```
Error: Error: Could not resolve app config. 
at Client._resolve_config (file:///Users/abidlabs/dev/gradio-repos/gradio/gradio/templates/node/build/server/chunks/2-C2y--WlB.js:10583:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Client.init (file:///Users/abidlabs/dev/gradio-repos/gradio/gradio/templates/node/build/server/chunks/2-C2y--WlB.js:10499:5)
at async Client.connect …
```
> Fix Python unit tests on `5.0-dev` branch

- .changeset/stupid-tires-stare.md
- gradio/routes.py
- test/test_routes.py
In `gr.mount_gradio_app`, we made a mistake setting the `ssr_mode` flag, since `bool("False")` is `True`, this was causing tests to fail. I've fixed the change and reverted the changes I made to the tests earlier in https://github.com/gradio-app/gradio/pull/9432
> Fix SSR mode flag with `mount_gradio_app` and revert changes to pytests 

- .changeset/khaki-ways-agree.md
- gradio/themes/base.py
- js/slider/Index.svelte
Tiny fix to ensure the custom `slider-color` var is respected. 
> Fix `slider-color` var

- .changeset/thin-boxes-matter.md
- gradio/blocks.py
- gradio/node_server.py
- gradio/routes.py
Previously, the `ssr_mode` parameter was not working unless the GRADIO_SERVER_NAME parameter was also set. You can test this by running 
```py
demo = gr.Interface(lambda x: x, "text", "text")
demo.launch(ssr_mode=True)
```
which would produce a stacktrace:
```py
* Running on local URL:  http://127.0.0.1:7872/, with SSR ⚡
[Errno 8] nodename nor servname provided, or not known
[Errno 8] nodename nor servname provided, or not known
[Errno 8] nodename nor servname provided, or not known
[Errno 8] nodename nor servname provided, or not known
[Errno 8] nodename nor servname provided, or not known
```
With this PR, SSR mode should work correctly
> Fix node process to run with correct server name

- .changeset/wicked-snails-drum.md
- js/dropdown/shared/Dropdown.svelte
- js/radio/Index.svelte
Fixes: gr.Dropdown and gr.Radio fire `.change()` events when page loads.
Closes: #9492
> Fix change triggers for dropdown and radio

- .changeset/smooth-places-walk.md
- js/dropdown/Index.svelte
- js/dropdown/dropdown.test.ts
- js/dropdown/shared/Dropdown.svelte
- js/dropdown/shared/Multiselect.svelte
`gr.Dropdown(multiselect=False)` sets the default value as `[]` of type `list`. It's a confusing behavior.
The fix is in a04ad54 where the default value is changed from `[]` to `undefined`.
As a result, the following `value` initializer that seems to have not been reached before became effective and the first item of `choices` is now set as the default value.
https://github.com/gradio-app/gradio/blob/0ab6ac5dc01b69e4f2462d00c4910f3354441227/js/dropdown/shared/Dropdown.svelte#L59-L65
I think
* setting a list value `[]` as the default value of a single-select dropdown is obviously a bug.
* but setting the first value of `choices` instead of `None` is an opinionated behavior, while I think it's desirable as the user can eliminate the null-checking from the user-defined `fn`. If it's a …
> Fix single select dropdown

- .changeset/tall-impalas-reply.md
- js/_website/generate_jsons/generate.py
- js/_website/src/lib/components/Demos.svelte
- js/_website/src/lib/components/DemosLite.svelte
- js/_website/src/routes/+layout.svelte
- js/_website/src/routes/playground/+page.svelte
Mirrors what we did for 5.0-dev: uses the latest lite wheel that represents main to show demos on the website and playground.
> Use latest lite wheel on website

- .changeset/chilly-dragons-smoke.md
- gradio/layouts/form.py
- js/column/Index.svelte
- js/row/Index.svelte
Allows columns to have expanding content in "equal_height" rows, e.g.:
```python
with gr.Row(equal_height=True):
with gr.Column(scale=2):
gr.Dropdown(choices=['a', 'b', 'c'], interactive=True)
gr.Button("Btn 1")
gr.Button("Btn 2")
with gr.Column(scale=2):
gr.Slider(interactive=True)
gr.Button("Btn 3")
gr.Image()
demo.launch()
```
Fixes: #3202
> Equal height columns

- .changeset/smooth-fans-hide.md
- js/multimodaltextbox/shared/MultimodalTextbox.svelte
- js/textbox/shared/Textbox.svelte
Suggestion: the submit button and the Enter-key submit should be disabled when the text is empty. I felt weird when using `gr.ChatInterface` where I could submit empty chat texts.
> Disable the submit button and enter-key submit when the text is empty

- .changeset/easy-snakes-arrive.md
- gradio/interface.py
- gradio/layouts/row.py
- guides/03_building-with-blocks/02_controlling-layout.md
Makes equal height false by default in rows:
```python
with gr.Row():
name = gr.Dropdown(["Alice", "Bob", "Charlie"], label="Name")
output = gr.Textbox(label="Output Box")
greet_btn = gr.Button("Greet")
```
before:
after:
> Equal height in row false by default

- .config/playwright-setup.js
- .github/workflows/test-functional.yml
> Fix e2e test bug

- .changeset/heavy-memes-create.md
- js/dataframe/shared/CellMenu.svelte
- js/dataframe/shared/Table.svelte
Context menu button now shows when you click on a cell (same for mobile). Context menus when clicking on headers will also only show add column options (not add row options) …
> Tweak gr.Dataframe menu UX

- .changeset/thick-teeth-crash.md
- client/python/gradio_client/utils.py
In the case the user specifies a file extension in `file_types`, we don't need to guess the mime type of the allowed file (which causes errors on unconventional file extensions). Instead, we can just check if the file extensions match.
Closes: #9646
2. You may need …
> Fix: `file_types` checking bug

- .changeset/khaki-sites-bow.md
- gradio/helpers.py
- gradio/queueing.py
- Fix to make progress bar compatiable with generators
Closes: #3841
There's no attribute `__len__` in generators, and even when users explicitly set the `total` argument, it defaults to None, preventing proper functionality with generators.
So we will use `total` as `length` if the object has no attribute `__len__`. 
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md …
> Fix progress bar compatibility with generators

- .changeset/calm-emus-post.md
- gradio/themes/base.py
Restores the ability to set the light / dark theme via:
- embedding attribute <gradio-app theme="dark">
- url param "http://localhost:7860/?__theme=dark"
> Restore light/dark custom setting

- js/dropdown/dropdown.test.ts
[My previous PR](https://github.com/gradio-app/gradio/pull/9699) that set the default value of the Dropdown to the be first choice in the backend (as opposed to the frontend) broke several js unit tests. This fixes them, so the js tests should now all pass.
> Fix js unit tests

- .changeset/calm-roses-suffer.md
- js/wasm/src/webworker/index.ts
- requirements.txt
* Starlette was updated in https://github.com/gradio-app/gradio/pull/9712 but installing the pinned version causes an error on Lite. `requirements.txt` is fixed.
* Also deleted out-of-date package installations in `webworker/index.ts`.
Resolves #9721
> Fix Lite dependencies

- .changeset/stale-jobs-reply.md
- gradio/themes/base.py
There was a CSS syntax error in the theme creation script, an extra curly brace was being added.
Fixes the failing storybook build.
> fix css syntax error

- .changeset/hot-dancers-drop.md
- js/atoms/package.json
- js/build/out/index.js
- js/build/src/index.ts
- js/markdown/package.json
- js/markdown/shared/MarkdownCode.svelte
- js/sanitize/browser.ts
- js/sanitize/index.d.ts
- js/sanitize/package.json
- js/sanitize/server.ts
- pnpm-lock.yaml
@gradio/markdown is not a dependency of @gradio/atoms so dev/build was broken for components that used them.
The `sanitize-html` library cannot be imported in the browser I think (uses `require` and has no export named `default`). I tried messing with `optimizeDeps` in the component config but it didn't work. So just changing the code in MarkdownCode to defer the import. …
> Custom component fixes

- README.md
- client/python/README.md
- guides/01_getting-started/01_quickstart.md
- guides/09_gradio-clients-and-lite/01_getting-started-with-the-python-client.md
- guides/10_other-tutorials/installing-gradio-in-a-virtual-environment.md
This pull request adds a note regarding an issue with the latest Python version (3.13) in the prerequisites. It doesn't close the issue but serves as a temporary notice while we work on the fix.
Related to:  #9696 
🎯 PRs Should Target Issues
Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small.
Not adhering to this guideline will result in the PR being closed.
Tests
PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: bash scripts/run_all_tests.sh
You may need to run the …
> Update prerequisite note to mention python 3.13 issue

- .changeset/honest-forks-pay.md
- js/preview/src/index.ts
This feature can help users receive more informative messages when running 'gradio cc dev' in case of network issues
In WSL2, accessing the localhost at 127.0.0.1 may result in a hang due to network isolation between WSL2 and the Windows host. As a result, using the 'is_free_port' function to check ports can lead to a blocking state.
> Add a port timeout detection feature for gradio/preview. 

- .changeset/chatty-pants-check.md
- client/python/gradio_client/client.py
If the Gradio server says there are Too Many Requests, I think it be best to acknowledge it and not immediatly try to make another request again.
Does not affect the `self.src_prefixed` which still may not have been declared.
Closes: #9683
> Update client.py: raise error on 429 get_config

- .changeset/happy-lies-study.md
- gradio/blocks.py
- test/test_blocks.py
Validator was not handling situation where function does not return anything.
Checks whether the unexpected value is None, and if so, assumes it is safe to ignore.
Closes: #9742  …
> Fixes #9742

- .changeset/busy-lions-pull.md
- js/upload/src/Upload.svelte
gr.Image() had broken select listener. Was due to Upload button appearing on top of image so it was preventing pointer events, because display:flex was overrriding display:none of Upload.svelte. Rearranged css rules so flex is overriden by none.
Fixes: #9182
Wanted to add a functional test but seems like we already have one in [fix_image_select/js/spa/test/image_component_events.spec.ts#L129 ](https://vscode.dev/github/gradio-app/gradio/blob/fix_image_select/js/spa/test/image_component_events.spec.ts#L129), unfortunately seems like playwright clicks through the upload.
> Fix broken image select

- build_pypi.sh
Cut down pypi storage in half by not uploading the source distribution. People can get the source distribution from github tagged releases. Not sure of any unintended breaking "changes" though. Maybe people who use `pip install --no-binary`. But not sure why they would do that. …
> Only publish wheel to pypi

- .changeset/salty-showers-study.md
- js/plot/shared/Plot.svelte
If a non-native plot was changed, there was a bit of a stutter between loading plots, as shown with the demo below:
```python
import plotly.express as px
import numpy as np
df = pd.DataFrame(
{
"Year": [2020, 2021, 2022, 2023, 2024, 2025] * 3,
"State": ["NY"] * 6 + ["CA"] * 6 + ["TX"] * 6,
"Value": np.random.randint(1, 100, 18),
}
)
def manually_animated_choropleth(year):
_df = df[df["Year"] == year]
fig = px.choropleth(
data_frame=_df,
locations="State",
locationmode="USA-states",
color="Value",
color_continuous_scale="Viridis",
scope="usa",
)
return fig
year = gr.Slider(minimum=2020, maximum=2025, step=1, label="Year")
chloropleth_map = gr.Plot()
demo.load(
manually_animated_choropleth,
inputs=[year], …
```
> Allow smoother plot changes

- .changeset/warm-roses-begin.md
- requirements.txt
Closes: #9774
Looks like it's a problem on `micropip` that the yanked version is installed (I raised a ticket: https://github.com/pyodide/micropip/issues/146). For now we need to exclude the version explicitly.
> Exclude python-multipart 0.0.13

- .changeset/odd-wolves-taste.md
- client/js/src/helpers/api_info.ts
- client/js/src/helpers/init_helpers.ts
- client/js/src/test/api_info.test.ts
It is possible to be using a subpath URL even when hosting on spaces which the client doesn't currently take into account. I have tweaked the client to support this.
This is what was breaking our demo space.
> support gradio apps on spaces served on subpaths

- .changeset/legal-months-speak.md
- js/_website/src/lib/components/DemosLite.svelte
The tab names are now "undefined".
Related to https://github.com/gradio-app/gradio/pull/9653/files#diff-e0279a31c4775aa9eedbbd4c28688d756f12f301651723b02c39e9521951766c
> Fix the tab names in the playground

- .changeset/tame-grapes-look.md
- gradio/node_server.py
- guides/04_additional-features/09_environment-variables.md
On spaces we set `GRADIO_NUM_PORTS` to `1` and a specific port. This make sense because we need to run gradio on that port for it to be accessible.
However, the node server is reusing this variable which can be problematic if multiple gradio applications are being spun up in the same space. Every app needs it own node server, but only ever 1 publicly accessible URL. 
The current demos 'work' right now but you'll actually notice that only the first one is being SSRed, the others are falling back to the SPA because it could not find a port (because the limit of 1 had been exhausted).
This PR introduces a separate env variable to control how many node ports we should limit ourselves to, defaulting to 100, like before. 
This should address this issue and out demo spaces should all correctly …
> use different env var for node port range

- .github/actions/install-frontend-deps/action.yml
- gradio/external.py
Adds a `user_provides_token` parameter to `gr.load` that creates a `Textbox` where a user can provide their own API token. This should be hopefully encourage api developers to create Gradio demos very easily and share them with other collaborators or on Spaces without the developer needing to hardcode a token.
Here's example usage:
```py
import sambanova_gradio
gr.load("Meta-Llama-3.1-70B-Instruct-8k", src=sambanova_gradio.registry, accept_token=True).launch()
```
https://github.com/user-attachments/assets/d1a79b3b-8e71-4531-93f3-2a5b2d23939e
cc @AK391 @yvrjsharma. Uses `@gr.render` under the hood -- very cool @aliabid94!
> Allow accepting user-provided-tokens in `gr.load`

- .changeset/thick-hounds-press.md
- js/datetime/Index.svelte
When using `gr.DateTime` with `include_time=False`, the frontend code creates a new `Date` object out of the chosen date string.
There is a discrepancy in the way date-only and date-time strings are dealt with in JS by the `Date` constructor, which causes the date string to be interpreted as if it specified a time in the UTC timezone ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format:~:text=When%20the%20time%20zone%20offset%20is%20absent%2C%20date%2Donly%20forms%20are%20interpreted%20as%20a%20UTC%20time%20and%20date%2Dtime%20forms%20are%20interpreted%20as%20a%20local%20time.%20The%20interpretation%20as%20a%20UTC%20time%20is%20due%20to%20a%20historical%20spec%20error%20that%20was%20not%20consistent%20with%20ISO%208601%20bu …
> fix: use system timezone in gr.DateTime with include_time=False

- .changeset/cyan-lights-sleep.md
- requirements.txt
Just pins python-multipart to 0.0.12 to avoid issues with yanked versions
> Pin multipart version to fix issues with yanking

- .changeset/clear-falcons-lose.md
- js/multimodaltextbox/Example.svelte
- js/simpletextbox/Example.svelte
- js/textbox/Example.svelte
This PR fixes a bug where some styling was not applied to example textboxes on render if they were initially invisible.
Specifically, the `white-space` css property was not being set due to the component having no width on rendering.
The fix is to not return from `set_styles()` if `el_width` is undefined (or 0) but instead to handle that case in the ternary operator where `el_width` is used. As `set_styles()` is called in `onMount()` and `el` is bound to the html element, which at this point in the lifecycle is guaranteed to be mounted, the check for `element` being undefined is not necessary.
Closes: #9830
> Fix a bug in example textbox rendering when it is initially invisible

- .github/actions/install-frontend-deps/action.yml
The built LIte cache should be purged when `requirements.txt` is changed.
Context: https://huggingface.slack.com/archives/C055NMB0S87/p1729832794471549?thread_ts=1729810407.444559&cid=C055NMB0S87
> Add requirements.txt to the gradio-lib-front-end-lite cache key

- .changeset/long-wolves-serve.md
- gradio/external.py
The current logic for fetching the config in `gr.load` fails if the app is SSR'd as `window.gradio_config` is not in the page. So made some modifications to fetch from the `/config` route if it exists and fallback to `window.gradio_config` if it fails.
Test with `gr.load("gradio/calculator", src="spaces")`
1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run …
> Fix Loading SSR'd apps via gr.load

- .changeset/tidy-bikes-allow.md
- js/textbox/shared/Textbox.svelte
This PR resolves the issue with the misplaced/invisible copy button in the gr.Textbox component when show_copy_button=True. The button was previously positioned inside the textarea, leading to improper alignment and invisibility.
Main changes include:
- Added a new wrapper <div class="textbox-container"> to give the copy button a separate positioning context.
- Moved the copy button outside of the input/textarea container for better alignment.
- Removed the copy button from within the textarea section to prevent overlap.
- Updated styles to adjust positioning and styling:
Closes: #9569
Thank you for considering this fix! I appreciate your time and look forward to your feedback.
> Fix: Resolve copy button visibility issue in Textbox component

- .changeset/beige-badgers-argue.md
- gradio/events.py
- gradio/layouts/accordion.py
- js/accordion/Index.svelte
- js/accordion/shared/Accordion.svelte
This PR was produced via programmatic use of `aider` + a lot of human intervention. More details available [internally](https://huggingface.slack.com/archives/C02SPHC1KD1/p1730334560275149)
Test with:
```py
with gr.Accordion("See Details") as accordion:
gr.Markdown("lorem ipsum")
t = gr.Textbox()
accordion.expand(lambda: "Accordion is expanded", None, t)
accordion.collapse(lambda: "Accordion is collapsed", None, t)
demo.launch()
```
Closes: https://github.com/gradio-app/gradio/issues/5197
> Adds `.expand()` and `.collapse()` events to `gr.Accordion`

- .changeset/slow-baboons-report.md
- js/chatbot/shared/Message.svelte
> Make sure the Tool accordion is closed if it is not the last message

- .changeset/empty-monkeys-do.md
- js/atoms/src/IconButton.svelte
- js/file/shared/FileUpload.svelte
- js/upload/src/Upload.svelte
Allows us to upload more files after already uploading files to the File component via an upload icon in the icon button wrapper. 
Closes: #9860
> Allow uploading more files in gr.File

- .changeset/social-terms-type.md
- js/dataframe/shared/VirtualTable.svelte
Closes: https://github.com/gradio-app/gradio/issues/9288
As far as I can tell, removing this line resolves the issue and does not have any side effects, whether in SSR mode or not.
> Fix dataframe height increasing on scroll

- .changeset/four-swans-throw.md
- gradio/blocks.py
- gradio/data_classes.py
- gradio/processing_utils.py
- test/test_routes.py
If a component expects a FileData from a client, then the request payload should contain the `meta` key.
> Enforce `meta` key present during preprocess in FileData payloads

- .changeset/breezy-ants-count.md
- gradio/components/checkboxgroup.py
- test/components/test_checkbox_group.py
This PR improves the error message in `preprocess` function of `gradio.components.checkboxgroup.CheckboxGroup` class by:
- Using `repr` instead of `str` representation which can be helpful in cases where `str` representation is ambiguous e.g. "1" vs 1 (see the linked issue for a detailed use-case.)
- Including type information in the error message.
Additionally, I have updated the tests in`test/components/test_checkbox_group.py` to test specifically for this ambiguous case.
Closes: #9902 
1. PRs …
> Clearer error message in CheckboxGroup's preprocess function

- CONTRIBUTING.md
Cloning this repository, then building & running scripts, can run into the issue of `import gradio` in python pulling `gradio` in from somewhere else (such as the virtual environment). To address this, users need to tell python where to look in order to use the cloned git repo for `gradio`.
Further details in https://huggingface.slack.com/archives/C02SPHC1KD1/p1731207233633159?thread_ts=1731206608.882719&cid=C02SPHC1KD1 for more
Closes: [#9924](https://github.com/gradio-app/gradio/issues/9924)
> Explain that PYTHONPATH must be updated

- demo/random_demos.py
1. Removes assumption/requirement that the script is run specifically in the demo/ directory.
2. Removes assumption/requirement that there are 3 unwanted large demos that should be removed.  (Note: currently, of the 3 demo directories that are hardcoded, the `.gradio/flagged` demo isn't there, so the code will throw an error even if the first issue is addressed.)
Closes: [#9926](https://github.com/gradio-app/gradio/issues/9926)
> Fix random_demos.py ValueError issues

- .changeset/nice-rice-smash.md
- js/file/shared/FileUpload.svelte
- js/multimodaltextbox/MultimodalTextbox.stories.svelte
- js/multimodaltextbox/shared/MultimodalTextbox.svelte
Prevents users from attempting to upload additional files when file_count="single" by hiding the upload button once a file is uploaded
```py
demo = gr.Interface(lambda x:x,
gr.MultimodalTextbox(file_count="single", value="Test"),
gr.MultimodalTextbox()
)
demo.launch()
```
Closes: https://github.com/gradio-app/gradio/issues/9922
Closes: https://github.com/gradio-app/gradio/pull/9891#issuecomment-2469493872
cc @spaceman-cb
> Hide upload button after upload when `file_count="single"`

- .changeset/smart-houses-deny.md
- client/js/src/client.ts
- client/js/src/helpers/init_helpers.ts
- client/js/src/types.ts
When using the javascript client, allow setting custom HTTP headers on `Client.connect`.
Note that this is already implemented for client/python by #7334
Usage example:
```js
const client = Client.connect(url,
headers: {'ngrok-skip-browser-warning': 'true'}
})
```
Closes: #9929
Closes: #7833
I didn't add any new test, since I couldn't find any other test using `fetch`
> Allow settings custom headers in js client

- .changeset/eighty-turtles-accept.md
- js/dataframe/shared/Table.svelte
I'm not 100% sure why the wrap CSS was fixed to no-wrap beforehand; it makes sense to allow the wrap to me. 
Closes: #9937
> Allow dataframe column content to wrap

- .changeset/purple-bugs-see.md
- gradio/blocks.py
Found that `run_extra_startup_events` is not called in the Lite env.
Closes: https://github.com/gradio-app/gradio/issues/9491
> Call `run_extra_startup_events` in Lite

- .changeset/large-words-happen.md
- gradio/blocks.py
Pyright complains about the type of `gr.launch` being partially unknown:
I am not sure exactly why but it seems that pyright does not recognize definitions that are imported and subsequently used like this
```python
from gradio import routes
...
routes.App
````
The issue can be solved by importing the definitions and using them like
```python
from routes import App 
...
App
```
It should be mentioned that this is only an issue when using gradio (or any other package I assume) as a library in another application. Pyright has no problem (at least for me) recognizing the current importing scheme when working directly inside the gradio project.
If you know of a better solution to this problem I can implement that instead. I just do not know any other way to fix this problem currently 😄 …
> fix typing of launcher function

- .changeset/tender-seals-kiss.md
- gradio/chat_interface.py
- test/test_chat_interface.py
Adds `api_name` parameter to ChatInterface to let developers set api_name=False or change the name of the api route.
Closes: #10047
2. Please run these bash scripts to automatically format your code: `bash …
> Add api_name for ChatInterface

- .changeset/real-words-listen.md
- gradio/helpers.py
- test/test_helpers.py
If one component does not have example values, then you get an out of index error when loading the example value because the data loaded from the dataset component has a different length than `self.input_has_examples`
See [context](https://huggingface.slack.com/archives/C02QZLG8GMN/p1732573418485419)
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment …
> Fix example loading issue

- .changeset/itchy-facts-retire.md
- gradio/oauth.py
I just noticed that the oauth code is using `huggingface_hub.HfFolder.get_token` to retrieve the token from the user's machine. This is deprecated in favor of the more straightforward `huggingface_hub.get_token`. Both are doing the same thing but we're trying to get rid of the `HfFolder` abstraction. Token is retrieved from either the environment variable, the local file or the colab secret. Nothing new, just a namespace update :hugs:
(note: I've also checked and minimal version of `huggingface_hub` is 0.25.1 which is recent enough to support `get_token`. This have been in place for 11 months now.)
> Use get_token instead of HfFolder.get_token

- .changeset/cyan-things-rule.md
- js/lite/src/index.ts
`stlite.js` can be loaded after the DOM initialization is finished, and in that case, the custom element is never initialized.
Acutally the Lite demos embedded into the document (e.g. https://www.gradio.app/docs/gradio/interface) are broken now.
This PR fixes it.
> Fix to call bootstrap_custom_element() if the script is loaded after the DOMContentLoaded event

- .changeset/angry-fans-sneeze.md
- js/paramviewer/ParamViewer.svelte
Simple change to paramviewer descriptions so that you can add links, like a demo that explains a parameter. [Internal discussion](https://huggingface.slack.com/archives/C03BHNJCBC4/p1732826555853109)
> Add HTML support to paramviewer descriptions

- .changeset/eight-games-decide.md
- gradio/chat_interface.py
- test/test_chat_interface.py
See [internal thread for context](https://huggingface.slack.com/archives/C02SPHC1KD1/p1732906018427149)
> Fix chatbot/chatinterface type mismatch

- gradio/route_utils.py
- requirements.txt
Commit febbed6db1c1 ("Pin multipart version to fix issues with yanking (#9834)") pinned this because of issues with `micropip` yanking versions. However, doing so blocks users of `gradio` from being able to resolve important security vulnerabilities (see [[1]] as an example).
This updates `python-multipart` to the patched version, as well as unpins it to prevent the need for `gradio` to cut new releases every time a `python-multipart` vulnerability is found.
[1]: https://github.com/advisories/GHSA-59g5-xgcq-4qw3
> build(deps): unpin and upgrade `python-multipart`

- .changeset/fast-wings-wave.md
- gradio/components/multimodal_textbox.py
API Snippet shows up fine now:
with 
```py
def fn(x, y):
print(message)
t = gr.File()
text = gr.MultimodalTextbox()
text.submit(fn=fn, inputs=[t, text])
demo.launch()
```
Closes: https://github.com/gradio-app/gradio/issues/10104
> Fix API docs for `multimodal_textbox.py`

- guides/05_chatbots/01_creating-a-chatbot-fast.md
Had forgotten to add these docs earlier in https://github.com/gradio-app/gradio/pull/10071
> Add docs for `additional_outputs` in `gr.ChatInterface`

- package.json
This PR fixes the error ERR_PNPM_UNSUPPORTED_ENGINE while creating a devcontainer. The details of the error are described in https://github.com/gradio-app/gradio/issues/10141#issuecomment-2525108481.
Closes: additional errors reported in the #10141.
> Fixes error ERR_PNPM_UNSUPPORTED_ENGINE while creating a devcontainer.

- .changeset/new-chefs-build.md
- js/atoms/src/Block.svelte
See latest comment in #9724 - the visible prop in chatbot was not reactive
2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes …
> Fix chatbot `visible` prop not reacting to changes

- .changeset/rotten-drinks-push.md
- gradio/exceptions.py
- gradio/queueing.py
- gradio/routes.py
- gradio/utils.py
> This would allow not printing stack traces for "expected" errors (while still using gr.Error in order to nicely display the error message in the UI). For instance in ZeroGPU, Spaces logs are full of "quota exceeded" stack traces that bring a lot of noise to the logs.
> Example usage: raise gr.Error("my error message", print_exc=False) ==> won't print the exception in the logs
Closes: #10136
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, …
> make printing the error message from a `gr.Error` to the console configurable

- .changeset/three-chefs-ask.md
- js/core/src/Login.svelte
- js/core/src/lang/en.json
- js/core/src/lang/ja.json
I added Japanese translations for login UI. It will be useful for Japanese users.
> Add Japanese translations for login UI

- .changeset/brave-plants-pay.md
- js/multimodaltextbox/shared/MultimodalTextbox.svelte
Fixes issue where multimodal textbox was always refocused after each update.
Closes: #10144
2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes …
> Multimodal autofocus fix

- .changeset/public-owls-mate.md
- gradio/components/html.py
- js/html/Index.svelte
- js/html/shared/HTML.svelte
- test/components/test_html.py
Small PR that adds a `.click()` event to HTML, which is useful if you are creating very custom buttons.
Silly example of what this allows:
```py
html_button = """
<style>
.stylish-button {
background-color: #4CAF50;
border: none;
color: white;
padding: 15px 32px !important;
text-align: center;
text-decoration: none;
display: inline-block;
font-size: 16px;
margin: 4px 2px;
cursor: pointer;
border-radius: 8px;
transition: all 0.3s ease;
box-shadow: 0 4px 6px rgba(0,0,0,0.1);
font-family: Arial, sans-serif;
text-transform: uppercase;
letter-spacing: 1px;
font-weight: bold;
}
.stylish-button:hover {
background-color: #45a049;
transform: translateY(-2px);
box-shadow: 0 6px 8px rgba(0,0,0,0.2);
}
.stylish-button:active {
transform: translateY(1px);
box-shadow: 0 2px 4px rgba(0,0,0,0.1);
} …
```
> Add a `.click()` event and `padding` parameter to the `HTML` component

- .changeset/wild-sheep-agree.md
- gradio/route_utils.py
- gradio/routes.py
(I'm not experienced about Python's dependency and packaging, sorry if my analysis or suggestions are wrong)
I'm using Gradio on a project that depends on https://pypi.org/project/python-multipart/ through Gradio and https://pypi.org/project/multipart/ through another dependecy.
I tried to update the Gradio version to 5.8.0 and now I get an error at startup.
```
File "/opt/XXXX/gradio_interface.py", line 5, in <module>
File "/root/poetry.cache/virtualenvs/non-package-mode-KSsrRO-R-py3.12/lib/python3.12/site-packages/gradio/__init__.py", line 3, in <module>
import gradio._simple_templates
File "/root/poetry.cache/virtualenvs/non-package-mode-KSsrRO-R-py3.12/lib/python3.12/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
from .simpledropdown …
```
> Fix  `multipart` ModuleNotFoundError by renaming import to `python_multipart`

- .changeset/twenty-waves-reply.md
- gradio/components/image.py
- gradio/interface.py
- test/test_interfaces.py
Small fixes, closes: https://github.com/gradio-app/gradio/issues/10234 and closes: https://github.com/gradio-app/gradio/issues/10230
> Fix typing for components in `gr.Interface` and docstring in `image.py`

- guides/05_chatbots/03_agents-and-tool-usage.md
Added Guide for Gemini2.0 Flash Thinking.  …
> Update the LLM Agents guide with Gemini2.0 Thinking demo

- .changeset/old-maps-enter.md
- CONTRIBUTING.md
- client/js/src/types.ts
- gradio/__init__.py
- gradio/helpers.py
- gradio/queueing.py
- gradio/server_messages.py
- js/icons/src/Success.svelte
- js/icons/src/index.ts
- js/statustracker/static/ToastContent.svelte
- js/statustracker/static/types.ts
- scripts/build_frontend.bat
- scripts/build_lite.bat
- scripts/create_test_requirements.bat
- scripts/format_backend.bat
- scripts/format_frontend.bat
- scripts/helpers.bat
- scripts/install_gradio.bat
- scripts/install_test_requirements.bat
- scripts/launch_website.bat
- scripts/lint_backend.bat
- scripts/run_backend_tests.bat
- scripts/run_frontend.bat
- scripts/run_lite.bat
- scripts/type_check_backend.bat
in this pr we add `gr.Success` && we updated `CONTRIBUTING.md` to support windows
Closes: https://github.com/gradio-app/gradio/issues/7489
> add gr.Success and update windows contributing

- demo/all_demos/templates/index.html
- scripts/copy_demos.py
- testing-guidelines/ci.md
There were a couple of issues with the deployed Spaces:
(1) The iframes were too tall preventing the gradio footer from showing. I've just made them a tad bit shorter, closes: https://github.com/gradio-app/gradio/issues/8282
(2) Some of the demos were broken, because we removed `matplotlib` as a requirements in `gradio` but hadn't added it to the requirements for the demos. The actual copy-demos script is located separately, [I've made the fix there](https://github.com/gradio-app/github/pull/12).
I also just improved the general styling a bit!
> Fix deployed Spaces

- js/lite/src/custom-element/index.test.ts
Fix flaky test like https://github.com/gradio-app/gradio/actions/runs/12599100419/job/35115321068?pr=10191
Not sure if this can completely fix the flakiness though.
* I could reproduce the error in local by specifying `jsdom` as the test env (adding `// @vitest-environment jsdom` at the top of the test file), and fixed it with the change of this PR.
> Fix js/lite/src/custom-element/index.test.ts that has been failing frequently

- .changeset/early-wombats-bathe.md
- gradio/cli/commands/reload.py
This pull request updates the regex pattern used to recognize Blocks declarations in the code. 
Certain linting tools enforce a style of import.
The previous pattern only matched gr.Blocks, which caused issues when Blocks was used directly. 
The updated pattern now supports both cases.
Closes: https://github.com/gradio-app/gradio/issues/10289
Closes: https://github.com/gradio-app/gradio/issues/6045
Following the previous patterns:
```python
patterns = [
f"with gr\\.Blocks\\(.*\\) as {demo_name}",
f"{demo_name} = gr\\.Blocks",
f"{demo_name} = gr\\.Interface",
f"{demo_name} = gr\\.ChatInterface",
f"{demo_name} = gr\\.TabbedInterface",
]
```
It's needed this format.
```python
with gr.Blocks(...)
>> Watching: xxx
```
But certain linting tools enforce a style of import. …
> Fixed warning about not being able to find the app for some pattern

- .changeset/long-snakes-notice.md
- js/imageeditor/Index.svelte
Closes: #8601 
Run the repro from the original issue to test. …
> ImageEditor: Trigger input event even if change event not defined

- .changeset/silly-jeans-suffer.md
- gradio/components/slider.py
- js/slider/Index.svelte
- js/slider/Slider.component.spec.ts
- js/slider/Slider.stories.svelte
- test/components/test_slider.py
Added an argument `show_reset_button` to `Slider` component to make reset button visible. By default `show_reset_button` is `False` to reduce visual clutter.
Test script
```
def multiply_by_two(x):
return x * 2
gr.Markdown("## Multiply by Two")
slider = gr.Slider(minimum=10, maximum=100, step=1, label="Input Number", show_reset_button=True)
output = gr.Number(label="Output")
button = gr.Button("Multiply")
button.click(fn=multiply_by_two, inputs=slider, outputs=output)
demo.launch()
```
Closes: #9973 
Not adhering to …
> Add `show_reset_button` to `gr.slider` initialization

- js/core/src/lang/sv.json
This pull request adds Swedish language translations to the Gradio language settings. The translations include user-facing strings for various components, such as audio, dropdowns, sliders, and error messages.
> Adds Swedish language to the lang-settings

- .changeset/honest-frogs-fall.md
- gradio/components/chatbot.py
- guides/05_chatbots/03_agents-and-tool-usage.md
- js/_website/src/lib/templates/gradio/03_components/chatbot.svx
- js/chatbot/shared/Thought.svelte
Tightens up the role of the `status` key. Now the behavior is as follows:
* status: The status of the message. If "pending", a spinner icon appears next to the thought title. If "done", the thought accordion becomes closed. If no value is provided, the thought accordion is open and no spinner is displayed.
Based on discussions with @yvrjsharma I think this will be more intuitive to users.
Closes: #10401 
Closes: #10402 
Here's an example demonstrating the new behavior, adapted from @yvrjsharma's issues:
```py
import time
def stream_messages(message):
messages = []
messages.append(gr.ChatMessage(role="user", content=message))
yield messages
parent_id = "search_1"
tool_parent = gr.ChatMessage(
role="assistant",
content="search('example query')",
metadata={
"title": "🛠️ …
```
> Tweak behavior related to the `status` of `gr.Chatbot` thought messages

- .changeset/open-teeth-give.md
- js/imageeditor/shared/ImageEditor.svelte
- js/imageeditor/shared/tools/Crop.svelte
- js/imageeditor/shared/tools/crop.ts
Fix Image Editor Cropping. 
Cropping now crops the background image instead of the image + canvas. This makes the `canvas_size` parameter behave more predictably. When we add canvas/image resizing shortly, users will be able to manipulate both at will.
https://github.com/user-attachments/assets/645bd277-8435-4a46-b1c3-0c357135938c
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment …
> Fix ImageEditor Cropping - Cropping now crops the background image instead of the image + canvas

- .changeset/shiny-walls-hear.md
- js/_website/src/lib/templates/gradio/03_components/chatbot.svx
Tiny syntax error that somehow slipped and is currently blocking the website builds. 
Since it's so simple I just went ahead and also updated the s3 templates so versioned docs can be fixed too.
> Fix error with website build in chatbot.svx 

- .changeset/four-buttons-say.md
- gradio/layouts/sidebar.py
- guides/03_building-with-blocks/02_controlling-layout.md
- js/_website/src/lib/templates/gradio/03_components/sidebar.svx
We forgot to create a template for sidebar when we added the component, so that's what this PR does. Also adds the guide to the docstring and fixes the link in that guide. 
I'll manually update the docs on s3 for 5.14.0 so it works there too.
> Add sidebar to the docs 

- .changeset/lucky-cars-follow.md
- gradio/external.py
- requirements.txt
cc @AK391 would you be able to test this? Context: [internal link](https://huggingface.slack.com/archives/C02QNREU24S/p1738592928748999)
> Add support for inference `providers` in `gr.load()`

- .changeset/green-heads-tan.md
- js/lite/src/LiteIndex.svelte
There is as error on Lite as below now, due to the new client implementation to support multipage apps.
```
client.ts:87 Uncaught (in promise) Error: Page lite.html not found
at LiteClient.get_page_config (client.ts:87:10)
at LiteClient.get_url_config (client.ts:79:15)
at Index.svelte:315:16
```
This PR is a workaround for Lite just to avoid the error, not to support MPA on Lite as well.
> Workaround for Lite to work with multipage client API

- .changeset/mighty-pandas-invite.md
- js/_website/src/lib/templates/gradio/04_helpers/05_selectdata.svx
Correct the **Example Usage** of **gradio.SelectData**, replaced the second arguments of `table.select`... to `None`
Closes: https://github.com/gradio-app/gradio/issues/10509
Now it works well.
> Fixed wrong example usage of docs/gradio/selectdata

- .changeset/rare-donuts-draw.md
- js/plot/package.json
- js/plot/shared/plot_types/PlotlyPlot.svelte
- pnpm-lock.yaml
Closes: #10475
The latest js lib is compatible with versions 5 and 6.
Test: https://huggingface.co/spaces/freddyaboulton/plotly-6.0 & https://huggingface.co/spaces/freddyaboulton/plotly-5.0
2. Please run these bash scripts …
> Plotly 6.0 Fix: Install latest plotly js version

- .changeset/public-phones-draw.md
- js/app/src/routes/[...catchall]/+page.svelte
Fixes #9695
Run any demo in SSR mode and try setting query param __theme="light" or "dark" to test
> support URL params for themes in SSR mode

- .changeset/curly-rules-change.md
- js/lite/src/dev/App.svelte
- js/wasm/src/webworker/index.ts
Now `installPackages()` (introduced by #10366) hides the error thrown from `micropip.install()` and it makes debugging less easy.
This PR fixes it so the original error is properly shown:
> Fix the wrapper function of micropip.install to throw the original error for better debug experience

- .changeset/great-llamas-read.md
- js/nativeplot/Index.svelte
- js/nativeplot/NativePlot.stories.svelte
> Native Plot respects the height parameters

- .changeset/blue-olives-fry.md
- gradio/components/plot.py
- guides/10_other-tutorials/developing-faster-with-reload-mode.md
- js/plot/Index.svelte
- js/plot/Plot.component.spec.ts
- js/plot/shared/Plot.svelte
- js/plot/shared/plot_types/PlotlyPlot.svelte
Closes: #10252
Closes: #9997 
Can't repro #10252 but I have refactored the code to only load the plotly css once. 
2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if …
> Fix gr.Plot change/load events and plotly css loaded

- .changeset/olive-pants-judge.md
- client/js/src/client.ts
- gradio/layouts/tabs.py
Quick fix for the client when can't find a page to default to the main page. Was hitting issues due to how how I'm using the url to get the path for a page, which is incorrect. I just use the pathname from the URL, remove the config.root path if its mounted on a subpath, and assume that's the final pathname. This doesn't work when embedded because for example on "http://gradio.app/guides/quickstart" it sees the pathname "guides/quickstart" from the URL and there is no page in the gradio app called "guides/quickstart", since its an embedded an HF space . The quick fix is to return the main page (whose route is "") when it can't find the "expected" page for a path.
> quick_fix_client

- scripts/build_frontend.bat
- scripts/build_lite.bat
- scripts/create_test_requirements.bat
- scripts/format_frontend.bat
- scripts/helpers.bat
- scripts/install_gradio.bat
- scripts/install_test_requirements.bat
- scripts/launch_website.bat
- scripts/run_frontend.bat
- scripts/run_lite.bat
- scripts/type_check_backend.bat
Scripts fail to run on Windows because Batch does not allow calling subroutines from another script.
To get around this, `scripts/helpers.bat` needs to accept a parameter and run the corresponding subroutine.
To fix this:
I replaced subroutine calls in batch scripts from:
```
call scripts/helpers.bat
cal :[SUBROUTINE_NAME]
```
to
```
call scripts/helpers.bat [SUBROUTINE_NAME]
```
I added logic to call the corresponding subroutine in 'helpers.bat'
Closes: #10609
> Fix subroutine in Windows batch scripts

- .changeset/four-eggs-dig.md
- gradio/components/chatbot.py
- js/atoms/src/Block.svelte
- js/chatbot/Index.svelte
- test/components/test_chatbot.py
Ok to make up our own terms but probably not our own spelling. Thanks @hysts for flagging
> fix spelling of `resizable` parameter in `gr.Chatbot`

- .changeset/fast-mammals-hide.md
- gradio/external.py
Fixes: https://github.com/gradio-app/gradio/issues/10617
e.g. this works now:
```py
gr.load(name="deepseek-ai/DeepSeek-R1", src="models", provider="together", examples=[["abc"], ["def"]]).launch()
```
Treating this as a bug since this should have always been the behavior according to the docstring for `gr.load()`
> Pass kwargs into `gr.ChatInterface` created by `gr.load()`

- .changeset/six-suits-fail.md
- gradio/blocks.py
- gradio/processing_utils.py
- js/button/package.json
- js/button/shared/Button.svelte
- pnpm-lock.yaml
This PR fixes the following error on Lite.
The direct reason of it was that `Button(icon=...)` was added to `ChatInterface` in #10191 and the icon option [calls](https://github.com/gradio-app/gradio/blame/1299267a8a78546d3f9e13d6b3c58231cf88f2b9/gradio/components/button.py#L76) `Blocks.serve_static_file()` which doesn't work on Lite.
This PR modifies `Blocks.serve_static_file()` to use the sync version of `move_files_to_cache()` because `Blocks.serve_static_file()` itself is synchronous. The sync version works on Lite.
In addition, I fixed the `Button` component to show the icon image on Lite properly.
```python
import time
demo = gr.ChatInterface(
lambda x,y:x,
type="messages",
flagging_mode="manual",
flagging_options=["Like", "Spam", "Inappropriate", "Other"], …
```
> Fix `Blocks.serve_static_file` and `Button.svelte` to work on Lite

- .changeset/salty-toes-kneel.md
- js/core/src/Embed.svelte
Got broken. Fixes: #10602
Test with:
```python
fn=None,
inputs=["textbox"],
outputs=None,
fill_width=True
)
demo.launch()
```
> Fix fill_width

- .changeset/pretty-colts-agree.md
- js/chatbot/shared/ChatBot.svelte
- Fixes Payload too large issue with chatbot sharing on spaces
- If payload is too large, we now try to reduce the chatbot messages and try sharing.
- If even one chatbot message is too large, we throw an error 
Closes: #10606
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the backed tests: `bash …
> Fix: Chatbot sharing payload too large

- .changeset/quick-tires-burn.md
- js/dataframe/shared/Table.svelte
- js/dataframe/shared/selection_utils.ts
Makes a few small fixes to cell-selection logic, see inline comments below:
> Fixes cell-selection logic in `Table.svelte`

- .changeset/rotten-states-see.md
- js/chatbot/shared/ChatBot.svelte
- js/chatbot/shared/utils.ts
The messages are being passed through the url, so this shortens the URL to be max 1800 characters to ensure there is no error.
Closes: #10606
2. Please run these bash scripts to automatically format your code: `bash …
> Fix chatbot share button payload too large

- .github/workflows/website-build.yml
- .github/workflows/website-deploy.yml
necessary for https://github.com/gradio-app/gradio/pull/10677 
only changes the paths in the CI, which has to be done in main. will probably disrupt website deploys until https://github.com/gradio-app/gradio/pull/10677 is merged but not a big deal.
> Change website to cloudflare adapter 

- .changeset/clear-boxes-dance.md
- gradio/external_utils.py
Closes: https://github.com/gradio-app/gradio/issues/10680
Closes: https://github.com/gradio-app/gradio/issues/10682
Test with, e.g.:
```py
gr.load(
"models/meta-llama/Llama-3.2-3B-Instruct",
provider="sambanova",
chatbot=gr.Chatbot(type="messages", allow_tags=["think"], scale=1),
).launch()
```
> Change `gr.load` chatinterface behavior to streaming

- .changeset/shaggy-llamas-shake.md
- js/wasm/package.json
- js/wasm/src/webworker/index.ts
- package.json
- pnpm-lock.yaml
Leverages all the new features released by Pyodide, notably fixes broken Gradio Lite apps on iOS/webkit browser.
Closes: #10705
> chore: bump Pyodide version to 0.27.3

- .changeset/common-nails-divide.md
- gradio/blocks.py
- gradio/routes.py
When running inside a trusted platform module, such as the Intel SGX, with a library operating system (e.g., Gramine), it is not possible to fork out new processes. Thus, a call to spawn a subprocess to invoke `which` in an attempt to check the Node.js path will fail.
However, this scenario is unlikely to happen when SSR mode is disabled. Hence, the check for Node.js path should also not happen unless SSR mode is enabled.
Note that SSR mode may work with Gramine but it will require additional configuration, but these are outside the merits of this PR and the related issue.
Closes: #10711
> fix: Check for Node.js path only if SSR mode is true.

- .changeset/pink-snails-arrive.md
- gradio/routes.py
- test/test_routes.py
Adds a couple of missing parameters to `mount_gradio_app` and because this is a common issue, adds a test to make sure we don't miss adding new parameters in the future.
Closes: https://github.com/gradio-app/gradio/issues/10716
> Add `pwa` and `enable_monitoring` parameters to `mount_gradio_app`

- .changeset/orange-dragons-rescue.md
- client/js/src/client.ts
- js/core/src/Blocks.svelte
Fixes: #10713
Issue was introduced when I tried to prevent the error message from popping up when a user clicked to a new page in multipage while a request was pending. The way it was implemented, all error messages stopped displaying.
Fixed now. 
Test multipage navigation with below (no errors should propogate on switching links while request pending):
```python
import random
import time
name = gr.Textbox(label="Name")
output = gr.Textbox(label="Output Box")
greet_btn = gr.Button("Greet")
@gr.on([greet_btn.click, name.submit, demo.load], inputs=name, outputs=output)
def greet(name):
time.sleep(10)
return "Hello " + name + "!"
with demo.route("Up") as incrementer_demo:
num = gr.Number()
demo.launch()
```
Test regular errors propogate with …
> Fix error display

- .changeset/mighty-rabbits-dance.md
- gradio/components/chatbot.py
I've changed the stacklevel for the warnings so it shows the actual calling code instead of the gradio code when showing warnings, that way you know where to fix the warning.
Closes: No issue, very small change.
It's a very tiny change, but it's very similar to: https://github.com/gradio-app/gradio/pull/4203
Before:
```
site-packages\gradio\chat_interface.py:310: UserWarning: The type of the gr.Chatbot does not match the type of the gr.ChatInterface.The type of the gr.ChatInterface, 'messages', will be used.
warnings.warn(
```
After:
```
gradio_test.py:582: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, …
```
> Changed warning stacklevel to improve warnings in console

- gradio/blocks.py
This PR addresses an issue where the Gradio application stalls indefinitely when localhost is inaccessible, causing startup events to fail silently. 
Specifically, when using `share=True` with a proxy that blocks localhost, the httpx.get request to `{self.local_api_url}startup-events` fails, and the event queue is never processed, resulting in components (e.g., dropdown triggers) loading forever.
Closes: [#10729](https://github.com/gradio-app/gradio/issues/10729)
> Raise exception when startup events fail due to inaccessible localhost

- .changeset/yummy-shirts-hide.md
- gradio/external.py
Allow tags in chatbot for `gr.load`
Closes: #10684 …
> Allow tags for chatbot models using `gr.load`

- .changeset/yellow-paws-grin.md
- js/dataframe/shared/selection_utils.ts
Previously, we would treat the cell that was farthest to the left and top as the "anchor" cell, which would lead to interesting behavior when using shift+arrow keys. For example, here, I'm pressing on a cell, and then doing shift + up/left. 
https://github.com/user-attachments/assets/60ce5f16-6710-4658-bc2c-99a518942cb9
In this PR:
https://github.com/user-attachments/assets/18e2ad2f-028a-4fae-812d-c9dfb3b44fd5
> Fix cell selection when using shift + arrow keys

- gradio/utils.py
This pull request updates the `get_node_path` function in the `gradio/utils.py` file to handle scenarios where the `which` command is missing. The function has been improved by splitting the error handling into two separate `try` blocks for better granularity and robustness.
- Split the `try` block into two separate `try` blocks for handling Windows and Unix-like systems.
- Added error handling for `FileNotFoundError` in addition to `subprocess.CalledProcessError`.
The original implementation did not properly handle the case when the `which` command is missing. This update ensures the function gracefully handles such scenarios and continues to check other possible locations for the `node` executable.
> Update `gradio/utils.py` to properly handle the case when the `which` command is missing.

- .changeset/ready-donuts-switch.md
- js/dataframe/shared/Table.svelte
- js/dataframe/shared/utils/drag_utils.ts
This is a super niche bug fix. Drag selection and then copying didn't work on mount unless you had selected a cell already because we needed to add focus to the parent. 
2. Please run these bash scripts to automatically …
> Add parent focus for drag selection

- .changeset/four-tips-pump.md
- js/dataframe/shared/EditableCell.svelte
Max characters was working as expected in editable dataframes but not in non-editable dataframes. This fixes that.
Note, this has flagged an issue that I notice that we should really be calculating the column widths based on the truncated values, not the original values. A viable workaround for now is just setting the column width manually which isn't ideal but there is a bit of time needed to rejig the native dataframe to calculate the column widths based on the truncated value. I think. 
1. PRs …
> Fix max characters in non-editable dataframes

- guides/09_gradio-clients-and-lite/01_getting-started-with-the-python-client.md
> Fix typo in 01_getting-started-with-the-python-client.md

- js/gallery/shared/Gallery.svelte
Fixed preview mode unexpected exit when selected_index is greater than the number of images in the gallery.
To maintain a smooth user experience, I introduced an additional edge case:
If selection_index exceeds the number of available images, it now selects the highest valid index instead of defaulting to null.
This ensures that when images are removed from the gallery, the preview remains active, selecting the last available image instead of forcefully exiting.
The gallery now only exits preview mode when the user explicitly selects the exit button.
Closes: #9599
Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. …
> Fix #9599: Preserve preview mode when selected_index exceeds the number of images in the gallery.

- .changeset/flat-memes-sort.md
- gradio/component_meta.py
This PR fixes an issue with insufficient typing of the `load` event listener due to not having imported the `Component` class.
2. Please run these bash scripts to automatically format your code: `bash …
> fix typing on load event listener

- .changeset/olive-sites-ask.md
- gradio/routes.py
Fixing if in the launch there is root_path assigned and it return back to "/" not the root path (especially when doing this in kubernetes). This bug is already tested with dev container vscode. Thank you
Closes: #10291
2. …
> bug fix logout if there is root_path in launch

- .changeset/puny-jokes-clap.md
- gradio/helpers.py
- test/test_helpers.py
When examples were cached, we previously combined two events together: loading the input value and loading the output value. For eager caching, this makes sense, but for lazy caching, we should first load the input value (since that's instantaneous) and _then_ load the output value, which can be time-consuming. 
Closes: https://github.com/gradio-app/gradio/issues/10866
> Improve UI for lazy caching

- .changeset/public-zoos-obey.md
- gradio/route_utils.py
A regression was introduced in https://github.com/gradio-app/gradio/pull/10841. This PR fixes it. Basically, we shouldn't be using the forwarded url header here since it's not going to include the full url with the full path. However, `request.url` should be fine to use.
See: https://github.com/gradio-app/gradio/pull/10841#issuecomment-2750507289 and https://github.com/gradio-app/gradio/pull/10875
cc @Kenxu2022, @tqbl, @cansik
> Switch from `root_url` to `request.url` in `get_api_call_path()`

- .changeset/some-masks-stay.md
- gradio/route_utils.py
- test/test_routes.py
I made a mistake in https://github.com/gradio-app/gradio/pull/10877, which was causing all demos on Spaces to hang. The mistake was that I was not stripping out query parameters when looking at the `request.url`. So on Spaces, we'd see an error like this:
```
ValueError: Request url 'http://gradio-pr-deploys-pr-10877-all-demos.hf.space/demo/calculator/gradio_api/queue/join?logs=container&__theme=dark' has an unkown api call pattern.
```
This fixes that.
> Fix request url

- .changeset/crazy-melons-exist.md
- gradio/route_utils.py
- test/test_routes.py
Lite is broken in the main branch and this PR fixes it.
This replacement of `.strip("/")` to `.rstrip("/")` is the core of the fix.
https://github.com/gradio-app/gradio/pull/10897/files#diff-7b70c24a1e3baea4acc4ef7072c619340363fe1e5f9f3860183da99be7463213R387
And this test case covers it.
https://github.com/gradio-app/gradio/pull/10897/files#diff-c96cc0d0cdce3ed40a62b12fe1138e01a135dc3825cade2fb3642d0794142a3cR1722-R1725
Other parts in this PR are all refactoring.
The problem was, `request.url` can be `"/gradio_api/call/predict"` that doesn't have a host name in the case of Lite, and in that case, `.strip("/")` deletes the leading slash and returns `"gradio_api/call/predict"` then it doesn't match in `if request_url.endswith(queue_api_url)` and leads to the error raised at the bottom. …
> Fix route_utils.get_api_call_path()

- .changeset/clear-vans-push.md
- gradio/routes.py
Hello!!
I was reading through the Gradio code today and noticed:
- A `stop_stream()` task was being created on every heartbeat, in an infinite loop. Past tasks were never cancelled. I guess this is not an issue in practice, but it will slowly leak memory.
- Some typos. A route here was spelled as `hearbeat` instead of `heartbeat`. I don't know what this impacts.
As a fix I:
- Made the code reuse the same `stop_stream()` task.
- Simplified slightly.
- Fixed typos.
> Fix minor heartbeat memory leak

- .changeset/plain-moments-cover.md
- js/multimodaltextbox/shared/MultimodalTextbox.svelte
In the `MultimodalTextbox` component, when `interactive=False`, the submit and microphone buttons remained active allowing users to submit inputs without being able to edit them. To fix this issue, I added restrictions to disable these buttons when the component is set to non-interactive. This ensures that users cannot submit inputs or use the microphone when `interactive=False`, maintaining consistency in the component’s behavior and preventing unintended interactions.
Initially, the component `MultimodalTextbox` is set to `interactive=True`, allowing input submissions. After the first submission, it changes to `interactive=False`, disabling the submit and microphone buttons.
```
def greet(a, c):
return gr.MultimodalTextbox(interactive=False), a, c+1
with gr.Blocks() …
```
> Fix disabling buttons in `MultimodalTextbox` when `interactive=False`

- .changeset/tough-pots-shake.md
- gradio/chat_interface.py
Puts the latest conversations at the top, which is more standard and makes more sense especially if you have a large number of conversations in history.
Closes: https://github.com/gradio-app/gradio/issues/10896
Also fixes a separate issue related to custom chatbot component. Closes: https://github.com/gradio-app/gradio/issues/10645
> Reverse order of conversations in chat history and render correctly with custom chatbot

- .changeset/funny-cows-draw.md
- js/nativeplot/Index.svelte
Previously, when a gr.NativePlot component was created with a DataFrame and the sort argument was omitted (i.e., set to null), the x-axis labels were automatically sorted alphabetically. Initially, the bug appeared to be isolated to gr.BarPlot, but I later discovered that it affected all gr.NativePlot components (gr.BarPlot, gr.LinePlot, and gr.ScatterPlot).
Although the data did not appear sorted during the program's execution, it became sorted when the rendered Svelte file was interpreted by the browser. This issue occurred because the reformat_sort function in index.svelte of NativePlot returned undefined when sort was not specified, and after compilation, undefined was treated as void 0, which implicitly triggered default sorting.
To fix this, I changed undefined to null, ensuring …
> Fix gr.NativePlot sorting of labels as default behaviour

- .changeset/tangy-parts-arrive.md
- gradio/chat_interface.py
Analogous change to https://github.com/gradio-app/gradio/pull/10928.
Closes: https://github.com/gradio-app/gradio/issues/10958
> Unrender user-provided textbox in `gr.ChatInterface` so that it is rendered in the right place as part of a `gr.Blocks` app

- .changeset/petite-grapes-wear.md
- js/_website/src/routes/playground/+page.svelte
Annoying issue where the lite js sometimes doesn't load if you directly access the link to the playground, which for a first time user looks like the preview is just empty. 
eg: https://www.gradio.app/playground vs https://www.gradio.app and then clicking on playground 
vs
https://b18250ab.gradio-website.pages.dev/playground
> Load lite js correctly in playground

- .changeset/silver-nights-jump.md
- gradio/components/audio.py
- test/components/test_audio.py
In the `gr.Audio` component, it accepts URLs, however, to check if the suffix is valid, it simply assumes that the url ends with e.g. `.mp3`. However, if a URL is signed with a token (let's say coming from a database), the check fails, and the audio module tries to load it like a regular file, which crashs the app
Closes: #(issue) See issue #10969 
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment …
> fix: accept signed URLs in gr.Audio

- .config/playwright.config.js
- js/spa/test/video_component_events.spec.ts
These tests are failing consistently in PRs now but in a confusing and inconsistent way. They are not high enough value to warrant the disruption. Disabling until we can figure it out.
> disable flaky tests

- .github/workflows/test-functional-lite.yml
Workaround for Firefox crashes in CI.
Debug note is https://github.com/gradio-app/gradio/pull/10973#issuecomment-2797207911
We still don't know why the problem started happen recently though.
> Use xvfb to run Playwright in the headed mode to avoid FireFox crash

- .changeset/tender-keys-find.md
- js/_website/src/lib/templates/gradio/04_helpers/05_selectdata.svx
- js/dataframe/shared/Table.svelte
- js/dataframe/shared/context/dataframe_context.ts
- js/utils/src/utils.ts
Test code:
```py
table = gr.Dataframe([[1, "text first"], [2,"text second"], [3, "text third"]], show_search='search', show_row_numbers=True)
statement = gr.Textbox()
def on_select(evt: gr.SelectData):
return f"{evt.value=}\n{evt.index=}\n{evt.row_value=}\n{evt.col_value=}\n{evt.target=}\n{evt._data=}"
table.select(on_select, None, statement)
demo.launch()
```
Closes: https://github.com/gradio-app/gradio/issues/10964
Closes: https://github.com/gradio-app/gradio/issues/11004
> Ensure that the `.select()` event in `gr.DataFrame` carries the `.row_value` and `.col_value`

- .config/playwright.config.js
> Disable Lite E2E tests on Firefox

- .changeset/floppy-pianos-dance.md
- gradio/blocks.py
Fixes the SSR notice message to correctly reference the `ssr_mode` parameter instead of `ssr` so users know the right parameter to use when disabling SSR.
> Fix `ssr_mode` parameter name in notice message

- .changeset/dull-breads-rest.md
- js/imageeditor/shared/core/editor.ts
Due to previous changes by a reckless penguin, uploading a new image would persist layer ids but the layer still needed to be recreated and there was no check to ensure the layer object (that we draw on) actually exists. The `id` was persisted and correct but the layer object was not set to the newly created layer with the same `id`. 
This PR fixes that.
Closes: #11024.
> Ensure it is possible to draw after uploading an image to the ImageEditor

- .github/workflows/test-python.yml
- pyproject.toml
- Log Python version used for testing (tests are too slow for all supported Python versions)
- Sync pyproject.toml (remove 3.8 3.9 add 3.11 3.12 3.13)
- Remove incorrect license classifier
> chore: log tested Python version

- js/imageslider/README.md
the js docs on the website can't find the images which is breaking the build. simplest fix is to use the github urls instead.
> Fix image url in ImageSlider README

- .changeset/hip-games-double.md
- client/python/gradio_client/client.py
Update client.py to always send file data, even for files without extensions
Closes: #10775
> Update client.py to always send file data, even for files without extensions

- guides/10_other-tutorials/building-an-mcp-client-with-gradio.md
Edits a link that we forgot to replace. currently breaking the website build
> Fix broken placeholder link in mcp guide

- .changeset/open-dragons-melt.md
- gradio/cli/commands/cli_env_info.py
We were not parsing requirements with `==` version pins correctly.
```bash
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 5.20.1
gradio_client version: 1.7.2
------------------------------------------------
gradio dependencies in your environment:
aiofiles: 23.2.1
anyio: 4.9.0
audioop-lts is not installed.
fastapi: 0.115.7
ffmpy: 0.3.2
gradio-client: 1.7.2
groovy: 0.1.1
httpx: 0.28.1
huggingface-hub: 0.29.3
jinja2: 3.1.2
markupsafe: 2.1.1
numpy: 1.24.4
orjson: 3.9.14
packaging: 24.2
pandas: 1.5.3
pillow: 11.1.0
pydantic: 2.11.3
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
ruff: 0.9.3
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.46.2
tomlkit: 0.12.0
typer: 0.15.1
typing-extensions: 4.13.2
urllib3: 2.3.0
uvicorn: …
```
> Fix gradio cc environment

- .changeset/ninety-bears-tickle.md
- js/core/src/api_docs/ApiDocs.svelte
This changes the instructions displayed for using an MCP Server with STDIO. It adds the "--transport sse-only" options after specifying the remote MCP endpoint. 
By default, 
Closes: #11114
Solves issue #11114
> update STDIO instructions to specify sse-only transport

- .changeset/weak-chicken-stop.md
- client/python/gradio_client/client.py
- client/python/test/test_client.py
The issue right now is that `iter_lines` uses an internal list of newline characters that include `\x85` and we can't control that list. So in those cases where one of those newline characters is returned, the line is shorter than expected and json.loads fails.
Closes: #10133
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run …
> Fix python client SSE decoding issue

- .changeset/famous-cougars-bake.md
- gradio/blocks.py
- gradio/routes.py
Type checkers currently highlight a type mismatch when we are trying to use `Path` for the `favicon_path`. This change aims to remove the "error" raised by the type checkers by hinting that we can also use `Path`.
The change is very small, I don't think it requires an issue.
> chore: Support Path type for the favicon

- .changeset/angry-years-flow.md
- gradio/components/file.py
Closes: #10382
When file_count="directory", the frontend does respect the "file_type" parameter. So I just removed the warning.
2. Please run these bash scripts to automatically format your code: `bash …
> Remove warning from gr.File about specifying file_types when file_count is directory

- .github/workflows/test-python.yml
- client/python/test/requirements.txt
- client/python/test/test_client.py
- test/requirements.txt
- test/test_docker/test_reverse_proxy/test_reverse_proxy.py
- test/test_docker/test_reverse_proxy_fastapi_mount/test_reverse_proxy_fastapi_mount.py
- test/test_docker/test_reverse_proxy_root_path/test_reverse_proxy_root_path.py
- test/test_interfaces.py
Nice idea @pngwn to parallelize the python unit tests. It looks like we have 4 workers on CI so parallelization helps quite a bit (even though certain tests that cannot be parallelized or they fail, hence the `serial` marker. This is something we should keep in mind for the future -- if a test is passing locally but not on CI, and we're not sure why, it might be because of parallelization). Also the handful of docker unit tests we have take almost 2 minutes to run by themselves, fyi @aliabid94. If runtime is an issue, we could optimize, but I don't think it's too urgent right now.
Net result of this PR: time for the `test-python` GH action goes from ~11 min to ~6 minutes.
> Parallelize pytests

- .changeset/flat-otters-admire.md
- gradio/components/base.py
- gradio/components/browser_state.py
- gradio/components/state.py
- gradio/components/timer.py
Small PR, fixes: https://github.com/gradio-app/gradio/issues/10330
> Refactor `gr.State`, `gr.BrowserState`, and `gr.Timer` to inherit from `FormComponent`

- .changeset/loose-feet-stick.md
- gradio/components/image_editor.py
This PR refactors the cache logic in `ImageEditor.preprocess()` and adds a check to ensure an entry exists in `blob_storage` before attempting to remove it. While there is probably room for further refinement, the current changes are intentionally minimal to reduce risk.
Closes: #11056
> #11056 Avoid unchecked pop from `blob_storage` cache in `ImageEditor::preprocess`

- .changeset/tasty-bees-stick.md
- js/chatbot/shared/ChatBot.svelte
I was experiencing multiple scrollbars in the `gr.Chatbot` component, cf screenshot below:
As seen with @freddyaboulton , I've done these changes in the style of my `gradio` demo under `app.py`:
```
#chatbot .role {
max-width:95%
}
#chatbot .bubble-wrap {
overflow-y: visible;
}
```
So this PR hopes to integrate these changes in the main code:  however maybe I've done mistakes since I'm not sure how svelte works!
Closes: https://github.com/gradio-app/gradio/issues/10934
> gr.Chatbot: Style fixes to remove multiple scrollbars

- .changeset/smooth-parents-sink.md
- gradio/components/native_plot.py
To make the initial `import gradio` faster, importing packages that are not necessarily used every time should be deferred.
This PR does it for `pandas`.  #7851 did it already but the same problem appeared again since then.
The following charts are the import time inspection during `import gradio` obtained by the following commands:
```
find . -name "__pycache__" -type d -exec rm -r {} +  # Remove the cache
python -X importtime -c 'import gradio' &> import_time.txt
tuna import_time.txt
```
These results show that this PR eliminates the `pandas` import from the execution of `import gradio`.
| `main` | This PR|
| ------ | ----- |
| ![image](https://github.com/user-attachments/assets/d9cd964e-7c83-4c73-804a-cbbd207827de) | ![image](https://github.com/user-attachments/assets/d633aecb-8740-4d77 …
> Lazy import pandas in native_plot.py

- guides/10_other-tutorials/developing-faster-with-reload-mode.md
This PR changes the lambda function in the demo to return a value whose type is compatible with the `gr.Label()` output component.
The changed code uses dictionary comprehension to convert the [list of dict with label and score keys](https://huggingface.co/docs/transformers/v4.51.3/en/main_classes/pipelines#transformers.TextClassificationPipeline.__call__) returned by `pipe()`  to a [{Dict[str, float]} of classes and confidences](https://www.gradio.app/docs/gradio/label#param-label-value) used by `gr.Label()` to show classes and confidence bars.
Example of the value before this change. The list was the immediate cause of the ValueError: 
```python
s = "hooray"
pipe(s)
```
Example of the value after this change. The dict has the class as key and confidence score as value:
```python
s = …
```
> Fix ValueError in Controlling the Reload demo

- .changeset/smooth-adults-draw.md
- js/dataframe/shared/Table.svelte
- js/dataframe/shared/context/dataframe_context.ts
We weren't storing the initial data's order. The fix stores a snapshot of the dataframe's data before the first sort is applied and restores it when clearing the sort.
- added an initial_data property to store the original data, display values, and styling
- restore all arrays from snapshot when `clear sort` is clicked
- ensured new data is properly stored when values change without sorting
Closes: #10929
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend …
> Ensure Clear sort works as expected

- .changeset/afraid-donuts-teach.md
- js/chatbot/shared/ChatBot.svelte
- Fixes autoscroll, since it was broken
- When chatbot is loaded with default value and autoscroll is True, the chatbot will already be scrolled to the bottom when first loaded
https://github.com/user-attachments/assets/ea216951-722e-434a-9cc0-4916053fc288
Closes: #11109
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the …
> Chatbot autoscroll fix

- .changeset/dirty-donkeys-fly.md
- gradio/blocks.py
- gradio/utils.py
- js/core/src/init.ts
If you re-render with a key, the new values should replace the existing values. However, we do a utils.delete_none to remove Nones from updates. So in a re-render previously, anything set to None was not passed as an update. Fixed now:
test with below (clearing with button wont work on main):
```python
tb1 = gr.Textbox()
clear = gr.Button()
state = gr.State()
tb1.change(lambda x:x, tb1, state)
clear.click(lambda: None, outputs=state)
@gr.render(inputs=state)
def render(state_val):
gr.Textbox(label=state_val, key="box", preserved_by_key=None)
demo.launch()
```
> Fix re-rendering with key when setting a value to None

- .changeset/shiny-zebras-swim.md
- gradio/mcp.py
- requirements-mcp.txt
- test/test_mcp.py
`mcp==1.9.0` introduced a breaking change in how paths are mounted (the new approach is actually the correct one, see https://github.com/modelcontextprotocol/python-sdk/pull/659)
This PR makes the corresponding change in Gradio's MCP server to account for this change and adds a test. 
Closes: https://github.com/gradio-app/gradio/issues/11225
Closes: https://github.com/gradio-app/gradio/issues/11219
> Fix MCP server mounted path

- .changeset/afraid-cycles-post.md
- gradio/components/markdown.py
- js/markdown/Index.svelte
Makes padding consistent across HTML and Markdown by adding a padding param to gr.Markdown. 
Should this actually be False to prevent unwarranted breaking changes? 
Closes: #11234
2. Please run these bash scripts to …
> Add padding param to gr.Markdown

- .changeset/fresh-vans-bow.md
- js/audio/player/AudioPlayer.svelte
- js/video/shared/Video.svelte
Closes: #10878
The issue is that the media player was not loaded on the page
Test:
```python
from time import sleep
def keep_repeating(audio_file):
for _ in range(1):
sleep(0.5)
yield audio_file
gr.Interface(keep_repeating,
gr.Audio(sources=["upload"], type="filepath"),
gr.Audio(streaming=True, autoplay=True)
).launch()
```
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment …
> Fix bug where streaming one chunk of audio or video would not play

- .changeset/spicy-meals-shave.md
- gradio/helpers.py
- gradio/server_messages.py
Closes: https://github.com/gradio-app/gradio/issues/10040
Run this demo adapted from the original issue to verify:
```py
import time
from tqdm import tqdm
from ast import literal_eval
def custom_function(number, progress=gr.Progress(track_tqdm=True)):
number = literal_eval(number) # cast str to int/float
progress(0, desc="Starting")
time.sleep(0.5)
pbar = tqdm(total=number, desc='Numbers..')
while pbar.n < pbar.total + 0.5:
time.sleep(1)
pbar.update(0.5)
gr.Markdown("### Passive Progress Bar Example")
number_inp = gr.Textbox(3.5, label="Enter Number")
output_text = gr.Textbox(label="Output")
with gr.Row():
process_button = gr.Button("Run Function")
process_button.click(custom_function, inputs=[number_inp], outputs=[output_text])
demo.launch() …
```
> Allow `gr.Progress` to take fractional steps and fractional total # of steps

- .changeset/free-coins-care.md
- gradio/blocks.py
- gradio/mcp.py
- test/test_mcp.py
Closes #11200 
Adds a streamable http transport at `/gradio_api/mcp/http`. Let's add to the docs later when more clients switch to the http protocol
In the meantime, you can test with mcp inspector:
2. Please run these bash …
> Streamable HTTP Transport for MCP server

- .changeset/angry-bushes-sip.md
- gradio/cli/commands/components/_create_utils.py
- gradio/cli/commands/components/files/tsconfig.json
- js/image/shared/ImagePreview.svelte
- js/preview/src/_deepmerge_internal.ts
- js/preview/src/build.ts
- js/preview/src/dev.ts
- js/preview/src/plugins.ts
For reasons that aren't clear to me, vite was refusing to correctly transform a commonjs module to esm. I was unable to convince it to do so, and so i went nuclear and replaced the module for the exact same module but converted to common js.
Another issue is that a recent version of svelte requires specific typescript compiler options or it won't work, so I have added a good default tsconfig when generating the custom component.
With this change it is now possible to do the following, which was not previously possible:
- create a new custom component using the Image or Audio as the template
- Run the dev mode
- Run the build
Everything still works as expected after this change.
Closes: #9879
Before your create a PR, please check to see if there is [an existing …
> Fix custom components build and dev mode with certain base components (Image and Audio at least)

- .changeset/wise-paws-sing.md
- .devcontainer/devcontainer.json
- CONTRIBUTING.md
- js/README.md
- js/dataframe/shared/RowNumber.svelte
- js/dataframe/shared/Table.svelte
- js/dataframe/shared/VirtualTable.svelte
- js/spa/test/dataframe_colorful.spec.ts
Fix `tr:nth-child(even)` breaking virtual rows on scroll using explicit base `tr` rules and a `tr.row-odd` override.
Closes: #11281
Closes: #11308
Closes: #11309
> Fix DataFrame Group Flicker

- guides/08_custom-components/01_custom-components-in-five-minutes.md
I just changed the documentation because you need to have your component published to PyPi otherwise the hugging face demo can not install the component.
See https://discord.com/channels/879548962464493619/1379499716831739924
Closes: #11319
> PyPi is required  to publish to hugging face spaces

- .changeset/pink-shrimps-accept.md
- gradio/utils.py
- test/test_utils.py
Closes: #11239 
This app shows the original error, basically deleting keys in a dictionary that's in a list. Added unit tests for this case.
```python
import time
def response():
yield [{'role': 'user', 'content': 'Hello!', "metadata": {"id": 1}}, {'role': 'assistant', 'content': 'b'}]
time.sleep(3)
yield [{'role': 'assistant', 'content': 'Thinking...', "metadata": {"title": "Thinking..."}}]
time.sleep(3)
yield [{'role': 'assistant', 'content': 'No Metadata', "metadata": {}}]
time.sleep(3)
yield [{"role": "user", "content": "finished!"}]
gr.Interface(fn=response, inputs=[], outputs=[gr.Chatbot(type="messages")]).launch()
```
Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, …
> Fix streaming chatbot diff logic

- .changeset/cute-zebras-repair.md
- js/textbox/shared/Textbox.svelte
Fixes issue where textbox autoscroll was not working when switching between tabs.
Simple Repro:
```
import time
def greet(name):
for i in range(200):
name = name + f"{i}\n\n\n\n\n"
time.sleep(0.1)
yield name
with gr.Tab():
name = gr.Textbox()
with gr.Tab():
output = gr.Textbox(lines=20,label="Output Box", autoscroll=True)
test_btn = gr.Button("Test")
test_btn.click(fn=greet, inputs=name, outputs=output)
demo.launch()
```
Closes: #10545
Not adhering to this guideline will result in the PR being …
> Fix textbox autoscroll in tabs

- .changeset/lazy-spoons-fail.md
- gradio/utils.py
- js/core/src/Blocks.svelte
- js/core/src/init.ts
- js/spa/src/Index.svelte
Closes: #10199 . You can run repro in issue.
gr.render + reload mode was not working at all. 
Two reasons:
1. When the python file changed and the app re-rendered, the Form component that's the parent of the Column where the `@gr.render` output gets placed was not in the `instance_map`.
2. When the python file changed and the app re-rerenderdd, the load event corresponding to `@gr.render` would fire with `undefined` for the component value since the load event was triggering before the components were added to the `_component_map`. 
When the page re-renders based on file changes, the `gr.render` event still triggers. We could fix this in a separate PR.
Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. …
> Fix Reload Mode when using gr.render

- .changeset/chatty-flowers-slide.md
- js/tabs/shared/Tabs.svelte
Fixes default tab label.
Closes: #11333 …
> Fixes default tab label

- .changeset/cool-pianos-report.md
- gradio/mcp.py
- test/test_mcp.py
Tools that returned **SVG** images through a `gr.Image` component produced an MCP payload like:
``` json
{ "type": "text",
"text": "{'path': None, 'url': 'data:image/svg+xml,%3Csvg…'}" }
```
instead of the expected:
``` json
{ "type": "image",
"data": "<base-64>",
"mimeType": "image/svg+xml" }
```
`gr.Image` sanitises SVGs for security and converts them to a **data-URI** that no longer has a filesystem path.  
`GradioMCPServer.postprocess_output_data()` relied on `path` to decide whether an output was an image (it opens the file with PIL). When `path` was missing the function treated the result as plain text, so MCP clients could not render the
diagram.
This PR updates `postprocess_output_data()` to handle SVGs in both forms and to **reconstruct a servable path** when necessary:
1. …
> fix(mcp): package SVG outputs as proper ImageContent for MCP clients

- .changeset/dull-llamas-divide.md
- client/js/src/client.ts
Closes: #11263
You can repro the original issue by adding some delay to the ws route. There was a race condition where we tried to send a ws message before the connection resolved. The fix is to only add `ws_map` when the connection is open.
```python
@router.websocket("/stream/{event_id}")
async def websocket_endpoint(websocket: WebSocket, event_id: str):
await asyncio.sleep(3)
await websocket.accept()
try:
while True:
data = await websocket.receive_json()
body = PredictBody(**data)
event = app.get_blocks()._queue.event_ids_to_events[event_id]
body_internal = PredictBodyInternal(
**body.model_dump(), request=None
)
event.data = body_internal
event.signal.set()
await websocket.send_json({"msg": "success"})
except WebSocketDisconnect:
pass
``` …
> Fix image streaming - wait for ws to open

- .changeset/stupid-radios-throw.md
- js/gallery/shared/Gallery.svelte
Closes: #10211
I was not able to reproduce the original issue exactly. I was able to scroll to the left and right to see the thumbnails that overflowed. The problem I noticed is the thumbnail preview doesn't correctly scroll to the image you clicked on if there are many images. This is because of the `justify-content: center` rule that's applied. My fix is to apply `justify-content: flex-start` when the gallery overflows and `justify-content:center` otherwise.
Notice that after clicking on the first image, the thumbnails don't show the image I clicked on
Not …
> Fix Gallery thumbnail overflow

- .changeset/ten-coins-sit.md
- js/spa/src/Index.svelte
There is the HTTP protocol hardcoded in the dev hot reload mode. Reloading fails when running `gradio app.py`.
Closes: https://github.com/gradio-app/gradio/issues/10048
> Fixes hardcoded HTTP protocol in dev reload

- .changeset/flat-rooms-stare.md
- js/dataframe/shared/VirtualTable.svelte
Combine the virtual table's mount handler and scroll handler to prevent inconsistencies in the table height changing on scroll. Increase the row buffer from one row to one page (up and down) to prevent render popping. Remove no-op `tick()` calls that delayed row rendering. Remove no-op row border calculation. React to table visibility to fix value changes while hidden.
Closes: #11321
https://github.com/user-attachments/assets/ac3fd531-7ba5-4df3-bc3c-e567cfff2ee9
> Fix DataFrame Scroll Divergence

- .changeset/brave-boxes-melt.md
- gradio/utils.py
Fixes this error, which can be quite frustrating, closes: https://github.com/gradio-app/gradio/issues/11280
Repro (which fails on `main` but works on this PR for me):
```py
import asyncio
def my_ui():
with gr.Blocks(fill_width=True, title="Test") as demo:
toggle_all_traces = gr.Button("On", scale=0, min_width=200)
def do_toggle_all_traces(state):
new_state = not state
new_label = "On" if new_state else "Off"
return gr.update(value=new_label), new_state
show_all_traces_toggle_state = gr.State(value=False)
toggle_all_traces.click(
fn=do_toggle_all_traces,
inputs=[show_all_traces_toggle_state],
outputs=[toggle_all_traces, show_all_traces_toggle_state],
)
return demo
async def test():
await asyncio.sleep(1)
asyncio.run(test())
demo = my_ui()
demo.launch()
```
> Make the method for getting the `asyncio` event loop more robust

- .changeset/busy-cooks-obey.md
- js/column/Index.svelte
~~Set the `gap` default in the binding to allow explicit `undefined` updates to gracefully fallback to `true`.~~
Prevent the column gap from disappearing on hot reload.
Closes: #8887
https://github.com/user-attachments/assets/2e4df007-3cd5-4ce3-9747-1eeca8aca36f
> Remove gap parametger from gr.Column

- .changeset/thick-hands-bet.md
- gradio/queueing.py
- gradio/utils.py
Closes: #8503
You can test with this repro. On main, the `finally` block won't be printed until you refresh the page or close the server. In this PR, it will be printed. This means the iterator resources, in this case the directory, are properly deleted.
```python
from tempfile import TemporaryDirectory
import time
import asyncio
def create_tmpdir():
try:
with TemporaryDirectory() as tmpdir:
print(tmpdir)
while True:
yield
except Exception as e:
print(f"Error: {e}")
finally:
print("FINALLY")
run_btn = gr.Button()
stop_btn = gr.Button("Stop")
event = run_btn.click(create_tmpdir)
stop_btn.click(None, cancels=event) # tmpdir persists until we exit gradio
```
Before your create a PR, please check to see if there is [an …
> Ensure Sync generators get closed if they are cancelled

- .changeset/easy-doodles-sip.md
- client/python/gradio_client/client.py
Closes: https://github.com/gradio-app/gradio/issues/10164 (not sure if we have a way to test this yet, @aliabid94?)
> Attach cookies to client after first request (to support multiple-replica setups with cookie-based affinity)

- .changeset/purple-lines-play.md
- gradio/mcp.py
- test/test_mcp.py
Closes: #11464
The problem was that we would modify the schema in place. So the first time the client connected, the FileData entries would be replaced with strings. During the events, we would not know the correct file data positions anymore.
To test, use something like this. On main, it will fail. On this branch it passes.
```python
def transcribe_video(video: str):
return "A nice video"
interface = gr.Interface(
fn=transcribe_video,
inputs=gr.Video(label="Video"),
outputs=gr.Textbox(label="Transcription"),
)
interface.launch(mcp_server=True)
```
Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very …
> Fix schema modification bug in MCP

- .changeset/social-pumas-ask.md
- gradio/mcp.py
- test/test_mcp.py
Fixes: https://github.com/gradio-app/gradio/issues/11455
e.g. test with:
```py
reuse_button = gr.Button()
reuse_button.click(
fn = lambda x:x*2,
inputs = [reuse_button],
outputs = [reuse_button]
)    
reuse_button2 = gr.Button()
reuse_button2.click(
fn = lambda x:x*2,
inputs = [reuse_button2],
outputs = [reuse_button2]
)    
demo.launch(mcp_server=True)
```
cc @evalstate for visibility
> Improve logic for sanitizing MCP tool names

- .changeset/six-trains-work.md
- gradio/utils.py
- test/test_utils.py
Preserve key paths in the diff utility when compensating for consecutive deletes.
Closes: #11470 
https://github.com/user-attachments/assets/0f4e4906-3455-45f1-ac87-b9c0e171e1c0
> Fix Delete Diff Keys

- .changeset/crazy-eels-feel.md
- gradio/brotli_middleware.py
I actually couldn't reproduce with`.stl` files but I was seeing `.ply` and `.splat` fail to initialise correctly. 
This makes sense because they both use the `gsplat` file loader. 
The source of the bug is actually in gsplat itself i think. It is using the `content-size` header to allocate a buffer but the content-size of a compressed resource and its uncompressed size do not match meaning the data was larger than the allocated buffer (hence the out of bounds error).
Closes: #11500.
> only compress text resources with brotli

- .changeset/small-ads-hang.md
- gradio/interface.py
The first segment of two warnings in `interface.py` was missing a trailing space before the next literal, causing the sentences to run together. This commit appends a space to:
- “Cache examples cannot be used with state inputs and outputs. ”
- “The `allow_flagging` parameter in `Interface` is deprecated. ”
> fix: add missing space at end of warning sentences for proper grammar

- .changeset/warm-goats-stop.md
- gradio/external.py
- gradio/external_utils.py
- test/test_external_utils.py
As suggested by @evalstate and @Wauplin [internally](https://huggingface.slack.com/archives/C02136Y252P/p1753341289591279?thread_ts=1753317024.694709&cid=C02136Y252P), this adds support for excluding certain paths and an auth token to `gr.load_openapi`. Also adds arbitrary kwargs which are passed into the resulting `Interface` that is created.
> Add `auth_token` and `exclude_paths` to `gr.load_openapi`

- .changeset/loud-mirrors-sin.md
- gradio/components/number.py
- gradio/components/slider.py
- test/components/test_number.py
- test/components/test_slider.py
This PR:
* Adds precision support to `gr.Slider`, enabling rounding and integer type conversion when `precision=0`
* Refactors min/max validation logic in `gr.Number` to a shared `raise_if_out_of_bounds` method, which is now also used by `gr.Slider` (closes: https://github.com/gradio-app/gradio/issues/3878) 
* Updates json schema based on the precision (closes: https://github.com/gradio-app/gradio/issues/11579)
* Adds unit tests
> Improve schema for `gr.Number` and `gr.Slider` and other related changes around precision and minimum/maximum range

- .changeset/bright-webs-rescue.md
- js/upload/src/Upload.svelte
Closes: https://github.com/gradio-app/gradio/issues/10746
When using the `File()` component, if you specify file extensions for the `file_types` argument, this ends up being case sensitive. For example, if `file_types=[".pdf"]` and you upload "file.PDF", the file will not upload, and an error will appear in the Gradio frontend: "Invalid file type only .pdf allowed."
The error comes from the `load_files_from_upload` function. The file type validation compares the acceptabile types to the uploaded file's file extension _exactly_, without controlling for case.
This does not match the logic of the other occurrences of file type validation within the [same file](js/upload/src/Upload.svelte), such as in `is_valid_file`, which makes the filename lowercase before validation, nor does it match the …
> Fix file upload error due to file extension case differences.

- .changeset/tired-otters-open.md
- js/statustracker/static/index.svelte
Closes: #11695
Progress animation max-height was set to not max screen height. Removing that.
2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes …
> Set Progress Animation to cover component height 

- .changeset/old-parrots-fold.md
- js/dialogue/Dialogue.svelte
- js/textbox/shared/Textbox.svelte
Replace custom copy button styling in Textbox and Dialogue components with standardized IconButton from atoms. Besides reduces code duplication, this fixes dark mode visibility issues in citrus theme, see below:
```py
with gr.Blocks(theme="citrus") as demo:
gr.JSON({"a":"b"})
gr.Textbox("abc", show_copy_button=True)
demo.launch()
```
Before:
https://github.com/user-attachments/assets/bde982ae-1f03-4f22-8ec2-1721d971f29e
After:
https://github.com/user-attachments/assets/57496245-39e7-4661-b7c1-d8ae0c39c4e2
> Consolidate copy button implementations to use IconButton

- .changeset/honest-horses-begin.md
- gradio/components/paramviewer.py
- js/paramviewer/Index.svelte
- js/paramviewer/ParamViewer.svelte
Added a max_height parameter to ParamViewer. If this value is set and the content exceeds it, the parameter table will scroll vertically while the header remains fixed in place.
Closes: [#11900]([https://github.com/gradio-app/gradio/issues/11900])
https://github.com/user-attachments/assets/e6e6de0d-c707-4cab-94f9-0174a0694a94
> Add max_height parameter to ParamViewer

- .changeset/red-deer-melt.md
- gradio/components/datetime.py
Closes: #11840
You can test with repro from issue …
> Fix bug where setting interactive prop of gr.Datetime from the backend was not working

- .changeset/social-bees-rescue.md
- gradio/routes.py
Closes: #11497 
Write up from the issue:
> Hi @goudakrishna - the issue is caused by two things:
> - Firstly, in order for gradio to finish cancelling the request it needs to wait for the `asyncio.sleep` call to finish. The reason is that in python you can only cancel iterators once they are not actively iterating. So the next time gradio is able to cancel the request is the second `yield` event (at which time the event is basically over) 
> - Basically this means that in practice you end up hitting the stop button twice.  This tells the gradio backend to remove the event from the processing queue. The second time it tries to remove the event you get the `KeyError` because the event was already removed.
> So I will open a PR to fix the issue in the second point. For the first point, it …
> Fix KeyError that can be caused by cancelling the same event twice

- .changeset/solid-brooms-lose.md
- gradio/routes.py
Closes: #11351
Issue was that we don't use orjson to serialize the data if the request doesn't go through the queue. This means that the i18n dict was kept as `{"__type__": "translation_metadata", "key": "Image"}` instead of the `__i18n__` string the frontend expects.
1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the …
> Serialize i18n data for events that dont go through queue

- .changeset/famous-banks-prove.md
- gradio/components/markdown.py
- js/markdown-code/utils.ts
- js/markdown/Markdown.stories.svelte
Closes: #11931
Added a storybook for this as well. …
> Add Syntax Highlighting for more languages in Markdown Component

- .changeset/rotten-donkeys-know.md
- client/python/requirements.txt
- gradio/cli/commands/deploy_space.py
- requirements.txt
This PR update the dependency requirements to allow `huggingface_hub` 1.x version.
No need for any change in the code as some minor changes have already been made in https://github.com/gradio-app/gradio/pull/11830 and https://github.com/gradio-app/gradio/pull/11852.
> Allow gradio to run with huggingface_hub 1.x

- .changeset/floppy-plums-suffer.md
- gradio/routes.py
The changes made is in the `gradio/routes.py` in the login function making it an async function using `inspect.iscoroutine()` to check if it needs to `await`. Otherwise it processes `app.auth`. 
Closes: #9244
> Clean fix for support of async auth functions in login (#9244)

- .changeset/stale-cycles-sit.md
- js/checkbox/Index.svelte
Earlier  the app renders the info text above the label, now will show info below checkbox.
Closes: #11897
Ran:
Formatting/Linting
```bash
bash scripts/format_frontend.sh
```
> fix: render checkbox info text below label for consistency

- .changeset/legal-zoos-swim.md
- js/core/src/init.ts
Closes: #11984
In https://github.com/gradio-app/gradio/pull/11615, we trigger change events if the component is explicitly hidden. But not if it is implicitly hidden in an unselected tab. 
You can test with the following demo:
```python
import random
gr.Markdown("## Tabs with visibility control")
num = gr.Number(label="Number")
with gr.Tabs():
with gr.Tab("Tab 1") as tab1:
gr.Markdown("This tab is visible by default")
with gr.Tab("Tab 2") as tab2:
tb = gr.Textbox(label="This tab is hidden by default")
tb.change(lambda: random.randint(0, 100000), None, num)
btn = gr.Button("Show the textbox", variant="primary")
btn.click(lambda: gr.update(visible=True, interactive=True), None, tb)
demo.load(lambda: "Loaded!", None, tb)
if __name__ == …
```
> Trigger Change Event if component is in inactive tab
